- .env
- config/webpack.config.js
- src/App.tsx
- src/contexts/swr/SwrContext.tsx
- tsconfig.json
now we can import from 'contexts/Boundary' instead of '../../../contexts/Boundary'
> Module resolution

- src/App.tsx
- src/contexts/auth/Auth.tsx
Created Auth context and moved Web3 use there from App
> Move Web3 use to Auth context

- package.json
- src/scenes/Gallery/Gallery.tsx
- yarn.lock
> Replace web3 with web3-utils

- src/components/GlobalNavbar/GlobalNavbar.tsx
- src/index.css
- src/scenes/AppContainer/AppContainer.tsx
- src/scenes/Gallery/Gallery.tsx
- src/scenes/Routes.tsx
POC with lots of TODOs
https://user-images.githubusercontent.com/12162433/113110459-1b7a6600-91d5-11eb-83c5-0c39dbee2325.mov
> Gallery detail POC

- config/webpack.config.js
- src/components/core/Link/Link.tsx
- src/components/core/Spacer/Spacer.tsx
- src/components/core/Text/Text.tsx
- src/components/core/colors.ts
- src/index.css
- src/scenes/Gallery/Body.tsx
- src/scenes/Gallery/Gallery.tsx
- src/scenes/Gallery/Header.tsx
- src/scenes/Gallery/NftPreview.tsx
- src/types/Nft.ts
- tsconfig.json
- add `types` dir
- add core components
- Link
- Title
- Text
- Spacer
- colors
> Collection view refactor

- src/components/GlobalNavbar/SignInButton.tsx
- src/components/GlobalNavbar/SignOutButton.tsx
- src/components/core/Button/TextButton.tsx
- src/components/core/colors.ts
Created a TextButton component that has button functionality but appears like text and uses the Link component styling
> Add TextButton component

- src/components/WalletSelector/WalletButton.tsx
- src/react-app-env.d.ts
> Prompt metamask install in wallet selector if no metamask detected

- src/components/Password/Password.tsx
- src/contexts/auth/AuthContext.tsx
- src/utils/password.ts
If they have, just display "Next"
If they are new, display pw input
> Remember if user entered pw successfully

- package.json
- src/scenes/CollectionCreationFlow/steps/AddNfts/AddNfts.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/Editor/Editor.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/Editor/SortableNft.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/NftSortableContext.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/useNftEditor.ts
- yarn.lock
https://drive.google.com/file/d/132yQGce_RpbOibJxjQnGVMMG2JVmi7YQ/view?usp=sharing
uses the magical [dnd-kit](https://5fc05e08a4a65d0021ae0bf2-afswkkwlzd.chromatic.com/)
> drag and drop NFTs

- src/contexts/wizard/WizardValidationContext.tsx
- src/contexts/wizard/useIsNextEnabled.ts
- src/scenes/CollectionCreationFlow/CollectionCreationFlow.tsx
- src/scenes/CollectionCreationFlow/WizardFooter.tsx
- src/scenes/CollectionCreationFlow/steps/AddUserInfo.tsx
This PR adds a WizardValidationContext so that any component in the Wizard can access and set validation state. This allows each step to control whether the Next button in the footer is enabled or not.
Additional changes
- AddUserInfo step to set username and bio
- basic validation for username
> Add WizardValidationContext to connect validation state in Steps with Wizard Footer

- src/scenes/Welcome/Welcome.tsx
> Match welcome step with design

- src/components/WalletSelector/WalletButton.test.tsx
- src/components/WalletSelector/WalletButton.tsx
- src/components/WalletSelector/WalletSelector.test.tsx
- src/components/WalletSelector/WalletSelector.tsx
- Added loading (Connecting...) state
- Revamped error state
- refactored WalletSelector and WalletButton components
- added test case for WalletSelector
> Wallet selector updates

- src/components/Password/Password.tsx
- src/components/WalletSelector/WalletButton.tsx
- src/components/WalletSelector/WalletSelector.tsx
- src/components/core/ActionText/ActionText.tsx
- src/components/core/Button/PrimaryButton.tsx
- src/components/core/Dropdown/Dropdown.tsx
- src/components/core/colors.ts
- src/contexts/wizard/WizardValidationContext.tsx
- src/scenes/CollectionCreationFlow/CollectionCreationFlow.tsx
- src/scenes/CollectionCreationFlow/WizardFooter.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/AddNfts.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/Directions.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/Sidebar/Sidebar.tsx
- src/scenes/CollectionCreationFlow/steps/AddUserInfo.tsx
- src/scenes/CollectionCreationFlow/types.ts
- src/scenes/Gallery/components/CollectionView.tsx
- src/scenes/Gallery/components/Header.tsx
- src/scenes/Welcome/Welcome.tsx
- more dynamic wizard footer (says "Cancel" if user is on first step, "Back" on any other step)
- styling polish on footer
- enableNext + disableNext => setNextEnabled
- update color palette to use scheme from figma
- add `thicc` prop to button for customizability
> Wizard polish, colors upgrade

- src/components/core/Button/PrimaryButton.tsx
- src/scenes/CollectionCreationFlow/WizardFooter.tsx
- src/scenes/CollectionCreationFlow/steps/CreateFirstCollection.tsx
- src/scenes/Welcome/Welcome.tsx
https://user-images.githubusercontent.com/12162433/116506080-7497f100-a88a-11eb-8b7f-471f8d8fe26a.mov
> Collection splash step

- src/components/core/BigInput/BigInput.tsx
- src/components/core/TextArea/TextArea.tsx
- src/contexts/modal/AnimatedModal.tsx
- src/scenes/CollectionCreationFlow/WizardFooter.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/AddNfts.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/CollectionNamingForm.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/Editor/Editor.tsx
- src/scenes/CollectionCreationFlow/steps/AddUserInfo.tsx
- src/utils/noop.ts
- collection naming form
- some refactor
> Collection naming modal

- package.json
- src/components/core/colors.ts
- src/mocks/collections.ts
- src/scenes/CollectionCreationFlow/CollectionCreationFlow.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/Editor/StagedNftImageDragging.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/Editor/StagedNftWrapper.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/Editor/StagingArea.tsx
- src/scenes/CollectionCreationFlow/steps/AddNfts/Sidebar/SidebarNftIcon.tsx
- src/scenes/CollectionCreationFlow/steps/OrganizeCollections/CollectionDnd.tsx
- src/scenes/CollectionCreationFlow/steps/OrganizeCollections/CollectionRow.tsx
- src/scenes/CollectionCreationFlow/steps/OrganizeCollections/CollectionRowDragging.tsx
- src/scenes/CollectionCreationFlow/steps/OrganizeCollections/CollectionRowWrapper.tsx
- src/scenes/CollectionCreationFlow/steps/OrganizeCollections/OrganizeCollections.tsx
- src/scenes/CollectionCreationFlow/steps/OrganizeCollections/SortableCollectionRow.tsx
- yarn.lock
https://user-images.githubusercontent.com/80802871/117246333-67c16180-ae77-11eb-887f-bd7672e4fa2f.mov
> Make collections re-orderable

- src/components/Profile/UserInfoForm.tsx
- src/contexts/modal/AnimatedModal.tsx
- src/flows/OnboardingFlow/steps/AddUserInfo.tsx
- src/scenes/Gallery/components/EditUserInfoModal.tsx
- src/scenes/Gallery/components/Header.tsx
This PR adds a the Edit User Info modal.
> Add Edit User Info modal

- src/components/NftPreview/NftPreview.tsx
- src/components/NftPreview/NftPreviewLabel.tsx
- src/components/Profile/UserInfoForm.tsx
- src/components/core/Gradient/Gradient.tsx
- src/components/core/Text/Text.tsx
- src/flows/OnboardingFlow/steps/AddUserInfo.tsx
- src/flows/OnboardingFlow/steps/Congratulations.tsx
- src/flows/OnboardingFlow/steps/CreateFirstCollection.tsx
- src/flows/OnboardingFlow/steps/Welcome.tsx
- src/flows/shared/steps/OrganizeCollection/CollectionNamingForm.tsx
- src/flows/shared/steps/OrganizeCollection/Directions.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/StagedNftImage.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/StagedNftWrapper.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/StagingArea.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/UnstageButton.tsx
- src/scenes/Home/Home.tsx
- src/scenes/NotFound/NotFound.tsx
- src/scenes/Password/Password.tsx
> Gradient component, onboarding stylistic refactor

- src/scenes/Password/Password.tsx
> Update password flow

- src/components/core/BigInput/BigInput.tsx
- src/components/core/Dropdown/Dropdown.tsx
- src/contexts/modal/AnimatedModal.tsx
- src/flows/OnboardingFlow/OnboardingFlow.tsx
- src/flows/shared/steps/OrganizeCollection/CollectionNamingForm.tsx
- src/flows/shared/steps/OrganizeCollection/OrganizeCollection.tsx
- src/flows/shared/steps/OrganizeGallery/CollectionRowSettings.tsx
- src/flows/shared/steps/OrganizeGallery/DeleteCollectionConfirmation.tsx
- Show modal when "Edit name & description" is clicked
- Show modal when "Delete" is clicked
- Fix z-index issue with dropdown+modal
> Make dropdown actions on Edit Gallery page do stuff

- src/components/GlobalNavbar/LoggedInNav.tsx
- src/components/GlobalNavbar/LoggedOutNav.tsx
- src/components/NftPreview/NftPreview.tsx
- src/components/WalletSelector/WalletSelector.tsx
- src/hooks/useAuthModal.tsx
- NFT text hover translate
- Open auth modal instead of navigating to auth, better error handling
- Link to etherscan
> Random polish

- src/components/Profile/UserInfoForm.tsx
- src/components/WalletSelector/WalletButton.tsx
- src/components/core/BigInput/BigInput.tsx
- src/components/core/Button/Button.tsx
- src/components/core/Loader/Loader.tsx
- src/components/core/TextArea/TextArea.tsx
- src/components/core/colors.ts
- src/contexts/wizard/WizardValidationContext.tsx
- src/flows/OnboardingFlow/steps/AddUserInfo.tsx
- src/flows/shared/components/WizardFooter/WizardFooter.tsx
- src/flows/shared/steps/OrganizeCollection/CollectionNamingForm.tsx
- src/flows/shared/steps/OrganizeGallery/OrganizeGallery.tsx
- src/index.css
- src/scenes/Gallery/components/Header/EditUserInfoModal.tsx
- src/scenes/Password/Password.tsx
- src/utils/isPromise.ts
- src/utils/regex.ts
- update UserInfoForm to be a controlled component (away from uncontrolled) [[explanation](https://stackoverflow.com/a/42522792)]. update parents in 1) welcome flow, 2) edit info modal to use new form
- centralized Loader component with customizable config (#135)
- update Button component to handle loading flag, which using above Loader (#132)
- update WizardFooter to handle async onNext submissions, displaying a loader while fetching
- update TextArea to take default value
- turn off autocomplete, autocorrect, autocapitalize, spellcheck on all inputs
- character length checker for bio (#136)
- misc
> Button loader, wizard button submit refactor, error handling, various other

- src/components/Profile/UserInfoForm.tsx
- src/components/Profile/useUserInfoForm.ts
- src/components/core/BigInput/BigInput.tsx
- src/components/core/Text/ErrorText.tsx
- src/flows/OnboardingFlow/steps/AddUserInfo.tsx
- src/flows/shared/steps/OrganizeCollection/CollectionNamingForm.tsx
- src/scenes/Gallery/components/Header/EditUserInfoModal.tsx
- generic ErrorText component
- update BigInput to handle errors
- hook for user info form logic
- fix ugly collection naming form
> Form error handling

- src/flows/shared/steps/OrganizeGallery/OrganizeGallery.tsx
Return to profile after clicking next in edit gallery wizard
> Add onNext behavior to edit view

- src/flows/shared/steps/OrganizeGallery/OrganizeGallery.tsx
- src/hooks/api/useNft.ts
- src/scenes/NftDetailPage/NftDetailPage.tsx
- src/setupProxy.js
- src/types/Nft.ts
Add useNft hook so we can mock more api calls
> Add useNft hook

- src/components/Profile/useUserInfoForm.ts
- src/scenes/Gallery/components/Header/EditUserInfoModal.tsx
Get the authenticatedUser and set existing username and description as default values for respective states
> Prepopulate username and bio on EditUsernameInfoModal

- src/components/WalletSelector/WalletSelector.tsx
- src/contexts/auth/AuthContext.tsx
- src/contexts/auth/clearLocalStorageWithException.ts
- localstorage util
- unsupported chain error support
- temp disable wallet link
> Auth cleanup

- .env
- config/paths.js
- config/webpack.config.js
- dev_server/checkPort.js
- dev_server/mocks.js
- dev_server/routes.js
- dev_server/server.js
- src/contexts/swr/fetcher.ts
`yarn start` will now automatically try to connect to go server. if it's not running, it'll spin up the local mock server
> Update proxy to support local go server

- src/hooks/api/useUser.ts
Change the param name for id in the Get user request from `id` to `user_id`
> change get user param name

- src/components/Profile/useUserInfoForm.ts
- src/contexts/swr/fetcher.ts
- src/hooks/usePersistedState.ts
- Add API call to UserInfoForm to update username and description
- Update Fetcher to handle responses with no Response body
- Update localstorage to only stringify Objects, so that we don't stringify strings and add unnecessary double quotes to values
> Add API call to UserInfoForm, fix issues with fetcher and localstorage util

- src/scenes/Auth/Auth.tsx
> Add "Gallery is non-custodial and secure. We will never request access to your NFTs."

- src/components/GlobalNavbar/LoggedInNav.tsx
- src/components/Profile/useUserInfoForm.ts
- src/hooks/api/users/useUser.ts
Super edge case (a user without an `addresses` array is an invalid state for user in database) but I encountered it so I thought we might as well handle it gracefully on the front end. Null check everything we can
> Null check user.addresses

- src/components/WalletSelector/WalletSelector.tsx
> Add wallets coming soon copy

- .env.sample
- dev_server/server.js
- package.json
> Simplify api baseurl in .env

- src/components/GlobalNavbar/LoggedInNav.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
> Move options under 'Edit Profile' to LoggedInNavbar, and get rid of EditProfile

- src/flows/shared/steps/OrganizeCollection/CollectionEditInfoForm.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/CollectionEditor.tsx
- src/flows/shared/steps/OrganizeCollection/OrganizeCollection.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarNftIcon.tsx
- src/flows/shared/steps/OrganizeGallery/DeleteCollectionConfirmation.tsx
- src/flows/shared/steps/OrganizeGallery/OrganizeGallery.tsx
- src/hooks/api/collections/nuke/useNuke.ts
- src/mocks/nfts.ts
- src/scenes/Nuke/Nuke.tsx
- src/types/Nft.ts
- src/utils/resizeNftImageUrl.ts
> Various bugfixes

- package.json
- src/components/WalletSelector/WalletButton.tsx
- src/components/WalletSelector/WalletSelector.tsx
- src/utils/mixpanel.ts
- yarn.lock
This PR adds Mixpanel
I made a mixpanel util to easily set up new events.
I added the first event that gets fired after the user connects with their wallet successfully.
> Set up Mixpanel and add first event

- src/flows/shared/steps/OrganizeCollection/Editor/StagingArea.tsx
Limit Collection edit DND width to 3 columns so it reflects how it will be displayed
> Limit Collection edit DND width to 3 columns

- .xo-config.json
turn off rule for capitalized comment cus it is a nuisance
> turn off rule for capitalized comment

- .xo-config.json
- src/components/ImageWithLoading/ImageWithLoading.tsx
- src/scenes/NftDetailPage/NftDetailAnimation.tsx
- src/scenes/NftDetailPage/NftDetailVideo.tsx
Fix shimmer for video, audio, animation detail view by turning off the shimmer `onLoadStart`
> Fix shimmer for video, audio, animation detail view

- src/scenes/NftDetailPage/NftAdditionalDetails.tsx
- src/scenes/NftDetailPage/NftDetailPage.tsx
- src/scenes/NftDetailPage/NftDetailText.tsx
Add Additional Details section to NFT Detail Page
> Add Additional Details section

- src/scenes/Password/Password.tsx
Increase font size + letter spacing and adjust Spacer heights
Before:
After:
> Visual changes to Gallery logo

- src/hooks/api/nfts/useNft.ts
Changes:
- get NFT by ID now returns a single NFT instead of a list with a single NFT. so update hook accordingly
> Update useNft hook to reflect backend changes

- package.json
- src/components/core/Text/Text.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
- src/types/User.ts
- yarn.lock
Changes
- Bump up username header font size
- adjust spacing
- Add `Curator since {created_at}`
- Fix word break/wrapping for bio text  and reduce total width of bio text box
> Adjust Gallery Profile Page content

- src/components/GalleryTitleIntro/GalleryTitleIntro.tsx
- src/scenes/Home/Home.tsx
- src/scenes/Password/Password.tsx
Also add the new title view to the post-password home screen
> Title tweak

- src/components/WalletSelector/WalletSelector.tsx
> Wallet error copy updates

- src/scenes/NftDetailPage/NftDetailText.tsx
- src/types/Nft.ts
Changes:
- add owner_username to Nft type
- on NFT Detail Page, display owner_username and link to user's Gallery
- if no owner_username, display owner_address and link to Etherscan
> Display owner username and link to gallery if exists

- src/components/WalletSelector/WalletButton.tsx
- src/components/WalletSelector/WalletSelector.tsx
- src/components/WalletSelector/authRequestUtils.ts
- src/components/WalletSelector/walletlinkSigner.ts
- src/hooks/useAuthModal.tsx
- src/types/Error.ts
> Coinbase Wallet

- src/utils/validators.ts
> fix typo in minLength validator

- src/components/core/Page/Footer.tsx
decrease bottom padding and total height
> Adjust footer padding and height

- src/components/WalletSelector/authRequestUtils.ts
- src/hooks/api/nfts/useOpenseaSync.ts
change `opensea_get?address=` to `opensea_get?addresses=`
> Update opensea addresses param

- .xo-config.json
- package.json
- src/components/Profile/UserInfoForm.tsx
- src/flows/shared/steps/OrganizeCollection/CollectionCreateOrEditForm.tsx
- src/flows/shared/steps/OrganizeGallery/CollectionRow.tsx
- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
- yarn.lock
> Unescape display strings

- public/index.html
- src/components/FadeTransitioner/FadeTransitioner.tsx
- src/contexts/navigation/GalleryNavigationContext.tsx
- src/contexts/navigation/NavigationContext.tsx
- src/contexts/navigation/sanitizePathname.test.ts
- src/contexts/navigation/sanitizePathname.ts
- src/flows/OnboardingFlow/OnboardingFlow.tsx
- src/scenes/NftDetailPage/NftDetailPage.tsx
- src/scenes/Routes.tsx
- src/scenes/UserGalleryPage/UserGalleryPage.tsx
> Handle scroll position

- src/scenes/NotFound/NotFound.tsx
Wanted to change exclamation mark to a period. Tone seemed a little off...
That's all lol
> exclamation mark to period on 404 copy

- src/components/WalletSelector/WalletSelector.tsx
changes: 
- adjust width of modal for mobile screen
before:
after:
> adjust mint page modal width for mobile

- src/scenes/MembershipMintPage/MembershipMintPage.tsx
> Upon succesful mint show cta to onboard

- src/scenes/NftDetailPage/NftDetailText.tsx
- src/types/Nft.ts
> show nft owner name on detail page

- src/flows/shared/steps/OrganizeGallery/OrganizeGallery.tsx
changes:
- when user clicks Cancel on Organize Gallery page, take them to previous page
- if no previous page, take them to their profile
> cancel button takes user to prev page

- src/components/NftPreview/NftPreviewAsset.tsx
- src/scenes/NftDetailPage/NftDetailAsset.tsx
> Toss obit orange

- src/flows/shared/components/WizardFooter/WizardFooter.tsx
- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
> visual fixes

- src/components/WalletSelector/WalletSelector.tsx
> Add more info to Missing NFT error message

- src/components/core/Page/GlobalFooter.tsx
- src/constants/urls.ts
**Changed ordering of Footer.**
Before:
1. Jobs
2. Twitter
3. Discord
4. Opensea
After:
1. Twitter
2. Discord
3. Mirror _(NEW!)_
4. Opensea
5. Jobs
> added mirror link + reorganized footer

- src/components/ImageWithLoading/ImageWithLoading.tsx
- src/components/core/Page/Page.tsx
- src/contexts/shimmer/ShimmerContext.tsx
- src/index.css
- src/scenes/NftDetailPage/NftDetailAsset.tsx
- src/scenes/NftDetailPage/NftDetailPage.tsx
- src/scenes/NftDetailPage/NftDetailText.tsx
|Before|After|
|----|----|
|<img width="1440" alt="Screen Shot 2021-11-25 at 9 17 27 PM" src="https://user-images.githubusercontent.com/12162433/143537323-2eb8eb71-1679-439b-812d-a3c25feeb69e.png">|<img width="1440" alt="Screen Shot 2021-11-25 at 9 17 35 PM" src="https://user-images.githubusercontent.com/12162433/143537319-c6a04199-354c-494f-a48b-c3bc8fbdf276.png">|
|Before|After|
|----|----|
|<img width="497" alt="Screen Shot 2021-11-26 at 12 46 47 AM" src="https://user-images.githubusercontent.com/12162433/143536939-cd21fff1-4cd4-4590-8820-7fb79794afb2.png">|<img width="497" alt="Screen Shot 2021-11-26 at 12 46 32 AM" src="https://user-images.githubusercontent.com/12162433/143536946-fd27f66d-c63a-4045-9820-a5f142f61b9c.png">|
|Before|After|
|----|----|
|<img width="497" alt="Screen Shot …
> Improve NFT detail page

- src/flows/shared/steps/OrganizeCollection/Editor/CollectionEditor.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/EditorMenu.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/StagingArea.tsx
also fix a weird height / centering issue that was causing this when you scroll down on the page:
remove column adjuster if empty
> Flatten out column adjuster

- src/contexts/swr/SwrContext.tsx
> Update SWR config

- src/contexts/swr/SwrContext.tsx
- src/contexts/swr/middleware/ensureLatestGallery.ts
- src/flows/EditGalleryFlow/EditGalleryFlow.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
- src/utils/time.ts
- Fix /nuke behavior, ignore caching inflight and errored requests
- Reverse sidebar NFTs to display latest first
- Update save and cancel UX
> SWR bugfixes and tweaks

- src/contexts/memberListPage/MemberListPageContext.tsx
- src/hooks/api/users/useMemberList.ts
- src/scenes/MemberListPage/MemberListFilter.tsx
- src/scenes/MemberListPage/MemberListOwner.tsx
- src/scenes/MemberListPage/MemberListPage.tsx
- src/scenes/MemberListPage/MemberListTier.tsx
- src/utils/featureFlag.ts
- use context for search query and faded username state
- dedupe repeated owners within a tier
> Members List improvements

- src/components/core/Page/GlobalFooter.tsx
> Thanks Lauren

- src/scenes/NftDetailPage/NftAdditionalDetails.tsx
This fixes long string conversion so that it outputs a number instead of scientific notation 🙏 e.g. this shows properly now https://gallery-git-connor-hex-fix-gallery-so.vercel.app/robin/21Qt76R6bIyM7fIDsBsgU9DrKCg/21R0nPXR1nlqXP9UD8hn7CQUsUP
> Better handling of hexadecimals 

- pages/membership/general.tsx
- src/scenes/MembershipMintPage/GeneralMembershipMintPage.tsx
- src/scenes/MembershipMintPage/MembershipMintPage.tsx
This PR updates the mint button text to make mint ineligibility and success state more clear.
Mint Ineligible
Mint Successful
> update mint button text to clarify meaning

- graphql.config.js
nothing complicated, just added configuration to get auto complete, syntax and go to definition in vs-code
> GraphQL config for vs-code

- public/icons/grid_layout.svg
- public/icons/list_layout.svg
- src/components/NftPreview/NftPreview.tsx
- src/components/core/enums.ts
- src/constants/layout.ts
- src/constants/storageKeys.ts
- src/scenes/UserGalleryPage/MobileLayoutToggle.tsx
- src/scenes/UserGalleryPage/UserGallery.tsx
- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
- src/scenes/UserGalleryPage/UserGalleryCollections.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
- src/scenes/UserGalleryPage/UserGalleryPage.tsx
> Add toggle between grid+list view on mobile

- src/contexts/wizard/WizardDataProvider.tsx
> Handle opensea refresh error

- pages/[username]/[collectionId]/index.tsx
- pages/membership/general.tsx
- src/components/WalletSelector/authRequestUtils.ts
- src/components/core/Page/GlobalNavbar/LoggedInNav.tsx
- src/components/core/enums.ts
- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
- src/utils/featureFlag.ts
> Implement dev feature flags; enable for single collection view

- .babelrc
- next-env.d.ts
- next.config.js
- package.json
- yarn.lock
Now that next.js supports relay, we can go back to the rust compiler.
> Re-enable rust compiler!

- src/hooks/useBackButton.tsx
- src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
- src/scenes/NftDetailPage/NftDetailPage.tsx
* Parsed the special character in the collection name
* Retain the scroll position when the user clicked the username in the single collection page
> Parsed collection name & retain scroll position

- src/contexts/swr/middleware/handleObscenelyLargeAssets.ts
the forbidden triple for loop is back to haunt us 😂
quick fix for this:
> fix error if collection.nfts is null

- src/components/core/Button/TextButton.tsx
- src/scenes/CollectionGalleryPage/CollectionGallery.tsx
- src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
- src/scenes/CollectionGalleryPage/CollectionGalleryPage.tsx
- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
* Added `back to gallery` nav
*  Moved the collection actions under collector notes
* Added three-dot options as an entry point to view collection page
* Some minor design updates - / should be in gray color and white space
> Single Collection design update 🚀

- src/components/Profile/UserInfoForm.tsx
- src/flows/shared/steps/OrganizeCollection/CollectionCreateOrEditForm.tsx
Update the max length of bio and collection name to 600.
This is already supported by the backend
> update max length of bio and collection name to 600

- src/components/NftPreview/NftPreviewAsset.tsx
- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
e.g. foundation NFTs that have been moved to opensea
> Support nfts that don't have image urls

- pages/opengraph/collection/[collectionId].tsx
- pages/opengraph/user/[username].tsx
- src/components/opengraph/OpenGraphPreview.tsx
> Redesign OpenGraph preview images

- src/components/ManageWallets/ManageWallets.tsx
- src/components/core/Page/GlobalNavbar/LoggedInNav.tsx
- src/scenes/Modals/ManageWalletsModal.tsx
* Restructured the logged in navbar 
* Added the sign out button in the manage wallet modal
> Logged In Navbar Improvements

- src/components/core/Page/GlobalFooter.tsx
- src/components/core/Page/constants.ts
> More footer polish

- src/scenes/UserGalleryPage/UserGalleryPage.tsx
more bottom padding for gallery page on mobile
> Yet more footer polish

- src/components/CopyToClipboard/CopyToClipboard.tsx
- src/flows/shared/components/WizardFooter/WizardFooter.tsx
- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
Allow users to edit their collection through main gallery / homepage.
> Edit collection from Main Gallery

- src/utils/nft.ts
> Fix broken NFT previews

- src/contexts/analytics/AnalyticsContext.tsx
Our signMessage was getting called twice due to an unstable callback.
https://user-images.githubusercontent.com/6754223/156704961-a4df1afe-bf7b-40d1-b182-9507d0713470.mov
Here's the fix
```
const AnalyticsProvider = memo(({ children }: Props) => {
const userId = useAuthenticatedUserId();
// Put the userId in a ref so we have something we can
// reach into for the current user id without needing
// to add a state dep to our useCallback.
//
// Without this, all of our downstream effects
// which rely on useTrack fire twice when
// the user logs in / logs out
const userIdRef = useRef(userId);
userIdRef.current = userId;
const handleTrack: TrackFn = useCallback((eventName, eventProps = {}) => {
_track(eventName, eventProps, userIdRef.current);
}, []);
return <AnalyticsContext.Provider …
```
> Fix double metamask prompt bug

- src/components/core/GalleryLink/GalleryLink.tsx
- src/scenes/Home/Home.tsx
> Gallery of the Week

- jest.config.js
I forgot to update our jest config when we upgraded to the Rust compiler. This fixes it!
> Fix jest config to support next compiler

- src/components/Profile/UserInfoForm.tsx
> Fix broken char counter

- src/components/WalletSelector/WalletSelector.tsx
> Improve unauthorized errors for missing member cards

- pages/_app.tsx
- src/utils/openGraphMetaTags.ts
> Use new logo for social previews

- pages/_app.tsx
- src/utils/openGraphMetaTags.ts
> Let's try that again

- src/scenes/UserGalleryPage/UserGallery.tsx
> add spacing at bottom of gallery

- cypress.json
Retry the failing cypress test to 2 times
> Set retry E2E failed test to 2

- src/components/core/Page/GlobalFooter.tsx
increase footer logo height to 24px
> increase footer logo height

- src/scenes/NftDetailPage/NftDetailNote.tsx
> Fix accidental horizontal overflow on mobile -> tablet

- src/components/NftPreview/NftPreview.tsx
> Full width single column on mobile

- schema.graphql
- src/components/NftPreview/NftPreview.tsx
- src/components/NftPreview/NftPreviewLabel.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/StagedNftImage.tsx
**Profile view**
This uses graphql
**Edit view**
This still uses the deprecated NFT model (opensea)
> Bump schema + collection name fix

- src/contexts/shimmer/ShimmerContext.tsx
Fixes a regression caused by a recent change.
**Before**
**After**
> Fix NFT detail overflow cutoff

- .vscode/settings.json
Prevent schema.graphql from autoformatting on save
> Prevent schema autoformatting

- pages/community/[contractAddress]/index.tsx
- schema.graphql
- src/components/core/InteractiveLink/InteractiveLink.tsx
- src/scenes/CommunityPage/CommunityPage.tsx
- src/scenes/CommunityPage/CommunityPageList.tsx
- src/scenes/CommunityPage/CommunityPageView.tsx
- src/scenes/NftDetailPage/NftDetailText.tsx
- src/types/Community.ts
This PR adds a Community Page for specific, hard coded communities.
Each page displays a list of Gallery users that have at least one NFT from that community's contract displayed in their Gallery.
> GAL-17 Add community page

- src/components/ImageWithLoading/ImageWithLoading.tsx
- src/components/NftPreview/NftPreview.tsx
- src/components/NftPreview/NftPreviewAsset.tsx
> Fix images that are too tall

- src/components/NftPreview/NftPreviewAsset.tsx
- src/scenes/NftDetailPage/NftDetailAudio.tsx
- src/utils/graphql/getVideoOrImageUrlForNftPreview.ts
> [graphql] media null safety checks

- src/components/ImageWithLoading/ImageWithLoading.tsx
- src/components/NftPreview/NftPreviewAsset.tsx
> Enforce full width for SVGs

- src/contexts/errorReporting/ErrorReportingContext.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarNftIcon.tsx
- src/utils/graphql/getVideoOrImageUrlForNftPreview.ts
Fix this full screen error, with reporting
> Handle media null check

- schema.graphql
- src/contexts/wizard/WizardDataProvider.tsx
- src/hooks/api/nfts/useRefreshOpenseaNfts.ts
- src/hooks/api/nfts/useUpdateNft.ts
- src/scenes/NftDetailPage/NftDetailNote.tsx
- src/scenes/NftDetailPage/NftDetailView.tsx
> Graphql updates

- src/components/core/Page/GlobalFooter.tsx
this PR adds the "BETA" text to the footer logo
> GAL-43 add BETA text to footer logo

- package.json
- sentry.client.config.js
- src/contexts/relay/relayFetchFunction.ts
- yarn.lock
> Sentry tracing

- src/components/opengraph/OpenGraphPreview.tsx
this PR adjust letter spacing on opengraph preview title to -4%
> GAL-33 adjust letter spacing on opengraph preview title

- cypress.json
- cypress/integration/specs/home-spec.ts
- src/contexts/toast/Toast.tsx
- src/scenes/PosterPage/PosterPage.tsx
1. I remove the top `Spacer` in the mobile view and move it to the bottom of the page
2. Regarding the toastr, seems like its a `z-index` issue and the `onClose` callback doesnt trigger properly in in the `autoClose` toastr.
> Fix UI poster page in mobile

- src/components/NftPreview/NftPreview.tsx
| <img width="1108" alt="image" src="https://user-images.githubusercontent.com/12162433/166315949-eb32e189-a580-49a3-b2df-ec726a0ea69f.png"> | <img width="1128" alt="image" src="https://user-images.githubusercontent.com/12162433/166315998-12230cba-8ad8-465c-a828-07344891a42f.png"> |
> [GAL-125] Fix tiny svgs

- pages/members/poster.tsx
- src/scenes/PosterPage/PosterPage.tsx
- src/scenes/_Router/GalleryRoute.tsx
- remove gallery link underneath title
- adjust layout to resemble nft detail page layout
- add footer on desktop
Before (desktop)
After (desktop)
Before (mobile)
After (mobile)
> address poster page design feedback

- src/flows/shared/steps/OrganizeCollection/Editor/StagingArea.tsx
Fixes an issue where hitting "refresh wallet" triggers a full-screen error. Screenshots on ticket.
> [GAL-130] Fix DBID not found error

- schema.graphql
- src/contexts/collectionEditor/CollectionEditorContext.tsx
- src/contexts/collectionEditor/deduplicateObjectByOpenseaIdAndPreferEarliest.test.ts
- src/contexts/collectionEditor/deduplicateObjectByOpenseaIdAndPreferEarliest.ts
- src/flows/shared/steps/OrganizeCollection/Editor/CollectionEditor.tsx
- src/flows/shared/steps/OrganizeCollection/types.ts
> [GAL-138] Deduplicate NFTs by opensea ID in sidebar

- sentry.client.config.js
Enable sentry tracing when connecting to local backend
> Enable sentry tracing when connecting to local backend

- src/scenes/CommunityPage/CommunityPageList.tsx
> Prevent new tab on username click on community page

- pages/opengraph/collection/[collectionId].tsx
- pages/opengraph/nft/[nftId].tsx
- pages/opengraph/user/[username].tsx
Reduce unnecessary spam that clutters our Sentry quota. More context in Threads.
> [GAL-146] Disable opengraph error reporting

- src/contexts/auth/AuthContext.tsx
Tracing used to be broken at the final login step because we fetch user info imperatively via Queries.
**Before**
**After**
> [GAL-148] Fix tracing for logins

- src/hooks/useTimer.ts
- src/scenes/PosterPage/PosterPage.tsx
- src/utils/featureFlag.ts
This PR enables the poster page on PROD.
changes included:
- link to blog post from Poster Page
- set deadline to midnight at 5/19 (can submit through 5/18)
- enable feature flag
> Enable poster page and link to blog post

- package.json
- src/constants/poster.ts
- src/hooks/useTimer.test.tsx
- src/hooks/useTimer.ts
- src/scenes/PosterPage/PosterBanner.tsx
- src/scenes/PosterPage/PosterPage.tsx
- yarn.lock
Added test scenario to cover `useTimer` hooks
1. Make sure its render the timestamp
2. If its the past date, it should return `hasEnded` false
3. if one hour left, it should correct timestamp and not ended
4. if one minute left, it should correct timestamp and not ended
> Add unit test for timer hooks

- src/components/NavActions/Follow.tsx
- src/components/core/Markdown/Bold.tsx
- src/components/core/Markdown/Link.tsx
- src/components/core/Markdown/List.tsx
- src/components/core/Markdown/MarkdownShortcuts.tsx
- src/components/core/TextArea/TextArea.tsx
alternate solution for triggering onChange when manually setting textarea value as discussed in #748
> alternate solution for triggering onChange when manually setting textarea value

- src/components/core/Markdown/Markdown.tsx
- src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
- src/scenes/NftDetailPage/NftDetailNote.tsx
- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
sync'd with jess on this; bullets were really messed up beforehand!
> Fix markdown styling

- src/scenes/_Router/GalleryRoute.tsx
PR to disable the poster banner now that the submission window is closed
Follow up PR to clean up unused banner coming soon, after we decide we don't need it
> disable poster banner

- src/components/core/transitions.ts
Bump modal transitions from 12px to 16px after pairing with jess
> Increase modal, NFT detail transition pixels

- src/contexts/globalLayout/GlobalNavbar/LoggedInNav.tsx
This PR makes clicking your username in the navbar reveal a dropdown.
The dropdown has two options: "My Gallery" and "Manage Accounts"
> [GAL-193 ] Implement new account mgmt navbar dropdown

- src/components/TokenHolderList/TokenHolderList.tsx
- src/components/TokenHolderList/TokenHolderListFilter.tsx
- src/scenes/CommunityPage/CommunityPage.tsx
- src/scenes/CommunityPage/CommunityPageView.tsx
- src/scenes/MemberListPage/MemberListPage.tsx
- src/scenes/NftDetailPage/NftDetailText.tsx
- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
- src/scenes/UserGalleryPage/UserGalleryCollections.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
- src/scenes/UserGalleryPage/UserGalleryLayout.tsx
This PR updates spacing for the following pages:
> [GAL-174] Implement updated spacing

- src/scenes/MembershipMintPage/cardProperties.ts
> Fix broken membership card images

- src/components/core/BigInput/BigInput.tsx
- src/components/core/TextArea/TextArea.tsx
> Input text => offBlack

- src/scenes/NftDetailPage/NftDetailAnimation.tsx
- src/scenes/NftDetailPage/processIFrameRenderUrl.test.ts
- src/scenes/NftDetailPage/processIFrameRenderUrl.ts
currently broken NFT:
https://gallery.so/casesimmons/27oC0NfBanAVu4nTtT9fW0rhx3U/243tlMKJse9JXhlQ53JFTGGBRmZ
Before:
After:
> Process broken youtube embeds

- src/components/FadeTransitioner/FadeTransitioner.tsx
- src/hooks/useBackButton.tsx
Bug repro steps:
1. arrive directly at an NFT detail page
2. close out and arrive at collection page
3. click username breadcrumb
4. modal re-opens (instead of taking you to the user's profile)
> Fix broken back button

- src/scenes/NftDetailPage/processIFrameRenderUrl.ts
> Cleanup youtube embed

- src/scenes/CollectionGalleryPage/CollectionGallery.tsx
- src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
original request:
**desktop**
**mobile**
> Improve collection header, options placement

- src/components/core/Dropdown/SettingsDropdown.tsx
- src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
- src/scenes/UserGalleryPage/MobileLayoutToggle.tsx
> Fix share layout regression on mobile

- src/flows/shared/steps/OrganizeCollection/Editor/ColumnAdjuster.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/SortableStagedNft.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/SortableStagedWhitespace.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/StagedNftImage.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/StagingArea.tsx
- src/flows/shared/steps/OrganizeCollection/Editor/constants.ts
- src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
- src/scenes/NftDetailPage/processIFrameRenderUrl.test.ts
**1) Fixes this user reported error**
**2) Ensures icon appears disabled if user reaches the end**
| ![Screen Shot 2022-05-30 at 1 20 04 AM](https://user-images.githubusercontent.com/12162433/170922064-451dd63d-f248-4b5c-9ef1-9808e58fd6e8.png) | ![Screen Shot 2022-05-30 at 1 20 11 AM](https://user-images.githubusercontent.com/12162433/170922063-d6588d2a-d83c-4048-94ec-86666bb3f092.png) |
**3) Hides label on smaller widths to prevent overflow**
Before
After
> Fix editor column adjuster

- src/scenes/PosterPage/PosterMintButton.tsx
- src/scenes/PosterPage/PosterPage.tsx
> Address poster typos

- src/contexts/wizard/WizardDataProvider.tsx
Fix full-screen errors for `DecoratedCollectionEditor could not access queryRef`
> Fix queryref bug

- src/components/WalletSelector/WalletSelector.tsx
- src/contexts/membershipMintPage/MembershipMintPageContext.tsx
- src/scenes/MembershipMintPage/CustomizedGeneralMembershipMintPage.tsx
- src/scenes/MembershipMintPage/GeneralMembershipMintPage.tsx
- src/scenes/MembershipMintPage/cardProperties.ts
Loom recording of flow shared in Early Access Launch thread
more comments in PR
> Early access allowlist flow

- src/contexts/globalLayout/GlobalNavbar/LoggedInNav.tsx
- src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
- src/scenes/UserGalleryPage/LinkButton.tsx
- src/scenes/UserGalleryPage/QRCode.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
- src/utils/graphql/isFeatureEnabled.tsx
This PR makes collection headers and navbar more in line with the Figma designs specified by Jess.
> [GAL-238] Fix collection header & layout

- src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
| ![Screen Shot 2022-06-16 at 11 40 09 PM](https://user-images.githubusercontent.com/12162433/174222321-9d0f7be5-e115-4743-a356-6056800f11a9.png) | ![Screen Shot 2022-06-16 at 11 39 29 PM](https://user-images.githubusercontent.com/12162433/174222339-1b588f8c-65e5-4163-a416-6cba6034e579.png) |
> Improve mobile header for collections

- src/components/Follow/NavActionFollow.tsx
consulted with jess on design / UX 👍
> Hide follow icon when you're signed out

- src/constants/storageKeys.ts
- src/contexts/globalLayout/GlobalBanner/GlobalBanner.tsx
- src/contexts/globalLayout/GlobalLayoutContext.tsx
> [GAL-248] Maintenance banner

- src/scenes/MaintenancePage/MaintenancePage.tsx
> Tweak maintenance page

- src/contexts/globalLayout/GlobalBanner/GlobalBanner.tsx
- src/icons/CloseIcon.tsx
- Use correct 16x16 svg
- Update icon that's displayed in banner
> Update close icon

- src/constants/storageKeys.ts
- src/contexts/globalLayout/GlobalLayoutContext.tsx
this PR removes the maintenance banner
> remove maintenance banner

- src/contexts/AppProvider.tsx
- src/scenes/MaintenancePage/MaintenancePage.tsx
This reverts commit 6f7074fe44be8e9c2e43f9d7b0214ff03295c0a7.
> Revert "default to maintenance (#850)"

- src/scenes/CommunityPage/CommunityPage.tsx
Set the error not found page to full height in the community page
**Before**
**After**
> [GAL-254] Set full height for not found community

- schema.graphql
- src/contexts/wizard/WizardDataProvider.tsx
- src/hooks/api/tokens/useSyncTokens.ts
conform to new schema as seen on https://github.com/gallery-so/go-gallery/pull/421
> refreshTokens => syncTokens

- pages/_secret.tsx
- src/components/core/colors.ts
- src/constants/storageKeys.ts
- src/contexts/globalLayout/GlobalAnnouncementPopover/Feed/GalleryOfTheWeekCard.tsx
- src/contexts/globalLayout/GlobalAnnouncementPopover/GlobalAnnouncementPopover.tsx
- src/contexts/globalLayout/GlobalAnnouncementPopover/useGlobalAnnouncementPopover.tsx
- src/index.css
> [GAL-264] Fast follows for feed popover

- src/scenes/LandingPage/LandingPage.tsx
small Mixpanel addition to track clicking on "Sign In" button on landing page
> track click on sign in button on landing page

- pages/announcements.tsx
- src/contexts/globalLayout/GlobalAnnouncementPopover/GlobalAnnouncementPopover.tsx
- src/contexts/globalLayout/GlobalAnnouncementPopover/useGlobalAnnouncementPopover.tsx
- prevent heavy gallery of the week query from being fired by default
- prevent popover from being displayed for new users onboarding
> Fix announcement popover behavior

- src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
- src/components/Feed/Feed.tsx
- src/components/Feed/FeedList.tsx
> Additional feed improvements

- src/flows/shared/steps/OrganizeGallery/CollectionRow.tsx
- src/flows/shared/steps/OrganizeGallery/CollectionRowDragging.tsx
- src/flows/shared/steps/OrganizeGallery/CollectionRowWrapper.tsx
- src/flows/shared/steps/OrganizeGallery/Header.tsx
- src/flows/shared/steps/OrganizeGallery/SortableCollectionRow.tsx
> Collection header fixes in Organize Gallery

- src/scenes/UserGalleryPage/UserGalleryCollections.tsx
Required for figure31 end state where every piece has been sold
> Ensure collection with only whitespace is still visible

- src/components/NftPreview/FailedNftPreview.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarNftIcon.tsx
will help once we're on our own indexer where spam NFTs will be more prolific
> Display likely spam NFTs (those without images) at the bottom of sidebar

- src/utils/graphql/isFeatureEnabled.tsx
- src/utils/token.ts
> Indexer transition touchups

- src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarNftIcon.tsx
- src/hooks/api/tokens/useRefreshToken.ts
- src/scenes/NftDetailPage/NftDetailAnimation.tsx
- src/utils/graphql/getVideoOrImageUrlForNftPreview.ts
**Before**
Corrupt images appearing in the middle of the sidebar
**After**
Corrupt image URLs moved to bottom, and made consistent with images that don't have a URL
> Address post-indexer issues

- src/components/HoverCard/HoverCardOnUsername.tsx
**Hide the follow button if its logged in user card**
**Removed the hidden collection from total number**
> [GAL-307] [GAL-306] Popover Improvement

- src/constants/sidebar.ts
- src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarNftIcon.tsx
Apply react virtualize to the sidebar in edit gallery page.
**Notes on how it works**
Utilize the `List]` component but added 3 items in each row.
| blank | 0 | 1 |
|-------|---|---|
| 2     | 3 | 4 |
| 5     | 6 | 7 |
**Demo**
https://user-images.githubusercontent.com/4480258/181875673-be42f6ff-f0ac-408a-b5af-f17aa9e92ba9.mp4
> [GAL-305] Virtualize Sidebar

- src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
> Fix sidebar search crash

- package.json
- yarn.lock
Trying to see if this fixes the tabbing/deep-link behavior of iOS browser -> Rainbow -> back
> small version bump of rainbowkit/wagmi

- src/hooks/useMintContractWithQuantity.tsx
- src/scenes/MerchStorePage/MerchMintButton.tsx
- src/scenes/MerchStorePage/PurchaseBox.tsx
- Moved more connection logic into `useMintContractWithQuantity`
- Force disconnect on mount to make user deliberately connect a wallet each time
Screencap: https://drive.google.com/file/d/1H3ViwWAuPIWHZP2xMJVpNFqclp6U3prp/view?usp=sharing
> Merch wallet connector (rainbow)

- .github/workflows/e2e.yml
- cypress.json
- cypress/integration/pages/home/home-page.ts
- cypress/integration/pages/page.ts
- cypress/integration/specs/home-spec.ts
Update sign flow cypress to adapt rainbowkit changes
> Update Auth cypress test cases

- codegen.yml
- package.json
- yarn.lock
The issue is described in detail here https://github.com/dotansimha/graphql-code-generator/issues/7888
I'm not waiting around for them to land my PR [here](https://github.com/dotansimha/graphql-code-generator/pull/7881) so we just forked and published to `@gallery-so/typescript-operations` for now.
> use gallery typescript operations fork

- src/scenes/MerchStorePage/PurchaseBox.tsx
> Add info about shipping to single item page and change year to 2022

- src/components/Follow/FollowerListButton.tsx
- src/components/Follow/NavActionFollow.tsx
Always show followers button for better discoverability
> always show followers button

- schema.graphql
- src/components/WalletSelector/AddWalletPending/AddWalletPendingDefault.tsx
- src/components/WalletSelector/AuthenticateWalletPending/AuthenticateWalletPendingDefault.tsx
- src/components/WalletSelector/multichain/EthereumAddWallet.tsx
- src/components/WalletSelector/multichain/EthereumAuthenticateWallet.tsx
- src/components/WalletSelector/mutations/useLoginOrRedirectToOnboarding.ts
Frontend changes to accommodate breaking changes introduced in https://github.com/gallery-so/go-gallery/pull/479
> EOA Auth Breaking Change

- package.json
- src/components/core/enums.ts
- src/contexts/globalLayout/GlobalFooter/GlobalFooter.tsx
- src/contexts/globalLayout/GlobalLayoutContext.tsx
- src/contexts/globalLayout/GlobalNavbar/LoggedInNav.tsx
- src/icons/LogoBracketLeft.tsx
- src/icons/LogoBracketRight.tsx
- src/scenes/LandingPage/LandingPage.tsx
- src/scenes/MerchStorePage/MerchStorePage.tsx
- src/scenes/MerchStorePage/SingleItemPage.tsx
- src/utils/graphql/isFeatureEnabled.tsx
Update (OBJECTS) to use proper brackets
> Add shop to logged in dropdown

- src/hooks/api/users/useCreateUser.ts
Fixes user reported bug. Verified the update works on dev.
> Fix reported user creation

- src/scenes/LandingPage/LandingPage.tsx
> [gotw] shatt

- src/components/NftFailureFallback/NftFailureFallback.tsx
- src/hooks/useNftRetry.tsx
- Fix aspect ratio on browsers that don't support `aspect-ratio`
- Refresh on retry to solve Relay bug for now
- Tooltip animation and offset
> NFT Retry Follow-Ups

- src/components/NftFailureFallback/NftFailureFallback.tsx
Addresses the issue in this video
**see comment in code for how i fixed this issue**
https://user-images.githubusercontent.com/6754223/187350892-273fd191-5c44-4230-8f0e-f92f8511bad2.mov
> reset tooltip state when refreshing

- src/components/ManageWallets/ManageWallets.tsx
- src/components/ManageWallets/ManageWalletsRow.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/WalletSelector/multichain/EthereumAddWallet.tsx
- src/components/WalletSelector/multichain/MultichainWalletSelector.tsx
- src/components/WalletSelector/multichain/WalletButton.tsx
- src/components/WalletSelector/multichain/tezos/TezosAddWallet.tsx
- src/components/WalletSelector/multichain/tezos/TezosAuthenticateWallet.tsx
- src/components/WalletSelector/multichain/tezos/tezosUtils.ts
- src/components/WalletSelector/mutations/useAddWallet.ts
- src/components/core/Button/Button.tsx
- src/components/core/colors.ts
- src/contexts/AppProvider.tsx
- src/contexts/beacon/BeaconContext.tsx
**Changes**
- Allow user to add tezos wallet into existing account
- Update UI for disconnect account
- Add chain icon in the list of accounts
- Used tooltip to display add/remove account
**Demo**
**Disconnect UI**
**Tooltips**
**Toastr**
**Full flow**
https://user-images.githubusercontent.com/4480258/187855123-c1b8a60b-e820-446f-97a4-6feb2e274fb3.mp4
> [GAL-342] [GAL-343] Add/Remove tezos wallet flow

- src/contexts/beacon/BeaconContext.tsx
- tests/graphql/mockGlobalLayoutQuery.ts
**Changes**
- Added `displayName` on the beacon context
- Add `chain` paramater to the mock global layout query
> Update unit test & fix lint

- src/contexts/toast/Toast.tsx
Before            |  After
:-------------------------:|:-------------------------:
> Toast Improvements

- src/components/NftFailureFallback/NftFailureFallback.tsx
- src/components/NftPreview/NftPreview.tsx
> actually fix failure fallback sizing

- src/components/WalletSelector/DeprecatedWalletSelector.tsx
- src/components/WalletSelector/multichain/MultichainWalletSelector.tsx
- src/components/core/Button/Button.tsx
- src/hooks/useMultiKeyDown.tsx
- always enable shortcut
- update shortcut to use Shift + T (instead of Ctrl + T)
- update `useMultiKeyDown` to be case insensitive
- update auth copy from wallets => chains
> Enable tezos button shortcut

- src/components/NftPreview/NftPreviewLabel.tsx
left over css rule for debugging
> remove important opacity

- package.json
- yarn.lock
https://nextjs.org/blog/next-12-3
didn't enable `swcMinify` since it seemed to make things slower
> upgrade to next 12.3

- src/contexts/globalLayout/GlobalAnnouncementPopover/useGlobalAnnouncementPopover.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarChainSelector.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/isRefreshDisabledForUser.ts
- src/hooks/oneOffs/useIs3ac.ts
- src/hooks/oneOffs/useIs3acProfilePage.ts
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
same applies for 3AC gallery so there was a light refactor
> Disable refresh button for test user

- src/contexts/globalLayout/GlobalLayoutContext.tsx
- src/contexts/modal/ModalContext.tsx
- src/contexts/toast/ToastContext.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarList.tsx
- src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetailsPOAP.tsx
- src/scenes/NftDetailPage/NftDetailText.tsx
- src/utils/getScrollbarWidth.ts
https://linear.app/galleryso/issue/GAL-436/hidden-toast-blocks-click-events-in-editor
https://linear.app/galleryso/issue/GAL-433/sidebar-scrollbar-appears-a-bit-tighter-than-before
**Before**
https://user-images.githubusercontent.com/6754223/190508204-82c68c92-32c1-40f2-92e2-9f0b2cd22eb1.mov
**After**
https://user-images.githubusercontent.com/6754223/190508188-5cfff832-827b-482b-b545-8ded2218dffd.mov
We just needed to handle the fallback correctly
> Bug fixes GAL-436 GAL-433 + others 

- src/scenes/NftDetailPage/NftDetailAsset.tsx
Fixes regression introduced in https://github.com/gallery-so/gallery/pull/939/files
> Fix bug with oveflowing video height on NFTDetail

- src/contexts/globalLayout/GlobalBanner/GlobalBanner.tsx
- src/contexts/globalLayout/GlobalLayoutContext.tsx
- src/contexts/modal/ModalContext.tsx
> Add poap banner

- src/errors/CouldNotRenderNftError.ts
- src/hooks/useNftRetry.tsx
- src/scenes/NftDetailPage/NftDetailVideo.tsx
- src/utils/browser.ts
**Collection Page**
| <img width="350" alt="image" src="https://user-images.githubusercontent.com/12162433/191901671-fdcce71e-11ff-4dd8-9cbd-a46ad7658375.png"> | <img width="354" alt="image" src="https://user-images.githubusercontent.com/12162433/191900676-de1032e9-35f4-486e-8cac-4656ac942c16.png"> |
**Detail Page**
| <img width="349" alt="image" src="https://user-images.githubusercontent.com/12162433/191901748-d22d7a38-f220-4cb7-a65f-aa5b3b02ab5f.png"> | <img width="355" alt="image" src="https://user-images.githubusercontent.com/12162433/191900699-e677653f-ccb9-495a-813e-46aa51ad15df.png"> |
**Tests**
> [GAL-451] Fix videos on iOS safari

- src/components/WalletSelector/multichain/MultichainWalletSelector.tsx
- src/components/core/enums.ts
- src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarChainSelector.tsx
- src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetailsEth.tsx
- src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetailsTezos.tsx
- src/utils/graphql/isFeatureEnabled.tsx
- src/utils/tezosEarlyAccess.ts
Enable tezos and cleanup resolved feature flags
> Enable tezos ⚡️

- src/contexts/globalLayout/GlobalAnnouncementPopover/GlobalAnnouncementPopover.tsx
Add theblkchain and Jeres to the popover, 2 partners for the launch
> add 2 partners

- src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
> Fix feed event spacing

- src/contexts/globalLayout/GlobalAnnouncementPopover/GlobalAnnouncementPopover.tsx
> add another partner

- src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetailsTezos.tsx
- src/utils/getObjktExternalUrl.ts
- src/utils/getTezosExternalUrl.ts
**Tezos NFT from FxHash**
**Tezos NFT not on FxHash**
**ETH NFT (no regression)**
> [GAL-468] Support fxhash external url

- tests/setupFileAfterEnv.js
> Fix broken unit tests

- src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetailsTezos.tsx
> FxHash => fx(hash)

- src/flows/OnboardingFlow/steps/CreateFirstCollection.tsx
Seems like a UI regression on Spacer
**Before**
**After**
> Fix Create first collection UI

- schema.graphql
- src/components/Badge/Badge.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
- src/scenes/UserGalleryPage/UserGalleryLayout.tsx
- src/utils/graphql/isFeatureEnabled.tsx
**Changes**
Show art gobbler badge if the user has badge with `image URL`. 
In this case, we mock with ENS collection. 
**Demo on Profile**
https://user-images.githubusercontent.com/4480258/192439948-df90f0a9-e86c-4807-bb52-be9ffaa840ea.mp4
> [GAL-464] Implement Badges UI on Profile username

- src/flows/shared/steps/OrganizeCollection/Sidebar/AddWalletSidebar.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarChainSelector.tsx
- src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarTokens.tsx
**Changes**
Only applicable  to the users that didn't connect any wallet based on selected editor chain
1. Show **Connect {selectedChain} wallet** Button that will trigger the manage accounts modal
2. Sync button will be disabled
3. Can't add blank space
**Demo**
**Scenario without tezos account**
https://user-images.githubusercontent.com/4480258/192956157-9332377d-8973-433a-a603-498e28dfa61c.mp4
**Scenario without ethereum account**
https://user-images.githubusercontent.com/4480258/193236356-1443b606-3d2b-4b7f-aca1-89caa98acf51.mp4
**Scenario without ethereum account for POAP**
https://user-images.githubusercontent.com/4480258/193236860-bfc3bfb5-6726-491c-9980-44c6869de3aa.mp4
**Note**
I'll open a follow up PR for the auto refresh!
> [GAL-463] Default Editor if not connected

- src/contexts/globalLayout/GlobalAnnouncementPopover/useGlobalAnnouncementPopover.tsx
disable for curated upon request
> Disable full page modal for select users

- src/contexts/globalLayout/GlobalLayoutContext.tsx
POAP banner is still being shown unnecessarily
> Toss poap banner

- src/components/ManageGallery/OrganizeCollection/CollectionCreateOrEditForm.tsx
- src/hooks/api/collections/useCreateCollection.ts
- src/hooks/api/collections/useUpdateCollectionInfo.ts
We weren't handling server errors appropriately
> [GAL-521] Collection Description too long bug fix

- src/components/Feed/Events/UserFollowedUsersFeedEvent.tsx
I forgot to add the border / padding to follow events
> [GAL-542] add border styles to follow event

- schema.graphql
- src/components/NftPreview/NftPreview.tsx
- src/components/NftPreview/NftPreviewAsset.tsx
- src/scenes/NftDetailPage/NftDetailAsset.tsx
- src/scenes/NftDetailPage/NftDetailGif.tsx
- src/utils/graphql/getVideoOrImageUrlForNftPreview.ts
- src/utils/isLiveMediaType.ts
https://user-images.githubusercontent.com/12162433/196815172-e48955c8-68fe-40a0-b7ff-57363265d170.mov
> Gif Liverender Support

- schema.graphql
- src/components/NftPreview/NftPreview.tsx
- src/components/NftPreview/NftPreviewAsset.tsx
- src/components/TokenHolderList/TokenHolderList.tsx
- src/scenes/CommunityPage/CommunityPageView.tsx
- src/scenes/MemberListPage/MemberListTier.tsx
- src/scenes/NftDetailPage/NftDetailAsset.tsx
- src/scenes/NftDetailPage/NftDetailGif.tsx
- src/utils/graphql/getVideoOrImageUrlForNftPreview.ts
- src/utils/isLiveMediaType.ts
Example community to test with: http://localhost:3000/community/0x5180db8f5c931aae63c74266b211f580155ecac8
> Update community schema

- package.json
- pages/_app.tsx
- yarn.lock
[awaiting upgrade to react 18]
> Vercel analytics

- pages/home.tsx
- src/index.css
https://user-images.githubusercontent.com/6754223/198928619-5647321e-4dcb-47aa-bb7f-bf374dd10622.mov
> halloween easter egg

- src/components/NftPreview/NftPreviewLabel.tsx
- src/scenes/NftDetailPage/NftDetailText.tsx
- src/utils/htmlDecode.ts
> [GAL-576] HTML Encoding Chars on Token Name

- src/contexts/toast/Toast.tsx
- src/contexts/toast/ToastContext.tsx
Keys based on the message were a bad idea
> Fix keys on toasts

- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
> art gobblers badge fix

- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
This bug happens on two different places
1. Bio
1. Collection description
**Before**
**After**
> [GAL-596] Fix newlines markdown

- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdownContent.tsx
Replace connect wallet modal with manage wallet modal
**Before**
https://user-images.githubusercontent.com/4480258/200292692-11a9aa04-b5af-4b5e-a2f8-11855cc156a3.mp4
**After**
https://user-images.githubusercontent.com/4480258/200292925-0377d1a4-34c1-4e22-af4a-8d2f8ad6e277.mp4
> Fix manage wallet modal

- src/scenes/UserActivityPage/UserActivity.tsx
Removed the key listener in the activity page
Note: not sure why I wrote this in the first place 🤦
> [GAL-671] Fixed activity page redirect

- src/components/Feed/Socialize/AdmireButton.tsx
- src/components/Feed/Socialize/CommentBox.tsx
- src/components/Follow/FollowButton.tsx
- src/contexts/globalLayout/GlobalNavbar/CollectionSaveButtonWithCaption.tsx
This PR adds events for rhino features. 
For signed in users:
- Click admire button
- Click send comment
- Saved collection with caption
- Click follow button
- Click unfollow
> Add events for rhino features

- package.json
- schema.graphql
- src/utils/graphql/isFeatureEnabled.tsx
- tests/graphql/mockGlobalLayoutQuery.ts
Pretty simple, made a new map of `Role => Flag => Boolean`. 
I also updated the `isFeatureEnabled` function to return `true` if any of the checks are `true`. This fixes the annoying situation where I update `PROD_FLAGS` but don't update `EMPLOYEE_FLAGS` and then none of the employees at Gallery can access it
Re: the schema changes
I added a script to fetch the latest schema from `main`. this should stop people's editors from formatting the file. 
In this PR, I just copied the file directly and I didn't see any formatting happening. So I'm not sure who the culprit is 🕵️
> Role Feature Flags

- src/components/Feed/Socialize/CommentBox.tsx
- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdownContent.tsx
this PR adds an event for when the user opens their Notifications.
and renames the Comment Saved event.
> Add more events for Rhino

- src/components/Email/EmailVerificationStatus.tsx
- src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
- src/components/NotificationsModal/Notification.tsx
- src/components/NotificationsModal/NotificationUserListTitle.tsx
- src/components/NotificationsModal/NotificationsModal.tsx
- src/contexts/globalLayout/GlobalNavbar/FeedNavbar/FeedLeftContent.tsx
- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/NavUpArrow.tsx
- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdown.tsx
**Incosistent feed event on mobile**
| Before  | After |
| ------------- | ------------- |
|  ![image (2)](https://user-images.githubusercontent.com/4480258/201620063-80044d36-7187-4668-b780-22f230f5adc4.png) | <img width="343" alt="CleanShot 2022-11-14 at 17 10 30@2x" src="https://user-images.githubusercontent.com/4480258/201620369-3ec82e99-c204-423f-9336-f113ee888c42.png">  |
**Edit Email button**
| Before  | After |
| ------------- | ------------- |
| <img width="288" alt="CleanShot 2022-11-14 at 17 11 34@2x" src="https://user-images.githubusercontent.com/4480258/201620598-75ce9a08-14bc-4714-bc15-313caaa36fa5.png">  | <img width="507" alt="CleanShot 2022-11-14 at 17 11 47@2x" src="https://user-images.githubusercontent.com/4480258/201620675-81a5c992-3810-4bc7-853a-61c84855af7a.png">  | …
> [GAL-624] White Rhino UI Fix

- src/components/Feed/FeedList.tsx
- src/components/Feed/Socialize/NoteModalOpenerText.tsx
- src/components/Feed/Socialize/NotesModal/NotesModal.tsx
- src/components/NotificationsModal/CollectionLink.tsx
- src/components/NotificationsModal/NotificationUserListModal.tsx
- src/components/NotificationsModal/NotificationsModal.tsx
- src/components/NotificationsModal/UserListItem.tsx
- src/components/NotificationsModal/notifications/SomeoneCommentedOnYourFeedEvent.tsx
- src/components/NotificationsModal/notifications/SomeoneViewedYourGallery.tsx
- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdownContent.tsx
- src/contexts/modal/ModalContext.tsx
https://user-images.githubusercontent.com/6754223/201377982-968c8644-a94b-4e60-923e-2042213da4e8.mov
> White rhino UI fixes

- src/components/Email/EmailForm.tsx
- src/components/core/Toggle/Toggle.tsx
- src/scenes/Modals/SettingsModal.tsx
**If no email attached, show the toggle but disabled it**
**Disabled toggle & turn off if the email not verified**
https://user-images.githubusercontent.com/4480258/202082185-09e52bd8-9226-49de-97c9-0c536ac8c08c.mp4
**Instantly updated the verification status**
https://user-images.githubusercontent.com/4480258/202081964-6ef7da88-ed05-4bc9-9c01-b81ae2f00f47.mp4
**Disabled toggle color**
> [GAL-670] Email Follow Up

- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdownContent.tsx
changes edit gallery font size from 10px to 12px
> change edit gallery font size to 12px

- src/components/NotificationsModal/NotificationsModal.tsx
This PR adds a loader to the suspense state of the notifications popover.
Video: (the changing width of the notifications popover is separate bug, ill make a different pr)
https://user-images.githubusercontent.com/80802871/202093628-d4e7ced2-8398-4ee2-92e2-7536be7fba5c.mp4
> [GAL-622] add loader to notifications

- pages/[username]/[collectionId]/index.tsx
- pages/[username]/activity.tsx
- pages/[username]/followers.tsx
- pages/[username]/galleries.tsx
- pages/[username]/index.tsx
- src/components/internal/GalleryViewEmitter.tsx
- src/scenes/NftDetailPage/NftDetailPage.tsx
Also fire off view events for all `/[username]/x`
> [GAL-571] Disable anonymous notifications

- src/components/Feed/Events/EventMedia.tsx
- src/components/Feed/Events/EventStyles.tsx
- src/components/Feed/Events/UserFollowedUsersFeedEvent.tsx
- src/components/Feed/FeedEvent.tsx
- src/components/Feed/FeedEventTokenPreviews.tsx
- src/components/Feed/Socialize/CommentLine.tsx
- src/components/Feed/Socialize/FeedEventSocializeSection.tsx
- src/components/Feed/dimensions.ts
**Desktop**
https://user-images.githubusercontent.com/12162433/202081874-00ae3c37-acad-4f5b-bf65-e63356c2c24d.mov
**Tablet, Mobile**
https://user-images.githubusercontent.com/12162433/202081822-61fd5dab-5a42-42ad-b528-fe1680b2f368.mov
**Timestamp alignment**
_Before_
_After_
> [GAL-677] Feed visual improvements

- codegen.yml
- pages/[username]/[collectionId]/index.tsx
- pages/[username]/activity.tsx
- pages/[username]/followers.tsx
- pages/[username]/galleries.tsx
- pages/[username]/index.tsx
- src/components/Feed/Socialize/AdmireLine.tsx
- src/components/Feed/Socialize/Interactions.tsx
- src/components/NotificationsModal/Notification.tsx
- src/components/NotificationsModal/NotificationsModal.tsx
- src/components/NotificationsModal/notifications/SomeoneAdmiredYourFeedEvent.tsx
- src/components/NotificationsModal/notifications/SomeoneCommentedOnYourFeedEvent.tsx
- src/components/NotificationsModal/notifications/SomeoneViewedYourGallery.test.tsx
- src/components/NotificationsModal/notifications/SomeoneViewedYourGallery.tsx
- src/components/internal/GalleryViewEmitter.tsx
- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdown.tsx
- src/scenes/NftDetailPage/NftDetailPage.tsx
- src/scenes/UserGalleryPage/UserGalleryLayout.tsx
|  Old  | New  |
|---|---|
| <img width="1245" alt="image" src="https://user-images.githubusercontent.com/6754223/201765783-f7e1556c-88f0-47b5-892e-4e5aba45dd68.png"> |  <img width="1238" alt="image" src="https://user-images.githubusercontent.com/6754223/201765725-86d1162e-162f-432a-a6dd-5153d7198248.png"> |
https://user-images.githubusercontent.com/6754223/201766014-2402e900-1d2f-43c5-a281-add14f7bdb63.mov
Look at the test cases in `SomeoneViewedYourGallery.test.tsx` to see how we're handling different situations. Right now the backend is erroring out so I can't actually see my changes. Let's wait on that fix to land this
> More UI fixes

- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdownContent.tsx
This PR adds back the event tracking for opening notifications. it was added in #1114 but I think It was overwritten accidentally
> Add back event for opening notifs

- pages/[username]/index.tsx
- src/components/Email/useUnsubscribeEmail.ts
- src/components/Email/useVerifyEmailActivation.tsx
- src/components/Email/useVerifyEmailOnPage.ts
- src/components/NotificationsModal/NotificationList.tsx
- src/scenes/Modals/SettingsModal.tsx
- src/scenes/UserGalleryPage/UserGalleryPage.tsx
URL: [http://localhost:3000/jakz?settings=true&unsubscribeToken=1234](http://localhost:3000/jakz?settings=true&unsubscribeToken=1234)
**Logged in user**
https://user-images.githubusercontent.com/4480258/202331083-6cec6351-fec4-4c10-9824-013a9d14788b.mp4
**If the user not signed in**
https://user-images.githubusercontent.com/4480258/202331272-c44fe328-7a58-46ea-be84-1c07b4edd337.mp4
> [GAL-679] Unsubscribe email

- .eslintrc.cjs
- pages/gallery/[galleryId]/collection/[collectionId]/edit.tsx
- pages/gallery/[galleryId]/collection/create.tsx
- pages/onboarding/edit-collection.tsx
- pages/onboarding/organize-collection.tsx
- src/components/ManageGallery/OrganizeCollection/Editor/CollectionEditor.tsx
- src/components/ManageGallery/OrganizeCollection/Editor/formatStagedCollection.ts
- src/contexts/globalLayout/GlobalNavbar/CollectionSaveButtonWithCaption.tsx
**Disabled button if no changes**
**[Fix delete token consider unchanged](https://linear.app/galleryso/issue/GAL-687/save-doesnt-work-when-deleting-piece)**
https://user-images.githubusercontent.com/4480258/202367438-60aeb33a-4ec6-460b-920d-154d9c4970ca.mp4
**New flow**
https://user-images.githubusercontent.com/4480258/202367630-2f9876e1-b534-4f3f-adc6-3823f4009bcb.mp4
> [GAL-674] [GAL-687] [GAL-675] New Caption Flow

- src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
- src/components/Feed/Events/CollectorsNoteAddedToCollectionFeedEvent.tsx
- src/components/Feed/Events/EventStyles.tsx
- src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
**If the feed has caption or description** 
**If the feed no caption - no background color**
> [GAL-689] Update feed caption

- src/contexts/globalLayout/GlobalNavbar/CollectionEditorNavbar/CollectionEditorNavbar.tsx
- src/contexts/globalLayout/GlobalNavbar/OnboardingCollectionEditorNavbar/OnboardingCollectionEditorNavbar.tsx
Its only happens on edit flow. The create collection flow is working fine
**Before**
**After**
> [GAL-690] fix unescape character

- src/contexts/globalLayout/GlobalNavbar/FeedNavbar/FeedLeftContent.tsx
- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/Breadcrumbs.tsx
> fix notification circle positioning on feed navbar

- src/contexts/globalLayout/GlobalAnnouncementPopover/GlobalAnnouncementPopover.tsx
- src/scenes/NftDetailPage/NftDetailAsset.test.tsx
- tests/graphql/mockGlobalLayoutQuery.ts
> fix announcement font stuff

- src/contexts/globalLayout/GlobalAnnouncementPopover/useGlobalAnnouncementPopover.tsx
Disable popover on a specific user's profile as it'll be featured at an exhibit
> Disable popover on 1of1 profile

- src/components/Follow/FollowListUsers.tsx
- src/components/NotificationsModal/NotificationUserListModal.tsx
- src/components/NotificationsModal/NotificationUserListTitle.tsx
**Fix overlap follower list**
| Before  | After |
| ------------- | ------------- |
| ![CleanShot 2022-11-21 at 11 56 21](https://user-images.githubusercontent.com/4480258/202962493-bc06beb6-9865-4c03-8904-9996cb4e50fc.png)  | ![CleanShot 2022-11-21 at 11 56 29](https://user-images.githubusercontent.com/4480258/202962504-87f52b57-35e9-4a7f-95b5-b08b99ece3cd.png) |
**Lowercase `Gallery views`**
| Before  | After |
| ------------- | ------------- |
| ![CleanShot 2022-11-21 at 11 59 27](https://user-images.githubusercontent.com/4480258/202962748-45cd0bce-ab1a-4c18-b08b-345a6ceec831.png)  | ![CleanShot 2022-11-21 at 11 59 19](https://user-images.githubusercontent.com/4480258/202962772-0068ec12-4c48-452e-ac0c-c9e7ae6bed01.png) |
** fix `...` in suspense **
**Before** …
> [GAL-711] [GAL-707] [GAL-708] white rhino follow up

- src/contexts/globalLayout/GlobalNavbar/CollectionEditorNavbar/GalleryNameAndCollectionName.tsx
Prompt "are you sure you want to leave" when clicking My Gallery from navbar in editor
**Before**
https://user-images.githubusercontent.com/4480258/202974364-fba419a0-e0c4-46c4-969f-09f1ce433015.mp4
**After**
https://user-images.githubusercontent.com/4480258/202974122-fbe60fb7-3892-44aa-aed1-e9f8c4643a9e.mp4
> [GAL-706] Add prompt on collection editor

- src/components/Feed/Events/UserFollowedYouEvent.tsx
> [GAL-702] Split user follow user event

- src/contexts/analytics/AnalyticsContext.tsx
- src/contexts/navigation/GalleryNavigationProvider.tsx
- src/scenes/CollectionGalleryPage/CollectionGalleryPage.tsx
- src/scenes/CommunityPage/CommunityPage.tsx
- src/scenes/NftDetailPage/NftDetailPage.tsx
- src/scenes/UserActivityPage/UserActivityPage.tsx
- src/scenes/UserGalleryPage/UserGalleryPage.tsx
**Changes**
- Added `checkAuth` options to `tracking`
- All the `Page View` will be recorded only its authenticated
> [GAL-724] Only track "Page View" events if user is signed in

- src/components/Follow/FollowListUsers.tsx
- src/utils/regex.test.tsx
- src/utils/regex.ts
**Changes**
Remove all the breakline for bio **only** in follower list modal
**Before**
**After**
> [GAL-709] fix bio appears weird in the follower list modal

- src/components/Feed/Socialize/NotesModal/CommentNote.tsx
- src/components/Feed/Socialize/NotesModal/UsernameLink.tsx
> [GAL-726] Wrap the comment

- src/components/Feed/Feed.tsx
There is feed width overflow on desktop
**Before**
**After**
> Fix feed overflow width

- next.config.js
- pages/_app.tsx
- src/contexts/relay/relayFetchFunction.ts
Something fucked started happening with out reverse proxy. Until we have more time to figure this out, let's just disable the reverse proxy and revert to good ol' CORS.
> disable reverse proxy and only prefetch on client

- .github/workflows/bundle-diff.yml
- next.config.js
Setting this up so we can monitor our bundle size going forward to avoid regressions https://github.com/transferwise/actions-next-bundle-analyzer
> Bundle Diff Github Action

- src/constants/storageKeys.ts
- src/contexts/globalLayout/GlobalBanner/GlobalBanner.tsx
- src/contexts/globalLayout/GlobalLayoutContext.tsx
- src/scenes/MaintenancePage/MaintenancePage.tsx
> New maintenance page, banner

- pages/gallery/[galleryId]/collection/[collectionId]/edit.tsx
- pages/gallery/[galleryId]/collection/create.tsx
- pages/onboarding/edit-collection.tsx
- pages/onboarding/organize-collection.tsx
- src/components/Feed/Events/FeedEventNftPreviewWrapper.tsx
- src/components/Feed/Events/UserFollowedYouEvent.tsx
- src/components/ManageGallery/OrganizeCollection/Editor/CollectionEditor.tsx
- src/components/ManageGallery/useConfirmationMessageBeforeClose.ts
- src/components/NftPreview/GalleryNftPreviewWrapper.tsx
- src/components/NftPreview/NftPreview.tsx
- src/contexts/globalLayout/GlobalNavbar/FeedNavbar/FeedNavbar.tsx
- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdown.tsx
- src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
- src/scenes/Modals/SettingsModal.tsx
- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
- src/scenes/UserGalleryPage/UserGalleryLayout.tsx
https://linear.app/galleryso/issue/GAL-747/weird-formatting
https://linear.app/galleryso/issue/GAL-749/collection-name-should-say-untitled-here
https://linear.app/galleryso/issue/GAL-745/replace-home-with-g-logo-on-home-page
https://linear.app/galleryso/issue/GAL-744/disable-all-nft-hover-states-on-moweb
https://linear.app/galleryso/issue/GAL-742/are-you-sure-you-want-to-leave-popover-should-not-appear-when-the-user
https://linear.app/galleryso/issue/GAL-734/manage-accounts-should-be-manage-accounts-on-settings-popover
https://linear.app/galleryso/issue/GAL-731/make-tap-area-of-the-logo-on-moweb-larger
https://linear.app/galleryso/issue/GAL-737/can-we-remove-the-follow-button-here
https://linear.app/galleryso/issue/GAL-733/16px-padding-above-the-username-on-the-profile-on-moweb
> Fix-it week fixes GAL-747 GAL-749 GAL-745 GAL-744 GAL-742 GAL-734 GAL-731 GAL-737 GAL-733

- src/components/Community/CommunityHolderList.tsx
- src/components/CommunityHolderGrid/CommunityHolderGrid.tsx
- src/components/CommunityHolderGrid/CommunityHolderGridItem.tsx
- src/components/HoverCard/HoverCardOnUsername.tsx
- src/components/TokenHolderList/TokenHolderList.tsx
- src/components/TokenHolderList/TokenHolderListItem.tsx
- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdown.tsx
- src/scenes/CommunityPage/CommunityPage.tsx
- src/scenes/CommunityPage/CommunityPageView.tsx
- src/scenes/MemberListPage/MemberListPage.tsx
- src/scenes/MemberListPage/MemberListTier.tsx
**Changes**
- fix notification position
- add children support to username hover card
- add hover card to community page (grid & list)
- add hover card to members page
- disabled the 3 images preview on community / members page
**Notes**
I've removed the 3 images preview on `/members` page too since community and members used the same component. Lmk if we wanna isolated this only to community page. 
**Demo**
**Notification**
**Before**
**After**
**Hover on community page (grid)**
https://user-images.githubusercontent.com/4480258/207018834-bf53c612-e1c4-42a5-9e5b-f9e0aa2817ca.mp4
**Hover card on community page (list)**
https://user-images.githubusercontent.com/4480258/207038462-fe349395-13d8-41fc-b6f9-41860e6e375a.mp4
**Hover card on members page** …
> [GAL-746] [GAL-800] Fix it week

- src/scenes/MintPages/ThankYouTokenPage.tsx
Added copy describing the eligibility criteria for the allowlist
> add details about eligibility criteria

- .github/workflows/bundle-diff.yml
we're always getting diffs since the main artifact isn't updating. this should fix that
> run bundle analyzer on main

- src/contexts/globalLayout/GlobalNavbar/CollectionNavbar/CollectionNavbar.tsx
- src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
> fix untitled collection regression

- src/scenes/MerchStorePage/MerchStorePage.tsx
> Add redemption announcement to shop page

- src/scenes/MintPages/ThankYouTokenPage.tsx
This PR extends the deadline for the thank you token mint so that people who requested to change their allowlisted address can mint this week.
> extend deadline for token

- src/components/NftPreview/NftPreviewLabel.tsx
- src/scenes/NftDetailPage/NftDetailText.tsx
> [GAL-1374] Remove pill if not clickable

- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
> [GAL-721] Fix bio truncate issue on safari

- src/scenes/UserActivityPage/UserActivityLayout.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
**Changes**
Added mobile padding in activity page
**Before**
**After**
> [GAL-1149] Fix activity space

- pages/gallery/[galleryId]/collection/create.tsx
- pages/onboarding/organize-collection.tsx
- sentry.client.config.js
- src/components/Feed/FeedEvent.tsx
- src/components/ManageGallery/OrganizeCollection/CollectionCreateOrEditForm.tsx
- src/contexts/boundary/ReportingErrorBoundary.tsx
- src/errors/ValidationError.ts
- src/hooks/api/collections/useCreateCollection.ts
- src/hooks/api/collections/useUpdateCollectionInfo.ts
- src/scenes/NftDetailPage/NftDetailPage.tsx
- No longer reporting errors related to feed event failures
- Distinguish validation errors so we don't report those to Sentry
- Globally ignore the web3 rejection errors
- Did some refactoring on the NftDetailPage to support the not found stuff.
> Quiet Sentry Errors GAL-1647 GAL-1083 GAL-1055 GAL-758

- src/components/Badge/Badge.tsx
- src/components/HoverCard/HoverCardOnUsername.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
- src/scenes/UserGalleryPage/UserGalleryLayout.tsx
https://user-images.githubusercontent.com/12162433/211907820-ad880df9-55c3-46aa-a8c3-cc3a91913fae.mov
> Multibadge

- next.config.js
Redirect landing page to /home
> Home redirect

- src/components/Badge/Badge.tsx
- src/components/Feed/FeedList.tsx
> Fix unusual outline

- src/constants/urls.ts
- src/scenes/Modals/SettingsModal/SettingsModal.tsx
> Hyperlink discord channel

- src/components/NftPreview/NftPreviewLabel.tsx
- src/scenes/NftDetailPage/NftDetailText.tsx
> Fix more stretched badges

- src/scenes/UserGalleryPage/UserGalleryCollection.tsx
- src/scenes/UserGalleryPage/UserGalleryCollections.tsx
- src/scenes/UserGalleryPage/UserGalleryHeader.tsx
**Bio**
**Before**
**After**
**Collection**
**Before**
**After**
**3AC**
3ac gallery not affected on this changes
> Fix bio / collection break line

- src/constants/sidebar.ts
small improvement from where we are today; ultimate goal is to enlarge the images even further
> Reduce gap between sidebar pieces

- .github/workflows/screenshots.yml
- cypress/integration/pages/home/home-page.ts
- cypress/integration/specs/home-spec.ts
- src/components/Feed/Feed.tsx
- src/components/Feed/GlobalFeed.tsx
- src/scenes/LandingPage/LandingPage.tsx
- fix homepage test; now we're redirecting to a feed
- disable screenshots; they're failing for an unusual reason and we weren't getting short-term use out of it
> Fix failing cypress tests

- src/components/GalleryEditor/CollectionSidebar/CollectionListItem.tsx
- src/components/GalleryEditor/GalleryEditorContext.tsx
- src/components/GalleryEditor/getInitialCollectionsFromServer.ts
- src/components/core/Dropdown/SettingsDropdown.tsx
- src/components/core/IconContainer.tsx
- src/contexts/globalLayout/EditGalleryNavbar/OnboardingEditGalleryNavbar.tsx
- src/contexts/globalLayout/GlobalNavbar/CollectionSaveButtonWithCaption.tsx
> Jess MultiGallery Feedback

- src/components/MultiGallery/Gallery.tsx
- src/scenes/GalleryPage/GalleriesPage.tsx
- src/scenes/UserActivityPage/UserActivityLayout.tsx
- src/scenes/UserGalleryPage/UserGalleryLayout.tsx
**Changes**
- Set max width to user galleries
- Fixed the delete gallery checking
**Demo**
**Before**
**After**
> User galleries polish

- src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryRightContent.tsx
https://user-images.githubusercontent.com/12162433/213898158-3ec5d1db-e08f-4bc1-ab04-4a71a4367d6d.mov
> Improve tooltip positioning

- pages/[username]/[collectionId]/index.tsx
https://user-images.githubusercontent.com/12162433/213898081-a5c01b0e-5ebf-415b-bdba-ec2c6dbee9d5.mov
> Redirect to rightful owner of collection

- pages/onboarding/organize-gallery.tsx
- src/components/Email/useVerifyEmailOnPage.ts
- src/components/Feed/FeedEvent.tsx
- src/components/NotificationsModal/NotificationList.tsx
- src/components/NotificationsModal/useNotificationsModal.tsx
- src/contexts/globalLayout/GlobalNavbar/CollectionNavbar/CollectionNavbar.tsx
- src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavLinks.tsx
- src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavbar.tsx
- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdown.tsx
- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdownContent.tsx
- src/scenes/Modals/useOpenSettingsModal.tsx
- src/utils/graphql/isFeatureEnabled.tsx
- resolve `WHITE_RHINO`, `EMAIL`
> Feature flag cleanup

- pages/[username]/galleries/[galleryId].tsx
- src/components/GalleryEditor/GalleryEditorContext.tsx
- src/components/MultiGallery/Gallery.tsx
- src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryLeftContent.tsx
- src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavbar.tsx
- src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/Breadcrumbs.tsx
- src/scenes/GalleryPage/GalleriesPage.tsx
- src/scenes/UserGalleryPage/FocusedGalleryPage.tsx
- src/scenes/UserGalleryPage/GalleryNameDescriptionHeader.tsx
- src/scenes/UserGalleryPage/UserGallery.tsx
- src/scenes/UserGalleryPage/UserGalleryCollections.tsx
- src/scenes/UserGalleryPage/UserGalleryLayout.tsx
- src/scenes/UserGalleryPage/UserGalleryPage.tsx
- src/scenes/UserGalleryPage/UserNameAndDescriptionHeader.tsx
- Featured gallery at `/{username}`
- Focused gallery at `/{username}/galleries/{galleryId}`
> New Gallery Pages

- .vscode/relay.code-snippets
Loom here https://www.loom.com/share/8d89009b72e84617b2a750639159ae8a
> add relay code snippets to shared vscode config

- pages/[username]/followers.tsx
- pages/[username]/index.tsx
- src/components/Follow/FollowList.tsx
- src/scenes/CollectionGalleryPage/CollectionGallery.tsx
- src/scenes/CollectionGalleryPage/CollectionGalleryPage.tsx
- src/scenes/GalleryPage/GalleriesPage.tsx
- src/scenes/UserActivityPage/UserActivityLayout.tsx
- src/scenes/UserActivityPage/UserActivityPage.tsx
- src/scenes/UserGalleryPage/FocusedGalleryPage.tsx
- src/scenes/UserGalleryPage/UserGallery.tsx
- src/scenes/UserGalleryPage/UserGalleryLayout.tsx
- src/scenes/UserGalleryPage/UserGalleryPage.tsx
The spacing / max width was littered everywhere. I moved it to a single component and made all the pages conform
https://user-images.githubusercontent.com/6754223/214147796-1d593684-ad30-4f2a-9ec1-78ef14a9c4a0.mov
> update all gallery routes to use same spacing component

- src/contexts/globalLayout/EditGalleryNavbar/GalleryTitleSection.tsx
> GalleryEditor untitled gallery copy change

- src/components/FadeTransitioner/FadeTransitioner.tsx
- src/components/NftPreview/NftPreview.tsx
- src/scenes/NftDetailPage/LinkToNftDetailView.tsx
- src/scenes/NftDetailPage/useDisplayFullPageNftDetailModal.tsx
- src/scenes/UserGalleryPage/FocusedGalleryPage.tsx
- src/scenes/UserGalleryPage/UserNameAndDescriptionHeader.tsx
We never wired up the modal for that page. Here it is!
> Nft detail link on focused gallery pages

- pages/opengraph/gallery/[galleryId].tsx
**Opengraph Link**
- `http://localhost:3000/opengraph/gallery/[galleryId]`
**Demo**
**Notes**
> [GAL-1760] Opengraph Preview Image for Single Gallery Page

- src/components/GalleryEditor/GalleryEditorContext.tsx
- src/components/MultiGallery/Gallery.tsx
- src/scenes/GalleryPage/GalleriesPage.tsx
- Fix collection name / description editing the wrong collection
- Fixed `1 Collections` => `1 Collection`
- Fixed the galleries page layout. It was quite broken before
https://user-images.githubusercontent.com/6754223/214382506-ee112107-c6ac-4540-b2a3-f08e11a05a41.mov
https://user-images.githubusercontent.com/6754223/214382499-24135ba9-5678-4135-a331-3f5336de0d53.mov
> More bug fixes

- pages/gallery/[galleryId]/edit.tsx
- src/components/GalleryEditor/GalleryEditorContext.tsx
- src/contexts/globalLayout/EditGalleryNavbar/EditGalleryNavbar.tsx
- src/icons/AllGalleriesIcon.tsx
- src/icons/TrashIconNew.tsx
- Replaced the back button in favor of the "All Galleries" button (doesn't apply to onboarding)
- Now we have three different "Done" button states (doesn't apply to onboarding)
https://user-images.githubusercontent.com/6754223/214439526-6c16db85-dd22-41a0-9912-41d056b17fe0.mov
> GalleryEditor All Galleries button and done button states

- src/components/GalleryEditor/CollectionEditor/ColumnAdjuster.tsx
- src/components/GalleryEditor/CollectionEditor/DragAndDrop/DroppableSection.tsx
- src/components/GalleryEditor/CollectionEditor/DragAndDrop/Section.tsx
- src/components/GalleryEditor/CollectionEditor/DragAndDrop/SectionDragging.tsx
- src/components/GalleryEditor/CollectionEditor/StagingArea.tsx
- src/icons/TrashIconNew.tsx
**Changes**
- Fix delete icon color regression on hover
- render markdown in the editor
- fix column count bug
**Demo**
**Delete Icon color on hover**
|-------|---|
| ![image](https://user-images.githubusercontent.com/4480258/214569158-bfd73002-a7dd-42b0-b6cb-bb16aedbdf75.png) | ![CleanShot 2023-01-25 at 20 57 43](https://user-images.githubusercontent.com/4480258/214569235-62130085-8f9b-4e9a-9c88-3b88259fdf80.png)  |
**Render markdown in editor**
|-------|---|
| ![CleanShot 2023-01-25 at 21 00 06](https://user-images.githubusercontent.com/4480258/214569780-f120e4a1-8806-474a-81fe-eec898156cbc.png)   | ![CleanShot 2023-01-25 at 20 58 34](https://user-images.githubusercontent.com/4480258/214569437-29849fae-7ce5-4545-ad89-9df346d0afb8.png) |
**Column …
> [GAL-1998] [GAL-1999] Multigallery Polish

- pages/[username]/galleries/[galleryId].tsx
Related: https://github.com/gallery-so/gallery/pull/1266
> Gallery OG Image

- schema.graphql
- src/components/GalleryEditor/CollectionSidebar/CollectionListItem.tsx
- src/components/GalleryEditor/CollectionSidebar/CollectionSearch.tsx
- src/components/GalleryEditor/CollectionSidebar/CollectionSearchResults.tsx
- src/components/GalleryEditor/CollectionSidebar/CollectionSidebar.tsx
- src/components/GalleryEditor/CollectionSidebar/MoveCollectionModal.tsx
- src/components/GalleryEditor/CollectionSidebar/useMoveCollectionModal.tsx
- src/components/GalleryEditor/CollectionSidebar/useMoveCollectionToGallery.tsx
- src/components/GalleryEditor/GalleryEditor.tsx
- src/components/GalleryEditor/GalleryEditorContext.tsx
- src/components/core/Checkbox/Checkbox.tsx
- src/contexts/toast/Toast.tsx
**Changes**
- Add Move collection to other gallery
- Add markdown support to toast
**Demo**
**Move collection flow**
https://user-images.githubusercontent.com/4480258/215779642-a50bf98f-ff78-4d49-bbc5-048da73b1160.mp4
**Move collection flow - edge cases**
1. Add token
2. Move collection to different gallery
3. Remove token again
Expected: Its not **unsaved changes**
https://user-images.githubusercontent.com/4480258/215780080-115fdb95-1910-46b9-b1ba-1af43bfe125e.mp4
**Modal with a lot of gallery**
https://user-images.githubusercontent.com/4480258/215782564-0c4bbc11-4ebc-47aa-a371-b6610bcc4d5e.mp4
> [GAL-2037] Move collection to other gallery

- src/components/GalleryEditor/CollectionSidebar/CollectionListItem.tsx
- src/contexts/globalLayout/EditGalleryNavbar/GalleryTitleSection.tsx
- src/contexts/globalLayout/GlobalNavbar/CollectionNavbar/CollectionNavbar.tsx
- Show "Untitled" in the collection navbar if they don't have a gallery name
- "Untitled Gallery" => "Untitled gallery" in gallery editor
- "Untitled Collection" => "Untitled collection" in gallery editor
> more jess multigallery feedback

- src/components/GalleryEditor/GalleryEditorContext.tsx
Fixes crash triggered by collection creation
> Fix collection creation crash

- src/components/Feed/Events/CollectionUpdatedFeedEvent.tsx
- src/components/Feed/Events/FeedEventNftPreviewWrapper.tsx
- src/components/NftPreview/NftPreview.tsx
**Changes**
- Fix `CollectionUpdated` title
- Fix token preview in the feed event
**Demo**
> Fix feed event UI

- apps/web/src/components/Featured/FeaturedUserCard.tsx
**Changes** 
1. Fix missing token preview
2. Blurry image on token preview
**Demo**
**Fix missing token preview**
**Before**
**After**
**Blurry image on token preview - squiggle**
**Before**
**After**
> Fix featured card

- apps/web/src/components/Feed/Socialize/Interactions.tsx
- apps/web/src/components/Feed/Socialize/NotesModal/NotesModal.tsx
| ![Screenshot 2023-02-07 at 3 58 47 PM](https://user-images.githubusercontent.com/12162433/217364302-be68fd32-3d71-489e-8673-12c54f2942a2.png) | ![Screenshot 2023-02-07 at 3 58 18 PM](https://user-images.githubusercontent.com/12162433/217364304-3ad7bfdf-10dc-4e52-b433-332fc503487e.png) |
| ![Screenshot 2023-02-07 at 3 58 30 PM](https://user-images.githubusercontent.com/12162433/217364303-a7ddbbbb-dff3-4665-a4e7-4aaebd546a7f.png) | ![Screenshot 2023-02-07 at 3 57 57 PM](https://user-images.githubusercontent.com/12162433/217364305-38789d0a-dc4b-46d5-a262-7da0f77251f6.png) |
> Improve interaction display ordering

- apps/web/src/components/GalleryEditor/CollectionSidebar/CollectionSidebar.tsx
**Changes**
- Make the help button float (fixed)
- Add extra bottom padding in the collection sidebar
**Demo**
https://user-images.githubusercontent.com/4480258/217463635-e3a3bdd8-35e0-481f-b57b-d3c804a75d2a.mp4
> [GAL-2325] fix help button position

- apps/web/src/scenes/Home/Latest/FollowingToggleSection.tsx
**Changes**
- Added worlwide pill in latest page
**Demo**
https://user-images.githubusercontent.com/4480258/217786401-37f1950a-cd16-4f03-bf5f-947088ba2983.mp4
> [GAL-2340] Add "Worldwide" pill to "Latest" feed

- apps/web/src/components/Feed/Events/CollectorsNoteAddedToTokenFeedEvent.tsx
> Fix collector note feed event

- apps/web/src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryRightContent.tsx
- apps/web/src/scenes/UserGalleryPage/UserGallery.tsx
- apps/web/src/scenes/UserGalleryPage/UserNameAndDescriptionHeader.tsx
**Changes**
- Add editable bio on profile page
- Remove navigation dropdown on top right
**Demo**
https://user-images.githubusercontent.com/4480258/218767910-7c50de7e-c004-4877-b04a-65f5864c6e15.mp4
> New edit bio

- apps/web/src/components/MultiGallery/Gallery.tsx
- apps/web/src/icons/ArrowDownIcon.tsx
- apps/web/src/icons/ArrowUpIcon.tsx
- apps/web/src/scenes/GalleryPage/GalleriesPage.tsx
**Changes**
- Added mobile reorder multigallery
**Demo**
https://user-images.githubusercontent.com/4480258/218769088-bd3a15c8-454d-415e-b421-401bc0ca4ab3.mp4
> [GAL-2038] Multigallery mobile web reorder

- apps/web/src/components/Follow/FollowButton.tsx
**Changes**
- Fix unfollow flash on mobile during follow/unfollow flow
**Demo**
**Before**
https://user-images.githubusercontent.com/4480258/218774364-a2b8ede9-65ed-4e6f-ac4b-d72012eb2a7f.mp4
**After**
https://user-images.githubusercontent.com/4480258/218774135-73939360-7c53-40b4-9ff6-de5077796b9c.mp4
**On desktop flow should remain same**
https://user-images.githubusercontent.com/4480258/218774773-6ea6f9e8-98e5-4a74-a059-87f58924d15f.mp4
> Fix unfollow flash

- apps/web/src/scenes/UserGalleryPage/UserNameAndDescriptionHeader.tsx
**Notes**
Only authenticated usr and his own account can trigger the edit bio modal
Tested on:
1. logged in state
2. logged out 
**Demo**
https://user-images.githubusercontent.com/4480258/219265359-5fcd6938-1f61-454e-95ef-8c8c01b1796d.mp4
> [GAL-2387] Only auth n own profile can edit

- apps/web/schema.graphql
- apps/web/src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
- apps/web/src/components/Feed/FeedEventData.tsx
**Changes**
Show collector notes for `CollectionCreatedFeedEvent`
**Before**
**After**
> Add feed collector note to feed event

- apps/web/src/contexts/globalLayout/GlobalNavbar/EditGalleryNavbar/OnboardingEditGalleryNavbar.tsx
step 6 wasn't appearing during onboarding
> bugfix: tooltip step 6 for onboarding

- apps/web/src/scenes/UserGalleryPage/UserNameAndDescriptionHeader.tsx
> [GAL-2434] Fix bio width

- apps/web/src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
- apps/web/src/components/Feed/Events/CollectorsNoteAddedToCollectionFeedEvent.tsx
- apps/web/src/components/Feed/Events/EventStyles.tsx
- apps/web/src/components/Feed/Events/GalleryUpdatedFeedEvent.tsx
- apps/web/src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
- apps/web/src/components/Feed/FeedEventData.tsx
**Changes**
- Updated new feed design
- Render link in collector notes
**Demo**
https://user-images.githubusercontent.com/4480258/220348992-fa5e5782-7361-40bc-b53b-5b65e298a32c.mp4
https://user-images.githubusercontent.com/4480258/220349167-3d879c3c-eac2-4546-859a-b7023246a8ac.mp4
> Feed Visual Update

- apps/web/src/components/NotificationsModal/Notification.tsx
- apps/web/src/components/NotificationsModal/NotificationsModal.tsx
- apps/web/src/components/NotificationsModal/useClearNotifications.tsx
**Before**
https://user-images.githubusercontent.com/4480258/220526125-985a608e-8a5e-4899-b557-5081ce6ddd75.mp4
**After**
https://user-images.githubusercontent.com/4480258/220526139-50dd32ab-7572-4c44-815f-ec1aa0b4b1ef.mp4
> [GAL-696] Clear Notification on click row popover

- apps/web/src/contexts/globalLayout/GlobalBanner/GlobalBanner.tsx
- apps/web/src/contexts/globalLayout/GlobalLayoutContext.tsx
- apps/web/src/scenes/MaintenancePage/MaintenancePage.tsx
https://user-images.githubusercontent.com/12162433/220836070-95581002-762e-4e1d-a567-3515ed9c69c6.mov
> feb 25 maintenance banner

- apps/web/src/components/core/breakpoints.ts
| ![Screenshot 2023-02-27 at 4 22 34 PM](https://user-images.githubusercontent.com/12162433/221688950-7e07b260-ae12-46b1-98e5-8c4d7bb2c379.png) | ![Screenshot 2023-02-27 at 4 23 58 PM](https://user-images.githubusercontent.com/12162433/221688967-a755c381-8263-427f-bbb5-d6faf6ea91b4.png) |
> Handle iphone 14 pro max for mobile width

- apps/web/src/components/GalleryEditor/PiecesSidebar/PiecesSidebar.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarChainButton.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarChainSelector.tsx
- apps/web/src/components/core/Button/Button.tsx
**Demo**
https://user-images.githubusercontent.com/4480258/221586589-74018c5a-6243-4058-aa8f-4976a14be0fd.mp4
> Update refresh section

- apps/web/src/components/GalleryEditor/PiecesSidebar/PiecesSidebar.tsx
**Changes**
- Add gap between two button
- Remove tooltips
- Move refresh icon to the left
**Demo**
https://user-images.githubusercontent.com/4480258/222073438-6f68cd1f-2559-43e7-aa49-74f766ea3820.mp4
> Polish refresh section

- apps/web/src/components/Twitter/TwitterSetting.tsx
- apps/web/src/components/Twitter/useUpdateTwitterDisplay.tsx
- apps/web/src/scenes/UserGalleryPage/UserTwitterSection.tsx
**Changes**
- Able to toggle the display from user profile
- Only show action button on hover
**Demo**
https://user-images.githubusercontent.com/4480258/222074219-e4dbfcd3-6f75-4343-9401-d107ab850990.mp4
> Twitter polish

- apps/web/src/components/HoverCard/HoverCardOnUsername.tsx
- apps/web/src/components/NotificationsModal/notifications/SomeoneCommentedOnYourFeedEvent.tsx
- apps/web/src/components/NotificationsModal/notifications/SomeoneFollowedYouBack.tsx
**Fix bold hover card**
**Before**
**After**
**Fix squish hover card**
**Before**
**After**
> Fix hover card UI

- apps/web/src/components/GalleryEditor/CollectionSidebar/CollectionListItem.tsx
- apps/web/src/components/NftGallery/NftGallery.tsx
- apps/web/src/utils/collectionLayout.test.ts
- apps/web/src/utils/collectionLayout.ts
Reverts gallery-so/gallery#1398
> Revert "Fix flaky ordering of sections"

- apps/web/src/components/Feed/Events/GalleryUpdatedFeedEvent.tsx
- apps/web/src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
> parse markdown in captions

- apps/web/src/scenes/UserGalleryPage/UserGallery.tsx
- apps/web/src/scenes/UserGalleryPage/UserNameAndDescriptionHeader.tsx
**Notes**
This bug only happens on **mobile** and if the user don't have any **bio**
Tested to avoid any regression
**Before**
**After**
**Desktop**
> Fix empty space on mobile if no bio

- apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
Was missing event tracking for opening notifications in LHN
> track notifications open

- apps/web/src/components/HoverCard/HoverCardOnUsername.tsx
- apps/web/src/components/ManageWallets/ManageWallets.tsx
- apps/web/src/components/ManageWallets/PrimaryWalletRow.tsx
- apps/web/src/components/Notifications/Notification.tsx
- apps/web/src/components/Notifications/notifications/SomeoneAdmiredYourFeedEvent.tsx
- apps/web/src/components/Notifications/notifications/SomeoneCommentedOnYourFeedEvent.tsx
- apps/web/src/components/Notifications/notifications/SomeoneFollowedYou.tsx
- apps/web/src/components/Notifications/notifications/SomeoneFollowedYouBack.tsx
- apps/web/src/components/Notifications/notifications/SomeoneViewedYourGallery.test.tsx
- apps/web/src/components/Notifications/notifications/SomeoneViewedYourGallery.tsx
- apps/web/src/components/Settings/Settings.tsx
- apps/web/src/components/Tooltip/useTooltipHover.ts
- apps/web/src/components/Twitter/TwitterSetting.tsx
- apps/web/src/components/core/Button/Button.tsx
- apps/web/src/contexts/globalLayout/GlobalSidebar/SidebarIcon.tsx
- apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
- apps/web/src/scenes/UserGalleryPage/UserTwitterSection.tsx
**Changes**
- Update Setting Visual
- Tooltip dissapear on click
- Fix edit twitter button - open setting drawer
- Fix sidebar & tooltip glitch on redirect from notification
- Fix bottom nav show G instead of whole nav
**Demo**
**Update Setting Visual**
https://user-images.githubusercontent.com/4480258/223329770-8868fda3-d473-431b-978a-1d874753467e.mp4
**Tooltip dissapear on click**
https://user-images.githubusercontent.com/4480258/223329946-6662e50b-6ed4-40c5-b222-cb7d49b8bf8d.mp4
**Fix edit twitter button - open setting drawer**
https://user-images.githubusercontent.com/4480258/223332074-2df38906-ae0c-4dbb-93dd-c17437d54470.mp4
**Fix sidebar glitch on redirect from notification**
**Desktop**
https://user-images.githubusercontent.com/4480258/223332398-96055722-27f9-4cc4-a93d-46eb5fea73a5. …
> Left Hand Nav Polish

- apps/web/src/components/Explore/ExplorePopoverList.tsx
- apps/web/src/components/Explore/ExploreUserCard.tsx
- apps/web/src/components/Follow/FollowButton.tsx
- apps/web/src/components/Follow/NavActionFollow.tsx
- apps/web/src/components/HoverCard/HoverCardOnUsername.tsx
- apps/web/src/contexts/globalLayout/GlobalAnnouncementPopover/components/FeaturedCollectorCard.tsx
- apps/web/src/contexts/globalLayout/GlobalAnnouncementPopover/components/GalleryOfTheWeekCard.tsx
- apps/web/src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavbar.tsx
it would be neat if we could see where people are clicking the Follow button. 
Are there any places that people click the follow button on more?
This PR adds an optional `source` prop to the `FollowButton` component to specify where the Follow Button is being used. this value is included in the click follow button event.
> Add source to follow button click

- apps/web/src/components/GalleryEditor/CollectionEditor/DragAndDrop/DroppableSection.tsx
- apps/web/src/contexts/collectionEditor/CollectionEditorContext.tsx
- apps/web/src/utils/collectionLayout.ts
**Changes**
- Able to add section in between sections
- Fix editor section merged into one sections
To reproduce this error, add an empty section (without any nft inside it) and save. 
**Demo** 
**Able to add section in between sections**
https://user-images.githubusercontent.com/4480258/224896151-125f45c1-f2d6-46fc-90c5-d816a84229df.mp4
**Fix editor section merged into one sections**
**Before**
https://user-images.githubusercontent.com/4480258/224896432-1a75aaef-29dc-4c82-be82-2eec94c5e768.mp4
**After**
https://user-images.githubusercontent.com/4480258/224896538-44b0b348-1647-4881-9aa3-6023ee29fa0e.mp4
> [GAL-2433] Editor Section

- apps/web/src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
- apps/web/src/components/Feed/Events/CollectorsNoteAddedToCollectionFeedEvent.tsx
- apps/web/src/components/Feed/Socialize/Interactions.tsx
**Changes**
- Reduce gap between comments
- Reduce whitespace of notes/caption
**Demo**
**Reduce gap between comments**
**Before**
**After**
**Reduce whitespace of notes/caption**
**Before**
**After**
> Fix UI feed whitespace

- apps/web/src/components/Community/CommunityHolderList.tsx
- apps/web/src/components/CommunityHolderGrid/CommunityHolderGrid.tsx
change copy for title on the Community Page user list from:
Gallery Members -> Collectors on Gallery
> reword title for community page list

- apps/web/src/components/Search/Search.tsx
- apps/web/src/components/Search/SearchResult.tsx
- package.json
- yarn.lock
https://user-images.githubusercontent.com/6754223/225641111-5dab8cff-ffc0-436a-aa68-81da92b6321f.mov
After we landed https://github.com/JohannesKlauss/react-hotkeys-hook/pull/918 in the `react-hotkeys-hook` library, I think we can start adopting it. After this PR lands, I'll start moving us over for realz.
> Arrow Keys on Search Results

- apps/web/src/components/Auth/TwitterAuth.tsx
`''` is not a valid JSON string.
> Fix JSON Parse of twitter redirect url

- apps/web/src/scenes/MintPages/MementosPage.tsx
- apps/web/src/scenes/MintPages/config.ts
> Memento #4

- apps/web/pages/[username]/index.tsx
- apps/web/src/components/core/Loader/FullPageLoader.tsx
**off-center suspense boundary**
| <img width="1511" alt="Screenshot 2023-03-20 at 3 37 34 PM" src="https://user-images.githubusercontent.com/12162433/226448917-63713942-3d8a-45af-b99e-981e45da666f.png"> | <img width="1512" alt="Screenshot 2023-03-20 at 3 37 20 PM" src="https://user-images.githubusercontent.com/12162433/226448918-829929cc-3dc3-404a-a943-7e778fe25de9.png"> |
**off-center 404**
| <img width="1512" alt="Screenshot 2023-03-20 at 3 43 04 PM" src="https://user-images.githubusercontent.com/12162433/226448915-3274b10f-610e-425a-bdb2-dcb084134802.png"> | <img width="1512" alt="Screenshot 2023-03-20 at 3 42 47 PM" src="https://user-images.githubusercontent.com/12162433/226448916-f508989f-c557-4b04-bdff-11c9084 …
> Fix full page alignment issues

- apps/web/src/components/Notifications/UserListItem.tsx
This glitch only happens on subview notifications
**Demo**
https://user-images.githubusercontent.com/4480258/228474698-296e29a2-b81d-4a7a-a6eb-3a49b23753c8.mp4
> Fix sidebar glitch on subview

- apps/web/src/components/Notifications/NotificationList.tsx
- apps/web/src/components/Notifications/Notifications.tsx
- apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
1. vertically center empty notifications
2. highlight profile icon if selected
https://user-images.githubusercontent.com/12162433/230538595-ae15b454-2234-421f-ab09-bcd7504af59a.mov
> LHN polish

- package.json
- schema.graphql
- yarn.lock
We should be fetching our schema from the graphql gateway instead of the backend directly now that we "compile" a schema for public use. The backend that we used to copy from is technically a "subgraph" now.
> Script to fetch latest schema

- apps/mobile/src/screens/SearchScreen.tsx
**Before**
https://user-images.githubusercontent.com/4480258/231260895-084bb19e-523f-42fa-90de-9dfac990d705.mp4
**After**
https://user-images.githubusercontent.com/4480258/231260763-40ae3247-6e16-4360-b18e-57fa44c4472f.mp4
> Fix keyboardAvoidingView android

- apps/web/src/components/Announcement/AnnouncementList.tsx
Add tracking event for clicking on announcement in notifications
> add event for clicking on announcement

- .github/workflows/openai-pr-reviewer.yml
Release Notes:
- New Feature: Added OpenAI Code Review Bot to review pull requests and provide comments.
> "Code quality improved,
> With OpenAI's help approved,
> Bugs and issues removed."
> OpenAI bot: summary_only

- apps/mobile/src/components/GallerySkeleton.tsx
- apps/mobile/src/navigation/FeedTabNavigator/FeedTabNavigator.tsx
- apps/mobile/src/navigation/MainTabNavigator/MainTabNavigator.tsx
- apps/mobile/src/screens/NftDetailScreen/LoadingNftDetailScreenInner.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailScreen.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx
- packages/shared/src/theme/colors.js
This PR adds a suspense loading statute the NFT Detail Screen.
`NftDetailScreen` contains the Suspense, and I moved the content to a new component, `NftDetailScreenInner`
https://user-images.githubusercontent.com/80802871/235071228-ccb73f00-6f81-4935-822b-27644e41f5f2.mp4
**Release Notes**
- New Feature: Adds a suspense loading state to the NFT Detail Screen in the mobile app.
> "Loading screens no more,  
> Suspense brings a new score.  
> Skeletons dance with glee,  
> As users wait patiently."
> Add Loading State to NFT Detail Screen

- apps/mobile/index.js
- apps/mobile/src/components/NftPreview/NftPreview.tsx
- apps/mobile/src/components/NftPreview/NftPreviewContextMenuPopup.tsx
- apps/mobile/src/components/ProfileView/ProfileView.tsx
- apps/mobile/src/components/Search/SearchResults.tsx
- apps/mobile/src/components/Search/User/UserSearchResult.tsx
- apps/mobile/src/components/Trending/SuggestedSection.tsx
- apps/mobile/src/components/Trending/TwitterSection.tsx
- apps/mobile/src/components/UserFollowList/UserFollowCard.tsx
- apps/mobile/src/components/UserFollowList/UserFollowList.tsx
- apps/mobile/src/navigation/LoggedInStackNavigator.tsx
- apps/mobile/src/navigation/MainTabNavigator/MainTabNavigator.tsx
- apps/mobile/src/navigation/MainTabNavigator/TabBar.tsx
- apps/mobile/src/navigation/MainTabStackNavigator.tsx
- apps/mobile/src/navigation/RootStackNavigator.tsx
- apps/mobile/src/navigation/types.ts
- apps/mobile/src/screens/AccountScreen.tsx
- apps/mobile/src/screens/HomeScreen/HomeScreen.tsx
- apps/mobile/src/screens/HomeScreen/TwitterSuggestionListScreen.tsx
- apps/mobile/src/screens/HomeScreen/UserSuggestionListScreen.tsx
- apps/mobile/src/screens/Login/EnterEmailScreen.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailScreen.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx
- apps/mobile/src/screens/NotificationsScreen.tsx
- apps/mobile/src/screens/ProfileScreen/ProfileScreen.tsx
- apps/mobile/src/screens/SearchScreen.tsx
Create a new stack navigator called `MainTabStackNavigator` which lives under each of the four main tabs. This allows the bottom tabs to stay on top while we navigate inside of the stack.
> Create new MainTabStackNavigator so we can keep the tabs on top

- apps/mobile/src/components/Feed/EventTokenGrid.tsx
- apps/mobile/src/components/Feed/FeedEventCarouselCellHeader.tsx
- apps/mobile/src/components/Feed/FeedList.tsx
- apps/mobile/src/components/Feed/FeedListCaption.tsx
- apps/mobile/src/components/Feed/FeedListCollectorsNote.tsx
- apps/mobile/src/components/Feed/FeedListItem.tsx
- apps/mobile/src/components/Feed/FeedListSectionHeader.tsx
- apps/mobile/src/components/Feed/FeedVirtualizedRow.tsx
- apps/mobile/src/components/Feed/createVirtualizedFeedEventItems.ts
- apps/mobile/src/components/ProfileView/ProfileView.tsx
Hard to capture everything in a list here, so here's a video scrolling through the feed. I used the Figma "Home Page (Feed + Explore)" as the source of truth. I had to do some guessing with different permutations of caption / collectors note but I think it looks much better than before.
https://user-images.githubusercontent.com/6754223/235513821-962d65f2-ec0b-49ba-b86a-001b599ddc5f.mp4
> Feed Spacing Improvements

- apps/mobile/src/components/Search/SearchDefault.tsx
- apps/mobile/src/components/Search/SearchFilter.tsx
- apps/mobile/src/components/Search/SearchInput.tsx
- apps/mobile/src/components/Search/SearchResult.tsx
- apps/mobile/src/components/Search/SearchResults.tsx
- apps/mobile/src/screens/SearchScreen.tsx
This PR adds some improvements to the Search Screen:
- add default list of users (shows Trending users using existing query)
- add "top" filter to represent default result state ("Top" shows top 4 results for each category)
- don't show filters if there is no search query
- add "cancel" button to close out of search
- scrolling on list closes keyboard
https://user-images.githubusercontent.com/80802871/236124078-f6817656-d602-4035-a02a-04908927352f.mp4
> GAL-2965 Search screen improvements

- apps/mobile/package.json
- apps/mobile/src/App.tsx
- apps/mobile/src/components/FeedbackButton.tsx
- apps/mobile/src/components/ProfileView/ProfileView.tsx
- apps/mobile/src/icons/ChatIcon.tsx
- yarn.lock
This PR adds a Feedback button that opens a sheet containing a CTA and link to a Feedback Google Form.
The goal is to provide users an easy way to leave feedback or report issues while testing the beta.
Demo
light mode
https://user-images.githubusercontent.com/80802871/236201790-0caa7059-de50-458b-895b-1a601a1989c8.mp4
dark mode
https://user-images.githubusercontent.com/80802871/236201810-4d31a519-8932-4af0-9d58-6c0f47447d44.mp4
> GAL-2962 Add Feedback button and form link

- apps/mobile/src/screens/HomeScreen/LatestScreen.tsx
- apps/mobile/src/screens/HomeScreen/TrendingScreen.tsx
this was causing the list to be emptied out
> [GAL-2971] only load previous if there are previous events

- apps/mobile/src/components/Feed/EventTokenGrid.tsx
- apps/mobile/src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
- apps/mobile/src/components/Feed/createVirtualizedFeedEventItems.ts
- packages/shared/src/relay/getVideoOrImageUrlForNftPreview.ts
@Robinnnnn recorded a loom w/ some bugs https://www.loom.com/share/08c6f83d9c814ddfa2409448d1e637b2
Here is my response loom https://www.loom.com/share/6441b81a09404090a387c852a234df34
> [GAL-3010] Feed Fixes

- .yarn/patches/nativewind-npm-2.0.11-dc2ccf9fb5.patch
- package.json
- yarn.lock
Loom https://www.loom.com/share/147ac7bfaa854c0e813e023dd939ee35
> patch nativewind to fix flash bug

- apps/mobile/src/screens/Login/QRCodeScreen.tsx
https://github.com/gallery-so/gallery/assets/6754223/f927efbf-6c0a-4d19-9fc9-9c67aa9ef6c1
Implementation is super simple. Just re-using what we already had
> [GAL-2956] QR Code Login

- apps/mobile/src/components/Feed/Events/GalleryUpdatedFeedEvent.tsx
- apps/mobile/src/components/ProfileView/ProfileView.tsx
- apps/mobile/src/components/ProfileView/Tabs/ProfileViewActivityTab.tsx
- apps/mobile/src/components/ProfileView/Tabs/ProfileViewFeaturedTab.tsx
- apps/mobile/src/components/ProfileView/Tabs/ProfileViewFollowersTab.tsx
- apps/mobile/src/components/ProfileView/Tabs/ProfileViewGalleriesTab.tsx
- apps/mobile/src/components/ProfileView/Tabs/useListContentStyle.ts
- apps/mobile/src/navigation/FeedTabNavigator/FeedTabNavigator.tsx
- apps/mobile/src/navigation/MainTabNavigator/MainTabNavigator.tsx
- apps/mobile/src/navigation/types.ts
- apps/mobile/src/screens/HomeScreen/LatestScreen.tsx
- apps/mobile/src/screens/ProfileScreen/ProfileScreen.tsx
- Avoid scroll views if possible
- Make tab navigators lazy so the first load doesn't feel shitty
- Fix spacing bug reported by Lau
- Remove "Load 3 then X more" first load optimization since it just causes JS thrash.
- Fix back button regression on Profile screen
> Perf Improvements & Spacing Fixes

- apps/mobile/index.js
- apps/mobile/package.json
- apps/mobile/src/App.tsx
- apps/mobile/src/components/Button.tsx
- apps/mobile/src/components/DevMenuItems.tsx
- apps/mobile/src/components/Notification/NotificationList.tsx
- apps/mobile/src/components/Notification/NotificationRegistrar.tsx
- apps/mobile/src/components/Notification/registerNotificationToken.ts
- apps/mobile/src/navigation/LoginStackNavigator.tsx
- apps/mobile/src/navigation/types.ts
- apps/mobile/src/screens/Login/EnterEmailScreen.tsx
- apps/mobile/src/screens/Login/LandingScreen.tsx
- apps/mobile/src/screens/Login/NotificationUpsellScreen.tsx
- apps/mobile/src/screens/Login/QRCodeScreen.tsx
- apps/mobile/src/screens/Login/WaitingForConfirmationScreen.tsx
- apps/mobile/src/screens/Login/navigateToNotificationUpsellOrHomeScreen.ts
- apps/mobile/src/screens/NotificationsScreen.tsx
- yarn.lock
Used AsyncStorage to ensure the user only ever sees this once.
> [GAL-3029] Mobile Notification Upsell

- apps/mobile/src/components/ProfileView/ProfileView.tsx
- apps/web/pages/[username]/[collectionId]/index.tsx
- apps/web/pages/[username]/activity.tsx
- apps/web/pages/[username]/followers.tsx
- apps/web/pages/[username]/galleries.tsx
- apps/web/pages/[username]/index.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailPage.tsx
- packages/shared/src/components/GalleryViewEmitter.tsx
Just had to make the code shared and drop it in on mobile
> [GAL-3034] Gallery View Event for Mobile

- apps/mobile/src/components/Feed/FeedList.tsx
- apps/mobile/src/components/Notification/NotificationList.tsx
- apps/mobile/src/components/ProfileView/ProfileView.tsx
- apps/mobile/src/hooks/useRefreshHandle.ts
- apps/mobile/src/screens/FeedEventScreen.tsx
- apps/mobile/src/screens/HomeScreen/ExploreScreen.tsx
- apps/mobile/src/screens/HomeScreen/LatestScreen.tsx
- apps/mobile/src/screens/HomeScreen/TrendingScreen.tsx
- apps/mobile/src/screens/ProfileScreen/ProfileScreen.tsx
https://github.com/gallery-so/gallery/assets/6754223/a4c6eed0-fff8-44eb-a15e-0bb72b37f482
Implemented it everywhere I could think
Also comes w/ a `useRefreshHandle` hook which takes a Relay refetch function and gives you the appropriate values to stick on a `RefreshControl`
> implement pull to refresh everywhere

- apps/mobile/src/components/Feed/EventTokenGrid.tsx
- apps/mobile/src/components/NftPreview/NftPreview.tsx
- apps/mobile/src/components/NftPreview/NftPreviewContextMenuPopup.tsx
- apps/mobile/src/components/NftPreview/NftPreviewErrorFallback.tsx
- apps/mobile/src/components/ProfileView/GalleryPreviewCard.tsx
- apps/mobile/src/components/ProfileView/Tabs/ProfileViewActivityTab.tsx
- apps/mobile/src/components/SvgWebView.tsx
- apps/mobile/src/components/Trending/TrendingUserCard.tsx
- apps/mobile/src/icons/ErrorIcon.tsx
- Make sure tokens fill available space after regression
- Add basic fallback view for failing NFTs
- Make NFTPreviews a bit more resilient to missing collections
> Fix some feed issues

- apps/mobile/src/contexts/relay/RelayProvider.tsx
- apps/web/src/contexts/relay/network.ts
- packages/shared/src/relay/deferNetwork.ts
- packages/shared/src/relay/missingFieldHandlers.test.tsx
- packages/shared/src/relay/network.ts
Really quite simple. 
DO NOT LAND THIS UNTIL https://github.com/gallery-so/go-gallery/pull/950 deploys
> Add Platform Headers to all GraphQL Requests

- apps/mobile/src/components/Feed/Socialize/CommentBox.tsx
- apps/mobile/src/components/Search/SearchInput.tsx
switch auto correct from search input to comment input
> switch auto correct from search input to comment input

- packages/shared/src/errors/ReportingErrorBoundary.tsx
The new behavior is what I expected to happen but didn't realize.
Expected: An error thrown in an error boundary's fallback should bubble up to the parent error boundary, not the current one
Actual: An error boundary handles it's own fallbacks errors too.
> make error boundary fallbacks bubble errors up

- apps/mobile/src/components/Gallery/GalleryVirtualizedRow.tsx
- apps/mobile/src/screens/CollectionScreen/CollectionScreen.tsx
**Changes**
- Fix infinite collection screen
**Demo**
https://github.com/gallery-so/gallery/assets/4480258/62bd1cce-4c5c-4cc2-ba1f-3840dddf14b5
> [GAL-3052] Fix infinite navigate collection

- apps/mobile/src/components/Feed/FeedListCaption.tsx
**Changes**
- Truncate caption
**Demo**
**Before**
**After**
> [GAL-3083] Truncate caption in feed events

- apps/mobile/src/screens/Login/EmailIcon.tsx
- apps/mobile/src/screens/Login/LandingScreen.tsx
- apps/mobile/src/screens/Login/QRCodeIcon.tsx
> [GAL-3101] make qr code the primary login method

- apps/mobile/src/components/GalleryBottomSheet/GalleryBottomSheetHandle.tsx
- apps/mobile/src/components/GalleryBottomSheet/GalleryBottomSheetModal.tsx
- apps/mobile/src/components/GalleryTouchableOpacity.tsx
- apps/mobile/src/components/Typography.tsx
- apps/mobile/src/navigation/types.ts
- apps/mobile/src/screens/Login/EnterEmailScreen.tsx
- apps/mobile/src/screens/Login/LandingScreen.tsx
- apps/mobile/src/screens/Login/QRCodeScreen.tsx
| Error State | Flow Video |
| <img src="https://github.com/gallery-so/gallery/assets/6754223/c49f2b35-3d52-4a88-9ba9-9c46cad3a965" width="300" /> | <video src="https://github.com/gallery-so/gallery/assets/6754223/41c41d0d-4528-4361-b03a-2ea43c2539fa" /> | 
- I also fixed the bug w/ the weird clipping on the bottom sheets.  <img width="402" alt="image" src="https://github.com/gallery-so/gallery/assets/6754223/2e6baf3c-d8c9-4651-9e20-75f57a5c8dde">
- Login navigation was janked up somehow we forgot to delete a second navigation
> [GAL-3102] QR Code Flow Changes

- apps/mobile/src/components/Feed/Events/UserFollowedUsersFeedEvent.tsx
Data is loaded lazily so we don't make the feed slower. But we should also make that followed list paginated.
https://github.com/gallery-so/gallery/assets/6754223/61543fa1-813b-4712-95bc-403ae2aa6fae
> [GAL-3095] Support ability to display list of followers in feed

- apps/mobile/src/components/Feed/Socialize/CommentButton.tsx
- apps/mobile/src/components/GalleryBottomSheet/GalleryBottomSheetBackdrop.tsx
**Changes**
- Fix the modal dismiss whenever we changed keyboard type
**Demo**
https://github.com/gallery-so/gallery/assets/4480258/28ca2cb1-839b-47c2-9ca1-74b5940909dc
> [GAL-3047] Comment Modal closes when you switch to the emoji keyboard

- apps/mobile/src/screens/Login/EnterEmailScreen.tsx
- apps/mobile/src/screens/Login/useVerifyEmailMagicLink.ts
- schema.graphql
Make sure the email is valid before heading into the magic link flow.
The error copy in the video is outdated, new copy is  `We don't recognize the email you entered. Login with QR code instead, or verify your email at gallery.so/settings`
https://github.com/gallery-so/gallery/assets/6754223/873629ef-63e5-4eb1-af32-c3d1b7ce8f4a
> [GAL-3106] Magic Link Email Check

- apps/mobile/src/contexts/MobileAnalyticsProvider.tsx
- apps/web/src/contexts/analytics/WebAnalyticsProvider.tsx
- packages/shared/src/contexts/AnalyticsContext.tsx
> Simplify tracking

- apps/mobile/src/components/ProfileView/ProfileView.tsx
**Changes**
- Left align username
**Demo**
> [GAL-3096] Left align username

- apps/mobile/src/components/ProfileView/Tabs/ProfileViewFollowersTab.tsx
**Changes**
Add empty state to follower/following tab
**Demo**
> [GAL-3082] Empty state for following/follower tab

- apps/mobile/src/components/Feed/Socialize/RemainingAdmireCount.tsx
Fix grammar **other(s)**
**Demo**
**Before**
**After**
> [GAL-3103] Fix grammar admire

- apps/mobile/src/components/SvgWebView.tsx
These were causing severe lag.
> fail on svgs bigger than 1mb

- apps/web/src/components/GalleryEditor/GalleryEditor.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/CreatorEmptyStateSidebar.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/PiecesSidebar.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarChainSelector.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarList.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarViewSelector.tsx
- apps/web/src/components/Settings/Settings.tsx
- apps/web/src/components/core/Dropdown/DropdownItem.tsx
- apps/web/src/utils/graphql/isFeatureEnabled.tsx
- packages/shared/src/theme/colors.d.ts
https://www.loom.com/share/3f2bdcff77e84745ad7490f298911552
> [GAL-2710] Created Tab

- apps/mobile/src/components/Community/CommunityCollectorsList.tsx
- apps/mobile/src/components/Community/CommunityView.tsx
- apps/mobile/src/components/Community/CommunityViewFallback.tsx
- apps/mobile/src/components/Search/Community/CommunitySearchResult.tsx
- apps/mobile/src/components/Search/SearchFilter.tsx
- apps/mobile/src/components/Search/SearchResults.tsx
- apps/mobile/src/navigation/MainTabStackNavigator.tsx
- apps/mobile/src/navigation/types.ts
- apps/mobile/src/screens/CommunityScreen/CommunityScreen.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx
**Changes**
- Add community screen
- Can be access from nft detail screen and search
**Demo**
**Nft Detail Screen**
https://github.com/gallery-so/gallery/assets/4480258/ca830197-e603-4e7e-a689-632c30586ef2
**Search**
https://github.com/gallery-so/gallery/assets/4480258/dc09bf89-afbb-4335-a613-8519621005d6
> [GAL-3077] Community screen

- apps/mobile/src/components/Feed/Socialize/CommentBox.tsx
- apps/mobile/src/components/Feed/Socialize/CommentButton.tsx
- apps/mobile/src/components/Feed/Socialize/NotesModal/NotesModal.tsx
- apps/mobile/src/components/GalleryBottomSheet/GalleryBottomSheetBackdrop.tsx
- apps/mobile/src/components/GalleryBottomSheet/GalleryBottomSheetModal.tsx
**Changes**
- Comment box support multiline
**Demo**
**Comment**
https://github.com/gallery-so/gallery/assets/4480258/a543c6b6-6f45-4dbb-9ee1-8afaeb91169f
**Notes**
https://github.com/gallery-so/gallery/assets/4480258/fcc2e2da-c421-417a-af5a-67beca0eb097
> [GAL-3024] Comment support multiline

- apps/web/src/components/Twitter/TwitterSetting.tsx
- apps/web/src/scenes/UserGalleryPage/UserTwitterSection.tsx
https://loom.com/share/386a2dc7f49542299448e90ee408e10c
> Always display social if connected

- apps/web/src/contexts/globalLayout/GlobalNavbar/CollectionNavbar/CollectionRightContent.tsx
- apps/web/src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryRightContent.tsx
> Remove edit button from desktop nav

- apps/web/src/components/NftPreview/NftPreview.tsx
| <img width="775" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/efaca0e5-a647-4c0d-b14e-54cde80e520d"> | <img width="769" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/5cf3ea2e-832b-4015-88ed-52eba95d7434"> |
> Temp fix for motzko full height iframe exemption

- apps/web/pages/_/components.tsx
- apps/web/src/components/RawProfilePicture.tsx
- apps/web/src/icons/EditPencilIcon.tsx
The goal of this PR is to get the components ready for use on web.
> Presentational Profile Pictures w/ Examples

- apps/mobile/src/components/Feed/Socialize/NotesModal/AdmireNote.tsx
- apps/mobile/src/components/GalleryBottomSheet/GalleryBottomSheetBackground.tsx
- apps/mobile/src/components/Pill.tsx
- apps/mobile/src/components/Search/SearchResult.tsx
- apps/mobile/src/components/Trending/TrendingUserCard.tsx
**Changes**
1. Fix ui for bottom sheet modal
2. fix explore card cut-off
3. update search result to remove empty space
4. update twitter pill border color
**Demo**
**Fix ui for bottom sheet modal**
| ![image](https://github.com/gallery-so/gallery/assets/4480258/fbdd17be-979e-4e7a-b28c-6cafb8e0cefa)| <img width="1080" alt="CleanShot 2023-06-12 at 20 18 56@2x" src="https://github.com/gallery-so/gallery/assets/4480258/1acaed2c-e64e-4363-a2f4-3cc3946f75ec"> | 
**Fix explore card cut-off**
| ![image](https://github.com/gallery-so/gallery/assets/4480258/59cd88b1-3f61-4d3d-b7fe-7f24b41ffe4c) | <img width="1080" alt="CleanShot 2023-06-12 at 20 20 41@2x" src="https://github.com/gallery-so/gallery/assets/4480258/b8916cd4-b …
> Fix fraser feedback

- apps/web/src/components/Twitter/TwitterFollowingModal.tsx
**Loading State**
**Disable if following everyone**
> Follow All button polish

- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedCommunities.tsx
- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedFollowers.tsx
Updates styling to make the tappable elements visually consistent with existing tappables in the app like usernames on the feed.
Before
After
> Update styling on shared followers and communities for consistency

- apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsEth.tsx
- apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsTezos.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx
- apps/web/src/components/NftPreview/NftPreviewLabel.tsx
- apps/web/src/constants/creator.ts
- apps/web/src/scenes/NftDetailPage/NftDetailText.tsx
**Changes**
- Show creator name in the NFT detail page in Web and Mobile
**Demo**
**Web**
**Mobile**
https://github.com/gallery-so/gallery/assets/4480258/31f7f625-69f5-47be-a1b3-1d80529b7962
> [GAL-3158] Creator name in NFT detail

- .vscode/extensions.json
- graphql.config.yml
- package.json
- yarn.lock
- Ensure that the LSP is picking up on all of our typescript files
- Install the latest version of the LSP
> Improvements for GraphQL in VSCode

- packages/shared/src/theme/colors.js
there was a regression after adding the different shades of black. this solution continues to be brittle 😭
> update dark mode colors for web

- apps/web/src/components/GalleryEditor/CollectionEditor/SortableStagedNft.tsx
**Before**
https://github.com/gallery-so/gallery/assets/3245367/f3f93a5f-cf81-43b3-bd52-dd7ea180cddb
**After**
https://github.com/gallery-so/gallery/assets/3245367/9161ed83-3ef7-4a06-8c1a-2197573b1b78
> Fix hover regression on LiveDisplayButton

- apps/web/src/components/Announcement/constants.ts
- apps/web/src/scenes/MintPages/MementosPage.tsx
> Memento tweaks

- apps/mobile/src/components/FollowButton.tsx
- apps/web/src/components/Follow/FollowButton.tsx
Add Follow Back state to follow button on mobile and web
Web
Mobile
> GAL-3408 Add Follow Back state to follow button on mobile and web

- apps/web/src/contexts/globalLayout/GlobalBanner/GlobalBanner.tsx
> Hyperblue banner

- apps/web/src/components/HoverCard/HoverCard.tsx
- apps/web/src/components/ProfilePictureStack.tsx
- apps/web/src/scenes/UserGalleryPage/UserGalleryHeader.tsx
- apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedCommunities.tsx
- apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedFollowers.tsx
- apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedInfo.tsx
- apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedInfoList/SharedCommunitiesList.tsx
- apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedInfoList/SharedFollowersList.tsx
- apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedInfoList/SharedInfoListRow.tsx
Added PFPs to the Shared Followers components
User Profile view
List view
> Display PFPs in Shared Followers component on User Profile and List View

- apps/web/src/components/NftSelector/NftSelector.tsx
- apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorFilterNetwork.tsx
- apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorFilterSort.tsx
- apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorViewSelector.tsx
- apps/web/src/components/NftSelector/NftSelectorToken.tsx
- apps/web/src/components/Profile/ProfilePictureDropdown.tsx
- apps/web/src/components/Profile/UserInfoForm.tsx
- apps/web/src/scenes/UserGalleryPage/UserNameAndDescriptionHeader.tsx
Add events to PFP Edit Flow + NFT Selector
> Add  PFP Edit Flow events

- apps/web/src/components/Feed/Socialize/AdmireLine.tsx
- apps/web/src/components/NftSelector/NftSelectorTokenPreview.tsx
- apps/web/src/components/ProfilePictureStack.tsx
- apps/web/src/components/RawProfilePicture.tsx
**Changes**
**Demo**
**Add hover state to edit pfp**
| <img width="282" alt="CleanShot 2023-07-05 at 19 55 47@2x" src="https://github.com/gallery-so/gallery/assets/4480258/6f4499cd-5889-4d8d-a91c-e37588fb8a87"> | <img width="246" alt="CleanShot 2023-07-05 at 19 59 21@2x" src="https://github.com/gallery-so/gallery/assets/4480258/74867325-1ce6-4ca3-b881-5f3d9f736ac7"> | 
**Remove border on nft hover**
| <img width="207" alt="CleanShot 2023-07-05 at 20 01 45@2x" src="https://github.com/gallery-so/gallery/assets/4480258/09a3fea5-8991-49a8-9efd-106b78f4e777"> | <img width="267" alt="CleanShot 2023-07-05 at 20 00 43@2x" src="https://github.com/gallery-so/gallery/assets/4480258/3eab610e-65af-4b17-b319-d443c697bb9b"> | …
> PFP QA - 1

- apps/web/src/components/NftPreview/NftPreview.tsx
**Changes**
Fix cropped NFT at mikegee gallery
**Demo**
| **Before** | **After** |
|<img width="1094" alt="CleanShot 2023-07-05 at 19 50 48@2x" src="https://github.com/gallery-so/gallery/assets/4480258/d890b791-c857-4955-83d4-6c3d691e4ea1"> | <img width="710" alt="CleanShot 2023-07-05 at 19 49 42@2x" src="https://github.com/gallery-so/gallery/assets/4480258/845bc83b-dcaa-4d83-a98b-ed56ef2f87b6"> |
| <img width="1476" alt="CleanShot 2023-07-05 at 19 46 39@2x" src="https://github.com/gallery-so/gallery/assets/4480258/c9a6945e-bb38-4a94-bb15-965289bc00b1"> | <img width="1477" alt="CleanShot 2023-07-05 at 19 47 45@2x" src="https://github.com/gallery-so/gallery/assets/4480258/ac58a965-9335-4346-947f-b735d33ffb5a">|
> Fix NFT cropped on 1 column

- apps/web/src/components/Feed/Socialize/RemainingCommentCount.tsx
Fixes "View all 1 comments" when there's one comment on an event:
Before:
After:
> Add check of total comments

- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarChainDropdown.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/chains.ts
- apps/web/src/components/WalletSelector/multichain/WalletButton.tsx
https://github.com/gallery-so/gallery/assets/80802871/93afda65-f0e0-46e2-9810-087e7747efda
> remove hover magnification, make icon background transparent, remove commented lines

- apps/web/src/components/Feed/Socialize/CommentBox/CommentBox.tsx
- apps/web/src/components/ProfilePicture/ProfilePicture.tsx
Fix when non-pfp user comment
**Demo**
https://github.com/gallery-so/gallery/assets/4480258/cb56d231-c5c9-4cf4-82a8-f4f55c55d6f2
> fix non-pfp comment crash

- apps/mobile/.eslintrc.json
- apps/mobile/index.js
- apps/mobile/src/components/Feed/AdmireBottomSheet/AdmireBottomSheet.tsx
- apps/mobile/src/components/Feed/FeedList.tsx
- apps/mobile/src/components/Feed/Socialize/AdmireLine.tsx
- apps/mobile/src/components/Feed/Socialize/Interactions.tsx
- apps/mobile/src/components/GalleryRefreshControl.tsx
- apps/mobile/src/components/Notification/NotificationList.tsx
- apps/mobile/src/components/PfpPicker/PfpBottomSheet.tsx
- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedFollowers.tsx
- apps/mobile/src/screens/HomeScreen/ExploreScreen.tsx
- apps/mobile/src/screens/NotificationsScreen.tsx
- apps/mobile/src/screens/ProfilePicturePickerScreen/ProfilePicturePickerGrid.tsx
- apps/mobile/src/screens/ProfileScreen/ProfileScreen.tsx
- All the things checked off in the image below
- Made a `GalleryRefreshControl` that adapts to the selected color scheme
- Forced to use the new with the lint rule
- Fixed the white flash on the notifications screen
> Mobile PFP Follow Ups

- apps/mobile/src/components/Feed/FeedListSectionHeader.tsx
- apps/mobile/src/components/Feed/FeedVirtualizedRow.tsx
- apps/mobile/src/components/Feed/createVirtualizedFeedEventItems.ts
- apps/mobile/src/components/ProfileView/ProfileView.tsx
- apps/mobile/src/components/ProfileView/ProfileViewHeader.tsx
- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedCommunities.tsx
- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedCommunitiesSheet.tsx
- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedFollowers.tsx
- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedInfo.tsx
- apps/mobile/src/components/Search/SearchDefault.tsx
- apps/mobile/src/components/Search/SearchResults.tsx
- apps/mobile/src/components/Search/User/UserSearchResult.tsx
- apps/mobile/src/components/UserFollowList/UserFollowCard.tsx
- apps/mobile/src/screens/ProfileScreen/ProfileScreen.tsx
- apps/mobile/src/screens/SettingsProfileScreen.tsx
- apps/mobile/src/utils/isFeatureEnabled.tsx
PFPs should be available to everyone with the mobile app now
> Remove PFP Flags

- apps/web/src/components/NftPreview/NftPreview.tsx
- apps/web/src/utils/isLiveMediaType.ts
Enable live rendering GLTF media
> Support gltf media for liverender

- apps/web/src/components/GalleryEditor/PiecesSidebar/chains.ts
Allow POAPs to be displayed in sidebar
> Fix poap regression

- apps/web/src/components/GalleryEditor/PiecesSidebar/chains.ts
> Enable zora chain

- apps/web/src/components/GalleryEditor/PiecesSidebar/PiecesSidebar.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarTokens.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarWalletSelector.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/createVirtualizedRowsFromGroups.ts
- apps/web/src/components/GalleryEditor/PiecesSidebar/groupCollectionsByAddress.ts
> [GAL-3581] add additional Wallet Selector dropdown in Editor sidebar

- apps/web/src/components/GalleryEditor/PiecesSidebar/chains.ts
> Enable arbitrum

- apps/web/src/scenes/NftDetailPage/NftDetailModel.tsx
> Disable interaction prompt for glbs (thanks Figure31!)

- apps/web/src/components/GalleryEditor/CollectionSidebar/CollectionListItem.tsx
- apps/web/src/components/MultiGallery/Gallery.tsx
- apps/web/src/components/Profile/ProfilePictureDropdown.tsx
- apps/web/src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
- apps/web/src/scenes/UserGalleryPage/UserGalleryCollection.tsx
> [GAL-3586] Update Dropdown Menu text styling to be lowercase + BaseM

- apps/mobile/.eslintrc.json
- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetLine.tsx
- apps/mobile/src/components/Feed/Socialize/CommentLine.tsx
- apps/mobile/src/components/Feed/Socialize/Interactions.tsx
- apps/mobile/src/components/Feed/Socialize/RemainingCommentCount.tsx
- apps/mobile/src/components/GalleryTouchableOpacity.tsx
- apps/mobile/src/components/UsernameDisplay.tsx
- apps/mobile/src/screens/SearchScreen.tsx
**Changes**
- Only show **View all comments** if its more than 1
- Update the comment UI to vertical instead of horizontal
**Demo**
**Only show **View all comments** if its more than 1**
**Update the comment UI to vertical instead of horizontal**
> [GAL-3707] [GAL-3727] Update comment UI

- apps/web/src/components/WalletSelector/multichain/WalletButton.tsx
- apps/web/src/components/WalletSelector/multichain/supportedAuthMethods.ts
> Update auth copy to display Ethereum and L2s

- apps/mobile/src/components/Community/CommunityView.tsx
> GAL-3582: remove created by block from POAP community pages

- apps/web/src/components/Feed/Socialize/CommentsModal/CommentsModal.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/AddWalletSidebar.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/PiecesSidebar.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarWalletSelector.tsx
- apps/web/src/components/ManageWallets/ManageWallets.tsx
- apps/web/src/components/NftSelector/NftSelectorView.tsx
- apps/web/src/components/NftSelector/groupNftSelectorCollectionsByAddress.ts
- apps/web/src/components/Twitter/useOpenTwitterFollowingModal.tsx
- apps/web/src/components/WalletSelector/WalletSelector.tsx
- apps/web/src/components/WalletSelector/multichain/EthereumAddWallet.tsx
- apps/web/src/components/WalletSelector/multichain/EthereumAuthenticateWallet.tsx
- apps/web/src/components/WalletSelector/multichain/MultichainWalletSelector.tsx
- apps/web/src/hooks/useAddWalletModal.tsx
- apps/web/src/scenes/Modals/ManageWalletsModal.tsx
https://www.loom.com/share/03a342393bba4756ab6705a7f52a1339?sid=710325c0-ef97-4f42-860e-ebf890c6d970
> Refactor wallet connect handlers, ensure refresh post-connection

- apps/mobile/src/components/Feed/FeedListSectionHeader.tsx
| <img width="465" alt="Screenshot 2023-07-25 at 12 17 44 PM" src="https://github.com/gallery-so/gallery/assets/12162433/558e51b7-ec23-4dde-a164-cc4b8bdba32b"> | <img width="509" alt="Screenshot 2023-07-25 at 12 17 20 PM" src="https://github.com/gallery-so/gallery/assets/12162433/51385327-ad17-41f0-be48-1d7bf88510eb"> |
> Truncate long collection titles on mobile

- apps/web/src/components/MultiGallery/Gallery.tsx
when coming from the edit flow, clicking anywhere on the gallery tile now takes us straight to edit mode
https://www.loom.com/share/492203cbd3c54dee899ef715dbe7837c?sid=40fabfed-6ff8-43cb-877e-ecf1a298fcce
> GAL-3728: edit mode for gallery tile

- apps/web/src/components/Notifications/notifications/SomeoneFollowedYou.tsx
> Fixes Follow Back Button in Notifications

- apps/mobile/src/components/ProfileView/ProfileViewHeader.tsx
- apps/mobile/src/components/ProfileView/SocialPills/ProfileViewFarcasterPill.tsx
- apps/mobile/src/components/ProfileView/SocialPills/ProfileViewTwitterPill.tsx
- apps/mobile/src/icons/FarcasterIcon.tsx
show Farcaster handle on mobile
tail wind was being a pain in the ass so the styling is super unsophisticated, just to get it out the door.
gap/spacing between pills wasn't working so hardcoded a right margin on the twitter pill. also doesn't handle long handles that might push the pill off-screen. 
we can follow up before lens next week
showing both
only 1
none
> show fc handle on mobile

- apps/mobile/src/components/LinkableAddress.tsx
- apps/mobile/src/icons/ExternalLinkIcon.tsx
- apps/mobile/src/screens/NftDetailScreen/DetailSection.tsx
- apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsEth.tsx
- apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsPOAP.tsx
- apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsTezos.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx
> [GAL-3847] Mobile NFT details regression

- apps/web/src/utils/formalUrl.test.ts
- apps/web/src/utils/formatUrl.ts
> [GAL-3647] Allstarz community description URL is not working

- apps/mobile/src/components/ProfileView/ProfileViewHeader.tsx
- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedInfo.tsx
> [GAL-3891] reduce the user bio and social pills for own profile

- apps/web/src/contexts/globalLayout/GlobalBanner/GlobalBanner.tsx
- apps/web/src/contexts/globalLayout/GlobalLayoutContext.tsx
- apps/web/src/scenes/MaintenancePage/MaintenancePage.tsx
- packages/shared/src/utils/processProjectUrl.ts
- schema.graphql
> Aug 2023 Maintenance

- apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailPage.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailView.tsx
- packages/shared/src/components/TokenViewEmitter.tsx
running with correct arguements
> ViewToken mutation

- apps/mobile/src/components/Community/CommunityHeader.tsx
- apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsEth.tsx
> [GAL-3794] Truncate community descriptions properly on mobile

- apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsEth.tsx
- apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsTezos.tsx
> [GAL-3924] update color of contracts on mobile nft detail

- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetLine.tsx
some context: https://galleryso.slack.com/archives/C058WRKCPR6/p1690548555823829
> [GAL-3640] update comments styling

- .github/labeler.yml
added `schema` and `libraries` labels
> More labels

- apps/web/src/components/NftPreview/NftPreview.tsx
| ![image](https://github.com/gallery-so/gallery/assets/12162433/54944a16-a6c6-46ec-a929-4fa7a762dd90) | <img width="749" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/032db2cc-7da0-463e-b4b0-ba5962ebba45"> |
> Fix tiny SVGs on safari

- apps/mobile/package.json
- apps/mobile/src/components/Community/CommunityBottomSheet.tsx
- apps/mobile/src/components/Community/CommunityMeta.tsx
- apps/mobile/src/components/Feed/Posts/DeletePostBottomSheet.tsx
- apps/mobile/src/components/Feed/Posts/PostBottomSheet.tsx
- apps/mobile/src/components/Notification/NotificationSkeleton.tsx
- apps/mobile/src/components/PfpPicker/PfpBottomSheet.tsx
- apps/mobile/src/components/Post/WarningPostBottomSheet.tsx
- apps/mobile/src/components/Select.tsx
- apps/mobile/src/hooks/usePostComment.ts
- apps/mobile/src/screens/Login/LandingScreen.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorScreenFallback.tsx
- yarn.lock
**Changes**
1. Fix overlap text on notification
2. Update community meta typography
3. Add NFT Selector fallback
4. Fix relay connection warning whenever user posted a comment
5. Fix keyboard crash when slide down the keyboard during comment
**Demo**
**Fix overlap text on notification**
| <img width="473" alt="CleanShot 2023-08-07 at 14 24 49@2x" src="https://github.com/gallery-so/gallery/assets/4480258/c2f90544-d17f-465c-880a-3852862ead80"> | <img width="487" alt="CleanShot 2023-08-07 at 14 24 07@2x" src="https://github.com/gallery-so/gallery/assets/4480258/02efd924-9cb4-417e-a7df-8af2c8dd2685"> | 
**Update community meta typography**
| <img width="445" alt="CleanShot 2023-08-07 at 14 28 25@2x" …
> [GAL-3953] [GAL-3075] Koala Polish

- apps/mobile/app.config.ts
bump mobile app version 1.0.14 -> 1.0.15
N/A
N/A
N/A
> bump mobile app version 1.0.14 -> 1.0.15

- apps/mobile/src/components/Notification/NotificationSkeleton.tsx
- Fix the user notification behaviour. 
- If only 1 user admire/comment should redirect to the user profile
- If > 1, open the user list bottom sheet
- Fix weird left padding on the bottom sheet
- Found out that click the user in the bottom sheet didn't redirect to the profile screen
**Before**
https://github.com/gallery-so/gallery/assets/4480258/86f07879-f4dc-4f3a-8070-53016971d421
**After**
https://github.com/gallery-so/gallery/assets/4480258/c087f681-41a1-4d2b-bf75-7ea2e7bb6729
**Padding issue**
| <img width="452" alt="CleanShot 2023-08-16 at 10 56 51@2x" src="https://github.com/gallery-so/gallery/assets/4480258/85cb7c11-05b1-469a-8668-b687ff05a416"> |<img width="440" alt="CleanShot 2023-08-16 at 10 57 27@2x" …
> [GAL-4007] Mobile: Notification PFP opens drawer 🐞

- apps/mobile/index.js
- apps/mobile/src/hooks/usePostComment.ts
Fix the comment didn't show up after submitting comment in the bottom sheet
**Before**
https://github.com/gallery-so/gallery/assets/4480258/8a0ef6e1-cb31-4f0f-9683-c15e1b67f50c
**After**
https://github.com/gallery-so/gallery/assets/4480258/2d278910-cb71-4094-8716-3b6e4880def3
1. Submit comment while opening bottom sheets 
2. Submit comment without opening bottom sheets
1. Open a comment bottom sheets (should be able to open if there is more than 3 comments)
2. Submit a comment and it should appear in the bottom sheets
> Fix comment didn't show up

- apps/web/src/components/Feed/Socialize/CommentLine.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNote.tsx
- apps/web/src/components/Feed/Socialize/PostSocializeSection.tsx
this pr makes some updates and fixes to comment layouts on web
before
after
before
after
multiple line comments
view comments on web
> update web comment layout and fix

- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheet.tsx
comments displayed in the bottom sheet go from old → new
**Before:**
**After:**
> GAL-4038: fix comments order on mobile

- apps/mobile/src/utils/isFeatureEnabled.tsx
- apps/web/src/utils/graphql/isFeatureEnabled.tsx
Enable Koala feature flag for Beta Testers
N/A
N/A
Users with the Beta Tester role can access Koala features
> enable koala for beta users

- apps/mobile/app.config.ts
bump mobile app version from 1.0.15 to 1.0.16
N/A
N/A
N/A
> bump mobile app version to 1.0.16

- apps/mobile/src/components/CommunitiesList/CommunityCard.tsx
- apps/mobile/src/components/Feed/Posts/FeedPostSocializeSection.tsx
- apps/mobile/src/components/Feed/Posts/PostListSectionHeader.tsx
- apps/mobile/src/components/Feed/Socialize/AdmireLine.tsx
- apps/mobile/src/components/Feed/Socialize/CommentLine.tsx
- apps/mobile/src/components/Feed/Socialize/FeedEventSocializeSection.tsx
- apps/mobile/src/components/Feed/Socialize/RemainingCommentCount.tsx
- apps/mobile/src/components/GalleryTabs/GalleryTabBar.tsx
- apps/mobile/src/components/UserFollowList/UserFollowCard.tsx
- apps/mobile/src/navigation/FeedTabNavigator/TabBar.tsx
Increase font size of comments on feed  + other style changes
before
after
before
after
n/a
look at feed and community+user lists
make sure Posts and Feed Events both look ok
> adjust comment sizing on feed + other style fixes

- apps/web/src/components/Feed/Socialize/CommentBox/CommentBox.tsx
Disable formatting in Comment Input on web
**Before:**
https://www.loom.com/share/aaa14a5804534dd4b9b31248896043e3?sid=19d3ed25-0823-4028-8727-01449129fd8d
**After:**
https://www.loom.com/share/0cb5d00a97054aa29c0119386898f151?sid=f94321ba-8a50-4853-a77f-14579dd0ee9a
> GAL-4043: disable formatting on comment input

- apps/web/pages/home.tsx
- apps/web/src/components/Feed/CuratedFeed.tsx
The Curated feed on dev was coming up empty as we weren't requesting Posts for that feed (other feeds were fine)
> Include posts in dev feed

- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedCommunities.tsx
add borders around community pfps
**Before:**
**After:**
> GAL-4003: add borders around community pfps

- pull_request_template.md
Some small updates / typo fixes
---
> PR template update

- apps/mobile/src/components/Notification/Notification.tsx
- apps/web/src/components/Notifications/Notification.tsx
Don't show notifications for deleted posts on web and mobile. also adds error boundary around each notification in the mobile app so that an error doesn't crash the whole notification screen.
Screenshots of Post notification before I deleted the Post (the green nft)
Before change (after deleting post)
Notice the notification is still there but the token preview is gone. clicking the notification won't take you to a valid link either.
on mobile app the notification screen crashes
After change (after deleting post)
Notification is no longer displayed
If a user has a bunch of Post notifications and they delete all  their posts, their notifications might be very empty, even if they have older valid notifications. to prevent this we'll need to filter notifications for deleted posts on the …
> GAL-4092 dont show notifications for deleted posts on web and mobile

- apps/mobile/app.config.ts
> Mobile bump 1.0.17

- apps/web/pages/anewhome/index.tsx
- apps/web/pages/koala/index.tsx
- new URL (`koala` -> `anewhome`)
- new password
- centered input
- fix `p` cutoff in safari
> Koala invite page hotfixes

- apps/web/src/components/Notifications/Notification.tsx
- apps/web/src/components/Notifications/notifications/SomeoneViewedYourGallery.tsx
remove chevron from notifications component
**Before:**
**After:**
> GAL-4079: remove chevron from notifications component

- apps/mobile/src/screens/SettingsScreen/SettingsScreen.tsx
This makes the push notification setting available to everyone, not just admin users. 
N/A
Go to the Settings screen you should see the notification setting
> make push notification setting available to all

- apps/web/pages/anewhome/index.tsx
Error state for incorrect password
https://github.com/gallery-so/gallery/assets/12162433/5d5cb3a1-27e0-452c-90c2-2392fe46df23
> Secret password error handler

- apps/web/src/components/Feed/Posts/PostHeader.tsx
support markdown in post caption.. and also respect new lines..
**Before:**
**After:**
> GAL-4159 & GAL-4023: support markdown in post caption

- apps/web/src/scenes/CommunityPage/CommunityPageView.tsx
- apps/web/src/utils/getCommunityUrlForToken.ts
- packages/shared/src/utils/extractRelevantMetadataFromToken.ts
- Enables community pages for umbrella contracts
- Fixes token ID conversion issue for external links
video: https://github.com/gallery-so/gallery/assets/12162433/2136405e-e00a-4f2c-8421-86ad00eb6245
- tested different contracts
> [GAL-4111] [GAL-4165] Unleash community pages

- apps/mobile/src/utils/isFeatureEnabled.tsx
- apps/web/pages/onboarding/add-user-info.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/PiecesSidebar.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarChainDropdown.tsx
- apps/web/src/components/NftSelector/NftSelector.tsx
- apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorFilterNetwork.tsx
- apps/web/src/components/core/Dropdown/DropdownItem.tsx
- apps/web/src/hooks/api/tokens/useSyncTokens.ts
- apps/web/src/scenes/CommunityPage/CommunityPageOwnershipRequiredModal.tsx
> [GAL-3406] Enable creator sync

- apps/mobile/src/components/Feed/Posts/PostListItem.tsx
- apps/mobile/src/components/Feed/Posts/PostListSectionHeader.tsx
- apps/web/src/components/Feed/PostItem.tsx
- apps/web/src/components/Feed/Posts/PostCommunityPill.tsx
- apps/web/src/components/Feed/Posts/PostHeader.tsx
- apps/web/src/components/HoverCard/HoverCardOnCommunity.tsx
- apps/web/src/scenes/CommunityPage/CommunityPageView.tsx
This PR moves the link to the collection page into a pill on web + mobile
Before - web
Before - mobile
After - web
After - mobile 
After- mobile dark
After - web long text
After- mobile long text
- long collection name
- no collection name 
Go to any post and look for the collection name
> move collection page entry to pill on web + mobile

- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
- apps/mobile/src/utils/isFeatureEnabled.tsx
- apps/web/pages/onboarding/add-user-info.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/PiecesSidebar.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarChainDropdown.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarList/CollectionTitle.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarList/SidebarList.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarList/ToggleSpamIcon.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarTokens.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarViewSelector.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarWalletSelector.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/useTokenSearchResults.ts
- apps/web/src/components/NftSelector/NftSelector.tsx
- apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorFilterNetwork.tsx
- apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorFilterSort.tsx
- apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorViewSelector.tsx
- apps/web/src/components/core/Dropdown/DropdownItem.tsx
- apps/web/src/hooks/api/tokens/useSyncTokens.ts
- apps/web/src/scenes/CommunityPage/CommunityPageOwnershipRequiredModal.tsx
- Allow users to display Created tokens on Post Composer
- Consolidated token searching logic
- Auto-fetch tokens for wallet under same chain family (fixes another UI bug)
- Improved searching UI
https://www.loom.com/share/99eb13f1400545959eada00726015815?sid=a7e1ab17-2fdd-4f58-a368-498c936ea424
**Web Composer**
**Web Sidebar**
**Other issues fixed**
- [Do the same thing on mobile](https://linear.app/galleryso/issue/GAL-4207/enable-creator-sync-for-mobile-composer)
- [Creator support beta modal](https://linear.app/galleryso/issue/GAL-4206/web-creator-support-in-beta-modal)
- [Supersync on user signup](https://linear.app/galleryso/issue/GAL-4203/supersync-on-user-signup)
- [Enable per-contract refresh for Creators](https://linear.app/galleryso/issue/GAL-3471/web-refresh-button-for-individua …
> [GAL4190] Created tab for Post Composer

- apps/web/src/components/Feed/Socialize/CommentLine.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNote.tsx
- apps/web/src/components/Notifications/notifications/SomeoneCommentedOnYourPost.tsx
Unescape comments with special characters
> unescape comments

- apps/web/src/components/GalleryEditor/PiecesSidebar/PiecesSidebar.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarTokens.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/createVirtualizedRowsFromGroups.ts
- apps/web/src/components/GalleryEditor/PiecesSidebar/groupCollectionsByAddress.ts
Move token filtering logic for "Wallet Picker' in Editor to the main filtering logic (one level up)
Still working after refactor
Nothing in specific tested
Can check in editor by selecting wallets
> Move filterTokenByWallet logic in SidebarPieces to parent

- apps/mobile/src/components/Feed/Socialize/CommentBox.tsx
- apps/web/src/components/Feed/Socialize/CommentBox/CommentBox.tsx
When pasting text content in comment box, it should truncate to 300 char and point cursor to last char
> [GAL-4194] Bump comment character limit to 300 

- apps/mobile/src/components/DeepLinkRegistrar.tsx
add deep link to post url - `https://gallery.so/post/:postId`
> [GAL-4226] Deep Link to Post

- apps/web/src/components/Feed/Events/FeedEventNftPreviewWrapper.tsx
- apps/web/src/components/Feed/Posts/PostNftPreview.tsx
- apps/web/src/components/NftPreview/CollectionTokenPreview.tsx
- apps/web/src/components/NftPreview/GalleryNftPreviewWrapper.tsx
- apps/web/src/components/NftPreview/NftPreview.tsx
- apps/web/src/components/NftPreview/NftPreviewAsset.tsx
> Refactor NFT Preview

- apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx
- apps/mobile/src/screens/NftDetailScreen/UniversalNftDetailScreenInner.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailAsset.test.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailText.tsx
When applicable, display `CREATOR` subtitle instead of `OWNER`
> Display owner subtitle if owner

- apps/mobile/babel.config.js
- apps/mobile/package.json
- yarn.lock
Fix pressing **View all** in the wallet connect modal
Reference: https://github.com/WalletConnect/modal-react-native/issues/38 
https://github.com/gallery-so/gallery/assets/4480258/fb8237e1-eedc-40e3-99b3-151730125bab
-
1. Open the wallet connect modal
2. Press the view all
> [GAL-4178] fix view all wallet connect

- apps/mobile/src/components/DeepLinkRegistrar.tsx
> Deeplink block comments

- apps/web/src/components/NftFailureFallback/NftFailureBoundary.tsx
Media wasn't being refreshed post-sync. This meant the image would appear broken even after a successful sync.
https://github.com/gallery-so/gallery/assets/12162433/2f1bb4e8-76bb-4091-8f7a-46e9359d9c44
> Ensure relevant fragments are refreshed after syncing complete

- apps/mobile/app.config.ts
> Mobile version bump 1.0.18

- apps/mobile/app.config.ts
> Mobile version bump 1.0.19

- apps/mobile/src/components/Feed/Posts/PostBottomSheet.tsx
- Unfollow action should be at the bottom of the list
- Follow action should continue to appear second
| ![image](https://github.com/gallery-so/gallery/assets/12162433/f0b2ce1e-8bc9-44f3-8df3-60bc897e9e4e) | <img width="403" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/b2466390-5ad7-400b-9059-424542e5e85c"> | 
> Change follow list item order

- apps/web/src/components/Feed/Socialize/CommentsModal/CommentsModal.tsx
Comment Modal list use full screen height on web
Before:
After:
> [GAL-4136] fix scroll height in web view

- apps/mobile/src/components/Community/CommunityMeta.tsx
| Before | After | After |
|--------|--------|--------|
| <img width="461" alt="Screenshot 2023-09-15 at 5 50 31 AM" src="https://github.com/gallery-so/gallery/assets/49758803/3ff2828f-e880-4fbc-90a0-abb61bc25ae3"> |  <img width="457" alt="Screenshot 2023-09-15 at 5 52 42 AM" src="https://github.com/gallery-so/gallery/assets/49758803/6c2f88e6-4f05-434c-9a59-7ffc86ed6612"> |<img width="457" alt="Screenshot 2023-09-15 at 5 55 35 AM" src="https://github.com/gallery-so/gallery/assets/49758803/5796053d-76c7-4f08-b275-946ef7f81158"> |
> Minor layout fix for community pages on mobile

- apps/mobile/app.config.ts
> version bump 1.0.20

- apps/mobile/src/screens/NotificationsScreen.tsx
When landing on the Notifications Tab, we should always force-refresh notifications
> [GAL-4309] tapping on a push notification, leads to the notification screen but stale

- apps/mobile/src/components/Notification/Notifications/SomeoneFollowedYou.tsx
Fix text styling in SomeoneFollowedYou notif on mobile
| <img width="475" alt="Screenshot 2023-09-21 at 9 56 29 AM" src="https://github.com/gallery-so/gallery/assets/49758803/6e45ab27-66f5-43f2-b0de-abe77cf8b7e0"> | <img width="512" alt="Screenshot 2023-09-21 at 9 53 11 AM" src="https://github.com/gallery-so/gallery/assets/49758803/e7c4cdf2-7b5e-4aa8-86e0-164609601700"> | 
> Follow Back button on mobile regression

- apps/mobile/app.config.ts
> mobile version 1.0.21

- apps/mobile/src/components/Login/ConnectWalletButton.tsx
- apps/mobile/src/components/UpsellBanner.tsx
- apps/mobile/src/contexts/ManageWalletContext.tsx
- apps/mobile/src/hooks/useLogin.ts
- apps/mobile/src/navigation/RootStackNavigator.tsx
Fix bug on onboarding flow + upsell banner
1. Fix the double signature popup when sign in with wallet
2. Fix upsell banner show up although the user already has wallet
3. Refactor/Clean up on how we use the web3 provider
https://github.com/gallery-so/gallery/assets/4480258/3108485b-e230-435d-ad97-611f48e7015b
1. Sign in with wallet connect
2. Sign up with wallet connect
3. Login with existing user
4. Login with email account (freshly created) and add connect wallet
> Fix mobile auth & upsell banner

- apps/mobile/src/components/DeepLinkRegistrar.tsx
Deeplink URL parsing was a likely cause for deeplink crashes
- out of scope: opening the post composer screen specifically
> Wrap deeplink handler in try/catch to prevent crashes

- apps/web/pages/home.tsx
- apps/web/pages/latest/index.tsx
> Enable posts for logged out users

- apps/web/src/components/NftSelector/NftSelectorToken.tsx
- apps/web/src/components/Notifications/notifications/NewTokens.tsx
| <img width="205" alt="Screenshot 2023-09-22 at 12 17 37 PM" src="https://github.com/gallery-so/gallery/assets/12162433/d8499142-fa27-4464-98e8-74f16e19fa90"> | <img width="207" alt="Screenshot 2023-09-22 at 12 17 23 PM" src="https://github.com/gallery-so/gallery/assets/12162433/dedf65aa-3ad7-4ed3-ad98-9ec4bf2bcb32"> |
| <img width="431" alt="Screenshot 2023-09-22 at 12 17 47 PM" src="https://github.com/gallery-so/gallery/assets/12162433/5bdb1e3c-9511-4550-90f4-98b22e664bf5"> | <img width="381" alt="Screenshot 2023-09-22 at 12 21 26 PM" src="https://github.com/gallery-so/gallery/assets/12162433/9da4b4be-f05b-498d-ad00-8a43526bce7e"> | 
> Fix broken token views on web

- apps/mobile/app.config.ts
> mobile version bump 1.0.22

- apps/mobile/src/components/Boundaries/TokenFailureBoundary/TokenFailureBoundary.tsx
- apps/mobile/src/components/Boundaries/TokenFailureBoundary/TokenFailureFallbacks.tsx
- apps/mobile/src/components/Notification/Notifications/NotificationTokenPreview.tsx
- apps/mobile/src/contexts/TokenStateManagerContext.tsx
Enable tap to refresh invalid tokens on mobile
https://github.com/gallery-so/gallery/assets/12162433/ed13fd48-5e20-461f-87b7-416b07b5fbde
> Refreshable invalid tokens on mobile

- apps/mobile/src/components/Login/SignInBottomSheet.tsx
- apps/mobile/src/components/MarfaCheckIn/CheckInWalletSelection.tsx
Some copy improvements for more clarity.
before
after
na
you can see the new copy on 1. the landing screen before signing in, and 2. after signing in scan the Marfa QR code
> Improving copy for Marfa

- apps/mobile/app.config.ts
> bump 1.0.22 -> 1.0.23

- apps/web/pages/community/[chain]/[contractAddress]/live.tsx
update resonance proejct id to final one, so that the screen page by default points to Resonance
na
na
go to /community/arbitrum/0x47a91457a3a1f700097199fd63c039c4784384ab/live it should show posts for Resonance
> update resonance proejct id

- apps/web/pages/community/[chain]/[contractAddress]/live.tsx
- apps/web/src/components/NftSelector/NftSelector.tsx
- apps/web/src/components/NftSelector/NftSelectorView.tsx
Make the NFT Selector mobile responsive so people can post from moweb
mobile:
https://github.com/gallery-so/gallery/assets/80802871/d25cb3cf-3927-4a57-ac2f-e25c59f9cc59
regression check - desktop still looks good
https://github.com/gallery-so/gallery/assets/80802871/965d7bee-312d-40df-9930-f27dce560337
mobile vs desktop (didnt do tablet, can take another polish pass later, not important for Marfa)
- go to create a post on mobile web
> Make NFT Selector on web responsive

- apps/mobile/app.config.ts
- apps/web/src/components/NftSelector/NftSelector.tsx
- apps/web/src/components/NftSelector/NftSelectorView.tsx
bump mobile app version 1.0.23 -> 1.0.24
> bump 1.0.23 -> 1.0.24

- apps/mobile/src/screens/PostScreen/PostComposerScreen.tsx
- apps/web/src/components/NftSelector/NftSelector.tsx
- apps/web/src/components/NftSelector/NftSelectorView.tsx
We allow user to multiple tap on post button that result to multiple requests. Added the tracking to state to prevent it
1. Write some post and press the `Post` button multiple times and check how many request have made
> [GAL-4331] Prevent multiple post from client

- apps/web/src/components/NftPreview/NftPreview.tsx
Ensure 3D models take up full height when applicable.
| <img width="1506" alt="Screenshot 2023-09-27 at 4 29 02 PM" src="https://github.com/gallery-so/gallery/assets/12162433/f49da7c8-ed66-4d04-91bb-63b816aa9a52"> | <img width="1507" alt="Screenshot 2023-09-27 at 4 28 44 PM" src="https://github.com/gallery-so/gallery/assets/12162433/45968e87-0f2c-4bda-882e-1cc6ca31e407"> | 
> fix full height issue for small iframes

- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedFollowers.tsx
adjust color for admire count pill on dark mode
before
after
light mode should still look good
look at post with more than 3 admires on dark mode
> GAL-4395 adjust color for admire count pill on dark mode

- apps/mobile/src/components/Feed/WorldwideFeed.tsx
- apps/mobile/src/components/ProfileView/Tabs/ProfileViewActivityTab.tsx
- apps/mobile/src/screens/HomeScreen/LatestScreen.tsx
- apps/mobile/src/screens/PostScreen/PostComposerScreen.tsx
- apps/mobile/src/screens/PostScreen/usePost.tsx
- apps/mobile/src/screens/ProfileScreen/ProfileScreen.tsx
- apps/web/pages/[username]/activity.tsx
- apps/web/pages/home.tsx
- apps/web/pages/latest/index.tsx
- apps/web/src/components/Feed/CuratedFeed.tsx
- apps/web/src/components/Feed/LatestFeed.tsx
- apps/web/src/hooks/api/posts/useCreatePost.ts
- apps/web/src/scenes/UserActivityPage/UserActivityFeed.tsx
- Remove all the `includePost` flag from `web` and `mobile`
- Test the optimistic update works
1. web - test post from sidebar
2. web - test post from community
3. mobile - test post from bottom bar
4. mobile - test post from community
> [GAL-4175] Clean include posts flag

- apps/mobile/src/components/Feed/Socialize/CommentLine.tsx
- apps/mobile/src/components/Feed/Socialize/RemainingCommentCount.tsx
- apps/mobile/src/components/Select.tsx
Fix spacing on this screen
1. Network filter
2. 'View all comment'
**Network filter**
|<img width="434" alt="CleanShot 2023-09-28 at 20 28 24@2x" src="https://github.com/gallery-so/gallery/assets/4480258/13561e56-a300-482f-846a-4c66950769c4"> |<img width="474" alt="CleanShot 2023-09-28 at 20 26 55@2x" src="https://github.com/gallery-so/gallery/assets/4480258/0547426e-8525-4c05-bd09-a4a5fcf7aac4">
**View all comment**
|<img width="399" alt="CleanShot 2023-09-28 at 20 29 00@2x" src="https://github.com/gallery-so/gallery/assets/4480258/96b40c1d-17bc-466e-a72d-ac3e55b90b59"> | <img width="400" alt="CleanShot 2023-09-28 at 20 27 39@2x" src="https://github.com/gallery-so/gallery/assets/4480258/b017fe40-5401-4d4f-9efe-2 …
> [GAL-4398] [GAL-4399] Fix UI spacing on mobile

- apps/web/src/utils/useClearURLQueryParams.ts
Added tracker to make sure the hooks only run once
> Fix infinite useClearURLQueryParams hooks trigger

- pull_request_template.md
⭐  Added before/after placeholder table. Default PR template below
---
Please make sure to review and check all of …
> [PR Template] Before/After placeholder

- apps/mobile/src/hooks/useLogout.ts
Un-register notification token during logout
> [GAL-3963] un-register notification token

- apps/mobile/src/components/Community/Tabs/CommunityViewPostsTab.tsx
- apps/mobile/src/components/ProfileView/Tabs/ProfileViewActivityTab.tsx
- apps/mobile/src/constants/feed.ts
- apps/mobile/src/screens/CommunityScreen/CommunityScreen.tsx
- apps/mobile/src/screens/ProfileScreen/ProfileScreen.tsx
Fix require cycle component. To avoid any unstable state in the screen
1. Test the profile activity feed
2. Test the community feed
> Fix require cycle warning

- apps/web/src/components/HoverCard/HoverCard.tsx
- apps/web/src/components/NftSelector/NftSelector.tsx
- apps/web/src/contexts/postComposer/PostComposerContext.tsx
Clicking Back from Post Composer on web should return to Collection View if I navigated from there
https://github.com/gallery-so/gallery/assets/49758803/394139fb-f0e4-4545-935e-941b7ce3be06
https://github.com/gallery-so/gallery/assets/49758803/4578e9b4-fcbb-4454-8297-425afa16bae6
Not sure how to handle case that contract address might be incorrect
> [GAL-4265] Clicking Back from Post Composer should return to Collection View

- apps/web/src/components/NftSelector/NftSelector.tsx
Improve clarity
| <img width="949" alt="Screenshot 2023-10-02 at 3 34 52 PM" src="https://github.com/gallery-so/gallery/assets/12162433/bbf5b791-910d-4cac-b75f-470b3458fc74"> | <img width="949" alt="Screenshot 2023-10-02 at 3 34 52 PM" src="https://github.com/gallery-so/gallery/assets/12162433/0871467d-7eb0-43cf-abc1-41bd423a12d0"> |
> Tweak refresh copy

- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedCommunities.tsx
- apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedInfo.tsx
| <img width="711" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/501c697b-0ba5-478d-a722-2286ce74e84b"> | <img width="709" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/68418940-9cd1-4fd8-9532-974f4cf1f456"> | …
> Reduce spacing between shared elements in mobile profile header

- apps/mobile/src/components/Feed/Posts/PostListItem.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx
- apps/web/src/components/Feed/Posts/PostCommunityPill.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailText.tsx
- packages/shared/src/utils/extractRelevantMetadataFromToken.ts
- packages/shared/src/utils/getTezosExternalUrl.ts
Converts FxHash family contract names to "FxHash". This is hack until we have proper sub-community support.
| <img width="312" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/077bd39d-aacb-45b8-9839-ff4ff565c8e2"> | <img width="94" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/e192e3f2-ce33-499a-8ed4-f62adb6d8a9c"> | 
**Before**
| Post                                    | Detail Page                                     |
| <img width="1018" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/506d3dfa-b734-47ef-969c-200c321d290d"> | <img width="1504" alt="image" …
> Normalize fxhash contract name in community pills

- apps/mobile/app.config.ts
> Version bump 1.0.25

- apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsTezos.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx
- packages/shared/src/utils/extractRelevantMetadataFromToken.ts
> fxhash -> fx(hash)

- apps/mobile/src/components/Community/CommunityHeader.tsx
- apps/mobile/src/components/ProfilePicture/CommunityProfilePicture.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx
- apps/web/src/components/Feed/Posts/PostCommunityPill.tsx
- apps/web/src/components/HoverCard/CommunityHoverCard.tsx
- apps/web/src/components/ProfilePicture/CommunityProfilePicture.tsx
- apps/web/src/scenes/CommunityPage/CommunityPageViewHeader.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailAsset.test.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailText.tsx
- apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedInfoList/SharedCommunitiesList.tsx
- packages/shared/src/utils/extractRelevantMetadataFromToken.ts
If a community doesn't have a name, fallback to its contract address.
Bonus: enable community and user hover cards on NFT Detail Page.
| User                                     | Community                                      |
| <img width="1007" alt="Screenshot 2023-10-05 at 12 48 32 AM" src="https://github.com/gallery-so/gallery/assets/12162433/709370d1-b0ce-46ee-8ba4-492e5b782876"> | <img width="1024" alt="Screenshot 2023-10-05 at 12 45 41 AM" src="https://github.com/gallery-so/gallery/assets/12162433/f6d567a7-74c4-47c8-ad3a-c72aeada1789"> | …
> Fix communities without a name

- apps/mobile/src/components/Feed/Socialize/Comments.tsx
- apps/mobile/src/contexts/ToastContext.tsx
- apps/mobile/src/navigation/MainTabNavigator/TabBar.tsx
- apps/web/pages/onboarding/add-user-info.tsx
- apps/web/src/components/GalleryEditor/CollectionEditor/DragAndDrop/Section.tsx
- apps/web/src/components/HoverCard/HoverCard.tsx
- apps/web/src/components/LoadingAsset/ImageWithLoading.tsx
- apps/web/src/components/MultiGallery/Gallery.tsx
- apps/web/src/components/NftSelector/NftSelectorTokenPreview.tsx
- apps/web/src/components/Notifications/notifications/SomeoneViewedYourGallery.test.tsx
- apps/web/src/components/WalletSelector/multichain/EthereumAddWallet.tsx
- apps/web/src/components/WalletSelector/multichain/tezos/TezosAddWallet.tsx
- apps/web/src/components/core/Input/Input.tsx
- apps/web/src/components/core/TextArea/TextArea.tsx
- apps/web/src/contexts/modal/ModalContext.tsx
- apps/web/src/icons/HdDisabledIcon.tsx
- apps/web/src/icons/HdIcon.tsx
- apps/web/src/icons/Video.tsx
- apps/web/src/icons/VideoDisabled.tsx
- apps/web/src/scenes/MerchStorePage/SingleItemPage.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailGif.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailImage.tsx
- apps/web/src/utils/noop.ts
- packages/shared/src/utils/noop.ts
Adds pfp in place of AccountIcon in bottom navbar mobile
|  <img width="447" alt="Screenshot 2023-10-06 at 6 13 20 PM" src="https://github.com/gallery-so/gallery/assets/49758803/66c96b6e-bf57-4077-b91d-6eef8c7a553d"> | <img width="433" alt="Screenshot 2023-10-06 at 4 22 14 PM" src="https://github.com/gallery-so/gallery/assets/49758803/dfb72c9c-8eda-4500-8c2b-ac682bbb4cff"> |
> Add pfp in navbar

- apps/mobile/app.config.ts
> Version bump 1.0.26

- apps/web/src/components/Announcement/AnnouncementList.tsx
- apps/web/src/components/Announcement/constants.ts
- apps/web/src/components/Announcement/useAnnouncement.tsx
- apps/web/src/components/Follow/FollowButton.tsx
- apps/web/src/components/core/Chip/Chip.tsx
- packages/shared/src/analytics/constants.ts
Part of https://github.com/gallery-so/gallery/pull/1998
Refactors `Chips` to be instrumented using latest tracking format
> Web instrumentation: Chips

- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetLine.tsx
| Before                                     | After                                      | After           2                           |
| ------------------------------------------ | ------------------------------------------ | ------------------------------------------ |
| <img width="464" alt="Screenshot 2023-10-10 at 3 01 59 AM" src="https://github.com/gallery-so/gallery/assets/49758803/5d1404ca-6e1e-4576-8fbc-30e9760fb527"> | <img width="467" alt="Screenshot 2023-10-10 at 3 00 29 AM" …
> overflow on comment in mobile

- apps/mobile/app.config.ts
> 1.0.26 -> 1.0.27

- apps/web/src/components/Feed/Socialize/CommentLine.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNote.tsx
|  <img width="877" alt="Screenshot 2023-10-15 at 8 09 03 AM" src="https://github.com/gallery-so/gallery/assets/49758803/bf2e13b2-d4e5-4f31-baa0-f35edfab8c73"> | <img width="752" alt="Screenshot 2023-10-15 at 8 07 38 AM" src="https://github.com/gallery-so/gallery/assets/49758803/9bb45e6a-81b3-4a6c-9701-a5b953f4bc52"> | …
> wrap long comments on web

- apps/mobile/src/components/Notification/NotificationRegistrar.tsx
- apps/mobile/src/components/Notification/NotificationSkeleton.tsx
- apps/mobile/src/components/Notification/Notifications/NewTokens.tsx
- apps/web/src/components/NftSelector/NftSelector.tsx
- apps/web/src/components/NftSelector/NftSelectorTokenPreview.tsx
- apps/web/src/components/NftSelector/NftSelectorView.tsx
- apps/web/src/components/Notifications/notifications/NewTokens.tsx
- apps/web/src/components/Posts/PostComposer.tsx
- apps/web/src/components/Posts/PostComposerModal.tsx
- apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
- apps/web/src/scenes/CommunityPage/CommunityPageMetadata.tsx
- apps/web/src/scenes/CommunityPage/CommunityPagePostsTab.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailText.tsx
- packages/shared/src/analytics/constants.ts
> More tracking

- apps/mobile/src/components/Feed/FeedFilter.tsx
- apps/mobile/src/components/MarfaCheckIn/MarfaCheckInSheet.tsx
- apps/mobile/src/contexts/MobileAnalyticsProvider.tsx
- apps/mobile/src/navigation/FeedTabNavigator/FeedTabNavigator.tsx
- apps/mobile/src/navigation/FeedTabNavigator/TabBar.tsx
- apps/mobile/src/navigation/types.ts
- apps/mobile/src/screens/HomeScreen/CuratedScreen.tsx
- apps/mobile/src/screens/Login/NotificationUpsellScreen.tsx
- apps/mobile/src/screens/Login/navigateToNotificationUpsellOrHomeScreen.ts
- apps/mobile/src/screens/PostScreen/PostComposerScreen.tsx
- apps/web/src/contexts/analytics/WebAnalyticsProvider.tsx
- apps/web/src/utils/logger.ts
- packages/shared/src/analytics/constants.ts
- packages/shared/src/contexts/AnalyticsContext.tsx
- packages/shared/src/utils/removeNullishValues.test.ts
- packages/shared/src/utils/removeNullishValues.ts
- packages/shared/src/utils/time.ts
Autologging for debugging in development environment
> Logging improvements

- apps/web/pages/onboarding/add-email.tsx
- apps/web/src/components/Onboarding/OnboardingFooter.tsx
- Enforce emails on web (remove `Skip` button)
> Enforce emails on web

- apps/web/src/components/core/Dropdown/DropdownLink.tsx
> Fix dropdown link regression

- apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsEth.tsx
- apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsTezos.tsx
Change table for external link from "Visit Site" to "Official Site"
|
| 
go to nft detail page
> change label for external link

- apps/mobile/src/components/Feed/Socialize/CommentBox.tsx
Enable auto caps for comment input
Type a comment
> enable auto caps for comment

- apps/web/src/components/Search/SearchResult.tsx
| <img src="https://placehold.co/500x300" /> | <img width="492" alt="Screenshot 2023-10-20 at 3 45 16 PM" src="https://github.com/gallery-so/gallery/assets/49758803/a016fc96-df9d-44b3-b7e1-89d00ef11bf3"> |
> ignore markdown-style correctly in search result

- packages/shared/src/utils/highlighter.ts
Forgot to roll this in; part of reconciling jakz and rohan's markdown changes
> Improve sanitization

- apps/web/src/components/Feed/Socialize/CommentLine.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNote.tsx
remove word-break and comment alignment issue
> comments styling regression on web

- apps/web/src/components/Feed/Socialize/AdmireModal/AdmireModal.tsx
| <img width="406" alt="Screenshot 2023-10-26 at 2 49 33 AM" src="https://github.com/gallery-so/gallery/assets/49758803/bed89f1a-17da-48fd-91f1-96fe005454eb"> | <img width="394" alt="Screenshot 2023-10-26 at 3 02 21 AM" src="https://github.com/gallery-so/gallery/assets/49758803/f9a42ea4-18ac-4f08-8c31-2bce3a0b796d">|
Please make sure to review and check all of the …
> admires modal being cutoff in mobile web view

- apps/mobile/src/components/Notification/NotificationBottomSheetUserList.tsx
- apps/mobile/src/components/Notification/Notifications/SomeoneAdmiredYourPost.tsx
https://github.com/gallery-so/gallery/assets/49758803/cbbc5566-d2fc-492a-ac49-082a3e7943b5
https://github.com/gallery-so/gallery/assets/49758803/81e254f5-46b9-4939-8576-6de146b39592
> see admirers from someone admired your post notif

- packages/shared/src/utils/chains.ts
> Enable creator support for Zora

- apps/mobile/src/components/Feed/Posts/PostListItem.tsx
- apps/mobile/src/components/Gallery/GalleryTokenPreview.tsx
- apps/mobile/src/components/NftPreview/NftPreviewContextMenuPopup.tsx
- apps/mobile/src/components/NftPreview/UniversalNftPreviewContextMenuPopup.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailAsset/useNftDetailAssetSizer.ts
- apps/web/src/components/Feed/Posts/PostNftPreview.tsx
- packages/shared/src/utils/fitDimensionsToContainer.ts
Not sure how to reliably test this yet
| <img width="437" alt="Screenshot 2023-10-31 at 5 10 01 AM" src="https://github.com/gallery-so/gallery/assets/49758803/261f4d8c-5b5a-4fcc-8b97-55956d4e32fd"> | <img width="456" alt="Screenshot 2023-10-31 at 5 08 15 AM" src="https://github.com/gallery-so/gallery/assets/49758803/3c1e1857-4738-4f3d-87c7-6050a90255a9"> |
| <img width="437" alt="Screenshot 2023-10-31 at 5 10 01 AM" …
> [GAL-4152] Support dynamic height assets on web, mobile feeds

- apps/web/src/components/NftFailureFallback/NftFailureFallback.tsx
> Fix refresh icon clickability

- apps/web/src/components/WalletSelector/multichain/MultichainWalletSelector.tsx
- apps/web/src/contexts/auth/Web3WalletContext.tsx
Fixes this error, though e2e flow still needs work
> Gnosis safe fix

- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheet.tsx
- apps/mobile/src/components/Feed/Posts/FeedPostSocializeSection.tsx
- apps/mobile/src/components/Feed/Socialize/FeedEventSocializeSection.tsx
- apps/mobile/src/hooks/useMentionableMessage.ts
- apps/mobile/src/screens/PostScreen/PostComposerScreen.tsx
- apps/mobile/src/utils/isFeatureEnabled.tsx
> [DO NOT MERGE YET] Enable Mention on Mobile

- apps/mobile/src/components/Notification/Notification.tsx
- apps/mobile/src/components/Notification/NotificationSkeleton.tsx
- apps/mobile/src/components/Notification/Notifications/SomeoneCommentedOnYourPost.tsx
- apps/mobile/src/components/Notification/Notifications/SomeonePostedYourWork.tsx
- apps/web/src/components/Notifications/Notification.tsx
- apps/web/src/components/Notifications/notifications/SomeonePostedYourWork.tsx
- schema.graphql
add SomeonePostedYourWork notifs on web and mobile
https://github.com/gallery-so/gallery/assets/49758803/10d54833-a4e8-47a0-b06c-4603934f1933
Tested long token names to ensure it truncates correctly
> add SomeonePostedYourWork notifs

- apps/mobile/src/hooks/useMentionableMessage.ts
- packages/shared/src/utils/regex.ts
The mention don’t pop up after tapping @ after a line breaks
Reference: https://galleryso.slack.com/archives/C04DUEVL22U/p1697881194006169
**Before**
https://github.com/gallery-so/gallery/assets/4480258/72fac3fe-fb03-4e0c-82d7-292ba22cbba8
**After**
https://github.com/gallery-so/gallery/assets/4480258/4fa58bd0-dcf1-4ab8-9f35-7e5d5bd7ce02
1. Create a post 
2. Add some line break to it and mention any user or community
> Fix un-mentionable if there is line break

- apps/web/src/scenes/CommunityPage/CommunityPageViewHeader.tsx
> Fix community header tooltip copy

- apps/mobile/src/App.tsx
| <img width="422" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/f79d4f13-ad3c-4840-8854-58c6bbd5a062"> | <img width="422" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/ce839ad7-f402-4989-b8b1-b8a5b324236c"> |
> Fix maintenance dark mode

- packages/shared/src/utils/highlighter.test.ts
- packages/shared/src/utils/highlighter.ts
- Fixes borked highlighting
- Adds tests
| <img width="412" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/4f886cca-a72b-4f53-a7fb-fbbccf55e8cc"> | <img width="412" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/83c33d52-12dd-4c76-b02f-88f0450dcaca"> |
Ensure there aren't any regressions
| Keyword-based search results | @mentions |
| <img width="423" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/3c21d9ab-3546-4895-aa64-a713be26ddd3"> | <img width="427" alt="Screenshot 2023-11-05 at 3 48 46 PM" …
> [GAL-4676] Search highlighter fix

- packages/shared/src/utils/extractMirrorXyzUrl.ts
> dynamic asset height on feed fix

- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheet.tsx
Use `store-and-network` policy on comments tab to ensure stale comments are refreshed.
https://github.com/gallery-so/gallery/assets/12162433/b1539a2f-681e-473d-b759-3bd86f90fe8d
> Refresh stale comments

- apps/mobile/src/components/Search/Community/CommunitySearchResult.tsx
- apps/mobile/src/components/Search/SearchResult.tsx
- apps/mobile/src/components/Search/SearchResults.tsx
- apps/mobile/src/components/Search/User/UserSearchResult.tsx
- apps/web/src/components/Mention/MentionModal.tsx
- apps/web/src/components/Search/SearchResult.tsx
- apps/web/src/components/core/TextArea/TextArea.tsx
- Fix search keyboard regression
- Add keyboard navigation (up & down) to mention web
- Add tracking event to mention mobile
https://github.com/gallery-so/gallery/assets/4480258/7ccc8145-344c-453e-9515-bfa0c3ba30d2
https://github.com/gallery-so/gallery/assets/4480258/94315356-d67a-42dc-b975-7a8a8166f777
1. Mention anyone in post/comment and use arrow up or down to navigation mention
2. Press enter to select the specific mention
> Mention web polish + Tracking mobile

- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNote.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/PostCommentsModal.tsx
- apps/web/src/scenes/Post/StandalonePostView.tsx
> Mention fixes

- packages/shared/src/hooks/useMentionableMessage.ts
- Fix multiple similar mention
- Solution: Whenever we select the mention, we check if there is any duplicate in the store state
**Before**
https://github.com/gallery-so/gallery/assets/4480258/aad91c81-9aa8-45a0-8829-439f21af23eb
**After**
https://github.com/gallery-so/gallery/assets/4480258/993f9b8d-2649-4310-9556-1fda3026174d
> Check if the mention already exist

- apps/mobile/src/components/Feed/Posts/PostCreatorAndCollectionSection.tsx
- apps/mobile/src/components/Feed/Posts/PostListItem.tsx
- apps/mobile/src/components/ProfilePicture/ProfilePictureAndUserOrAddress.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx
- apps/web/src/components/Feed/Posts/PostCreatorAndCollectionSection.tsx
- apps/web/src/components/ProfilePicture/ProfilePictureAndUserOrAddress.tsx
- apps/web/src/scenes/NftDetailPage/NftDetailText.tsx
Adds creator label to posts on mobile and web
S - small length name
L - large size name
| After (S and S)                                     | After        (L and L)                   |
| <img width="1071" alt="Screenshot 2023-11-14 at 2 52 56 AM" src="https://github.com/gallery-so/gallery/assets/49758803/9f9caec9-d109-448c-bf68-b131176acc58"> | <img width="1105" alt="Screenshot 2023-11-14 at 3 06 39 AM" src="https://github.com/gallery-so/gallery/assets/49758803/c8e58a32-2cf1-4999-a106-3a2b11082a8b"> |
| After (S and L)                                     | After        (L and S)                   |
| <img …
> creator labels

- .moon/toolchain.yml
- apps/mobile/moon.yml
- apps/mobile/package.json
- apps/web/package.json
- package.json
- packages/shared/moon.yml
- yarn.lock
> Upgrade Moon

- apps/web/src/components/Feed/Socialize/CommentLine.tsx
Before
After
browser compatibility:
safari
another example with diff comment
short and long comments
> make comment wrap under username on web

- apps/mobile/src/components/Feed/Socialize/CommentBox.tsx
input text was slightly below vertical center
Before
After
na
open comment input and look at input
> vertically center input

- apps/mobile/src/components/Trending/TrendingUserList.tsx
- apps/web/src/components/Explore/ExploreList.tsx
Hide user cards without token previews. We're getting more of these because users are signing up simply to Post before they set up a gallery.
| <img width="1336" alt="Screenshot 2023-11-16 at 4 33 59 PM" src="https://github.com/gallery-so/gallery/assets/12162433/02b30694-fe34-4bb4-b327-ff47da379d01"> | <img width="1349" alt="Screenshot 2023-11-16 at 4 36 17 PM" src="https://github.com/gallery-so/gallery/assets/12162433/32981d3e-ee6e-4bd4-a652-2ecf44c42ec9"> | …
> Hide user cards without token previews

- apps/mobile/src/components/Feed/Posts/PostCreatorAndCollectionSection.tsx
on the mobile feed, make the labels ‘Creator’ / ‘Collection’ on a post also tappable
Uploading Screen Recording 2023-11-17 at 2.53.12 PM.MOV…
> make the labels ‘Creator’ / ‘Collection’ also tappable

- apps/web/src/components/Feed/Socialize/Comments.tsx
make comment preview on web clickable to open CommentsModal
https://github.com/gallery-so/gallery/assets/49758803/ffb587c2-f39e-45ca-8fc4-90245905eba7
> make comment preview on web clickable

- apps/web/src/components/NftSelector/NftSelector.tsx
| <img width="993" alt="Screenshot 2023-11-17 at 7 57 30 PM" src="https://github.com/gallery-so/gallery/assets/49758803/89cf56cd-5097-49e7-97f6-cbfd80c548b2"> | <img width="959" alt="Screenshot 2023-11-17 at 7 54 53 PM" src="https://github.com/gallery-so/gallery/assets/49758803/7d9bde0d-d217-47c7-b65b-30f031b20746"> |
Verified still works correctly when 'Created' filter is selected
Provide steps on how the reviewer can …
> show refresh icon only when 'Created' filter is selected

- apps/web/src/scenes/NftDetailPage/NftDetailText.tsx
on web nft detail page, display owner and creator new row if username is long
| <img width="551" src="https://github.com/gallery-so/gallery/assets/49758803/d4e182d2-90d2-4def-bf36-965d1793a35a" /> | <img width="551" alt="Screenshot 2023-11-17 at 6 44 35 PM" src="https://github.com/gallery-so/gallery/assets/49758803/3acaecbf-078f-4322-9731-4051f656bee8"> |
remove double user hovercard
| <img width="685" …
> display owner and creator new row if username is long

- apps/web/src/scenes/NftDetailPage/NftDetailView.tsx
| <img width="423" alt="Screenshot 2023-11-20 at 12 53 15 AM" src="https://github.com/gallery-so/gallery/assets/49758803/a97223c8-401c-4f85-a21b-a847edbafbd3"> | <img width="465" alt="Screenshot 2023-11-20 at 12 48 40 AM" src="https://github.com/gallery-so/gallery/assets/49758803/a9bbe288-7854-4655-9a9b-2e0282673b99"> |
Made sure to check it still works correctly for other dimensions
tested with own token to check that editor does not break styling either …
> [GAL-4652] fix collector's note display on moweb and tablet

- apps/web/src/components/Explore/ExplorePopoverList.tsx
| <img width="418" alt="Screenshot 2023-11-20 at 5 33 22 AM" src="https://github.com/gallery-so/gallery/assets/49758803/dfff40ff-98c5-4ef2-8957-693e03103984"> | <img width="444" alt="Screenshot 2023-11-20 at 5 31 04 AM" src="https://github.com/gallery-so/gallery/assets/49758803/65872124-5681-433d-8de3-b2c0ac24d366"> |
List any …
> [GAL-4460] Add PFPs for explore modal -> see all

- apps/mobile/app.config.ts
- apps/mobile/package.json
- apps/mobile/src/contexts/MobileAnalyticsProvider.tsx
- yarn.lock
> Revert tracking transparency

- apps/mobile/app.config.ts
- apps/mobile/version-bump.sh
> [mobile] bump version 1.0.32

- apps/mobile/src/components/AnimatedRefreshIcon.tsx
- apps/mobile/src/components/Toast/transition.ts
- apps/mobile/src/contexts/SyncTokensContext.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorContractScreen.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx
> creator autosync part 2

- apps/mobile/src/components/AnimatedRefreshIcon.tsx
- apps/mobile/src/components/Toast/transition.ts
- apps/mobile/src/contexts/SyncTokensContext.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorContractScreen.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx
- apps/web/src/components/GalleryEditor/PiecesSidebar/PiecesSidebar.tsx
- apps/web/src/components/NftSelector/NftSelector.tsx
- packages/shared/src/utils/doesUserOwnWalletFromChainFamily.ts
Trigger auto sync when switching Collected/Created tabs, in the following places
Web
- Composer
- Editor
Mobile
- Composer
Mobile does not currently sync created tokens for new contracts
https://github.com/gallery-so/gallery/assets/80802871/786c6bdc-3087-4be6-abef-739cc93edf8f
> trigger auto sync when switching ownership type filter in composer/editor, web and mobile

- apps/mobile/src/screens/NftSelectorScreen/NftSelectorContractScreen.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
https://github.com/gallery-so/gallery/assets/12162433/c5fa721e-880b-4a01-8f5b-2e432ebdf26e
> Pull to refresh mobile sync

- apps/mobile/src/components/Select.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorFilterBottomSheet.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx
- packages/shared/src/utils/chains.ts
- conditionally allow permutations to be selected when attempting to sync on mobile
- introduce `disabled` prop to Select component
| Network                                     | Created/Collected                                      |
| <img width="509" alt="Screenshot 2023-11-23 at 12 18 13 AM" src="https://github.com/gallery-so/gallery/assets/12162433/d8131f1b-186b-4a78-b5f9-4af5e186cf11"> | <img width="509" alt="Screenshot 2023-11-23 at 12 18 32 AM" src="https://github.com/gallery-so/gallery/assets/12162433/57bd2e09-ec7f-45e6-802e-fe8e6b0f99d5"> |
https://www.loom.com/share/5cb648438122409e99ea6c92311096ab?sid=39e6bf14-05a0-4595-b062-c18b9d003c6c
List any common edge cases that you have …
> Mobile conditional filtering

- .github/workflows/mobile-build.yml
- .moon/toolchain.yml
- apps/mobile/moon.yml
- apps/mobile/package.json
- apps/web/moon.yml
- apps/web/package.json
- package.json
- packages/shared/moon.yml
- yarn.lock
Upgrading moon. Doing this in a separate PR to figure out the root issues.
Edit: I tested a bunch of tasks except for local mobile dev, since I don't have ios/android stuff setup on my computer.
> Upgrade to moon v1.17

- apps/web/src/scenes/NftDetailPage/NftDetailText.tsx
> Fix duplicate NFT detail text

- apps/web/src/scenes/CommunityPage/CommunityPageViewHeader.tsx
| <img width="276" alt="Screenshot 2023-11-28 at 7 48 08 AM" src="https://github.com/gallery-so/gallery/assets/49758803/65ff22fa-253b-43e9-9fd6-f34fab34d30b">
| <img width="318" alt="Screenshot 2023-11-28 at 7 46 55 AM" src="https://github.com/gallery-so/gallery/assets/49758803/6ceae1df-21ad-4913-b838-aa2eacd3bf14"> |
List any …
> change community page shareIcon to copyIcon

- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetSection.tsx
- Fix optimistic update on replying top comment
https://github.com/gallery-so/gallery/assets/4480258/f1ba18eb-ec6d-42b5-8fdd-11571c713c68
1. Reply on any comment
> Fix optimistic update on replying top comment

- apps/mobile/src/components/Feed/Posts/PostBottomSheet.tsx
- apps/mobile/src/components/Feed/Posts/ReportPost.tsx
- apps/mobile/src/components/ProfileView/BlockUserConfirmationForm.tsx
- apps/mobile/src/components/ProfileView/GalleryProfileMoreOptionsBottomSheet.tsx
- apps/mobile/src/components/ProfileView/GalleryProfileNavBar.tsx
- apps/mobile/src/components/ProfileView/ProfileView.tsx
- packages/shared/src/hooks/useBlockUser.ts
- packages/shared/src/hooks/useReportPost.ts
- packages/shared/src/hooks/useUnblockUser.ts
- Introduce post reporting, user blocking
- Refactor top nav icons around profile
https://www.loom.com/share/e3a557a735c5418eb4f6edbadb40214b?sid=84864cf3-59b1-4e6d-abbc-757a7500c81c
- Ensure no regressions for own profile
> Report Content

- apps/mobile/src/components/Feed/Posts/PostBottomSheet.tsx
- apps/mobile/src/components/Feed/Posts/ReportPost.tsx
- apps/mobile/src/components/ProfileView/BlockUserConfirmationForm.tsx
- apps/mobile/src/components/ProfileView/GalleryProfileMoreOptionsBottomSheet.tsx
- apps/mobile/src/components/ProfileView/GalleryProfileNavBar.tsx
- apps/mobile/src/components/ProfileView/ProfileView.tsx
- packages/shared/src/hooks/useBlockUser.ts
- packages/shared/src/hooks/useReportPost.ts
- packages/shared/src/hooks/useUnblockUser.ts
> [cherry-pick] Report Content, Block User (#2137)

- apps/web/src/contexts/globalLayout/GlobalBanner/LocalStorageGlobalBanner.tsx
- apps/web/src/contexts/globalLayout/GlobalLayoutContext.tsx
LocalStorage-based survey banner. Ideally want this sanity-controlled in the future
> Survey banner

- apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx
replace `Markdown` component with the new `ProcessedText` component
| <img width="452" alt="Screenshot 2023-11-30 at 9 04 01 AM" src="https://github.com/gallery-so/gallery/assets/49758803/431fa719-7830-4968-acd6-52e10e055f6b" > | <img width="452" alt="Screenshot 2023-11-30 at 9 04 01 AM" src="https://github.com/gallery-so/gallery/assets/49758803/4bf46fd1-1eb4-4990-95a0-1df24d98a257"> |
tested markdown rendering still working as usual
Provide steps on …
> weird markdown rendering on nft detail mobile

- apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx
update color of admire button text for the "admired" state
| <img width="494" alt="Screenshot 2023-12-01 at 6 46 33 PM" src="https://github.com/gallery-so/gallery/assets/49758803/944eef7e-2f81-4cc8-b390-36685ba66811"> | <img width="454" alt="Screenshot 2023-12-01 at 6 46 49 PM" src="https://github.com/gallery-so/gallery/assets/49758803/ab8cc47f-65bd-4403-bae1-97ec32677152"> |
> minor admire nft polish

- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNote.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentRepliedBanner.tsx
> Replies web polish spacing

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.34

- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNoteSection.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentsModal.tsx
Address the comment from https://github.com/gallery-so/gallery/pull/2122#pullrequestreview-1760506699
> Improve replies web

- apps/web/src/contexts/globalLayout/GlobalLayoutContext.tsx
> Remove survey banner

- apps/web/src/contexts/snow/SnowContext.tsx
Some users don't want snow
https://twitter.com/rayesalexander/status/1731799746178592986
> Disable snow for certain users

- apps/mobile/app.config.ts
> version bump 1.0.35

- apps/mobile/app.config.ts
> Disable tablet support in app config

- apps/mobile/src/components/ProfileView/BlockUserConfirmationForm.tsx
Bringing this over from https://github.com/gallery-so/gallery/pull/2102
> Report copy tweak

- apps/mobile/src/components/Feed/Posts/PostListSectionHeader.tsx
- apps/web/src/components/Feed/Posts/PostHeader.tsx
Show active badge in the feed web and mobile
**Web**
**Mobile**
> Show active badge in feed

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.36

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.37

- apps/mobile/src/screens/PostScreen/SharePostBottomSheet.tsx
Types were broken due to prop change from parallel PR
> Fix new button typecheck

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.38

- apps/mobile/src/components/Feed/Posts/FeedPostSocializeSection.tsx
- apps/web/src/components/Feed/Socialize/Comments.tsx
- schema.graphql
Update total comments in web and mobile to display comments + replies
**Mobile**
https://github.com/gallery-so/gallery/assets/4480258/6b4580bd-fb6a-4730-869d-e11de542afbc
**Web**
https://github.com/gallery-so/gallery/assets/4480258/aaf1726f-3b75-4da8-a5a1-8453a0b3759a
1. Open any comment in the post that has replies.
2. The total comments shown should be sum of comments + replies
> Display total comments + replies

- apps/mobile/src/components/Notification/NotificationRegistrar.tsx
Include the opened push notification type 
NA
NA
hard to test locally/dev. low risk change
> Include the opened push notification type 

- apps/mobile/src/components/Feed/Posts/PostListSectionHeader.tsx
- apps/mobile/src/components/Notification/Notifications/YouReceivedTopActivityBadge.tsx
- apps/mobile/src/components/ProfileView/ProfileView.tsx
- apps/mobile/src/utils/isFeatureEnabled.tsx
- apps/web/src/components/Badge/Badge.tsx
- apps/web/src/components/Feed/Posts/PostHeader.tsx
- apps/web/src/components/Notifications/Notification.tsx
- apps/web/src/scenes/UserGalleryPage/UserNameAndDescriptionHeader.tsx
- apps/web/src/utils/graphql/isFeatureEnabled.tsx
> Enable Activity Badges, tweak copy

- apps/mobile/src/components/MintLinkButton.tsx
- apps/mobile/src/components/Post/SupportedMintLinkBottomSheet.tsx
- apps/mobile/src/icons/SuperRareIcon.tsx
- apps/web/src/components/MintLinkButton.tsx
- apps/web/src/components/Posts/PostComposerMintLinkInput.tsx
- apps/web/src/icons/SuperRareLogoIcon.tsx
- packages/shared/src/utils/getMintUrlWithReferrer.test.ts
- packages/shared/src/utils/getMintUrlWithReferrer.ts
Add SuperRare support to mint link 
**Mobile**
**Web**
> Add SuperRare support to mint link

- apps/mobile/src/components/Feed/Posts/PostListMintButtonSection.tsx
- apps/web/src/components/MintLinkButton.tsx
- Remove the mint link popup on web
- Fixed regression white space on mobile feed
**Remove the mint link popup on web**
https://github.com/gallery-so/gallery/assets/4480258/aa715450-a7b7-4a09-8576-fcc5a33fd5da
**Fixed space regression**
https://github.com/gallery-so/gallery/assets/4480258/86b45872-ef4b-469f-a003-f2646537f065
> Polish Mint link web & mobile

- apps/mobile/src/components/MintLinkButton.tsx
- apps/mobile/src/components/Post/SupportedMintLinkBottomSheet.tsx
- apps/mobile/src/icons/HighlightIcon.tsx
- apps/web/src/components/MintLinkButton.tsx
- apps/web/src/components/Posts/PostComposerMintLinkInput.tsx
- apps/web/src/icons/HighlightLogoIcon.tsx
- packages/shared/src/utils/getMintUrlWithReferrer.test.ts
- packages/shared/src/utils/getMintUrlWithReferrer.ts
- Add highlight.xyz support to web and mobile
- Update bottom sheet copy
**Mobile**
**Web**
> Add highlight + Update bottom sheet copy

- apps/web/src/components/Notifications/Notification.tsx
- apps/web/src/components/Notifications/notifications/GalleryAnnouncement.tsx
- schema.graphql
- Add `GalleryAnnouncementNotification` support
> Custom notification web

- apps/web/src/components/core/GalleryLink/VerifyNavigationPopover.tsx
| <img width="499" alt="Screenshot 2023-12-15 at 11 53 15 PM" src="https://github.com/gallery-so/gallery/assets/49758803/6628444e-330c-41ac-805e-f2851eb34af1"> | <img width="502" alt="Screenshot 2023-12-15 at 11 52 54 PM" src="https://github.com/gallery-so/gallery/assets/49758803/b4131057-b1a5-4577-9416-3277569411d7"> |
Please make sure to review and check all of the …
> [GAL-4888] leaving gallery warning improvement

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.39

- apps/mobile/src/screens/PostScreen/SharePostBottomSheet.tsx
> fix spelling typo

- packages/shared/src/relay/useFollowUser.ts
- packages/shared/src/relay/useUnfollowUser.ts
runs an optimistic update for the Follow Button state on web and mobile
https://github.com/gallery-so/gallery/assets/49758803/5aa9f569-7f9c-45da-bde4-de687721d5ab
https://github.com/gallery-so/gallery/assets/49758803/740b5810-2afd-4a1f-b36e-b7a72a8cc8c1
> [GAL-4005] optimistically update Follow Button state

- apps/web/src/components/NftPreview/NftPreview.tsx
Animated SVGs were being categorized as `ImageMedia`. This is fine, but should be able to be live-rendered (or put on high-def)
Allows for this to appear animated
> Option to "liverender" images

- apps/mobile/src/components/Community/CommunityMeta.tsx
- apps/mobile/src/components/MintLinkButton.tsx
- apps/mobile/src/screens/PostScreen/PostComposerScreen.tsx
- apps/web/src/components/MintLinkButton.tsx
- apps/web/src/components/Posts/PostComposer.tsx
- apps/web/src/scenes/CommunityPage/CommunityPageMetadata.tsx
- schema.graphql
Use mint url from `Token` instead of `Community`.
> Replace mint url token

- apps/web/src/components/Posts/PostComposer.tsx
fix composer header padding
before
after
na
look at composer on web
> fix composer header padding

- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNote.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNoteSection.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentsModal.tsx
- apps/web/src/components/Notifications/Notification.tsx
- apps/web/src/components/Notifications/notifications/SomeoneAdmiredYourComment.tsx
- apps/web/src/hooks/api/feedEvents/useCommentOnFeedEvent.ts
- apps/web/src/hooks/api/posts/useAdmireComment.ts
- apps/web/src/hooks/api/posts/useCommentOnPost.ts
- apps/web/src/icons/SocializeIcons.tsx
- Add admire to comment
- Add notification if someone admire your comment
https://github.com/gallery-so/gallery/assets/4480258/210648e8-37f9-44f3-988a-1de2f70cab93
**Notification**
https://github.com/gallery-so/gallery/assets/4480258/d8127a53-b8c7-4ed5-b4b6-c5b4f552c90e
1. Admire any comment
2. The comment owner should receive the nofication
> Web Admire comment

- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheet.tsx
- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetLine.tsx
- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetList.tsx
- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetSection.tsx
- apps/mobile/src/components/Feed/CommentsBottomSheet/constants.ts
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNoteSection.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentsModal.tsx
- Set reply to auto expand on web and mobile
- set limit to 10 replies
https://github.com/gallery-so/gallery/assets/4480258/ad67e3ff-d345-4cc4-a516-11de2d880df7
https://github.com/gallery-so/gallery/assets/4480258/2d25ee4a-e074-4b16-a992-0c35c2b7c05b
> Expand replies by default

- apps/web/src/scenes/CommunityPage/CommunityPageViewHeader.tsx
update globe icon on community page tooltip to reflect link as a link on explorer rather than official project url.
> update globe icon copy

- apps/web/src/components/Feed/Socialize/Comments.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNote.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/DeleteCommentConfirmation.tsx
- apps/web/src/hooks/api/feedEvents/useCommentOnFeedEvent.ts
- apps/web/src/hooks/api/posts/useCommentOnPost.ts
- apps/web/src/hooks/api/posts/useDeleteComment.ts
User able to delete own comment
https://github.com/gallery-so/gallery/assets/4480258/7045abbf-25c4-4239-9f6c-3a1a3c00aa4b
https://github.com/gallery-so/gallery/assets/4480258/72f107d1-d699-40c2-b28f-691727ee7752
1. Delete only reply
2. Delete all comment
3. Delete latest comment and see if the feed preview comment get updated
1. Delete any comment or reply in the feed
> Add delete comment for web

- apps/web/src/hooks/api/feedEvents/useAdmireFeedEvent.ts
- apps/web/src/hooks/api/feedEvents/useCommentOnFeedEvent.ts
- apps/web/src/hooks/api/posts/useAdmirePost.ts
- apps/web/src/hooks/api/posts/useAdmireToken.ts
- apps/web/src/hooks/api/posts/useCommentOnPost.ts
Optimistic updates were broken for anything involving tokens, including PFPs when admiring something
> fix optimistic update regression for token definitions

- packages/shared/src/relay/useFollowUser.ts
- packages/shared/src/relay/useUnfollowUser.ts
update the optimisticReponse of follow/unfollow mutations
https://github.com/gallery-so/gallery/assets/49758803/a0434033-63dd-4104-9252-69fb2ba2bf4c
https://github.com/gallery-so/gallery/assets/49758803/d47aa790-cd9f-48aa-a890-d091bfe5eaf2
> Follow Button Optimistic Update

- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetLine.tsx
- apps/mobile/src/components/Notification/Notifications/YouReceivedTopActivityBadge.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNote.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/UsernameLink.tsx
- Fix the alignment of admire and comment in the comment for **web** and **mobile**. Top aligned
- Fix can't admire non-owner comment (mobile)
- Fix alignment white space on top activity badge (mobile)
**Web alignment**
| ![CleanShot 2024-01-02 at 13 20 11@2x](https://github.com/gallery-so/gallery/assets/4480258/660d2fb8-ed20-4432-b4d7-6a36109f134e)| ![CleanShot 2024-01-02 at 13 09 51@2x](https://github.com/gallery-so/gallery/assets/4480258/2f651838-7263-46f7-b839-0b42af9b6593)|
**Mobile alignment**
| …
> [GAL-4989] Admire Comment Polish + Bug fix

- apps/web/src/contexts/globalLayout/GlobalLayoutContext.tsx
- apps/web/tests/graphql/mockGlobalLayoutQuery.ts
Remove creator global popover
no one should see this anymore, regardless of if they have seen it or not
You should no longer see this popover, even if you haven't seen it before.
> GAL-4900 remove creator global popover

- apps/web/src/contexts/AppProvider.tsx
- apps/web/src/contexts/globalLayout/GlobalNavbar/CollectionNavbar/CollectionNavbar.tsx
- apps/web/src/contexts/globalLayout/GlobalNavbar/CommunityNavbar/CommunityNavbar.tsx
- apps/web/src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavbar.tsx
- apps/web/src/contexts/globalLayout/GlobalNavbar/HomeNavbar/HomeNavbar.tsx
- apps/web/src/contexts/snow/SnowContext.tsx
- Remove snowfall 🥲
- I'm leaving in the `<SnowContext>` and making it easier to enable/disable in the future
- Alpha: You can secretly enable / disable via `Ctrl + S`
> Remove snow

- apps/web/src/hooks/useAuthModal.tsx
Fix width on auth modal buttons on mobile web
Before
AFter
Regression check on desktop:
NA
open sign in modal on mobile web
> GAL-5017 fix width on auth modal buttons

- apps/mobile/tsconfig.json
- apps/web/tsconfig.json
> Commit autoformatted tsconfig

- packages/shared/src/utils/getTezosExternalUrl.ts
fxhash updated their URL scheme
it works now!
> [GAL-4991] Fix incorrect links to fxhash

- apps/web/src/components/Posts/PostComposerModal.tsx
Make less janky
Before/After!
https://github.com/gallery-so/gallery/assets/12162433/50d8b49f-7230-44f4-a81c-37bbe0ecdc8c
> [GAL-5027] Fix suspense boundary for post composer

- apps/mobile/src/components/ButtonChip.tsx
- apps/mobile/src/components/FollowButton.tsx
- apps/mobile/src/components/Notification/NotificationSkeleton.tsx
- apps/mobile/src/components/Notification/Notifications/NewTokens.tsx
- apps/mobile/src/components/Notification/Notifications/NotificationTokenPreview.tsx
- apps/web/src/components/Notifications/Notification.tsx
- apps/web/src/components/Notifications/notifications/NewTokens.tsx
- consistent button sizing, text size, alignment
- fix multi-token mint image background, alignment
| <img width="483" alt="Screenshot 2024-01-05 at 1 12 40 AM" src="https://github.com/gallery-so/gallery/assets/12162433/7d352a98-39b1-4916-8c75-893b0c378cc7"> | <img width="527" alt="Screenshot 2024-01-05 at 1 11 51 AM" src="https://github.com/gallery-so/gallery/assets/12162433/18765540-16c6-4eec-8eb7-68e7f6e54334"> |
- fix multi-token mint image background, alignment
- fix bug where collector list drawer was appearing when tapping on multi-mint
- ensure single-token mint row notifications are clickable
| …
> [GAL-5028] Fix multiple tokens minted notification on web, mobile

- apps/web/src/components/GalleryEditor/PiecesSidebar/PiecesSidebar.tsx
- apps/web/src/components/UpsellBanner/UpsellBanner.tsx
- apps/web/src/hooks/useAddWalletModal.tsx
- remove creator application form
- update add wallet modal to not display the upsell text in most situations
| <img width="1505" alt="Screenshot 2024-01-05 at 2 47 25 PM" src="https://github.com/gallery-so/gallery/assets/12162433/f3c7399b-431b-4479-b95f-4535b43c319a"> | <img width="1510" alt="Screenshot 2024-01-05 at 2 47 12 PM" src="https://github.com/gallery-so/gallery/assets/12162433/61375020-eb2f-45b0-9810-befd964f5787"> | …
> [GAL-4992] Remove creator application form on editor

- apps/web/src/components/WalletSelector/multichain/MultichainWalletSelector.tsx
- apps/web/src/components/WalletSelector/multichain/WalletButton.tsx
- apps/web/src/components/WalletSelector/multichain/supportedAuthMethods.ts
Add Solana soon button.
design pending review. 
it should appear in the auth menu in all flows, always disabled.
go to the auth or connect wallet flow, you should see this button
> GAL-5012 add solana soon button

- apps/mobile/src/components/Notification/Notification.tsx
- apps/mobile/src/components/Notification/NotificationSkeleton.tsx
- apps/mobile/src/components/Notification/Notifications/SomeoneMentionedYourCommunity.tsx
- apps/web/src/components/Notifications/Notification.tsx
- apps/web/src/components/Notifications/notifications/SomeoneMentionedYourCommunity.tsx
Add support for `SomeoneMentionedYourCommunity`
Mobile
Web
> [GAL-5026] Someone mentioned your community notification support

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.40

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.41

- apps/web/src/components/core/TextArea/TextArea.tsx
Collection descriptions were broken due to a [recent change](https://github.com/gallery-so/gallery/pull/2228/files#diff-5819393a4a4ea9793ed9352b10fdb4bfbd8f3926c665e7e369d7087570e6bd2dR212-R215) that overrode default textarea `onChange` behavior
> Fix broken collection description updates on web

- apps/mobile/src/components/Feed/CommentsBottomSheet/CommentListFallback.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreenFallback.tsx
- Polish fallback list comment in bottom sheet
- Add fallback to nft selector for post (to remove blank white screen)
**List comment fallback**
| ![CleanShot 2024-01-08 at 14 14 15@2x](https://github.com/gallery-so/gallery/assets/4480258/69dc39ce-10ed-4bcf-b152-78875a1c6452) | ![CleanShot 2024-01-08 at 13 31 14@2x](https://github.com/gallery-so/gallery/assets/4480258/b69e1340-153c-403c-bd32-e7eae19fc0c9) |
**Nft selector fallback**
**Before**
https://github.com/gallery-so/gallery/assets/4480258/5ad7fb2f-33db-409f-9e83-3efdd490271a
**After**
https://github.com/gallery-so/gallery/assets/4480258/b3484f07-a112-41 …
> Polish fallback mobile

- apps/mobile/src/components/FollowButton.tsx
Fix follow button in the profile screen
| ![CleanShot 2024-01-08 at 13 07 29@2x](https://github.com/gallery-so/gallery/assets/4480258/cedf370d-78e5-462b-928e-1a5e03952dcb) | ![CleanShot 2024-01-08 at 13 06 54@2x](https://github.com/gallery-so/gallery/assets/4480258/c6911a3b-dffa-4b8e-a460-f673bccdf098) |
1. Profile screen - follow user
2. Profile screen - unfollow user
3. Notification screen - follow user
4. Notification screen - unfollow user
> Fix regression follow btn profile

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.42

- apps/mobile/src/components/Community/CommunityCollectors.tsx
- apps/mobile/src/components/Community/CommunityCollectorsList.tsx
- apps/mobile/src/components/Community/CommunityView.tsx
Make the header + tab in the community screen scrollable. 
https://github.com/gallery-so/gallery/assets/4480258/5eafe0df-2537-47a9-8e27-2d277b11de92
1. Test the collector tab to make sure its scrollable too
> Community header scrollable

- apps/web/src/contexts/snow/SnowContext.tsx
Unfortunately `useMultikeyDown` is buggy :')
> Remove secret snow toggle

- apps/mobile/src/components/MintLinkButton.tsx
- apps/web/src/components/MintLinkButton.tsx
> Track mint providers

- apps/mobile/src/components/Feed/Posts/PostListItem.tsx
| <img width="468" alt="Screenshot 2024-01-18 at 6 11 03 PM" src="https://github.com/gallery-so/gallery/assets/49758803/c4affbc4-bddb-4d8c-945c-6d2c1373d6a6"> | <img width="463" alt="Screenshot 2024-01-18 at 6 08 32 PM" src="https://github.com/gallery-so/gallery/assets/49758803/d99029ec-60f3-4f00-944a-9ef690878cfe"> |
Please make sure to review and check all of the …
> center VideoMedia in posts

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.43

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.44

- apps/mobile/src/screens/PostScreen/PostComposerScreen.tsx
- apps/web/src/components/Posts/PostComposer.tsx
Manual mint links weren't available for all chains. This PR enables the toggle for any chain, and allows the user to provide a link from a supported platform.
| <img width="662" alt="Screenshot 2024-01-23 at 6 20 13 PM" src="https://github.com/gallery-so/gallery/assets/12162433/d2f2680e-6173-4890-9767-9ee4a600fbe3"> | <img width="683" alt="Screenshot 2024-01-23 at 6 18 37 PM" src="https://github.com/gallery-so/gallery/assets/12162433/6abb328a-8cf4-4e9b-a9a5-f767519b8441"> |
| ------------------------------------------ …
> Always enable mint link toggle

- packages/shared/src/utils/getOpenseaExternalUrl.ts
polygon links were broken
| <img width="1883" alt="before" src="https://github.com/gallery-so/gallery/assets/12162433/f5197837-0807-4d20-9467-28f6b5e3c8c4"> | <img width="1884" alt="Screenshot 2024-01-23 at 9 31 52 PM" src="https://github.com/gallery-so/gallery/assets/12162433/6aac7aaa-f507-4db3-8364-9ccfecb3fee5"> |
> fix polygon OS links

- apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
Update behavior when clicking Home in the sidenav:
if signed out: navigate to / (landing page)
if signed in: navigate to /home (feed, no change)
signed out
signed in
Click Home buton
> if logged out home will navigate to landing page

- apps/web/src/components/Community/CommunityHolderList.tsx
- apps/web/src/components/CommunityHolderGrid/CommunityHolderGrid.tsx
- apps/web/src/components/CommunityHolderGrid/CommunityHolderGridItem.tsx
- apps/web/src/components/ProfilePicture/RawProfilePicture.tsx
- apps/web/src/components/TokenHolderList/TokenHolderList.tsx
- apps/web/src/scenes/CommunityPage/CommunityPageCollectorsTab.tsx
- apps/web/src/scenes/CommunityPage/CommunityPageTabs.tsx
- apps/web/src/scenes/CommunityPage/CommunityPageView.tsx
- apps/web/src/scenes/CommunityPage/LayoutToggleButton.tsx
- apps/web/src/scenes/NftDetailPage/LinkToFullPageNftDetailModal.tsx
- apps/web/src/scenes/UserGalleryPage/MobileLayoutToggle.tsx
- packages/shared/src/utils/communities.ts
- Add grid token view to the collection page
- Clean up the specific contract that we enabled grid view previously
**Desktop**
https://github.com/gallery-so/gallery/assets/4480258/7870fd94-b194-43f4-9e49-7c71b6dae448
**Mobile**
1. Tested with svg collection
2. Tested with the different aspect ration nft
> Community Grid View (Web)

- apps/mobile/src/components/Community/CommunityCollectors/CommunityCollectorsGridFallback.tsx
- apps/mobile/src/components/Community/CommunityCollectors/CommunityCollectorsGridItem.tsx
- apps/mobile/src/components/ProfilePicture/RawProfilePicture.tsx
1. Make the username clickable in grid collection mobile
2. Align center for raw pfp
3. Fix white space on small mobile device
**Username clickable**
https://github.com/gallery-so/gallery/assets/4480258/80eff024-563f-4b00-9e2c-f5183998b630
**Align center the raw pfp**
**Fix grid on small device**
| ![IMG_6246](https://github.com/gallery-so/gallery/assets/4480258/8cefad1a-e6bb-4640-9fbf-a0c5eff9176b) |![CleanShot 2024-01-26 at 11 40 51@2x](https://github.com/gallery-so/gallery/assets/4480258/b5f32c2c-4a67-45ce-b2f4-b57ed536622d)| 
> Polish new grid collection page

- apps/web/pages/[username]/[collectionId]/index.tsx
- apps/web/pages/opengraph/collection/[collectionId]/fcframe.tsx
- apps/web/pages/opengraph/user/[username]/fcframe.tsx
- apps/web/src/constants/opengraph.ts
- apps/web/src/utils/openGraphMetaTags.ts
Will explain everything better tomorrow
TL;DR video
https://github.com/gallery-so/gallery/assets/12162433/0adad803-fff7-458b-bd9b-04e2de73727e
> Farcaster frames support

- apps/web/pages/opengraph/user/[username]/fcframe.tsx
- Limit # of frames due to fallbacks being triggered too easily
- Also increase text size
> Limit number of frames, increase text size

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.45

- apps/web/src/contexts/globalLayout/GlobalSidebar/SidebarPfp.tsx
- apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
- apps/web/src/icons/HomeIcon.tsx
Move sidebar icons around
after
desktop, not logged in
mobile, not logged in
desktop, logged in
mobile, logged in
> reorder sidebar

- apps/web/src/scenes/GalleryPage/GalleriesPage.tsx
Don't want to use `localCompare` which uses collation
> ditch localCompare for gallery sorting

- apps/mobile/src/components/Community/CommunityMetadataFormBottomSheet.tsx
- apps/mobile/src/components/Notification/Notifications/SomeoneAdmiredYourToken.tsx
- apps/mobile/src/components/Toast/Toast.tsx
- apps/mobile/src/contexts/ToastContext.tsx
- apps/mobile/src/hooks/useToggleTokenAdmire.tsx
- apps/mobile/src/icons/BookmarkIcon.tsx
- apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx
- Rename admired to bookmark
- Add `position` support to `Toast` component
- Renamed Admired token notification to bookmkar
**Demo bookmark nft**
https://github.com/gallery-so/gallery/assets/4480258/68b1d362-8a41-487d-b52f-5373f015bde2
**Notification**
> Mobile Bookmark token

- apps/web/pages/[username]/galleries/[galleryId].tsx
we were only emitting for featured galleries
tested network request emission
> emit gallery view for non-featured galleries

- apps/web/src/components/Feed/FeedList.tsx
> delete console logs

- apps/mobile/src/components/Community/CommunityGalleries/CommunityGalleries.tsx
- apps/mobile/src/components/Community/CommunityGalleries/CommunityGalleriesItem.tsx
- apps/web/src/components/Community/CommunityGalleryList.tsx
- apps/web/src/components/Community/CommunityGalleryListItem.tsx
- apps/web/src/components/Explore/ExploreUserCard.tsx
- apps/web/src/contexts/globalLayout/GlobalFooter/GlobalFooter.tsx
- apps/web/src/scenes/CommunityPage/CommunityPageGalleriesTab.tsx
- apps/web/src/scenes/CommunityPage/CommunityPageTabs.tsx
- apps/web/src/scenes/CommunityPage/CommunityPageView.tsx
Added a gallery tab to the community page in **web**
Note:
- Will add the **Add to Gallery** cta in future PR when the backend is ready
**Web**
https://github.com/gallery-so/gallery/assets/4480258/ed726e61-06a9-42f5-8653-22fb7ad771d9
**Mobile**
> Add gallery tab to web

- apps/web/src/scenes/WelcomeAnimation/WelcomeAnimation.tsx
Fix incorrectly positioned images on onboarding animation page
before
after
na
go to onboarding 
> fix onboarding animation position

- apps/mobile/src/components/Notification/Notifications/SomeoneRepliedToYourComment.tsx
- apps/web/src/components/Feed/Socialize/CommentsModal/CommentNoteSection.tsx
- apps/web/src/components/Notifications/Notification.tsx
- apps/web/src/components/Notifications/notifications/SomeoneRepliedToYourComment.tsx
- add inline **admire** and **reply** to reply notification on **web** and **.mobile**
https://github.com/gallery-so/gallery/assets/4480258/28a5bb3c-6775-4690-8d50-eabdcc29174c
https://github.com/gallery-so/gallery/assets/4480258/d2cba914-1e73-4666-bd81-a6f2f28a3fca
> Add inline reply & admire to reply notification

- packages/shared/src/relay/useGetPreviewImages.ts
suppress could not render nft error from reporting
> suppress could not render nft error from reporting

- apps/web/src/utils/openGraphMetaTags.ts
check the old `twitter:image` content URL
check the new `twitter:image` content URL
> update twitter image meta to og server changes

- apps/web/src/components/Follow/FollowButton.tsx
Adding the new behavior when following for first time
before:
https://github.com/gallery-so/gallery/assets/51178245/fa48f4fe-8c60-4ba3-8177-5ea81d198c6f 
after:
https://github.com/gallery-so/gallery/assets/51178245/fd080db7-dbee-4211-91f9-6e629fcfef84
> Follow Button Hover UX on Web

- apps/web/src/components/Search/Community/CommunitySearchResult.tsx
- apps/web/src/components/Search/Gallery/GallerySearchResult.tsx
- apps/web/src/components/Search/Search.tsx
- apps/web/src/components/Search/SearchResult.tsx
- apps/web/src/components/Search/User/UserSearchResult.tsx
https://github.com/gallery-so/gallery/assets/49758803/b6731af0-0576-4059-9052-82e93748eec7
can search on web and use arrow keys and enter key to scroll through results and select.
> [GAL-5093] Enter key now allows you to select Search Result

- apps/mobile/src/components/Notification/Notifications/NewTokens.tsx
- apps/web/src/components/Notifications/Notification.tsx
tapping on the “you collected X” notification outside of the button leads to that token’s detail page
https://github.com/gallery-so/gallery/assets/49758803/858c3378-415b-4fe3-bd64-292cb441b0a1
https://github.com/gallery-so/gallery/assets/49758803/e3e423b0-8163-4931-be78-cda83e634743
> navigate to NftDetailPage from new tokens notification

- apps/mobile/package.json
- apps/web/package.json
- package.json
- yarn.lock
Been a few releases, so updating! 
Changelog: https://github.com/moonrepo/moon/releases/tag/v1.21.0
cc: @Robinnnnn 
CI
> Upgrade moon to v1.21

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.46

- packages/shared/src/utils/getRemainingCharacterCount.ts
Awaiting some more UX updates on web / mobile
> [do not merge] Bump max post char count 600 -> 1200

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.47

- apps/web/pages/community/[chain]/[contractAddress]/index.tsx
> add new community frame meta tag data

- apps/mobile/app.config.ts
Builds are broken as they're trying to read from an un-committed secrets file
> Fix secrets

- apps/mobile/src/components/Onboarding/OnboardingTextInput.tsx
- apps/mobile/src/contexts/SyncTokensContext.tsx
- apps/mobile/src/screens/Login/OnboardingEmailScreen.tsx
- apps/mobile/src/screens/Onboarding/OnboardingUsernameScreen.tsx
- Consolidate fetch tokens on ethereum, base and zora
- Left align caret for email input
https://github.com/gallery-so/gallery/assets/4480258/80ffab5f-8a8d-433d-8685-5d846d03597b
1. Tested during onboarding mobile flow
2. Tested during (auth) creating post
> sync token support multiple chain & polish

- apps/web/pages/community/[chain]/[contractAddress]/index.tsx
- apps/web/src/utils/openGraphMetaTags.ts
> add content field for initial button for frame

- apps/web/src/components/Email/useUpdateEmailNotificationSettings.ts
- apps/web/src/components/Settings/ManageEmailSection/ManageEmailSection.tsx
- schema.graphql
Fix breaking change situation with unsubscription status
**Next Steps:** actually display the unsubscription state for each email category in UI
> Update unsubscription schema access to latest

- packages/shared/src/utils/highlighter.ts
Prevent special characters in search input from crashing the site
> fix search regex

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.48

- apps/mobile/src/navigation/types.ts
- apps/mobile/src/screens/Login/NotificationUpsellScreen.tsx
- apps/mobile/src/screens/Login/navigateToNotificationUpsellOrHomeScreen.ts
Fix the tooltips doesnt show up if coming from `Notification Upsell` screen
https://github.com/gallery-so/gallery/assets/4480258/09f6c257-c14a-4d24-97f0-1f99e5075e55
> Fix new user flow from notification screen

- apps/mobile/src/components/DeepLinkRegistrar.tsx
Add deep link support for collection page.
Confirmed works for regular collection pages + artblocks/prohibition subcommunity pages.
https://github.com/gallery-so/gallery/assets/80802871/b55620d5-cbd5-4d5f-8d95-6ff25fc3fe02
- normal collection page
- artblocks
- prohibition
Test deep links to different collection pages
https://gallery.so/community/ethereum/0xfc0946b334b3ba133d239207a4d01da1b75cf51b
https://gallery.so/community/Tezos/KT1U6EHmNxJTkvaWJ4ThczG4FSDaHC21ssvi
https://gallery.so/community/artblocks/0x059edd72cd353df5106d2b9cc5ab83a52287ac3a/0
https://gallery.so/community/prohibition/0x47a91457a3a1f700097199fd63c039c4784384ab/182
existing deep link types like profiles and posts should continue to work
> GAL-5103 add deep link support for collection page

- apps/mobile/src/components/WelcomeNewUserOnboarding.tsx
- apps/mobile/src/icons/WalletIcon.tsx
- apps/mobile/src/screens/Onboarding/OnboardingPersonaScreen.tsx
- apps/mobile/src/screens/Onboarding/OnboardingRecommendedUsers.tsx
Fix onboarding flow on darkmode
- Wallet icon
- Friend finder screen support dark mode
- Persona screen
- Tooltips
https://github.com/gallery-so/gallery/assets/4480258/9435d087-c79e-47df-afc0-4f1151f80598
> Fix onboarding darkmode

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.49

- apps/web/src/components/MintLinkButton.tsx
- apps/web/src/hooks/oneOffs/useIsCuratedProfilePage.ts
hide for our VIPs
| <img width="1477" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/06eb6768-aeb8-4b2c-9051-72dc0dd0c820"> | <img width="1475" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/59784996-cf48-4903-bd22-27a08201611d"> |
> hide mint button for curated profile page

- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
- apps/mobile/src/screens/PostScreen/PostComposerScreen.tsx
Add Skeleton State fallback to NFT Composer on mobile app
Before
https://github.com/gallery-so/gallery/assets/80802871/c955ceb1-6e81-45ce-ac8e-354032e2e9ba
After
https://github.com/gallery-so/gallery/assets/80802871/55690f43-66af-4ff4-b973-89624f0031e2
na
popen post composer
> add skeleton state to composer

- apps/mobile/src/screens/Onboarding/OnboardingRecommendedUsers.tsx
- schema.graphql
Query `suggestedUsersFarcaster` during onboarding flow
> Add suggested farcaster graph in onboarding

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.50

- apps/mobile/src/components/Notification/Notification.tsx
- apps/mobile/src/components/Notification/NotificationSkeleton.tsx
- apps/mobile/src/components/Notification/Notifications/SomeoneYouFollowOnFarcasterJoined.tsx
- apps/mobile/src/components/Text.tsx
- apps/web/src/components/Notifications/Notification.tsx
- apps/web/src/components/Notifications/notifications/SomeoneYouFollowOnFarcasterJoined.tsx
- schema.graphql
Show notification when someone you follow on FC joins Gallery - web +  mobile
na
- test as a user who has this notification, and check the notifications panel
> Add notification when someone you follow on FC joins Gallery - web + mobile

- apps/mobile/src/components/Login/WalletProvider/WalletConnect/WalletConnectProvider.tsx
- apps/mobile/src/components/Login/WalletProvider/WalletConnect/useWallectConnect.ts
- apps/mobile/src/components/Login/WalletSelectorBottomSheet.tsx
- apps/mobile/src/contexts/ManageWalletContext.tsx
1. Refactor the `WalletConnect` context to make the context more independent instead of tied to `WalletConnect`. It allow us to add more Wallet Provider in future. (e.g: Coinbase Wallet)
2. Ensure everything was working perfect on edge cases
1. Connect wallet and close it
2. Connect wallet and didn't signed the transaction
3. Back and fourth on connect and …
> Refactor the manage wallet context

- apps/mobile/README.md
> update readme for dev instructions

- apps/web/src/components/Explore/Explore.tsx
- apps/web/src/components/Explore/GallerySelects.tsx
add GallerySelects to Explore page to feature the article with Elle
NA
go to /explore and confirm the article is highlighted at the top of the page
> add GallerySelects to Explore page

- apps/mobile/app.config.ts
- apps/web/public/.well-known/assetlinks.json
We created a new project on playstore
> update android package name

- apps/mobile/src/components/AnimatedRefreshIcon.tsx
- apps/mobile/src/contexts/SyncTokensContext.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorContractScreen.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx
- Fix the regression of token syncing
https://github.com/gallery-so/gallery/assets/4480258/24e0eb4e-24b8-4c69-936f-ed9c48f3644a
> Fix token regression

- apps/mobile/src/contexts/SyncTokensContext.tsx
Had to make sure to refresh the media cache!
| ![image](https://github.com/gallery-so/gallery/assets/12162433/c5ad274c-0d60-4107-b3cc-7033b03959be) | ![image](https://github.com/gallery-so/gallery/assets/12162433/308a90b5-b5b5-49d4-b9a4-fadbc70e426d) |
> Fix mobile sync tokens regression

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.51

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.52

- apps/web/src/components/Explore/GallerySelects.tsx
Send event when user clicks the article on the explore page
na
na
click article on explore page /explore
> add event for opening explore page article

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.53

- apps/mobile/README.md
- apps/mobile/app.config.ts
- apps/mobile/moon.yml
- apps/mobile/package.json
- apps/mobile/src/App.tsx
- apps/mobile/src/components/GalleryBottomSheet/GalleryBottomSheetModal.tsx
- apps/mobile/src/components/Notification/Notifications/SomeoneAdmiredYourComment.tsx
- apps/mobile/src/components/Notification/Notifications/SomeoneCommentedOnYourFeedEvent.tsx
- apps/mobile/src/components/Notification/Notifications/SomeoneCommentedOnYourPost.tsx
- apps/mobile/src/components/Notification/Notifications/SomeoneMentionedYou.tsx
- apps/mobile/src/components/Notification/Notifications/SomeoneRepliedToYourComment.tsx
- apps/mobile/src/components/Notification/Notifications/YouReceivedTopActivityBadge.tsx
- yarn.lock
Fixed several Android bugs. 
- Status bar should now display proper color
- Notifications now have ellipsis (its automatic in iOS without width but not Android)
- Added expo compiler library in order to change the android compiler sdk 
- Fixed major issue with modals not showing after maintenance rework
> fix android issues

- apps/mobile/src/components/LinkableAddress.tsx
| <img width="481" alt="Screenshot 2024-03-26 at 04 11 39" src="https://github.com/gallery-so/gallery/assets/49758803/86b821d1-c928-493f-9821-7f6c13b5da39"> |  <img width="464" alt="Screenshot 2024-03-26 at 04 09 55" src="https://github.com/gallery-so/gallery/assets/49758803/e41f8d37-ea3a-4265-8c6e-00035694f4c9"> |
Please make sure …
> truncate chain address on nft detail page mobile

- apps/web/pages/post/[postId].tsx
> update isFrameCompatible flag for post links

- apps/web/src/components/Onboarding/FullPageCenteredStep.tsx
- packages/shared/src/utils/regex.ts
- improve progress bar UI
- allow more email TLDs
> Web onboarding improvements

- apps/web/src/components/MintLinkButton.tsx
- apps/web/src/icons/TopActivityBadgeIcon.tsx
- apps/web/src/icons/ZoraLogoIcon.tsx
- apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedFollowers.tsx
can't get em all :(
icon unchanged:
> remove some errors logged in console in feed

- apps/mobile/src/hooks/useLogout.ts
Allow for signing out on local device
> Improve signout on local device

- apps/mobile/src/components/Login/SignInBottomSheet.tsx
> reorder signin

- apps/mobile/src/components/Notification/Notification.tsx
make exception for apr-2024-mchx-collab so that only updated clients see the announcement
Please make sure to review …
> make exception for apr-2024-mchx-collab so that only updated clients see the announcement

- apps/mobile/src/components/Mint/MintCampaign/MintCampaignPostTransaction.tsx
- apps/mobile/src/components/Mint/MintCampaign/MintCampaignPreTransaction.tsx
Rename project to Radiance in error message and make copy changes
> rename to radiance

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.54

- apps/mobile/src/components/Notification/Notifications/SomeoneYouFollowOnFarcasterJoined.tsx
import was missing for reportError in one usage
> add missing import

- apps/mobile/app.config.ts
- apps/mobile/src/App.tsx
> mobile version bump

- apps/mobile/src/components/MintLinkButton.tsx
- apps/web/src/components/MintLinkButton.tsx
- packages/shared/src/utils/getMintUrlWithReferrer.test.ts
- packages/shared/src/utils/getMintUrlWithReferrer.ts
> Remove mint.fun button from mobile

- apps/mobile/src/components/GalleryBottomSheet/GalleryBottomSheetModal.tsx
- apps/mobile/src/components/Notification/Notifications/SomeoneYouFollowOnFarcasterJoined.tsx
Fixed issue with coment modal in ios where typing on keyboard would move the input behind the keyboard
Now:
> fix modal closing when typing

- apps/mobile/src/screens/Login/Onboarding2FAScreen.tsx
- apps/mobile/src/screens/Onboarding/OnboardingUsernameScreen.tsx
- apps/web/src/components/Email/EmailForm.tsx
- apps/web/src/scenes/Onboarding/OnboardingAddUsernamePage.tsx
- packages/shared/src/hooks/useCreateUser.ts
- packages/shared/src/hooks/useUpdateEmail.ts
- schema.graphql
Supply authMechanism in updateEmail call after creating the user
> Supply authMechanism in email update during mobile user creation flow

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.56

- apps/mobile/src/components/Search/SearchDefault.tsx
- apps/mobile/src/components/Search/SearchDefaultFallback.tsx
- apps/mobile/src/components/Trending/TrendingUserCard.tsx
- apps/mobile/src/screens/SearchScreen.tsx
| <img width="461" alt="Screenshot 2024-04-08 at 20 50 13" src="https://github.com/gallery-so/gallery/assets/49758803/cf6a9637-a8c0-482a-8394-c278ab5a3930"> | <img width="457" alt="Screenshot 2024-04-09 at 03 34 53" src="https://github.com/gallery-so/gallery/assets/49758803/6bf88aed-0014-4975-ae23-97fd3e76f62e"> |
light mode …
> update Search Default state on mobile

- apps/web/src/contexts/globalLayout/GlobalSidebar/SidebarIcon.tsx
Fixed an issue where clicking the home button wasn't hiding the notification sidebar
https://github.com/gallery-so/gallery/assets/112896251/6ad4d091-34a8-4f63-aa52-7a1e3acb654a
> fix click not handling sidebar hide

- apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarChainDropdown.tsx
- apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorFilterNetwork.tsx
Enable any network to be selected from Created tokens for admins
> Allow admins to select any network for created tokens

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.58

- apps/web/src/components/Notifications/notifications/NewTokens.tsx
Bug fix
| ![Screenshot 2024-04-11 at 22 26 33](https://github.com/gallery-so/gallery/assets/49758803/a6ec3a98-9fad-488f-b8fa-419c7fe1d833) | ![Screenshot 2024-04-11 at 22 26 16](https://github.com/gallery-so/gallery/assets/49758803/f40bfe19-80b7-489a-8241-0800217acb66) |
> tall token in NewToken notif is squished

- apps/web/src/components/Feed/SuggestedProfileCard.tsx
- apps/web/src/components/Search/Search.tsx
- apps/web/src/contexts/globalLayout/GlobalSidebar/AnimatedSidebarDrawer.tsx
update design (mainly bg color) to match design
| <img width="484" alt="Screenshot 2024-04-11 at 22 38 52" src="https://github.com/gallery-so/gallery/assets/49758803/e96912a3-7a15-4016-b0fb-f4ae26a2b94e"> | <img width="490" alt="Screenshot 2024-04-11 at 22 40 29" src="https://github.com/gallery-so/gallery/assets/49758803/1c6c4150-bbf6-4237-bc82-ddbebb1c9acf"> |
> followup to Search Default state on web

- apps/mobile/src/App.tsx
- apps/mobile/src/components/Login/AuthProvider/Farcaster/FarcasterAuthProvider.tsx
- apps/mobile/src/components/Login/SignInBottomSheet.tsx
The farcaster auth provider had to be wrapped further down given the new BottomSheetModal setup
> Fix mobile login with farcaster

- apps/mobile/app.config.ts
> bump version to 1.0.59

- apps/mobile/src/screens/Onboarding/OnboardingUsernameScreen.tsx
Username screen should start at 30% instead of 20% given additional previous steps
> Improve mobile onboarding progress bar

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.60

- apps/mobile/src/components/GalleryEditor/GalleryEditorHeader.tsx
- apps/mobile/src/components/GalleryEditor/GalleryEditorRenderer.tsx
- apps/mobile/src/components/GalleryEditor/GalleryEditorSection.tsx
- apps/mobile/src/components/GalleryEditor/SortableRowList.tsx
- apps/mobile/src/screens/GalleryScreen/GalleryEditorScreen.tsx
Polish gallery editor
- Added bottom padding to provide space for **actions button**
- Fix section title and description spacing
- Make the editor navigation floating at the top
- Able to update gallery name and description
**Added bottom padding to provide space for actions button**
| ![image](https://github.com/gallery-so/gallery/assets/4480258/9fcc0f47-c81d-4be8-9d40-f2e7a931853b)| ![CleanShot 2024-04-26 at 16 56 15@2x](https://github.com/gallery-so/gallery/assets/4480258/5ab16520-4e70-4f71-911c-9c5294e450c9)|
**Fix section title and description spacing**
**Editor navigation floating at the top**
**Update …
> Gallery editor polish

- packages/shared/src/utils/chains.ts
> enable base creator support

- apps/web/pages/onboarding/recommend-users.tsx
- apps/web/src/scenes/Onboarding/OnboardingRecommendUsersFallback.tsx
> added fallback to onboarding recommend users on web 

- apps/mobile/package.json
- yarn.lock
Bumping expo version to `50.0.17` since its supposed to fix issues with apple new privacy guidelines
Solution and more in depth infromation in here
https://github.com/expo/expo/issues/27796
> bump expo version

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.61

- apps/mobile/src/components/GalleryTouchableOpacity.tsx
- apps/mobile/src/components/ProfilePicture/ProfilePicture.tsx
https://github.com/gallery-so/gallery/assets/49758803/49788372-632f-4e7f-8678-74286371e6b8
https://github.com/gallery-so/gallery/assets/49758803/75bd37c1-c352-4cf8-82f1-ae8b8000f68c
> followup: remove opacity dip for trending user card mobile

- apps/mobile/src/components/AnimatedRefreshIcon.tsx
- apps/mobile/src/components/Button.tsx
- apps/mobile/src/components/IconContainer.tsx
- apps/mobile/src/components/NftSelector/NftSelectorContract/NftSelectorContractHeader.tsx
- apps/mobile/src/components/NftSelector/NftSelectorContract/NftSelectorContractPickerGrid.tsx
- apps/mobile/src/components/NftSelector/NftSelectorContract/NftSelectorContractToolbar.tsx
- apps/mobile/src/components/NftSelector/NftSelectorHeader.tsx
- apps/mobile/src/components/NftSelector/NftSelectorSelectionIndicator.tsx
- apps/mobile/src/components/NftSelector/NftSelectorToolbar.tsx
- apps/mobile/src/icons/CheckIcon.tsx
- apps/mobile/src/icons/CheckboxIcon.tsx
- apps/mobile/src/icons/MultiSelectIcon.tsx
- apps/mobile/src/navigation/RootStackNavigator.tsx
- apps/mobile/src/navigation/types.ts
- apps/mobile/src/screens/GalleryScreen/GalleryEditorNftSelector.tsx
- apps/mobile/src/screens/GalleryScreen/GalleryEditorNftSelectorContractScreen.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
- apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerSingularAsset.tsx
- Add an ability to add multiple token into gallery editor
https://github.com/gallery-so/gallery/assets/4480258/ce7ff2ed-5808-423c-9a60-fe89dc3b39b4
1. Add single token and group token at the same times
> Add multiple token into gallery editor

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.62

- apps/web/src/scenes/UserGalleryPage/UserGalleryCollections.tsx
- Temporary fix: Changed length of the sliced tokens so that the first token's pending state is the one showing the skeleton
> fix profile skeleton

- apps/web/src/scenes/UserGalleryPage/UserGalleryCollections.tsx
> fix add useMemo to tokenids

- apps/mobile/src/components/Login/SignInBottomSheet.tsx
- apps/mobile/src/components/Login/WalletSelectorBottomSheet.tsx
Fix bottom sheet regression in the connect wallet flow
https://github.com/gallery-so/gallery/assets/4480258/052d402b-ac28-40a5-b041-d1efe166b00c
> Fix bottom sheet regression on Connect wallet flow

- apps/mobile/app.config.ts
> [mobile] bump version 1.0.63

- apps/web/src/components/Notifications/AnnouncementNotification.tsx
- apps/web/src/components/Notifications/NotificationList.tsx
- apps/web/src/contexts/SanityAnnouncementProvider.tsx
- apps/web/src/contexts/globalLayout/GlobalSidebar/GlobalSidebar.tsx
- apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
- apps/web/src/scenes/ContentPages/MobileAppLandingPage.tsx
Add Sanity powered announcement notification to web
https://github.com/gallery-so/gallery/assets/80802871/f46e2991-3d8c-45b8-abfa-36331c5433be
> add announcement notification via sanity to web

- packages/shared/src/utils/wallet.ts
updated zora explorer url to zora.co
After clicking on the creator address button on NftDetailPage
| <img width="457" alt="Screenshot 2024-05-07 at 17 10 26" src="https://github.com/gallery-so/gallery/assets/49758803/90d27858-5c08-4fec-8811-91bac9da5b8d"> | <img width="483" alt="Screenshot 2024-05-07 at 17 06 02" src="https://github.com/gallery-so/gallery/assets/49758803/24f17fe0-287c-4631-a284-1d0448390875"> |
> updated zora creator address links to redirect to zora page

- apps/mobile/src/screens/Login/Onboarding2FAInput.tsx
- apps/mobile/src/screens/Login/Onboarding2FAScreen.tsx
- Changed the single input in  onboarding 2fa to be a series of boxes
https://github.com/gallery-so/gallery/assets/112896251/8f3cee78-c2fb-4d61-8fa9-4c5926d92ea0
> 2fa code boxes input
