gallery-so/gallery

src/components/WalletSelector/WalletSelector.tsx

This PR modifies WalletSelector to
- catch errors during `signMessageAndAuthenticate`
- set an errorCode that we define, like `REJECTED_SIGNATURE`
- display an error message associated with the errorCode to the user 
- allow the user to retry connecting a wallet

Handle case where user doesnt sign message, allow retry

---

src/components/Password/Password.tsx
src/components/WalletSelector/WalletButton.tsx
src/components/WalletSelector/WalletSelector.tsx
src/scenes/CollectionCreationFlow/CollectionCreationFlow.tsx
src/scenes/Home/Home.tsx
src/scenes/Routes.tsx
src/scenes/Welcome/Welcome.tsx

The wallet step appears after the user enters the password. After they connect their wallet, they are authenticated and are redirected to the Welcome screen.
additional changes:
- add placeholder welcome page shown before /create
- redirect non logged in users from /create to /

Add Wallet Step to landing page

---

.env
package.json
src/setupProxy.js

deprecate `$ yarn start:mock` in favor of:
```
$ yarn start      => develop against local mock server
$ yarn start:dev  => develop against AWS dev (coming soon)
$ yarn start:prod => develop against AWS prod (coming soon)
```

Fix broken proxy

---

src/components/Profile/UserInfoForm.tsx

Fixes "Pressing enter quickly proceeds through all of the next steps" #258
Add isSubmitting state to UserInfoForm to prevent rapid-hitting Enter from submitting multiple times

use isSubmitting state to prevent redundant submits

---

.env
package.json
src/components/WalletSelector/WalletSelector.tsx
src/components/WalletSelector/authRequestUtils.ts
src/contexts/swr/SwrContext.tsx
src/contexts/swr/fetcher.ts
src/setupProxy.js
src/types/ApiResponse.ts

- improved authentication pipeline
- fetch nonce => sign message => login user OR signup user
- generic `fetcher` function to make network requests imperatively (outside of hooks)
- updated .env to connect to AWS dev services
- support for "hack" environment (ngrok proxied on ivan's machine)
- improved gallery-specific ApiResponse type, error handling
**Known Issues**
- after signing up, app makes a request to `/users?id=${userId}`, but this endpoint does not yet support `userId` query param (as well as `username`)
- preflight endpoint is returning `user_exists: false` even after user has been created. this prompts the app to sign up user, instead of login
- auth endpoints aren't mocked in local proxy, so merging this PR will break development on local + dev

e2e auth and error handling improvements

---

src/components/WalletSelector/authRequestUtils.ts

Looks like the server expects the param name to be `address` instead of `addr` now

update preflight request param name

---

src/contexts/swr/fetcher.ts
src/types/ApiResponse.ts

Since we changed our http responses to use error codes (4xx, 5xx) rather than embed the error message inside a successful response, our Fetcher should be able to detect these cases and throw an error when appropriate.

Handle error http codes in fetcher

---

src/flows/OnboardingFlow/OnboardingFlow.tsx
src/flows/shared/steps/OrganizeCollection/CollectionNamingForm.tsx
src/flows/shared/steps/OrganizeCollection/OrganizeCollection.tsx
src/flows/shared/steps/OrganizeCollection/OrganizeCollectionWrapper.tsx
src/flows/shared/steps/OrganizeGallery/CollectionRowSettings.tsx
src/types/Collection.ts

- Wrapped OrganizeCollection step with new component, `OrganizeCollectionWrapper` to provide access to collection context during wizard onNext()
- Added Create Collection response type (for create collection endpoint)
- Add API call to Create 1st Collection (called when user clicks "Create Collection", before modal appears)
- Add API call to save collection name (called when user clicks "Save" in modal)

Add API calls for creating first collection and saving collection name

---

src/flows/shared/steps/OrganizeCollection/CollectionEditInfoForm.tsx
src/flows/shared/steps/OrganizeCollection/OrganizeCollection.tsx
src/flows/shared/steps/OrganizeCollection/OrganizeCollectionWrapper.tsx
src/flows/shared/steps/OrganizeGallery/CollectionRowSettings.tsx
src/flows/shared/steps/OrganizeGallery/OrganizeGallery.tsx
src/hooks/api/useGalleries.ts
src/types/Gallery.ts

Collection info form changes:
- Changed the endpoint that's used to save collection info to `/update/info`
- The collection info form now saves the collection name and collectors note (description)
- Renamed `CollectionNamingForm` to `CollectionEditInfoForm` to align with associated endpoint
OrganizeGallery changes (this allows the OrganizeGallery step to load properly)
- Added a `useGalleries` hook to retrieve a user's galleries from `/galleries/user_get`
- Added a `Gallery` type
- updated OrganizeGallery to use the `useGalleries` hook instead of `useCollections`

Use /update/info to update collection info + and add useGalleries hook

---

src/components/GlobalNavbar/LoggedInNav.tsx
src/components/WalletSelector/authRequestUtils.ts
src/flows/OnboardingFlow/steps/AddUserInfo.tsx
src/flows/shared/steps/OrganizeGallery/CollectionRowSettings.tsx
src/flows/shared/steps/OrganizeGallery/OrganizeGallery.tsx
src/hooks/api/collections/types.ts
src/hooks/api/collections/useUpdateCollectionHidden.ts
src/hooks/api/galleries/useAuthenticatedGallery.ts
src/hooks/api/nfts/useUnassignedNfts.ts
src/hooks/api/users/useUpdateUser.ts
src/hooks/api/users/useUser.ts
src/scenes/Auth/Auth.tsx
src/scenes/Nuke/Nuke.tsx
src/scenes/UserGalleryPage/EditUserInfoModal.tsx
src/scenes/UserGalleryPage/UserGalleryPage.tsx

1. remove `as User` when calling `useAuthenticatedUser` by definitively returning a user
2. in areas where an authenticated user may not be present, we call `usePossiblyAuthenticatedUser`

Migrate useAuthenticatedUser

---

src/scenes/UserGalleryPage/UserGalleryCollections.tsx

Currently if you're authenticated and you load your own Gallery page, it shows your hidden collections as well. 
This happens because the hidden collections are included in the GET gallery request because you are authenticated, which in itself is fine.
This PR ensures we don't render the hidden collections.

Hide your hidden collections when on your own page as an authenticated user

---

src/flows/shared/steps/OrganizeGallery/CollectionRow.tsx
src/scenes/UserGalleryPage/UserGalleryCollection.tsx

This PR updates the dnd collection view to truncate the collection_note if it's more than 100 characters
I also increased the width of the collectors_note in the main gallery view from 50% to 70% - I think it looks better that way

Truncate collectors_note with ellpises in dnd view

---

src/components/WalletSelector/WalletSelector.tsx
src/components/WalletSelector/authRequestUtils.ts

Disable new user sign up for now, and show an appropriate error message if someone tries to connect a wallet that is not associated with an existing Gallery user.

Disable new user sign up

---

src/contexts/boundary/ErrorBoundary.tsx
src/contexts/swr/useFetcher.ts
src/errors/types.ts
src/scenes/NotFound/NotFound.tsx
src/scenes/Routes.tsx
src/scenes/UserGalleryPage/UserGallery.tsx
src/scenes/UserGalleryPage/UserGalleryPage.tsx
src/scenes/UserGalleryPage/UserGalleryPageErrorBoundary.tsx

Changes:
- Added new Error Boundary for Gallery Page to specifically handle 404 case
- Updated ApiError class to include response code
- 404 view is now rendered without redirecting to /404 route
- Updated 404 view message

Add new Error Boundary for Gallery Page and handle 404 correctly

---

.xo-config.json
src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarNftIcon.tsx

Changes:
- add effect to Sidebar Icon where once the NFT is selected, we auto scroll to that NFT DnD element

When adding an NFT to collection dnd that is off screen, auto scroll to it

---

src/components/WalletSelector/WalletSelector.tsx

Changes:
- The error message was displayed as expected locally but not on deployed environments.
- Refactor WalletSelector's displayed error to differentiate web3 provider error types properly
- Use error type instead of error.name to differentiate errors.

Make Polygon/Unsupported chain error display correctly 

---

src/components/core/Button/Button.tsx
src/contexts/modal/AnimatedModal.tsx
src/flows/shared/steps/OrganizeGallery/DeleteCollectionConfirmation.tsx

Changes:
- increased AnimatedModal's background's opacity (see less of background content)
- tweak "X" close modal button alignment
- adjust Modal border color
- shorten Delete Collection confirmation copy
before
after

tweaks to AnimatedModal and Delete confirm

---

src/components/ImageWithLoading/ImageWithLoading.tsx

Changes
- use loading="lazy" to lazy load images on the Gallery profile page
- only works on Chromium based browsers, but it's an improvement

use browser native lazy load sto improve page bandwidth

---

src/components/NftPreview/NftPreviewAsset.tsx

Changes:
- add preload="metadata" property to video tag to prevent loading the whole video on the profile page
- set src to start from t=0.5, this ensures the thumbnail used is a valid frame from the video
before: 
nothing visible
after

Get NftPreview for video thumbnail to render properly on mobile

---

src/components/ManageWallets/ManageWalletsRow.tsx
src/contexts/modal/AnimatedModal.tsx
src/flows/shared/steps/OrganizeGallery/OrganizeGallery.tsx
src/scenes/Auth/Auth.tsx
src/scenes/Modals/ManageWalletsModal.tsx
src/scenes/UserGalleryPage/EditUserInfoModal.tsx

Changes:
- Make AnimatedModal itself mobile responsive (on mobile, width is always 90vw)
- Make content ManageWalletsRow fit on narrow mobile screens
- Make /auth page responsive (non-custodial text was overflowing on mobile)
- Show toast on Edit Gallery view on mobile, warning users page isn't optimized for mobile yet
screenshots

Some improvements for mobile

---

build.sh
package.json

Alright so basically, I followed this https://www.storyblok.com/tp/different-build-commands-branch-name-vercel . So NextJS provides us an environment variable telling us what the branch is, we just use that to determine which build command to use. 
If you look at the image below, pretty much the only thing we need to change the build command since all of the other configs are the same across `create-react-app` and `nextjs` other than the development command but I'm pretty sure we don't use that so....
**After this merges, I should be able to push up the nextjs branch and things should deploy just fine.**. I think a good way to test this would be to create another project in vercel on the same repo but change the branch to `nextjs` so we have one last confirmation that things are working …

Build NextJS when on nextjs branch

---

src/components/ImageWithLoading/ImageWithLoading.tsx

from 100vh to 80vh, that way it doesn't appear to go over the navbar/footer

reduce max height image size

---

src/components/core/Page/GlobalFooter.tsx
src/constants/urls.ts

- renamed `GALLERY_MIRROR` constant to `GALLERY_BLOG`
- updated URL to new gallery.mirror.xyz publication
- changed footer to say `Blog` instead of `Mirror` (generalize in case we move off Mirror in future)

update mirror link to new publication

---

pages/_app.tsx
pages/_document.tsx
src/scenes/NftDetailPage/NftDetailPage.tsx
src/scenes/UserGalleryPage/UserGalleryPage.tsx
src/scenes/_Router/Router.tsx

Make the Page title dynamic, so that we include the username on the Gallery Page, and username+artwork name on the Detail Page.
example:

Make user + nft page titles dynamic

---

src/scenes/UserGalleryPage/UserGalleryPageErrorBoundary.tsx

We ran into a regression where 404 pages are now showing this:
New:

Fix broken 404s

---

src/components/core/GalleryLink/GalleryLink.tsx
src/components/core/Markdown/Markdown.tsx

rather than crashing, we now handle broken URLs.
the screenshot uses the following bio:
```
aaa
[]()
bbb
ccc
```

Improve gallerylink markdown resiliency

---

src/scenes/NftDetailPage/NftAdditionalDetails.tsx

Looks like this ([example](https://gallery-n3d8zs5s1-gallery-so.vercel.app/connorr/23d4gAV1jK7EorGmfphDTTD7tuK/23sellWLGTpApQwMi7Vslgj3mqR)):

Show 'More Info' button on assets that have external_url

---

src/contexts/swr/useFetcher.ts
src/scenes/NftDetailPage/NftDetailAnimation.tsx
src/scenes/NftDetailPage/NftDetailAsset.tsx

The issue here was `StyledNftDetailAnimation` containing iframes. Tall assets that are not iframes don't seem to have the same overlap issue ([example image](https://gallery.so/mikey/22euUUNhWUZuJoHkqU402V6p9Bj/22euRj0cL6PxPKjcu1pqihhHwRs), [example GIF](https://gallery.so/mikey/1zVE7ilCacNz0IL35AhlKbW0956/1zVDDGiS1plOeZtxC5rFzuT6Jc2)). 
In cases where the embedded asset was recorded as having an aspect ratio other than 'wide', we passed an `aspectRatio: 1` to the parent container (derived from [this code](https://github.com/gallery-so/gallery/blob/main/src/scenes/NftDetailPage/NftDetailAsset.tsx#L77)). 
This is problematic on small screens because the iframe height will always be `500px`; this is because `StyledIframe` has a `min-height` rule of 500px and a `height` rule of 100%. But …

Show tall assets on small screens/mobile devices

---

src/scenes/Auth/Auth.tsx
src/scenes/WelcomeAnimation/Image.tsx
src/scenes/WelcomeAnimation/Images.tsx
src/scenes/WelcomeAnimation/WelcomeAnimation.tsx
src/scenes/WelcomeAnimation/intro.css

Images are preloaded on `/auth` now. For users who auth but do not yet have an account (and are sent to welcome page), this means that images are already loaded and jankiness is prevented. 
The videos below shows onboarding flows for users with "Good 3G" connection before and after preloading:
https://user-images.githubusercontent.com/13339581/149637045-479610c3-24e5-4bcf-aa22-c96221a05e3e.mov
https://user-images.githubusercontent.com/13339581/149637062-302e16d8-9461-4edb-b8e6-3cdbdea3cf6e.mov
The loading of each screen is slow regardless (~11 sec), but when preloading the images are fully loaded as soon as `/welcome` loads, and they do not blink/flicker in
**Note**: This does mean that we're loading images for any user who visits `/auth`, but I don't think this is an issue; the sum of …

Welcome page optimization & tweaks

---

src/scenes/NftDetailPage/NftAdditionalDetails.tsx

This amends a previous change https://github.com/gallery-so/gallery/pull/531 where we converted all token IDs with alphabet from hexadecimal -> decimal.
This change removes the alphabetical check and converts **all token IDs** to decimal. Any token IDs that seem to be correct are actually artifacts of old data; once we update Opensea data for that asset/user, they will be properly converted to hexadecimal (and then back to decimal on the frontend).
This means that any bugs related to improper token IDs are not related to our code, but rather should be fixed through manually updating Opensea data for that user.

Convert hexadecimals for all token IDs

---

src/components/WalletSelector/AddWalletPending/AddWalletPendingDefault.tsx
src/components/WalletSelector/AddWalletPending/AddWalletPendingGnosisSafe.tsx
src/components/WalletSelector/AuthenticateWalletPending/AuthenticateWalletPendingDefault.tsx
src/components/WalletSelector/AuthenticateWalletPending/AuthenticateWalletPendingGnosisSafe.tsx
src/types/Error.ts
src/utils/mixpanel.ts

We currently only track one event during the whole auth flow - when it's successful. 
This alone isn't very useful for us to measure how the flow is performing.
This PR introduces more detailed events:
`trackSignInAttempt`
`trackSignInSuccess`
`trackSignInError`
and equivalent for `AddWallet`
these get recorded for Logging In and Multi Wallet for both EOA and Contract Accounts. 
no PII such as address is recorded.

Add more detailed events for authentication flow to discern attempt, success, and error cases

---

pages/members.tsx

Sounds like we had consensus that the SSR version of the members page felt slow. We can profile this stuff later to see what we can do to make it faster, but for now let's just turn it off.

Disable SSR on members page

---

src/components/core/Dropdown/Dropdown.tsx

The mobile toggle was appearing over the dropdown. This PR fixes it by setting a z-index on the dropdown.
before:
after:

set z-index on dropdown

---

src/scenes/UserGalleryPage/UserGalleryCollection.tsx

Noticed the collection title is underlined on the main gallery page even if the feature flag is off. Quick fix to not underline the collection title on hover if the SiNGLE COLLECTION flag is off

Disable collection title underline if feature is off

---

src/components/NftGallery/NftGallery.tsx
src/components/NftPreview/NftPreview.tsx
src/constants/layout.ts

This is a refactor PR to change our Gallery layout to use display: grid instead of display: flex.
This allows column widths to be automatically calculated while preserving the desired behavior of evenly spacing the nfts on rows that are complete(using space-between) while left-aligning rows that are incomplete.
Being able to use space-between to automatically space nfts apart means we don't have to use margin, which means we don't have to then use negative margin to re-align the row with the parent container.
This also fixes an issue where the right side of the collection wasn't flush with the parent container.
before:
after:
Confirmed the following:
- works on Brave (chrome) , Safari, Firefox
- works for 1-6 column collections (1 column layouts are displayed at 50% width)
- works on …

refactor gallery to use display:grid instead of flex

---

src/contexts/swr/SwrContext.tsx
src/contexts/swr/middleware/ensureLatestGallery.ts
src/contexts/swr/middleware/handleObscenelyLargeAssets.ts
src/flows/shared/steps/OrganizeCollection/Editor/CollectionEditor.tsx
src/hooks/api/collections/useCollectionById.ts
src/hooks/api/nfts/useAllNfts.ts
src/hooks/api/users/useMemberList.ts

Dmitri Cherniak's Dead Ringers NFT, while very beautiful, would borderline crash the gallery experience given its massive dimensions.
Opensea should normally resize the image and provide it under `image_url`, but @kaitoo1's suspicion is that _Opensea itself_ is failing to resize the image due to its gargantuan nature. Indeed, uploading the image to various image resizing services online wouldn't work, and we had to resort to manually resizing on figma.
This is a PR I'm certainly not proud of, but will temporarily stop the bleeding to get our app to load.

Handle obscenely large images

---

src/components/EnsOrAddress.tsx
src/scenes/NftDetailPage/NftDetailText.tsx

This quickly translates an address to an ENS name (where available) using [a highly cached API I built](https://ensideas.com/about).
The results look like this:
This could be optionally coupled with some lightweight frontend caching that stores the last ~day of queries in localStorage, but not strictly necessary - Cloudflare edge cache is very fast (~50ms for me).
I only swapped out the address for one page/component, but happy to do more if you like this approach!

Add EnsOrAddress component

---

src/components/EnsOrAddress.tsx

Meant to do this in #561. This ensures a consistent cache key in SWR and avoids a redirect/round trip at the API.
Also went ahead and did the more defensive check for `data.address` in case the request fails or returns bad JSON for any reason.

lowercase address before querying ENS name

---

src/components/core/Markdown/Markdown.tsx

Changes:
This PR updates the markdown component to specify which elements we allow via markdown. 
For now we will allow users to use the following elements in their bio and collection+nft collectors notes: `['a', 'strong', 'em', 'ol', 'ul', 'li', 'p']`

specify which elements we allow in markdown

---

src/contexts/toast/ToastContext.tsx

Toast would never actually be dismissed, preventing the user from being able to click on any elements behind it (even post-dismissal)

Fix dangling toast

---

src/hooks/api/users/useUpdateUser.ts

Users were seeing outdated bios if they re-opened the modal immediately after editing their bio

Fix stale bio

---

src/components/EnsOrAddress.tsx
src/components/PlainErrorBoundary.tsx

This should protect against all sorts of errors: 404s, malformed JSON, etc.

Wrap ENS handler in error boundary

---

src/components/FadeTransitioner/FadeTransitioner.tsx

There was some pretty gross jank when transitioning to a route which suspended while waiting for data.
The root cause here was the `FullScreenLoader` wasn't getting the same transition styles as the actual route, so it just looked really sudden / jarring.
**Before / After**
On the right, you're not seeing the fallback since the API resolves faster than the transition finishes. I tested it out with a component which suspends forever and the functionality looks right.
https://user-images.githubusercontent.com/6754223/152666156-01b6d6fb-87f0-449b-91df-66c036103f2f.mp4

Fix fade transition with suspense jank

---

src/scenes/NftDetailPage/NftDetailNote.tsx

Adds Mixpanel tracking to collector's note saves, indicating whether the note was added (`note_added`, returning `false` if the user has deleted their note) and the length of the note `num_chars`

Track collector's note events

---

src/flows/shared/steps/OrganizeCollection/Editor/StagingArea.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
src/scenes/NftDetailPage/NftDetailText.tsx

This PR removes extraneous scrollbars by replacing `overflow: scroll` with `overflow: auto`. It affects three elements:
<div style="display: flex;">
</div>
<div style="display: flex;">
</div>
<div style="display: flex;">
</div>
---
These scrollbars will still appear if **there is overflow**, but in events where content does not overflow no scrollbars appear.
For those interested, us Mac OSX were likely being tricked because trackpads automatically hide scrollbars. This is also why plugging in an external mouse would cause the scrollbars to reappear: https://kilianvalkhof.com/2021/css-html/you-want-overflow-auto-not-overflow-scroll/

Replace instances of overflow: scroll with overflow: auto

---

src/hooks/api/collections/useCreateCollection.ts

When we optimistically save the newly created collection in the cache, put it at the beginning of your gallery.

Put optimistically create collection at top of gallery

---

src/components/NftPreview/NftPreview.tsx
src/components/NftPreview/NftPreviewLabel.tsx

This PR adjusts styling of asset preview text on small screens. It fixes the bug where collection titles/NFT names were cut off on mobile/small screens. Before/after:
<div style="display: flex;">
</div>
---
On screens under our `tablet` breakpoint, we 
1. reduce font size and line height, 
2. hide overflow, and 
3. apply a `text-overflow` property of `ellipsis` which leads to the `...` truncation when overflow begins. 
We use `-webkit-line-clamp` so that the NFT title will be truncated after one line of text, and the collection title will begin truncation after 2 lines of text (as you can see in the screenshot above). We can adjust these numbers, although generally 3 lines of text is the upper limit if we want to preserve the current design of the Nft preview text only taking up a max of …

Adjust styling of NFT preview text on small screens

---

src/components/core/Page/GlobalNavbar/GlobalNavbar.tsx

fixes dat z-index bug (before/after):
<div style="display: flex;">
</div>

Place navbar and its dropdowns above asset on nft detail page

---

src/components/WalletSelector/AddWalletPending/AddWalletPendingDefault.tsx
src/components/WalletSelector/AddWalletPending/AddWalletPendingGnosisSafe.tsx
src/components/WalletSelector/AuthenticateWalletPending/AuthenticateWalletPendingDefault.tsx
src/components/WalletSelector/AuthenticateWalletPending/AuthenticateWalletPendingGnosisSafe.tsx

Send handled auth errors to sentry in the following areas
- sign in (EOA + Gnosis)
- add wallet (EOA + Gnosis)

send handled auth errors to sentry

---

public/icons/grid_layout.svg
public/icons/list_layout.svg
src/scenes/UserGalleryPage/MobileLayoutToggle.tsx

This updates the icons used for the list/grid toggle buttons. The icons are directly exported from Figma.
Spacing is also in line with expectations as laid out by Figma:
<div style="display: flex;">
(As a quick note, if we want pixel-precision on the entire page, that should be a more diligent effort; there are things in our current layout that make it difficult to measure exact px distances between elements, such as the line-height of text elements.)
Behind the scenes, I moved away from imports of the SVG icons as images and instead wrote the SVG [directly](https://github.com/gallery-so/gallery/compare/connor/mobile-grid-toggle?expand=1#diff-189e82c4c56e01bd3b60d712b732ac0b632eb686cb63d7bab28f5d4c74de4cdbR10-R30). This enables hover events on the stroke, which wouldn't be possible if we …

Improve appearance of mobile list/grid toggle icons

---

sentry.client.config.js

This PR enables the tunnel option during Sentry.init to to use our Sentry proxy.
official docs:
https://docs.sentry.io/platforms/javascript/troubleshooting/#using-the-tunnel-option
bug successfully submitted on brave:
bug received in sentry:

configure sentry tunnel with new proxy

---

src/contexts/analytics/AnalyticsContext.tsx
src/contexts/errorReporting/ErrorReportingContext.tsx

Any error triggering the top-level error boundary would trigger a cascade of `AnalyticsContext` errors due to it trying to render `GalleryLink` outside of the analytics context – when it's in fact a dependency and must be rendered within.
This PR updates the tracking function to revert to a no-op should a situation like this arise in the future.

Fix broken analytics context

---

src/contexts/analytics/AnalyticsContext.tsx
src/contexts/auth/AuthContext.tsx

We want to set the user's id as the `distinct_id` field in mixpanel when possible. This is done by calling mixpanel.identify() when the user logs in, or on page load and they are already logged in. 
Includes a bonus change to add Sentry logging when there's a Mixpanel error.

Set user id using mixpanel identify function

---

src/components/WalletSelector/AddWalletPending/AddWalletPendingDefault.tsx
src/components/WalletSelector/AddWalletPending/AddWalletPendingGnosisSafe.tsx
src/components/WalletSelector/AuthenticateWalletPending/AuthenticateWalletPendingDefault.tsx
src/components/WalletSelector/AuthenticateWalletPending/AuthenticateWalletPendingGnosisSafe.tsx

This tries to address the following issue:
https://sentry.io/organizations/usegallery/issues/3122657620/events/ce4b0f3370a04bdcb13a559a69111561/?project=6187637
We aren't capturing web3 errors correctly because they are not Error types. The suggested solution is to just capture the message. If we find that isn't sufficient we can dig deeper on how to capture the full error.

capture web3error and error separately during wallet actions

---

src/components/ManageWallets/ManageWallets.tsx
src/components/ManageWallets/ManageWalletsRow.tsx
src/hooks/api/users/useRemoveUserAddress.ts

**Summary**
This fixes a bug where upon disconnecting a wallet from a user account, the wallet row remained on screen. The expected behavior is that the wallet row is unmounted so that there is visual feedback that the wallet was removed.
As a bonus I also added a notification that says `Wallet ${removedAddress} has been removed.` upon successful removal, since we already have a notification upon successful addition.

Fix so wallet row is unmounted after disconnecting the wallet

---

src/scenes/NftDetailPage/NftDetailPage.tsx
src/scenes/NftDetailPage/NftDetailText.tsx

This PR changes the detail text on the NFT Detail Page to show username under "Owned By" instead of the owner's address.
(this means we won't show the .eth for user who have a .eth for "Owned By". We will still show .eth where applicable for "Created By")

show username under Owned By on NFT Detail Page

---

src/components/ManageWallets/ManageWallets.tsx

This PR fixes a default notification message being incorrectly displayed when viewing the multi wallet modal.

fix default notification message

---

src/contexts/wizard/WizardDataProvider.tsx

This will give us more visibility into how often this issue occurs

Capture error to sentry when refresh nfts returns an error

---

src/scenes/UserGalleryPage/UserGalleryCollection.tsx

A timeout was preventing the icon from re-appearing when the mouse quickly left and re-entered.
Not sure why the timeout was there in the first place (original [PR](https://github.com/gallery-so/gallery/pull/571/files#diff-32f8df5768976d7f398a2e18a88ccafff55d8ae1aeb11765e8530e5af2ccd022R57-R61))

Fix collection hovering bug

---

src/components/NftGallery/NftGallery.tsx
src/components/NftPreview/NftPreview.tsx
src/contexts/shimmer/ShimmerContext.tsx

full width if single column + landscape (before/after)
60% width if single column + NOT landscape. current behavior is 50% (before/after)

Full width on landscape

---

src/flows/shared/steps/OrganizeGallery/CollectionRowSettings.tsx

This PR removes the "Share" option from each collection on the /edit page.

remove share button from Reorder Gallery page

---

src/scenes/WelcomeAnimation/WelcomeAnimation.tsx

The welcome page has logic where if you already have a username, it would push you to your user profile, rather than continuing you through the onboarding flow.
This seems like an unnecessary check, as the only way one could end up in this state is to visit `/welcome` directly as an authenticated user. Furthermore, if they do choose to go through the welcome flow again, it works just fine (their username/bio is pre-populated in the next step, and they can create a new collection in the next, etc).
Honestly the other cool thing about this is it's one less place to handle graphql migration lolll

Remove unnecessary username check for welcome flow

---

src/contexts/swr/middleware/handleObscenelyLargeAssets.ts

opensea Is returning a new url for the dead ringer edge case. this pr adds that url to our exception list of obscenely large images

handle new deadringer url

---

src/scenes/CommunityPage/CommunityPageList.tsx

This PR fixes a bug where the search filter on the community page didn't properly update the list of users. Changing the value used as the key worked.

Fix community page filter

---

src/scenes/NftDetailPage/NftDetailText.tsx

The description on the NFT Detail text was rendered twice in a row by accident. This PR removes the redundant one.

delete duplicate description

---

src/scenes/CommunityPage/CommunityPageView.tsx

This PR truncates long community descriptions so that only 4 lines (approx) of the description are displayed by default.
a "Show More" button will reveal the rest of the description.
Also reduces the width of the description to 50% on non mobile

truncate long community descriptions and reduce width

---

src/components/core/InteractiveLink/InteractiveLink.tsx
src/scenes/CommunityPage/CommunityPage.tsx
src/scenes/CommunityPage/CommunityPageList.tsx
src/scenes/CommunityPage/CommunityPageView.tsx

This pr improves how we limit long community descriptions to 4 lines using css rather than by character length.
It also adds 2 mixpanel events for the community page.

Improve how # of lines in community description are limited and add analytics events

---

src/components/ImageWithLoading/ImageWithLoading.tsx
src/scenes/NftDetailPage/NftDetailImage.tsx
src/scenes/NftDetailPage/NftDetailVideo.tsx

this PR fixes image ratio bug for safari
before
after

fix image ratio on safari

---

src/flows/shared/steps/OrganizeCollection/Editor/SortableStagedNft.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarNftIcon.tsx
src/flows/shared/steps/OrganizeGallery/CollectionRow.tsx

This prevents accidental highlighting of NFT preview images while in editing contexts, by adding `user-select: none` to three places:
Here we add `user-select: none` and `pointer-events: none` to the individual images so that the user does not accidentally drag the **image** when they intend to drag the **row**.
https://user-images.githubusercontent.com/13339581/164994892-fa334480-57dd-46cf-a34e-5512ef77765a.mov
Here we add `user-select: none` to individual images so that a user who tries to drag images (thinking dragging is a functionality here, which it is not) do not see highlighting of the other NFTs:
https://user-images.githubusercontent.com/13339581/164995045-e38e6a48-76a7-4849-b924-ccc0565cee02.mov
Finally we add a `user-select: none` to each individual image so that the user does …

Prevent accidental image selection when editing collections/galleries

---

src/components/core/TextArea/TextArea.tsx
src/hooks/useKeyDown.tsx
src/scenes/NftDetailPage/NftDetailView.tsx

This fixes a bug where if you type a backspace in a textarea and then click right or left arrow key the app navigates to `/{username}` rather than the next/previous NFT id. This was because it was registering the `Backspace` key and "queuing" it up for when the next key press was registered. 
https://user-images.githubusercontent.com/13339581/164838867-8fc6a483-f05c-4c10-a914-ae4149453831.mov
Fixed by resetting `keyPressed` to false when key is released. Also, moved the `activeEl` declaration outside of the useEffect so that we listen for changes in focused element.

Fix weird keyboard navigation bug

---

pages/community/[contractAddress]/index.tsx
src/scenes/NftDetailPage/NftDetailText.tsx

This PR enables Community Pages for every collection except Art Blocks, which we need custom support for due to their collections existing on a single contract.

GAL-55 enable Community Pages for every collection except umbrella contracts like art blocks and foundation

---

src/components/NftPreview/NftPreview.tsx
src/flows/shared/steps/OrganizeCollection/Editor/SortableStagedNft.tsx
src/flows/shared/steps/OrganizeCollection/Editor/StagedNftImageDragging.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarNftIcon.tsx
src/flows/shared/steps/OrganizeGallery/CollectionRow.tsx
src/scenes/NftDetailPage/NftDetailAsset.tsx
src/utils/nft.ts

This PR adds a background color override mechanism that allows us to specify a background color for nfts from specific contracts.
This was requested by Obits to set the background of their nfts which have a transparent background to #E0E0E0.
Gallery page:
Editor dnd:
Editor sidebar:
/edit collection rows

GAL-42 Add image background override to let us set backgrounds for certain contracts

---

src/scenes/NftDetailPage/NftAdditionalDetails.tsx
src/scenes/NftDetailPage/NftDetailText.tsx

This PR updates two things:
- Move "HIDE DETAILS" button to the bottom of nft detail description
- Change button copy from "ADDITIONAL DETAILS" -> "SHOW DETAILS" 
SHOW DETAILS
HIDE DETAILS

GAL-61 Move hide details to the bottom of nft details and update copy

---

pages/community/[contractAddress]/index.tsx
src/scenes/CommunityPage/CommunityPageView.tsx

now that we're opening community pages up, I checked out a few pages to try to find any edge cases and issues.
This PR does the following
- adds Braindrops to the list of disabled contracts. It's another umbrella contract
- fixes a bug where markdown lists were not clamped/hidden properly on safari. affected certain community pages that are now available, like Bob the Bean Farmer `0x2079812353e2c9409a788fbf5f383fa62ad85be8`
Before
After

disable another umbrella contract + adjust description clamping:

---

package.json
yarn.lock

Vercel previews deploys have been failing with the error:
```/vercel/path0/node_modules/relay-compiler/linux-x64/relay: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory```
this PR bumps `relay-compiler` to `13.2.0` to see if it fixes verbal preview deploys

see if bumping relay-compiler version fixes vercel preview deploy

---

src/components/NftPreview/NftPreview.tsx
src/components/NftPreview/NftPreviewLabel.tsx
src/components/core/InteractiveLink/InteractiveLink.tsx

This PR makes the Collection Name in Nft Previews clickable , and they link to the community page.

GAL-128 Make Collection Name in Nft Preview clickable to link to community page

---

src/components/NftPreview/NftPreviewLabel.tsx

Make touch target for nft preview label link smaller so that only the text is clickable.
also matches the link's text style with the text above

Make touch target for nft preview label link tighter

---

src/contexts/relay/relayFetchFunction.ts

Helps fix an issue in tracing where a span for a request would last a very short amount of time, rather than the length of the request.
More details in comments!

Add await to relayFetchFunction

---

src/components/NftPreview/NftPreviewLabel.tsx

On the label that appears when you hover on an NFT, the collection name was a bit bigger than the name name on mobile.
This PR fixes that so that the sizing is consistent.
Before:
After:

make collection name in hover text smaller on mobile

---

src/flows/shared/steps/OrganizeCollection/Editor/StagedNftImage.tsx
src/flows/shared/steps/OrganizeCollection/Editor/StagedNftImageDragging.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarNftIcon.tsx

Instead of causing a full-screen error, make the problematic NFT display a fallback image instead (and silently report the error to sentry)

Prevent full-page errors on image load failure

---

src/scenes/MembershipMintPage/MembershipMintPage.tsx

Fixes a bug on the membership mint page where upon a successful mint, we also showed the user the "Ineligible to mint" message since technically they are no longer eligible. 
We now only show the success state message and link to onboarding
full video in threads.
.

[GAL-173] fix membership success state to not show ineligible message

---

src/constants/poster.ts

This PR updates the Poster Page's deadline to be 11PM(EST) on 5/18 wed.
previously the time left was localized so users would see different hours remaining, but it should now show the remaining time until 11PMEST for everyone.

Update poster deadline and make it based on EST

---

src/components/EnsOrAddress.tsx

Toss a boundary around the component that was triggering full-page loader

ENS suspense boundary

---

src/components/core/Dropdown/Dropdown.tsx

For certain users, the dropdown was closing too quickly for the underlying `onClick` to fire. Made sure to test in various scenarios that there was no jank.

Fix dropdown bug

---

src/components/Profile/UserInfoForm.tsx
src/components/core/BigInput/BigInput.tsx
src/components/core/Markdown/Bold.tsx
src/components/core/Markdown/IconContainer.tsx
src/components/core/Markdown/Link.tsx
src/components/core/Markdown/List.tsx
src/components/core/Markdown/MarkdownShortcuts.tsx
src/components/core/TextArea/TextArea.tsx
src/contexts/modal/AnimatedModal.tsx
src/flows/shared/steps/OrganizeCollection/CollectionCreateOrEditForm.tsx
src/scenes/NftDetailPage/NftDetailNote.tsx
src/scenes/UserGalleryPage/EditUserInfoModal.tsx

This PR addresses remaining design+polish items described here: https://github.com/gallery-so/gallery/pull/748#issuecomment-1126583289
Additionally, it enables Markdown for the Collection description editor on the Edit Gallery page, and fixes undefined text refs wherever we used `TextAreaWithCharCount`.  also made som changes to the Collectors Note editor to match the updated specs.
detailed list of changes:
Markdown Buttons (before)
Markdown Buttons (after)
Modal Editor (before)
Modal Editor (after)
Collectors Note Editor (before)
Collectors Note Editor (after)

Polish items for markdown, add to collection desc and edit gallery pages

---

src/scenes/CollectionGalleryPage/CollectionGalleryPage.tsx
src/scenes/UserGalleryPage/UserGallery.tsx

Wanted to use something like `preventDefault` on the modal but the problem is the callback is already registered from the parent by then; seemed cleanest to put the check on the parent

[GAL-190] Fix error flash when hitting `e` on modal

---

src/contexts/modal/ModalContext.tsx

Currently, clicking "X" on the modal explicitly will keep your URL at the NFT detail route, rather than returning you to the homepage.
This is because the desired `onClose` wasn't getting called, since the callback was being passed a truthy MouseEvent.

Fix modal close regression

---

src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarNftIcon.tsx

`justify-content: space-between` was spreading out sidebar content if users had an uneven number of NFTs. fixed with `grid-gap`.
before vs. after
before vs. after
ensure no regressions (top of sidebar)
property is well supported

Fix sidebar alignment issue for NFTs

---

src/components/Follow/FollowList.tsx
src/components/Follow/FollowerListButton.tsx
src/contexts/modal/AnimatedModal.tsx
src/contexts/modal/ModalContext.tsx
src/index.css
src/utils/featureFlag.ts

sync'd with jess for some design tweaks:
**Truncated long bios**
| ![Screen Shot 2022-05-31 at 3 20 04 PM](https://user-images.githubusercontent.com/12162433/171271270-e1407889-7bf5-46a7-bb41-d787f4d41dc1.png) | ![Screen Shot 2022-05-31 at 3 19 48 PM](https://user-images.githubusercontent.com/12162433/171271272-f72e5f93-96cc-4e4f-9f9a-d51e7bb40a5f.png) |
**Updated padding**
| ![image](https://user-images.githubusercontent.com/12162433/171271412-16ea8f0e-85d7-4b9c-b234-614cc209215e.png) | ![Screen Shot 2022-05-31 at 3 34 17 PM](https://user-images.githubusercontent.com/12162433/171271337-96912a1e-d667-47cd-b5d0-e6d815a31879.png) |
**Removed scrollbar from appearing by default**
Will only be displayed when scrolling; …

Follow tweaks

---

src/components/core/Button/TextButton.tsx

fix a recent regression that messes with button positioning
**current**
**new**

Fix button positioning regression

---

src/components/Follow/FollowerListButton.tsx
src/components/Follow/NavActionFollow.tsx

This PR makes the "Followers" button that displays the Followers List always visible for non-logged in users, to improve discoverability.

[GAL-207] make followers list button visible for non logged in users always

---

src/components/WalletSelector/AddWalletPending/AddWalletPendingDefault.tsx
src/components/WalletSelector/AddWalletPending/AddWalletPendingGnosisSafe.tsx
src/components/WalletSelector/AuthenticateWalletPending/AuthenticateWalletPendingDefault.tsx
src/components/WalletSelector/AuthenticateWalletPending/AuthenticateWalletPendingGnosisSafe.tsx
src/components/WalletSelector/WalletSelector.tsx
src/contexts/analytics/authUtil.ts

Sentry alerts keep getting fired because an error gets logged when a user tries to sign in and they don't have a membership nft.
This isn't an app error, so we don't need to log it in Sentry. we still track the event in analytics, so we don't lose this information.
Added a util function `isNotEarlyAccessError` to check the error type using the error message, and updated the add wallet + sign in flows to not log the exception if this is true.

dont log exception if because user is not early access

---

src/components/core/Markdown/Link.tsx

If the user clicks the Link button while their cursor is in a newly created link (`[](https://)`) this will remove that link.
This does not handle the case where a user selects text (`Hello`), creates a link (`[Hello](https://)`) and then clicks again. This is a more difficult problem because the middle text (`Hello`) could be any number of characters; it is difficult to handle in our current configuration.

[GAL-212] Remove link formatting when clicking on empty link

---

src/scenes/Home/Home.tsx

Missed a button when updating button styles/removing styling overrides- this PR updates the home page sign in button
before
after

adjsut home button style

---

src/components/ManageWallets/ManageWallets.tsx

for some reason the change to this button was omitted from the original PR
before
after

update Add Wallet button styling

---

src/scenes/Modals/ManageWalletsModal.tsx

this pr removes extra spacing at the bottom of the add wallet modal
before
after

Remove extra spacing from add wallet modal

---

pages/opengraph/user/[username].tsx

Fixes bug where hidden collections are included in the gallery link preview image

[GAL-135] filter hidden collections from gallery link preview image

---

src/contexts/globalLayout/GlobalNavbar/LoggedInNav.tsx

update copy for Edit gallery menu option for more clarity
before
after

update copy for Edit Gallery menu option

---

src/scenes/UserGalleryPage/UserGalleryPage.tsx

Set vertical allignment to the top in the user gallery page
**Before**
**After**
Notes:
Seems like there is no regression since only one page that used this component `<UserGallerypage>`

[GAL-202] Remove vertical center on user gallery page

---

src/scenes/CollectionGalleryPage/CollectionGallery.tsx
src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx

Change the spacing above and below the header on the collection page for mobile, reported by jess
this makes the spacing  consistent with the main gallery page
collection
gallery

change collection page top spacing for mobile

---

src/components/WalletSelector/WalletSelector.tsx

If the user is not in the `mainnet` we show `switch network` button 
**Before**
**Demo**
https://user-images.githubusercontent.com/4480258/176084115-2b707f51-645f-47d6-9a74-9a9a738a6b31.mp4

[GAL-234] Add switch network method during sign in

---

src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
src/components/Feed/Events/CollectorsNoteAddedToTokenFeedEvent.tsx
src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
src/components/Feed/Events/UserFollowedUsersFeedEvent.tsx
src/components/Feed/Feed.tsx
src/components/Feed/FeedList.tsx
src/components/Feed/GlobalFeed.tsx
src/components/Feed/ViewerFeed.tsx
src/components/Feed/analytics.ts
src/components/NavbarGLink.tsx
src/components/core/Button/Button.tsx
src/components/core/Button/SuppressedHrefWrapper.tsx
src/scenes/LandingPage/LandingPage.tsx

Added click events to 
Also added a SuppressedHrefWrapper that allows us to wrap components like Buttons that navigate on click, so that we can properly have <a> tags with hrefs on elements that cause navigation

Add feed tracking events and some clean up

---

src/components/core/Button/TextButton.tsx
src/components/core/Dropdown/Dropdown.tsx
src/contexts/globalLayout/GlobalNavbar/LoggedInNav.tsx
src/flows/shared/steps/OrganizeCollection/Editor/EditorMenu.tsx
src/flows/shared/steps/OrganizeCollection/Editor/LiveDisplayAdjuster.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/SearchBar.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
src/flows/shared/steps/OrganizeGallery/CollectionRow.tsx
src/flows/shared/steps/OrganizeGallery/CollectionRowSettings.tsx
src/flows/shared/steps/OrganizeGallery/CollectionRowWrapper.tsx
src/flows/shared/steps/OrganizeGallery/Header.tsx
src/icons/Video.tsx
src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
src/scenes/UserGalleryPage/UserGalleryCollection.tsx

Figma/dev: (Note: we want to replace the collection description with the # of pieces? just confirming)
Figma/dev: 
**Note: the Figma designs specify an approach to the dropdown that would require a sort of refactor across all dropdowns (change dropdown padding from `12px` -> `8px`, and increase the size of dropdown elements within)**. I think this should be scoped to a different PR, maybe? Or if this dropdown is meant to appear differently, we could style it independent of others
**Note: I figured we wanted to keep the "select"/"deselect all" button here?**
Figma/dev:
Figma/dev:
**Note: Live display button currently does nothing, so it is commented out.** Unless this functionality is live? I didn't think so.

[GAL-275] Polish pass on Collection Editor (desktop, moweb)

---

src/flows/shared/steps/OrganizeGallery/CollectionRow.tsx
src/flows/shared/steps/OrganizeGallery/CollectionRowSettings.tsx
src/flows/shared/steps/OrganizeGallery/OrganizeGallery.tsx
src/scenes/CollectionGalleryPage/CollectionGallery.tsx

forgot to push the last change here (was just sitting in my staged changes...) all it does is reduce the height of the spacer on our /edit page from 64px to 16px

Fix height of spacer on top of collection editor page on mobile

---

src/flows/shared/steps/OrganizeGallery/SortableCollectionRow.tsx

Ensures the `CollectionRowSettings` are clickable

Fix non-clickable settings on collection row

---

src/hooks/useWindowSize.ts
src/scenes/NftDetailPage/NftDetailAudio.tsx

Find out that the bug only happens on audio NFT that have `<audio>` tag and used the`desktop` breakpoints. It didn't happen on tablet and mobile view
Add spacing if its desktop view and only applicable to audio NFT components
**Before**
**After**

[GAL-269] Fix collector notes overlap on Audio NFT

---

src/components/opengraph/OpenGraphPreview.tsx
src/constants/opengraph.ts

Reported bug 1:
Reported bug 2:

Fix OG image cutoff

---

src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
src/components/Feed/Events/CollectorsNoteAddedToCollectionFeedEvent.tsx
src/components/Feed/Events/CollectorsNoteAddedToTokenFeedEvent.tsx
src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
src/components/Feed/Events/UserFollowedUsersFeedEvent.tsx
src/components/Feed/FeedEvent.tsx
src/components/HoverCard/HoverCardOnUsername.tsx
src/components/IconButton/IconButton.tsx
src/hooks/useLoggedInUserId.ts

- Add `<HoverCardOnUsername/>` component
- Some query fragment passed into sub component for follow button 
https://user-images.githubusercontent.com/4480258/180928501-015f0980-ef37-4010-bf91-29590a6bd428.mp4
https://user-images.githubusercontent.com/4480258/180928629-5a58a049-8d0e-4c69-b8ff-779b41a0a537.mp4
In future, we can abstract into  `popover` component when we want to use it on other use-case likes collection hover, etc

[GAL-303] Feed: user preview card on hover

---

src/scenes/NftDetailPage/NftAdditionalDetails.tsx
src/scenes/NftDetailPage/NftDetailText.tsx
src/scenes/NftDetailPage/NftDetailView.tsx
src/utils/isSvg.ts

1) Allow anyone to refresh metadata. This action used to be limited to authenticated users, but anyone should be able to "fix" another person's NFT
2) Make SVG detection more lenient
**Before**
**After**

Improved metadata support

---

src/scenes/NftDetailPage/NftDetailNote.tsx

The collector's note title is now aligned with the styling of other "NFT Detail Text" (`Owner`, `Creator`, etc). It applies the styles from `TitleXS`
Before
After

Fix collector's note title styling

---

src/components/core/BigInput/BigInput.tsx
src/components/core/Text/Text.tsx
src/components/core/TextArea/TextArea.tsx
src/index.css
src/scenes/BasicTextPage/BasicTextPage.tsx

This explicitly renders `serif` as a fallback font for `GT Alpina`, and `Helvetica, Arial, sans-serif` as a fallback for `ABC Diatype`.
I can't actually replicate Jess' problems with the brief flash of incorrect fonts, but for posterity here is a comparison of each font with its fallback:

Add fallback fonts

---

src/components/Follow/FollowerListButton.tsx

The following/follower popover had a lower width breakpoint (`useIsMobileWindowWidth`) than `FollowList` (`useIsMobileOrMobileLargeWindowWidth`). Practically, this meant that the `FollowList` applied a `width` and `height` of 100% on any screen between mobile -> tablet width, while `fullscreen` was not yet true for the modal.
This resulted in a modal that looked like this:
Fixed:

[GAL-321] Fix follower/following popover on mobile width

---

src/components/LoadingAsset/ImageWithLoading.tsx
src/scenes/NftDetailPage/NftDetailAsset.tsx
src/scenes/NftDetailPage/NftDetailImage.tsx

This opens images in a new tab when clicked from an NFT detail page. 
* Audio: Does not open in new tab, because I think these are usually two separate components (one for audio, one for video)
* Video: Clicking pauses/plays videos
* **GIFs: Open in new tab**
* **SVGs: Open in new tab**
* **Images: Open in new tab**

[GAL-322] Open images in new tab from NFT Detail Page

---

src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx

Only full rows were being pushed into the set of rows to display, and the last row was being ignored if it wasn't full.
**Before** – only 2 zorbs appearing in sidebar
**After** – all zorbs listed

Ensure final row of NFTs are displayed in sidebar

---

src/components/Debugger/Debugger.tsx
src/components/Debugger/useDebugAuth.ts
src/components/Profile/UserInfoForm.tsx
src/components/core/Input/Input.tsx
src/constants/storageKeys.ts
src/contexts/AppProvider.tsx
src/contexts/auth/AuthContext.tsx
src/flows/shared/steps/OrganizeCollection/CollectionCreateOrEditForm.tsx
src/hooks/useMultiKeyDown.tsx

Enables "log-in-as-user" for local development. Does not connect to production, and requires a specific version of the backend to be running.
- Toggle debugger with `Ctrl + D`. You can also hit `Escape` to close
- Input values will persist across sessions so that the debugger remains auto-filled
- Enable further flexibility whenever `AuthMechanism!` is used, allowing us to control Account Creation + Adding Wallet flows.
- Multi-chain (implied by above)
- More informative error messages

[GAL-139] Debug Authenticator

---

src/components/Feed/Events/CollectorsNoteAddedToCollectionFeedEvent.tsx
src/components/Feed/Events/CollectorsNoteAddedToTokenFeedEvent.tsx
src/components/core/InteractiveLink/InteractiveLink.tsx
src/components/core/InteractiveLink/NavigateConfirmation.tsx
src/components/core/Markdown/Markdown.tsx

This PR creates two changes to support popover components to verify navigation when a user clicks on an external link
The content passed into our `StyledNote` is now passed into our `Markdown` component ([see change](
https://github.com/gallery-so/gallery/pull/923/files#diff-cd0356a1bacbd0b4c7256769d68afa4638e61c1836aa9e9d0a30d9ac50b192a8R118-R120)]. Associated with this change is a new prop called `inheritLinkStyling`, which essentially tells the `Markdown` component to skip its usual styling of links, and instead inherit styles of the parent text. In our case, we wanted to do this so that the links rendered in Markdown would inherit the same size, font family, etc. as the note (which was an H3 title).
By passing this prop into the `InteractiveLink` components, we are able to bypass the …

[GAL-323] Popover component when clicking on links from the feed

---

src/hooks/useResizeObserver.ts
src/scenes/UserGalleryPage/UserGalleryCollection.tsx
src/scenes/UserGalleryPage/UserGalleryCollections.tsx

**Changes**
1. Added react virtualized to the main gallery page
2. Removed the slicing collection array + scroll event
3. Added new hooks to monitor element size - [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)
**How it works**
We consider one collection as one row in the virtualized list
**Notes on how the height calculation works**
1. Seems like the way react virtualized work is its calculate the sizing before rendering it in the DOM. In this case it only get the height of the `collection name` and `collection description`. 
2. To get the exact sizing of the collection, we may need to wait for the NFT to load (especially for live render). 
3. I've added a callback function in the `UserGalleryCollection` components,  it will trigger whenever the height …

Virtualize main gallery

---

src/components/Feed/Events/FeedEventNftPreviewWrapper.tsx
src/components/LoadingAsset/ImageWithLoading.tsx
src/components/NftPreview/GalleryNftPreviewWrapper.tsx
src/components/NftPreview/NftPreview.tsx
src/components/NftPreview/NftPreviewAsset.tsx

Enforce full width on images displayed in main gallery.
|  ![image](https://user-images.githubusercontent.com/12162433/183775504-a68e675a-d5a6-4f53-96e5-8b5b1b1a9e3a.png) | ![image](https://user-images.githubusercontent.com/12162433/183775566-cd6a7cb7-94c8-4d07-83c6-f57fc8c35a41.png) |

Apply full width on images displayed in main gallery

---

src/components/Feed/Events/FeedEventNftPreviewWrapper.tsx
src/components/LoadingAsset/ImageWithLoading.tsx
src/components/NftPreview/GalleryNftPreviewWrapper.tsx
src/components/NftPreview/NftPreview.tsx
src/components/NftPreview/NftPreviewAsset.tsx
src/components/opengraph/OpenGraphPreview.tsx
src/contexts/shimmer/ShimmerContext.tsx
src/hooks/useWindowSize.ts
src/scenes/NftDetailPage/NftDetailAnimation.tsx
src/scenes/NftDetailPage/NftDetailAsset.tsx
src/scenes/NftDetailPage/NftDetailImage.tsx
src/scenes/NftDetailPage/NftDetailView.tsx

Cleans up a lot of complex asset handling logic that was leading to regressions.
**This PR may lead to further regressions, but I believe the simplifications and improvements are a step in the right direction.** A perfect solution would require a deeper cleanup.
Fix stretched out images
^ Tall images look better aligned when window is tall
Fix cutoff on tall iframes
Fix stretched iframes
Ensure no regression when live-rendering squiggles
Ensure no regression when live-rendering videos
Fix opengraph issue
This is because it's difficult to determine an iframe's inner contents / dimensions. Without enforcing an aspect ratio, the iframe images would appear very small – only with a height of ~150px. This would also cause a regression in square/wide iframes, so for now we're enforcing an aspect …

Asset sizing improvements

---

public/manifest.json
src/components/WalletSelector/mutations/useLoginOrRedirectToOnboarding.ts
src/hooks/api/users/useAuthPayloadQuery.ts
src/hooks/api/users/useCreateUser.ts

[GAL-285] Fix gnosis safe auth

---

src/contexts/collectionEditor/CollectionEditorContext.tsx
src/flows/shared/steps/OrganizeCollection/Editor/DragAndDrop/DroppableSection.tsx
src/flows/shared/steps/OrganizeCollection/Editor/StagingArea.tsx

Multi-section Delete follow ups 

---

package.json
src/contexts/modal/AnimatedModal.tsx
src/contexts/modal/ModalContext.tsx
yarn.lock

Enable modal stacking by storing an array of modals in state rather than building the context around a singleton. Ended up having the nice effect of cleaning up a bunch of anti-pattern-y stuff where we were setting and un-setting config variables as the modal came and went.
**Tests**
**Before**
https://user-images.githubusercontent.com/12162433/184471307-47da74fe-1978-4f2c-af58-c212f6145105.mov
**After**
https://user-images.githubusercontent.com/12162433/184471310-0356ebf7-9cca-4702-992e-2470a25e0076.mov
**Before**
https://user-images.githubusercontent.com/12162433/184471313-993e4a61-b21d-4d70-91fa-bb5da85642c2.mov
**After**
https://user-images.githubusercontent.com/12162433/184471356-cac6a8fb-1060-4800-8671-5c0551a5c4a6.mov

[GAL-324] Enable multi-modal

---

src/components/NftPreview/NftPreview.tsx

**Finding**
* This bug can be replicable on Safari desktop and iOS devices
* Seems like on safari, the NFT preview use 100% height on the container altought we already inherit the sizing from the asset itself. 
* Only set the `initial` height on Safari browser.
**Before**
**After**
https://user-images.githubusercontent.com/4480258/184568403-4a664bc8-7059-4e10-88d0-6d9d22b8541e.mp4
https://user-images.githubusercontent.com/4480258/184568726-82909674-e6ed-45be-a0e3-71a9b4707623.mp4

Fix NFT spacing on safari

---

src/components/opengraph/OpenGraphPreview.tsx
src/components/opengraph/SingleOpenGraphPreview.tsx

**Changes**
1. Set initial height to image since some SVG dont have it
2. Trim the nft description on single nft preview link
**Before/After - NFT Description**
**Before/After - Single NFT (SVG)**
**Before/After - Collection with NFT (SVG)**

[GAL-329] Fix broken OG Image link

---

src/contexts/globalLayout/GlobalFooter/GlobalFooter.tsx

1.The broken footer only happens on large mobile devices ( > 420px )
2. Removed the `isFixed` props since we didn't used it
**Demo**
Before
After

[GAL-205] Broken footer on mobile

---

src/scenes/CommunityPage/CommunityPageView.tsx
src/utils/formatUrl.ts
src/utils/regex.test.tsx
src/utils/regex.ts

If there is any url in the community description, it will automatically render it as anchor text
Before
After
https://user-images.githubusercontent.com/4480258/185041081-c03011e3-9eee-405d-a904-05725a0f06af.mp4

[GAL-127] Render links in community page description

---

src/scenes/MerchStorePage/MerchMintButton.tsx
src/scenes/MerchStorePage/SingleItemPage.tsx

wallet connected (desktop)
wallet connected (mobile)
no wallet connected

Move connected address to top of screen

---

src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
src/hooks/useKeyDown.tsx

**Problem:** Pressing backspace in the searchbar of the editor ended up remaining sections from the main editing area.
**Solution:** Ignore keypress events if they're coming from inputs

Backspace bugfix on editor

---

src/components/core/InteractiveLink/NavigateConfirmation.tsx
src/contexts/modal/AnimatedModal.tsx

The navigation confirmation modal had a hard-coded width of 400px, making it appear cropped for screen widths <400px.
In a future PR, the width should be dictated when opening the modal, such as:
```js
showModal({
width: '400px',
...
})
```
and the ModalContext should use that to set the width in non-mobile scenarios. This will avoid us having to set custom logic on the inner content.
|  ![image](https://user-images.githubusercontent.com/12162433/187277711-2a12565b-6780-473b-bb58-9aaccbf81426.png) | ![image](https://user-images.githubusercontent.com/12162433/187277841-43c2a425-f839-481d-a519-0272b298d877.png) |

Fix modal width

---

src/components/WalletSelector/multichain/WalletOnboardingMessage.tsx
src/components/WalletSelector/multichain/tezos/TezosAddWallet.tsx
src/components/WalletSelector/multichain/tezos/TezosAuthenticateWallet.tsx
src/contexts/beacon/BeaconContext.tsx
src/flows/shared/steps/OrganizeCollection/Directions.tsx

**Changes**
- Update the empty state design for tezos auth flow & collection editor
- The message title will based on pre-selected wallet on beacon
**Screenshot**
**Auth for Tezos**
**Kukai**
**Temple**
**Collection Editor**
**Pending**
**Notes**
- Not sure why the cypress can't run. Will do a follow up PR to tackle the issue

[GAL-373] [GAL-361] Update empty state UI

---

src/contexts/auth/EthereumProviders.tsx

Use ABC Diatype for rainbowkit font

---

src/components/NftFailureFallback/NftFailureFallback.tsx

In a grid, if the failed NFT is the only item, it has no basis for a width since there are no other NFTs to fill the space and give the other stuff a reference. 
The fix is to give the fallback a `min-width` in the case that there are no other NFTs.

give failure fallback min width

---

src/components/NftPreview/NftPreviewAsset.tsx
src/scenes/NftDetailPage/NftDetailImage.tsx
src/scenes/NftDetailPage/NftDetailVideo.tsx
src/utils/isVideoUrl.ts

Rendering a video URL as a `poster` causes the video component to throw an error; the poster must be an image.
Follow-up: ensure `previewURLs` that are sent from the server are always images

Fix video poster bug

---

src/components/WalletSelector/multichain/MultichainWalletSelector.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/Sidebar.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarChainButton.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarChainSelector.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarTokens.tsx
src/flows/shared/steps/OrganizeCollection/Sidebar/chains.ts
src/utils/tezosEarlyAccess.ts

- Tezos hot key now sets a flag in local storage so we can rely on that for now in the sidebar
- POAP relies on feature flag
- Eth is always enabled
https://user-images.githubusercontent.com/6754223/189994332-c32a12f5-579f-4d62-9028-7ffcc4136d55.mov

Enable SidebarChainSelector w/ feature flags

---

src/components/NftPreview/NftPreview.tsx

Seems like the Safari 16 deprecated the `-webkit-appearance`
Can't find the documentation that mentioned its deprecated but this tweet helps - https://twitter.com/bigel/status/1570953610611294208 😬
**Before**
https://user-images.githubusercontent.com/4480258/190954844-ca06bb58-f317-424e-a3bb-3363718cca6d.MP4
**After**
https://user-images.githubusercontent.com/4480258/190954860-a0c60272-4b5e-467c-9b5c-6c47be5f2f16.MP4

[GAL-442] Rows rendering incorrectly on Safari 16

---

src/components/core/TextArea/TextArea.tsx

This PR creates the magic "paste-to-link" functionality seen on Notion, etc.
https://user-images.githubusercontent.com/13339581/190868703-53a47f5b-1c38-411a-8acc-6a1b6ab44076.mov
https://user-images.githubusercontent.com/13339581/190869107-442536e0-24bf-46e5-b5f7-fe026fda0a8a.mov
It only triggers the "paste-to-link" when the user's clipboard text begins with `http`. Otherwise, the paste behavior will be default (overwriting the selected text)
https://user-images.githubusercontent.com/13339581/190868800-ba8d2513-77c4-4d9f-b127-5e6a0e547e7b.mov
---
We wrap the pasting functionality in a `try/catch` block which means if it errors out for any reason, it will default to normal pasting behavior.
[`navigator.clipboard.readText()` is not supported in …

Paste URL onto text to create link

---

src/hooks/useMintContractWithQuantity.tsx

The item price didn't appear on the item page on the merch store, preventing users from minting.
It was caused by an error thrown while calculating the owned supply that prevented the page from fetching the price.
Before 
After

[GAL-445] fix issue getting owned supply which prevented price from showing

---

src/components/LoadingAsset/ImageWithLoading.tsx
src/components/NftPreview/NftPreview.tsx
src/scenes/NftDetailPage/NftDetailVideo.tsx
src/utils/browser.ts
src/utils/isFirefox.ts

Disable video looping if browser is Safari. As of Sept 2022, there's a bug on Safari where data will continuously download each time the video loops, at worst case leading to several gigabytes being fetched (which is really bad on mobile devices)

Disable video looping on safari

---

src/flows/shared/steps/OrganizeCollection/Sidebar/SidebarChainSelector.tsx
src/hooks/api/users/useCreateUser.ts

During onboarding (create user), if you enter an invalid bio, the UI displays the error message "Username is invalid". 
This confused a user who thought their username was bad and couldn't proceed through onboarding, even though it was the bio that caused the error.
In the edit username/bio ui, (for existing users), the message we display is "Username or bio is invalid", so this PR updates the error message when creating a user to match.
Error message for invalid bio when creating a user (confusing)
Error message for invalid bio when editing an existing user (less confusing)

GAL-450 Update error message during create user to account for invalid username OR bio

---

src/components/Feed/Events/UserFollowedUsersFeedEvent.tsx
src/components/NftPreview/NftPreviewLabel.tsx

**Finding**
The bug only happens on Safari < 15.5 because of the flex CSS  `end`  value 
**Changes**
- Replace the `end` into `flex-end` for most wide browser support on all components
**Reference**
- https://caniuse.com/mdn-css_properties_align-items_flex_context_start_end
- https://github.com/chakra-ui/chakra-ui/issues/5562
- https://stackoverflow.com/questions/70339367/flexbox-align-items-and-justify-content-end-not-working-in-safari-macos
**Before**
**After**

[GAL-457] NFT Preview Hover Text is misaligned on safari

---

src/components/NftPreview/NftPreviewLabel.tsx
src/flows/shared/steps/OrganizeCollection/Editor/StagedNftImage.tsx

**Ensure POAP community link is clickable from NFT label on gallery**
| ![image](https://user-images.githubusercontent.com/12162433/192440207-17926afd-4a07-4c23-a7ff-54bfcf5f3450.png) | ![image](https://user-images.githubusercontent.com/12162433/192440794-a424cf19-ac6e-44a0-89a0-a23f28e3fb99.png) |
**Disable non-POAP community links from being clickable on editor**
| ![image](https://user-images.githubusercontent.com/12162433/192440423-f2f8e7d9-78fb-45de-81e6-0251c94e53df.png) | ![image](https://user-images.githubusercontent.com/12162433/192440691-cb605c14-a9cb-4b80-90dd-552278b70c8c.png) |
Tested against regressions:
- Make sure community link for standard NFTs continue to appear clickable on gallery
- Make sure …

Fix poap community label

---

src/scenes/CollectionGalleryPage/CollectionGallery.tsx

Seems like this issue happens only on **Single Collection page** and there is only **one NFT inside** the collection. 
**Before**
https://user-images.githubusercontent.com/4480258/192917240-cf66d05d-8d57-47ea-81c0-a65afc04d9e9.mp4
**After**
https://user-images.githubusercontent.com/4480258/192917122-8a4f1506-293a-406a-877e-e8f9c1866c03.mp4
**Before**
**After**

[GAL-471] Fix gallery width

---

src/components/Profile/useUserInfoForm.ts
src/flows/OnboardingFlow/steps/AddUserInfo.tsx

I cleaned up some of the logic in `useUserInfoForm` while I was at it.
The new flow is we track this new state `isUsernameValid` which starts as `false`. 
- Every time the username is changed, we reset it to `false`.
- Only when the validation passes do we finally set it to `true`.
All of this logic feels very imperative. Bringing the bottom bar (the thing with the "next" button) into the step component itself should help make this logic simpler. In the future, the "Next" button itself can `useLazyLoadQuery` with the validation state. The fallback state for that component would be a disabled version of the button. 
For now, this is fine.

[GAL-466] Block "Next" step until username is valid

---

src/components/Profile/useUserInfoForm.ts

fixes a regression where the Edit modal broke for existing users, claiming that their own username was taken (and was thus unable to add bio, etc.)

Fix username taken regression

---

pages/gallery/[galleryId]/collection/[collectionId]/edit.tsx

Currently, when you click "save" in the editor, there is no confirmation that the change was saved and instead a confirmation modal appears saying "Would you like to stop editing?" 
This is confusing (user reported this was difficult to understand) and I believe the original behavior was to return to where the user came from.
This PR changes the editor so that upon saving it redirects the user instead of showing the "Would you like to stop editing?"  popover.

dont show confirmation modal on save

---

src/scenes/UserGalleryPage/UserGalleryCollections.tsx

Recompute the virtualize height on user gallery if the browser size changed (Device rotate, resize browser, etc)
**Before**
https://user-images.githubusercontent.com/4480258/195970213-86fbf049-b150-43ba-8409-b8b22466b6a9.mp4
**After**
https://user-images.githubusercontent.com/4480258/195970226-5b1bdc65-219a-4f4c-b9dd-498b7642d074.mp4

[GAL-533] Recompute virtualized row heights on window resize

---

src/contexts/globalLayout/GlobalFooter/GlobalFooter.tsx

This overflow bug on happens on small devices (width < 294px).
**Before**
**After**

[GAL-534] Fix footer overflow on small devices

---

src/scenes/NftDetailPage/NftDetailAnimation.tsx

**Finding**
Seems like this iframe failed to fetch an [image](https://gallery.infura-ipfs.io/ipfs/QmUme7vRedQ1poJBmQrqEQUM1sCjcUAzd8NajP2VbpAHUf/Bayer8x8.png) assets that required to render the design. 
[Example NFT](https://gallery.so/qaulv/2FLxx0S2M3NIgIKy1FE7MwmPZHy/2FLyBAGeprYirFgubtluKGsMOxJ)
[IPFS Asset](https://gallery.infura-ipfs.io/ipfs/QmUme7vRedQ1poJBmQrqEQUM1sCjcUAzd8NajP2VbpAHUf/)
Error log from the nft itself:
`Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.`
**Before**
https://user-images.githubusercontent.com/4480258/195979042-f4cb4b8f-e778-4d78-94aa-7c9a5c69cab8.mp4
**References**
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#sandbox
- …

[GAL-514] Interactive FxHash NFT detail page appears frozen

---

schema.graphql
src/components/Feed/Socialize/AdmireButton.tsx
src/components/Feed/Socialize/Interactions.tsx

Fixing an edge case with admires / comments. See this comment
```
* There's a bit of extra logic you can see where we're checking the `PageInfo.total`
* as well as checking the actual length of the admires / comments array.
*
* This is because there is a possibility that the user will either delete a comment
* or delete an admire. Under this case, the total count of comments / admires might
* be some large number, but we only actually have 0, 1, or 2 in the list
*
* Imagine this:
* 1. We load the page, and we hypothetically fetch 5 comments posted by the logged in user
* 2. There's actually a total of 10 comments on the server, but we only fetched 5
* 3. The user then goes and deletes all 5 of those comments
*
* Now we're in a state where `totalComments` is 5, but we don't actually have …
```

Interactions fixes

---

src/components/Feed/FeedEvent.tsx
src/components/Feed/FeedList.tsx
src/components/Feed/Socialize/AdmireButton.tsx
src/components/Feed/Socialize/CommentBox.tsx
src/components/Feed/Socialize/FeedEventSocializeSection.tsx
src/components/Feed/Socialize/Interactions.tsx

- Height recomputations are now done in a `useLayoutEffect` so the user sees no jitter when the height of an event changes
- Fixed pasting of stylized text into the comment box (we were seeing some weird behavior before)
The layout shift you're seeing at the end of the video is from the server stripping a trailing newline (I'm 99% sure)
https://user-images.githubusercontent.com/6754223/196294988-505f15d2-3d4a-4cfb-841f-66b8300907c7.mov
There is one more incredibly shitty behavior I'm seeing when scrolling through the list (independent of admire / comment). There seems to be this issue where when you scroll fast enough you can get into this fucked state where scrolling up one pixel shifts you way far, and then scrolling down one pixel scrolls you way far. I'm not sure what the root cause …

[GAL-519] Improve Admire Comment Jitter

---

pages/gallery/[galleryId]/collection/[collectionId]/edit.tsx

Simple little prompt to ensure users don't accidentally close the tab while editing their collections.

[GAL-541] prompt before closing collection editor

---

pages/gallery/[galleryId]/collection/[collectionId]/edit.tsx
pages/gallery/[galleryId]/collection/create.tsx
pages/gallery/[galleryId]/collection/useConfirmationMessageBeforeClose.ts

previous the warning only existed on `/edit`
extension of #1062

Add close warning on create page

---

src/scenes/NftDetailPage/NftDetailVideo.tsx

It seems like the browser is reporting an error on the video without there actually being an error on the element.
- Tested that actual errors still trigger the failure state
- Tested that TV's gallery works now

[GAL-544] Fix TV's gallery 

---

src/scenes/UserGalleryPage/UserGalleryCollections.tsx

**FInding**
Seems like the issue happens because the virtualize recompute the height when the window size changed (in this case the height changed)
Solution: We only monitor the `width` of the window, if its changed we will recomputed the height. To cover if the user rotate their phone or resize browser. 
**Demo**
**Before**
https://user-images.githubusercontent.com/4480258/196842375-7f2eb78f-fdf7-4ee8-9f9a-4763a9fc302f.mp4
**After**
https://user-images.githubusercontent.com/4480258/196842430-b479193e-9508-45ad-bdf6-81fa323dd760.mp4

[GAL-549] Fix profile jank on iOS

---

pages/home.tsx
pages/index.tsx

Pretty straight forward, basically we're just showing a landing page as the fallback while we're figuring whether or not they should be redirected.

[GAL-557] Redirect to /home from / when logged in

---

pages/[username]/activity.tsx
src/components/Feed/Feed.tsx
src/scenes/UserActivityPage/UserActivity.tsx
src/scenes/UserActivityPage/UserActivityFeed.tsx
src/scenes/UserActivityPage/UserActivityLayout.tsx
src/scenes/UserActivityPage/UserActivityPage.tsx
src/scenes/UserGalleryPage/UserGalleryLayout.tsx
src/scenes/UserGalleryPage/UserGalleryPage.tsx

**Changes**
- Added user activity feed
- Access it directly through https://gallery.so/username/activity
**Demo**
**Mobile**
https://user-images.githubusercontent.com/4480258/196184395-23dc714a-9b7a-4a6e-bceb-d69b074c44bc.mp4
**Desktop**
https://user-images.githubusercontent.com/4480258/196184753-5c307752-2a8a-4e99-af8c-92b49a87e26f.mp4

[GAL-385] Add Activity View (User Feed) to User Gallery page

---

src/utils/time.ts

`m` was pretty confusing as it referred to both `months` and `minutes`

Switch to 'mo' for months

---

src/contexts/toast/Toast.tsx

Users couldn't click things behind the Toast area before. Setting up these pointer events mitigates that

[GAL-581] Let users click through toast bar

---

src/components/Feed/Events/UserFollowedUsersFeedEvent.tsx
src/components/Feed/Events/UserFollowedYouEvent.tsx
src/components/Follow/FollowButton.tsx
src/components/Follow/NavActionFollow.tsx
src/components/HoverCard/HoverCardOnUsername.tsx
src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavbar.tsx
src/contexts/globalLayout/GlobalNavbar/SignInButton.tsx

Fix
**Before**
**After**
**Before**
**After**
https://user-images.githubusercontent.com/4480258/199407161-d879faf2-da90-4242-80df-eea7c80c22b7.mp4
https://user-images.githubusercontent.com/4480258/199407168-8698b1ce-4a6f-4cd2-b772-2223d429823c.mp4

Social Nav QA

---

src/scenes/UserGalleryPage/UserGalleryCollection.tsx

**Reported Bug**
**Before**
- no padding in between paragraphs
- weird expanding behavior on-click
https://user-images.githubusercontent.com/12162433/199828898-02f0a0ba-a8de-4326-b38c-46c2d2d9d4d5.mov
**After**
- ensure padding
- no padding change on click

Remove padding in between paragraph blocks for collection description

---

pages/[username]/activity.tsx
pages/home.tsx
schema.graphql
src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
src/components/Feed/Events/CollectorsNoteAddedToCollectionFeedEvent.tsx
src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
src/components/Feed/constants.ts

**Addressed**
Fetches a maximum of 4 tokens when referencing an existing collection.
**Not Addressed**
- `GAL-609` Adding many tokens to a brand new collection still have a potential to cause perf issues
- `GAL-608` "number of additional tokens" feature has been disabled for one particular feed event. This will be addressed once above issue is implemented

Limit feed event token preview count

---

pages/gallery/[galleryId]/edit.tsx

**Previous behavior**
Clicking "Done" after creating a new collection would send the user back to create a new collection
**Root cause**
We deprecated the wizard and replaced it with routes. In a world where each step in the editor is its own route, `canGoBack` would tell us that we should go to the previous route, which would be the literal `/collection/create` route as opposed to the pre-editor page.
Addressing the above with `replace` would not fix the issue, since `canGoBack()` pairs poorly with routes that are reached via `router.replace` vs. `router.push`. Even though `router.replace` doesn't impact nextjs router's history, it adds to our internal stack that we track manually. This would cause the "Done" button to mistakenly think that the _current page_ was the previous page, and …

[GAL-601] fix: unusual redirects in edit flow

---

src/components/Feed/Events/CollectionUpdatedFeedEvent.tsx
src/components/Feed/FeedEvent.tsx

Adds the component to handle the `CollectionUpdatedFeedEvent`. This event always guarantees that there will be a new collectors note and new tokens, otherwise it'll be categorized as their respective feed events by the backend, so no need to handle the cases where either is missing.
Please tear it apart and let me know if I did anything wrong 😄 
The event in all its glory:

Add collection updated component

---

pages/onboarding/add-email.tsx
pages/onboarding/organize-gallery.tsx
schema.graphql
src/components/Email/EmailForm.tsx
src/components/Email/EmailManager.tsx
src/components/Email/EmailVerificationStatus.tsx
src/components/Onboarding/OnboardingFooter.tsx
src/components/Onboarding/constants.ts
src/icons/AlertTriangleIcon.tsx
src/icons/CircleCheckIcon.tsx
src/icons/ClockIcon.tsx
src/utils/graphql/isFeatureEnabled.tsx
src/utils/regex.ts

This PR adds the "Add Email" component, and adds it as a step to the onboarding flow. This step replaces the "Congratulations" last step of the existing onboarding flow. The White Rhino feature flag controls which step is shown.
The default state before an email address has been added is to show an input.
Once an email is entered, it will be in an unverified state, required the user to verify via an email they receive.
The EmailVerificationStatus component reflects the various verification states:
verified
error

GAL-516 add "add email" component and step

---

src/scenes/UserGalleryPage/UserGalleryCollection.tsx

This issue only happens on safari
**Before**
https://user-images.githubusercontent.com/4480258/202072954-72f6972a-e448-459b-9c10-03f9e3bfa139.mp4
**After**
https://user-images.githubusercontent.com/4480258/202072678-c03c0688-f29e-4bac-b0b6-91f1c6734026.mp4

Fix user description line clamp in safari

---

src/components/Follow/NavActionFollow.tsx

This PR makes the username in the navbar turn gray if the user is viewing a different tab such as Galleries or Activities.
This already existed on mobile, so the changes are for desktop and follow the existing pattern used for mobile.
before:
After:

[GAL-649] make nav username gray if viewing a different tab

---

src/components/ManageGallery/OrganizeCollection/Sidebar/SearchBar.tsx
src/components/ManageGallery/OrganizeCollection/Sidebar/Sidebar.tsx
src/components/ManageGallery/OrganizeCollection/Sidebar/SidebarChainSelector.tsx
src/components/ManageGallery/OrganizeCollection/Sidebar/SidebarList.tsx
src/components/ManageGallery/OrganizeCollection/Sidebar/SidebarViewSelector.tsx

This PR addresses visual polish items ahead of launching hidden nfts
Hover state:
Added the hover state for when the dropdown is open too, so it still appears "pressed down" after you hover off
4px padding:
(search bar + hidden dropdown + collected selector have 4px padding, other items have more)
Vertically aligned text:
(the drop shadow in the screenshot is cus I used another browser window as a straightedge lol)

[GAL-682] Visual polish for sidebar for hidden nfts

---

src/components/NotificationsModal/NotificationsModal.tsx

This PR fixes the width of the notifications popover instead of using min-width, so that content does not stretch the popover out.
Before:
After:

fix width of notifications popover

---

src/components/Email/EmailForm.tsx
src/components/Email/EmailVerificationStatus.tsx
src/components/Feed/FeedList.tsx
src/components/NftFailureFallback/NftFailureFallback.tsx
src/components/NotificationsModal/Notification.tsx
src/components/NotificationsModal/NotificationEmailAlert.tsx
src/components/NotificationsModal/NotificationUserListModal.tsx
src/components/NotificationsModal/useNotificationsModal.tsx
src/components/core/Markdown/Bold.tsx
src/components/core/Markdown/IconContainer.tsx
src/components/core/Markdown/Link.tsx
src/contexts/globalLayout/GlobalNavbar/BackButton.tsx
src/contexts/globalLayout/GlobalNavbar/CollectionSaveButtonWithCaption.tsx
src/contexts/modal/AnimatedModal.tsx
src/contexts/modal/ModalContext.tsx
src/contexts/toast/Toast.tsx
src/icons/CloseIcon.tsx
src/scenes/UserActivityPage/UserActivityFeed.tsx

All modals now use the design system icon container. I made sure the other usages of the icons were good and modal alignment was good
I confirmed with my own account that this polling works
I want to call out why using `keyMapper` instead of blowing the `CellMeasurerCache` fixed the glitching problem when loading more results.
Previously, wiping the cache was a good workaround whenever new results loaded at the top of the list. Let's say we have item A at index 0 w/ a height of 420 px. When we refresh the feed, item B comes to the top of the list at index 0 w/ a height of 69px. You can see how caching the heights based on index becomes a problem. RV thinks that index 0 should have a height of 420px when it should clearly have a height of 69px. 
Completely blowing the cache works because …

Pre Launch Fixes: GAL-666 GAL-650 GAL-680 GAL-639 GAL-685 GAL-629 GAL-628 GAL-625

---

src/components/Email/useVerifyEmailOnPage.ts

This PR fixes a regression where the email verification mutation was not called if the user was not logged in.

fix verify email for non authed

---

src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
src/components/Feed/Events/CollectionUpdatedFeedEvent.tsx
src/components/Feed/Events/CollectorsNoteAddedToCollectionFeedEvent.tsx
src/components/Feed/Events/EventStyles.tsx
src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
src/components/Feed/Feed.tsx
src/components/Feed/FeedEvent.tsx
src/components/Feed/FeedEventTokenPreviews.tsx
src/components/Feed/Socialize/FeedEventSocializeSection.tsx
src/components/Feed/dimensions.ts

`StyledEventWrapper` is old news now that we have `Interactions` involved. So a lot of the styles that were in `StyledEventWrapper` have now been moved to `FeedEventContainer` and we've completely removed `StyledEventWrapper`.
This consolidated some clashing styles between interactions / feed events and now the padding lives in one place.
The `FeedEventTokenPreviews` has to manually manage widths right now due to reasons™️. I'm convinced we can make this better in the future, but not right now.
Those widths that are manually calculated now have to take into account that they can be inside of a captioned feed event which gets double padding. 
So we have this `isInCaption` which changes how many paddings we have to subtract from the total width.

DONT LOOK AT THIS PR (Fix feed event styling)

---

src/components/NotificationsModal/Notification.tsx
src/components/NotificationsModal/notifications/SomeoneViewedYourGallery.tsx

We have to make sure we add a `last` param, otherwise the server freaks out a bit.
also we don't want to show a caret for count <= 1

Fix `userViewers` field

---

src/components/ManageGallery/OrganizeCollection/Editor/CollectionEditor.tsx
src/components/ManageGallery/OrganizeCollection/Editor/useCheckUnsavedChanges.tsx

**Changes**
- Add `collectionMetadataState` too to keep track of token metadata change
- Move the check unsaved part into own hook
**Demo**
https://user-images.githubusercontent.com/4480258/202956927-1a4884d1-1d87-4852-80ad-e70bf4a8debc.mp4

[GAL-718] Fix save button for toggle live render

---

src/components/Feed/Socialize/NotesModal/NotesModal.tsx

Sort the notes bt **comment** first and then **admire**. Both in `descending` order - `latest to oldest`
**Before**
**After**

[GAL-701] Sort interaction by comment and admire

---

src/contexts/globalLayout/GlobalFooter/GlobalFooter.tsx

We are out of beta!
before
after

Remove beta from footer

---

src/components/Feed/Socialize/AdmireLine.tsx
src/components/Feed/Socialize/Interactions.tsx

**Notes**
- "x others admired this " on feed is be clickable
- I changed the style of `x others admired this` to link (gray color & underlined) since its clickable. Lmk if we want to revert back to old style. 
**Before**
**After**
https://user-images.githubusercontent.com/4480258/203670471-e5e1bd7b-0786-48c5-82f3-8f781e42cd07.mp4

[GAL-723] Total admire will be clickable

---

src/components/core/Markdown/List.tsx
src/components/core/TextArea/TextArea.tsx

[GAL-728] Fix editor icon misalign

---

src/components/Feed/dimensions.ts

**Findings**
This bug only happens on desktop with 3 images. 
**Before 1**
**After 1**
**Before 2**
**After 2**

[GAL-727] Fix feed image event overflow

---

src/scenes/MerchStorePage/ItemPreview.tsx

We dropped a bug yesterday while trimming the bundle size. It seems like modals need to be separately wrapped with their relevant contexts since they make their way to a separate part of the tree.

Wrap `/shop` modal in EthereumProvider

---

sentry.client.config.js
sentry.server.config.js

- the biggest offender to our quota was `/__nextjs_original-stack-frame`, which was only being reported from localhost

chore: sentry improvements

---

src/components/NftPreview/NftPreviewLabel.tsx
src/scenes/NftDetailPage/NftDetailAsset.test.tsx
src/scenes/NftDetailPage/NftDetailText.tsx

This PR turns the community link into a clickable pill.  Also updated the NFT Detail Page to display badges.
NFT preview text
Wtihout badge, default (no hover)
Without Badge, on hover
With Badge, On hover
Non-link text (non-clickable)
NFT Detail Page
Default
Hover
Editor
Pill is non clickable
Pill content adapts if text is wider than NFT

GAL-741 turn community link into clickable pill

---

src/scenes/UserGalleryPage/UserGalleryCollection.tsx

revert change where we show `untitled` on gallery page

fix regression showing untitled on user's gallery GAL-914

---

src/components/ManageGallery/OrganizeCollection/Editor/SortableStagedNft.tsx
src/components/ManageGallery/OrganizeCollection/Editor/StagedItemDragging.tsx
src/components/ManageGallery/OrganizeCollection/Sidebar/SidebarNftIcon.tsx
src/components/ManageGallery/OrganizeGallery/BigNft.tsx
src/components/NftFailureFallback/NftFailureBoundary.tsx
src/components/NftPreview/NftPreview.tsx
src/contexts/boundary/ReportingErrorBoundary.tsx
src/errors/ErrorWithSentryMetadata.ts
src/scenes/NftDetailPage/NftDetailAsset.tsx
src/scenes/TokenDetailPage/TokenDetailAsset.tsx

We've seen a large increase in errors on Sentry re: the inability to render an NFT. Adding context to the errors w/ a token id will be helpful here.

Add tokenId to errors so we know the context

---

src/components/Feed/FeedEvent.tsx

This PR removes the side padding from feed events on mobile, as requested by Design.
This also fixes an issue where images are clipped on mobile.
Before
After

GAL-730 remove side padding from feed events on mobile

---

src/scenes/MerchStorePage/Redemption/RedeemedItem.tsx
src/scenes/MerchStorePage/Redemption/RedeemedPage.tsx
src/scenes/MerchStorePage/Redemption/ToRedeemPage.tsx
src/scenes/MerchStorePage/constants.ts

This PR handles the case where the user owns merch NFTs that have already been marked as `redeemed` on the user's behalf (e.g. for employees, people from NFT NYC who received a free one, etc.). Without this, the user would think they could redeem their existing, redeemed NFTs for more merch.
**Before**
This copy wasn't totally accurate; I _have_ merch NFTs, they've just been manually redeemed for me
**After**
**Before**
Copy icon displayed despite lack of discount codes
**After**
Clearer status

Clarify copy for manually redeemed items

---

src/scenes/CommunityPage/CommunityPageView.tsx

Also ensure line breaks are respected 
**Before**
**After**

Increase line clamp for community pages

---

src/scenes/MerchStorePage/ItemPreview.tsx
src/scenes/MerchStorePage/ListMerchItems.tsx
src/scenes/MerchStorePage/MerchStorePage.tsx

**Notes**
This scenario only happens if the users transferred out his merch nft after they minted. 
**Changes**
Instead of getting the quantity from the **contract**,  we used the existing `getMerch` backend to map all the value
Example: My wallet only have 1 Merch NFT (TShirt)
**Before**
**After**

Fix shop owned quantity

---

src/components/ManageGallery/OrganizeCollection/Sidebar/SidebarTokens.tsx
src/components/ManageGallery/OrganizeCollection/Sidebar/createVirtualizedRowsFromGroups.ts
src/components/NftFailureFallback/NftFailureBoundary.tsx
src/contexts/AppProvider.tsx
src/contexts/NftErrorContext.tsx
src/hooks/useNftRetry.tsx
src/scenes/NftDetailPage/NftDetailAsset.test.tsx

The root cause here is that RV isn't reusing component state since keys are based off of the index. I think this is solved in React Window.
Either way, the solution is to hoist the error state to a higher up context so that even if the component gets wiped, its state is saved elsewhere. 
UNIT TESTS ARE STILL PASSING WHICH IS HUGE VALUE

Fix sidebar infinite loop

---

src/components/HoverCard/HoverCardOnUsername.tsx
src/components/NotificationsModal/notifications/SomeoneAdmiredYourFeedEvent.tsx
src/components/NotificationsModal/notifications/SomeoneFollowedYou.tsx

The bold UI regression only happens on **following** and **admire** event
**Before**
**After**
**Text cut-off**
**Before**
**After**

[GAL-738] Fix cut off text on hover card and remove bold

---

src/components/ManageWallets/ManageWallets.tsx
src/components/NotificationsModal/NotificationEmailAlert.tsx
src/components/NotificationsModal/useNotificationsModal.tsx
src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdownContent.tsx
src/scenes/Modals/SettingsModal.tsx
src/scenes/Modals/SettingsModal/SettingsModal.tsx
src/scenes/Modals/SettingsModal/SettingsRowDescription.tsx
src/scenes/Modals/useOpenSettingsModal.tsx
src/utils/getOpenseaExternalUrl.ts

Show the user's Early Access status (whether or not they are holding a Premium card) in the settings popover
Early Access active (desktop)
Early Access active (mobile)
Early Access not active (desktop)
Early Access not active (mobile)

Show early access status in settings popover

---

sentry.client.config.js
src/contexts/NftErrorContext.tsx
src/contexts/boundary/ReportingErrorBoundary.tsx
src/errors/CouldNotRenderNftError.ts

The goal of this PR is to stop NFT errors from making their way to Sentry.
A core part of how our fallback system works is letting any function throw a `CouldNotRenderNftError` while trying to render. 
The problem is, whether or not we catch that with an error boundary, the error will get reported to Sentry via the `TryCatch` and `GlobalHandlers` integrations. 
Turning those integrations off makes us a bit more vulnerable to things like uncaught exceptions in callback functions, etc. Historically, these features have not been all that helpful to us so we're moving forward understanding this tradeoff.

disable reporting of nft errors

---

src/scenes/Modals/SettingsModal/SettingsModal.tsx

Settings modal felt a bit too cluttered

Cleanup settings modal

---

src/components/NftPreview/NftPreview.tsx
src/components/NftPreview/NftPreviewAsset.tsx
src/scenes/NftDetailPage/NftDetailAnimation.tsx
src/scenes/NftDetailPage/NftDetailAsset.tsx

Provide basic support for `TextMedia` by
- Fetching the type for preview urls
- Decoding the text media url for an `iframe` on the `NftDetailAsset`

support html text media

---

src/components/ManageWallets/ManageWallets.tsx

As per request from a user with more than 10 wallets, this bumps the limit up to 15!

Bump max allowed wallet addresses from 10 to 15

---

src/scenes/Modals/SettingsModal/SettingsModal.tsx

Require email address for early access

Specify early access qualifications in settings modal

---

src/components/Follow/NavActionFollow.tsx
src/components/HoverCard/HoverCardOnUsername.tsx
src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavbar.tsx
src/scenes/UserGalleryPage/UserGalleryHeader.tsx
src/utils/handleCustomDisplayName.ts

Handle custom display name for løyd. We actually did something similar already for the 3AC gallery, so this PR establishes a hacky pattern for using custom display names in certain places.
This is a stop gap until we have backend support for display names.

Handle custom display names

---

src/scenes/CommunityPage/CommunityPageView.tsx

Fix stretched out badge for community page

---

src/components/internal/GalleryViewEmitter.tsx

This PR re-enables tracking of un-authed views so that we can use it to track trending galleries.

Turn on un-authed views

---

pages/home.tsx
pages/settings.tsx
src/components/FadeTransitioner/FadeTransitioner.tsx
src/hooks/useAuthModal.tsx
src/scenes/Modals/SettingsModal/SettingsModal.tsx
src/scenes/Modals/useOpenSettingsModal.tsx

Introduce a new `/settings` route that displays the settings popover
- If logged out, it'll prompt you to log in, and display settings afterwards
- If logged in, it'll open the popover from the home screen
https://user-images.githubusercontent.com/12162433/212435238-e4db29ad-79a8-4868-bbf5-7b85c59d40dd.mov

/settings route with popover redirect

---

pages/gallery/[galleryId]/edit.tsx
pages/onboarding/add-user-info.tsx
pages/onboarding/edit-gallery.tsx
src/components/GalleryEditor/CollectionEditor/StagingArea.tsx
src/components/GalleryEditor/GalleryEditor.tsx
src/components/GalleryEditor/GalleryEditorContext.tsx
src/components/Onboarding/constants.ts
src/contexts/globalLayout/EditGalleryNavbar/EditGalleryNavbar.tsx
src/contexts/globalLayout/EditGalleryNavbar/GalleryTitleSection.tsx
src/contexts/globalLayout/EditGalleryNavbar/OnboardingEditGalleryNavbar.tsx

Great news!
We get to remove like 3 or 4 steps if you're in the new feature flag!
- Move the header controls out of `GalleryEditor` and into their respective pages (onboarding gallery editor, and regular gallery editor page)
- Create an onboarding specific gallery editor navbar
- Functionality is mostly the same with a few tweaks
- Fix a small bug in the `StagingArea`

Onboarding Gallery Editor Feature Flag

---

pages/[username]/activity.tsx
pages/[username]/followers.tsx
pages/[username]/galleries.tsx
pages/[username]/galleries/[galleryId].tsx
pages/[username]/index.tsx
pages/gallery/[galleryId]/edit.tsx
src/components/GalleryEditor/GalleryEditorContext.tsx
src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryLeftContent.tsx
src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavbar.tsx
src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryRightContent.tsx
src/scenes/UserGalleryPage/UserGalleryCollection.tsx
src/scenes/UserGalleryPage/UserGalleryCollections.tsx

- Had to thread through a `galleryRef` to the `GalleryNavbar` so the edit button is aware of which gallery we're talking about
- Updated the edit collection button to link to the new editor if you're in the FF
- Updated the new gallery editor to allow for an initial collection id so you get right to the content you want to edit

Fix edit gallery links

---

public/icons/delegate_cash_logo.svg
src/components/WalletSelector/multichain/DelegateCashMessage.tsx
src/components/WalletSelector/multichain/MultichainWalletSelector.tsx
src/components/WalletSelector/multichain/WalletButton.tsx
src/components/WalletSelector/multichain/supportedAuthMethods.ts

This PR adds "Delegate Cash" as a wallet option. Clicking on it will display a coming soon message with instructions for New and Existing Users to assist them with using a cold wallet with Gallery.
There is a back button that allows them to return to the wallet selection menu.
[ ] Add event to button click

Add Delegate Cash as a wallet option, with coming soon message

---

src/components/Featured/Featured.tsx
src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavLinks.tsx
src/contexts/globalLayout/GlobalNavbar/HomeNavbar/HomeNavbar.tsx
src/contexts/globalLayout/GlobalNavbar/NavbarLink.tsx

Fixed unstyled gallery nav links by setting `legacyBehavior` to false
Updated copy from "collector" to "curator"

Fix unstyled gallery nav links and update copy

---

src/components/Featured/FeaturedList.tsx

Seems like the issue is kind of not solvable. The workaround is to use `cssMode` (author's response here https://github.com/nolimits4web/swiper/issues/5471#issuecomment-1041465412).
The animations when using a mouse feel a little bit worse but it fixes the double swipe.

Fix double swipe bug w/ Swiper

---

schema.graphql
src/components/ManageWallets/ManageWallets.tsx
src/components/ManageWallets/ManageWalletsRow.tsx
src/components/ManageWallets/PrimaryWalletRow.tsx
src/components/WalletSelector/mutations/useRemoveWallet.ts
src/components/WalletSelector/mutations/useUpdatePrimaryWallet.ts
src/components/core/Button/Button.tsx
src/scenes/Modals/SettingsModal/SettingsModal.tsx
src/utils/wallet.ts
tests/graphql/mockGlobalLayoutQuery.ts

This PR updates the Settings popover to add a way for users to set a primary wallet.
**details around behavior:**
- A primary wallet is required. A backend migration has set a default primary wallet for every user.
- A user cannot disconnect their primary wallet directly. They must first unset it as the primary, and then disconnect. A tooltip informs the user about this limitation.
**notable changes:**
- Added a new row to display the primary wallet, and updated the existing rows to only display non-primary wallets.
- Removed the logic around not letting users disconnect the wallet they signed in with. The only thing that matters is that they cannot disconnect their only wallet, which will also be their primary wallet.
- Updated some styling around the error/warning state of the button. …

Add Primary Wallet selector

---

src/components/GalleryEditor/GalleryEditorContext.tsx
src/components/GalleryEditor/getInitialCollectionsFromServer.ts

Prior to this PR, we were not resetting the collection state in the context after a save.
I've updated the logic to make sure
- Collections from the server are shown to the user after hitting save
- Deleted collectionIds don't get sent twice
- Created collections get reset after saving
Bonus:
- Clicking on another section no longer causes the editor to think you have unsaved changes.

Fix double creations of collections

---

apps/web/src/scenes/_Router/GalleryRedirect.tsx

The dependency array in `GalleryRedirect` was causing significant and unnecessary redirects, in turn causing a flood of network requests in certain scenarios
_Before_
_After_

Fix overactive redirects in GalleryRedirect

---

apps/web/src/contexts/globalLayout/GlobalNavbar/CollectionNavbar/CollectionRightContent.tsx
apps/web/src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
apps/web/src/scenes/CollectionGalleryPage/CollectionGalleryPage.tsx

Certain sequences would land the user on the old editor (e.g. clicking "Edit Collection" directly from a collection-focused page)

Prevent navigating to old editor

---

apps/web/src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdown.tsx

Today the nav dropdown opens upon hovering on the "G" icon. On mobile the dropdown doesn't open because you can't hover. 
This PR updates the behavior so that on touch screen devices, the dropdown opens by clicking (tapping) on the "G" icon. 
In summary: 
On Desktop:
- Hover on "G" to open dropdown
- Click on "G"to navigate to homepage
On Mobile:
- Click on "G"to open dropdown
- There won't be a shortcut to navigate to the homepage. You can still click on "Home" in the dropdown for the same result.
Before
https://user-images.githubusercontent.com/80802871/217223083-c8beb9d3-97f8-47b0-a788-7d2c9ea90b92.mp4
After
https://user-images.githubusercontent.com/80802871/217223065-82fbd50d-1585-48ae-8c43-49671deabff5.mp4

On mobile, open dropdown on click

---

apps/web/src/components/Email/EmailForm.tsx
apps/web/src/components/WalletSelector/multichain/MagicLinkLogin.tsx
apps/web/src/components/core/Input/Input.tsx

iOS automatically zooms in on an input if the font size is < 16px. 
This made signing in via email a bit annoying because the screen zoomed in immediately after clicking the "Email" option.
The Fix: changes input font size from 14px to 16px on mobile
I also made a new styled component, SlimInput that we can share between the Magic Link input and the "Set your email" input 
Before:
https://user-images.githubusercontent.com/80802871/217430335-2be47576-658b-4733-a70d-5251f2db9568.mp4
After:
https://user-images.githubusercontent.com/80802871/217430364-ac9d2ace-885f-43c6-86f7-364e4d246079.mp4
Verification that the new styled component works in the Set Your Email Input  too

increase input font size on mobile to prevent auto-zoom

---

apps/web/src/components/GalleryEditor/CollectionSidebar/CollectionSidebar.tsx

Previous url was our internal link so it didn't directly go to the public version and showed this instead:
New url is the public url so it goes directly to the help article.

update notion help article link

---

apps/web/src/contexts/globalLayout/GlobalNavbar/ProfileDropdown/ProfileDropdown.tsx

this is a follow up to #1321  (on mobile, tapping "G" should open nav dropdown instead of navigating home")
On mobile if a user is signed out, there's no dropdown for them to open, so tapping "G" should navigate them home

clicking on G logo should navigate home for non-authed users on mobile

---

apps/web/src/components/Feed/Socialize/AdmireButton.tsx
apps/web/src/components/Feed/Socialize/CommentBox/CommentBoxIcon.tsx
apps/web/src/components/Follow/FollowButton.tsx
apps/web/src/components/WalletSelector/WalletSelector.tsx
apps/web/src/components/WalletSelector/multichain/MultichainWalletSelector.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/HomeNavbar/HomeNavbar.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/SignInButton.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/SignUpButton.tsx
apps/web/src/hooks/useAuthModal.tsx
apps/web/src/scenes/MerchStorePage/MerchStorePage.tsx
apps/web/src/scenes/Modals/useOpenSettingsModal.tsx

This PR adds a Sign Up button next to the Sign In button on the home page.
It also makes it possible to show slightly different content on the auth modal depending on whether its sign up vs sign in, like showing the Email Sign In option, and showing custom text.
- Add a Sign Up button to home nav
- Add `authType` to `AuthModal` to display different content based on sign in vs sign up
- don't show Magic Link option if sign up, because it's only for existing users
- show different subheadings that are appropriate for each flow to improve user friendliness
-`authType` doesn't affect flow logic, just the content of the modal. If an existing user connects their wallet via the "Sign Up" modal, they'll still be able to sign in (this is existing behavior)
- Defaults to "Sign In", so other places …

add sign up button next to sign in button

---

apps/mobile/App.tsx
apps/mobile/babel.config.js
apps/mobile/index.ts
apps/mobile/moon.yml
apps/mobile/package.json
apps/mobile/src/contexts/relay/RelayProvider.tsx
apps/web/moon.yml
packages/shared/moon.yml
packages/shared/package.json
packages/shared/src/relay/deferNetwork.ts
packages/shared/src/relay/network.ts
packages/shared/src/relay/subscription.ts
packages/shared/src/relay/utils.ts
schema.graphql
yarn.lock

The goal of this PR is to enable support for the `@defer` directive on mobile. 
- I've completely separated this new network layer from the web one to make sure web stays stable until we've figured this out.
- I've manually tested this about 1000x locally to make sure things work
- Automatic persisted queries still work.
React Native does not support streaming responses out of the box. To get this to work I had to add a few polyfills. You can read more about that [here](https://github.com/acostalima/react-native-polyfill-globals).
The `fetch-multipart-graphql` library does a lot of the heavy lifting for us to actualy parse the streaming bytes of the response and turn them into streaming objects which we can use to send to Relay.
It's really hard to see but if you look closely, `b_ez_man` …

Setup GraphQL Defer support on mobile

---

apps/web/src/components/Featured/Featured.tsx
apps/web/src/components/Featured/FeaturedList.tsx
apps/web/src/components/Featured/FeaturedPopoverList.tsx
apps/web/src/components/Featured/FeaturedSection.tsx
apps/web/src/components/Featured/FeaturedUserCard.tsx
apps/web/src/components/Featured/SuggestedSection.tsx
apps/web/src/components/Featured/TrendingSection.tsx
apps/web/src/components/core/Input/FadedInput.tsx
schema.graphql

This PR adds a Suggested Users section to the Featured Page.
This re-purposes the Featured Section that are currently displayed on the page, with a different list of users. 
It also introduces a "See All" button that opens a popover listing the users in vertical list format.
The backend changes ([PR](https://github.com/gallery-so/go-gallery/pull/811)) should be merged and deployed first.
TODOs

Add Suggested Users section to Featured Page

---

apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarNftIcon.tsx
apps/web/src/contexts/NftErrorContext.tsx
apps/web/src/hooks/api/tokens/useSyncTokens.ts

The `NftErrorContext` state is stale after a sync / refresh. This ensures that the state gets reset after a failure.

Clear token error after sync

---

apps/web/src/scenes/MintPages/MementosPage.tsx

Fixes a small visual issue with the Mementos Mint button where the button was hyuge on Safari
Before
After
Regression check on mobile ✅

fix mint button dimensions for safari

---

apps/web/src/scenes/MintPages/MementosPage.tsx

memento image on the mint page was busted 
before:
after:

fix memento image size

---

apps/mobile/moon.yml
packages/shared/src/relay/deferNetwork.ts
relay.config.js

It seems like the Metro bundler is not doing a good job of reloading the `persisted_queries.json` file and causes a bunch of annoying errors while development. For now, we'll just disable it.

Disable APQ on mobile

---

apps/mobile/package.json
apps/web/moon.yml
apps/web/package.json
yarn.lock

We were using `concurrently` to run our dev processes in parallel before. I only just recently found out that we can leverage Moon to do this. Mobile was already switched in another PR
This will fix the bugs we had with multiple processes trying to touch the `tsconfig.json` at once.

Switch to Moon for parallel dev processes

---

apps/web/src/components/GalleryEditor/CollectionSidebar/CollectionListItem.tsx
apps/web/src/components/NftGallery/NftGallery.tsx
apps/web/src/utils/collectionLayout.test.ts
apps/web/src/utils/collectionLayout.ts

HAHAHAHAHHAHAHAHAHHA
Okay, so we were using a map to store the parsed collection layout (not sure why). As it turns out, when we iterate over this using `Object.entries`, the key order in which we inserted into the object is not always preserved. See [thread here](https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order).
I switched the parsing function to just return a list since we have no use case for the map
Also fixed some text wrapping

Fix flaky ordering of sections

---

apps/web/src/components/ManageWallets/ManageWalletsRow.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/AnimatedSidebarDrawer.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/GlobalSidebar.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/SidebarDrawerContext.tsx

This PR fixes issues with the Left Hand Nav on mobile devices.
Before
After (url bar expanded)
After (url bar minimized)
View Notifications screen (shows height is ok when the drawer content is less than view height)
The `overscroll-behavior: contain;` property on the drawer content prevents scroll if the drawer was scrollable, but has no effect if the content is not scrollable. for example the header and footer areas of the drawer, or if the drawer content is not tall. This led to unpleasant scroll behavior, causing seemingly random scrolling (and elastic scrolling on iOS) depending on where you happened to touch.
Added `overflow:hidden` to `body` if drawer is open. This provides a small improvement in preventing unnecessary scroll. It's not perfect since you can still trigger the …

Left Hand Nav - mobile improvements + fixes

---

apps/web/src/components/Feed/Events/CollectorsNoteAddedToTokenFeedEvent.tsx
apps/web/src/components/Feed/Events/FeedEventNftPreviewWrapper.tsx
apps/web/src/scenes/NftDetailPage/NftDetailAsset.test.tsx
apps/web/src/scenes/NftDetailPage/NftDetailPage.tsx
apps/web/src/scenes/NftDetailPage/NftDetailView.tsx

Instead of including the NftDetailView's data as a part of the main request, we just split it off into its own when the user clicks on the preview.

Add back nft detail modal w/o blocking feed page

---

apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx

The notifications unread dot wasn't appearing, even when there were unread notifications.
Just needed to pass the unread prop into the icon component.
https://user-images.githubusercontent.com/80802871/223298045-faf045e2-fabd-4e24-bbec-c0adaf048390.mp4

fix notifications dot for lhn

---

apps/web/src/scenes/UserGalleryPage/UserGalleryCollection.tsx
apps/web/src/utils/baseUrl.ts

`baseUrl` isn't working as expected on prod, and causes the link copied by the Share button to have localhost instead of gallery.so
getting the baseurl from the next env vars didn't seem to be working as expected on deployed environments, so this is a temp solution to use window.origin until we figure out why

GAL-2507 temp fix for baseurl

---

apps/web/pages/[username]/activity.tsx
apps/web/pages/[username]/index.tsx
apps/web/pages/_app.tsx
apps/web/pages/latest/index.tsx
apps/web/pages/trending.tsx
apps/web/src/components/Notifications/notifications/SomeoneViewedYourGallery.test.tsx
apps/web/src/contexts/AppProvider.tsx
apps/web/src/contexts/auth/AuthContext.tsx
apps/web/src/contexts/globalLayout/GlobalLayoutContext.tsx
apps/web/src/scenes/NftDetailPage/NftDetailAsset.test.tsx
apps/web/src/types/PageComponentPreloadQuery.ts
apps/web/tests/graphql/MockAppProvider.tsx
apps/web/tests/graphql/mockAuthContextQuery.ts
apps/web/tests/graphql/mockProviderQueries.ts
apps/web/tsconfig.json
package.json
yarn.lock

I haven't quite figured out what was causing the duplicate queries to happen earlier but this definitely fixes it.
Preloaded Queries are Relay's solution to the problem we had before with waterfalls. I'm pretty sure my original solution was relying on a race condition to work. With Preloaded Queries, we'll definitely never run into this problem again.
The code behind this is quite annoying (it's the same as what we were doing before). I want to callout that all of this nonsense should get better with the new Next.js app directory stuff.
1. Start loading query
2. Get reference to this preloaded query
3. Pass that reference to the page  / component that needs it
4. That component now does `usePreloadedQuery`.
No room for race conditions here, very transparently passing around a reference to …

Switch to Relay's supported preloaded query pattern to fix dedupes.

---

apps/web/src/contexts/modal/ModalContext.tsx

This PR fixes an issue where after clicking Sign In, the contents of the global nav shifted right.
Before
After
desktop
https://user-images.githubusercontent.com/80802871/223702897-ff5b8bca-ab4c-4839-8ca9-65387ef85a05.mp4
mobile
The fix removes a line of code that is related to the banner width, so attaching a screenshot confirming that the banner still looks good post-change

fix nav shift

---

apps/web/src/components/Explore/ExploreUserCard.tsx

Changes are based on discussion around replacing collection # with bio on Explore page user cards.
Bio is truncated to one line to visually balance cards with and without bios.
before
after

Show bio instead of collection # in Explore page user cards

---

apps/web/src/scenes/CommunityPage/CommunityPageView.tsx

This PR adds the contract address to the community page so that it's easier for the user to verify that the community page they're viewing is for the contract they expect.
For now, we show the address and link to the appropriate explorer (etherscan / tzkt) depending on chain. We won't show a link for POAP since Poap's website uses an event ID instead of contract name/address, so we can add that as a follow up.
Ethereum: (with description)
Tezos: (without description)
POAP
don't show anything
Looks good on mobile

show address on community page

---

apps/web/src/components/Feed/Events/FeedEventNftPreviewWrapper.tsx
apps/web/src/components/Feed/Socialize/Interactions.tsx
apps/web/src/components/NftFailureFallback/NftFailureFallback.tsx

**Changes**
- Refresh button not clickable from feed & shouldn't redirect to collection page
- Broken NFT state looks too big on mobile feed
**Refresh button not clickable from feed**
**Before**
https://user-images.githubusercontent.com/4480258/225192756-20b3a4a3-a8b2-4d93-b2ae-07edddfaa225.mp4
**After**
https://user-images.githubusercontent.com/4480258/225192789-6d4a9e8d-7969-41b4-8edc-8f1d5e0c011d.mp4
**Broken NFT state looks too big on mobile feed**
**Before**
**After**

[GAL-2492] [GAL-1150] Fix failed NFT on Feed

---

apps/web/src/components/Settings/Settings.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx

- Remove "Done" footer from Settings sidebar drawer
- fix Search icon button so that clicking it when Search is open, closes the drawer
before: (settings)
after: (settings)

Remove done footer from settings and make Search closable when clicking the icon

---

apps/web/src/components/core/Markdown/Link.tsx
apps/web/src/components/core/Markdown/MarkdownShortcuts.test.tsx
apps/web/src/components/core/TextArea/TextArea.tsx

This PR fixes 2 bugs with the markdown text editor - specifically the link functionality.
**Bug 1: Pasting a link into the text editor deletes text that follows** [GAL-2619](https://linear.app/galleryso/issue/GAL-2619/pasting-a-link-into-the-text-editor-deletes-text-that-follows)
before
https://user-images.githubusercontent.com/80802871/225652221-660789bc-4ecf-4010-a9cd-456f03c840df.mp4
after
https://user-images.githubusercontent.com/80802871/225652264-859de658-d464-4b22-a555-ca30ac7b2637.mp4
**Bug 2: Pasting a link into the url portion of the markdown format** []() adds more markdown [GAL-2620](https://linear.app/galleryso/issue/GAL-2620/pasting-a-link-into-the-url-portion-of-the-markdown-format-[]-adds)
before
https://user-images.githubusercontent.com/80802871/225652335-3d8d5266-7804-427 …

[GAL-2619] [GAL-2620] fix paste link bugs

---

apps/web/pages/community/[contractAddress]/index.tsx
apps/web/src/scenes/CommunityPage/CommunityPageDisabled.tsx
apps/web/src/scenes/CommunityPage/CommunityPageView.tsx
apps/web/src/utils/getCommunityUrlForToken.ts

We currently automatically redirect home from the community page if the contract is in the disabled list.
We disable umbrella contracts since we don't support sub collections yet.
Since we're surfacing the community page in more places now, the redirect leads to a poor+confusing experience. instead of disabling the page entirely, we'll show a message informing the user the page isn't available yet.

add special msg for community page for disabled contracts

---

apps/mobile/src/components/Feed/CollectionCreatedFeedEvent.tsx
apps/mobile/src/components/Feed/CollectionUpdatedFeedEvent.tsx
apps/mobile/src/components/Feed/CollectorsNoteAddedToCollectionFeedEvent.tsx
apps/mobile/src/components/Feed/EventTokenGrid.tsx
apps/mobile/src/components/Feed/FeedListItem.tsx
apps/mobile/src/components/Feed/GalleryUpdatedFeedEvent.tsx
apps/mobile/src/components/Feed/NonRecursiveFeedListItem.tsx
apps/mobile/src/components/Feed/TokensAddedToCollectionFeedEvent.tsx
apps/mobile/src/components/NftPreview.tsx

We just want to make sure that images that are actually showing as you scroll have a higher download priority than other content.

Feed Perf: Give first slide images higher download priority

---

apps/web/src/components/HoverCard/HoverCard.tsx
apps/web/src/components/HoverCard/HoverCardOnUsername.tsx
apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedCommunities.tsx
apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedFollowers.tsx
apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedInfo.tsx

This PR adds shared communities ("Also owns xyz") to the user hover cards on the feed.
It also removes the Collection Count from the card as well to reduce text, and removes the wrapping Link so that only clicking the username navigates to the bio instead of the whole card.
Before
After
The text wraps if it's longer than the card max width.
there are a few other small improvements as well:
- **let username take up as much space as possible:**
before
after
- **fit card on screen on mobile**
Before:
After

Show shared communities on user hover card

---

apps/web/src/components/HoverCard/HoverCard.tsx

title says it all
clicking the follow button if signed out will open the sign in modal, as usual

add follow button to hover card even if signed out

---

apps/web/src/contexts/analytics/AnalyticsContext.tsx

This PR enables analytics for non authed users. This is feasible because of changes to the Mixpanel pricing plans.

enable analytics events for non authed users

---

apps/web/src/components/Feed/FeedList.tsx

This PR attempts to fix an issue with the feed where returning to the feed list after it had been mounted before (ie navigating from Trending -> Latest -> Trending) results in virtualization being broken, with extra whitespace and rows not being rendered.
Before
https://user-images.githubusercontent.com/80802871/230043529-c90f3c1b-a025-4bb9-a2e3-2aa8802c1523.mp4
After
https://user-images.githubusercontent.com/80802871/230043551-731a8bcf-0d84-481a-89a9-c2c3ad23dd81.mp4

fix broken virtualization on feed

---

apps/web/src/components/GalleryEditor/GalleryEditorContext.tsx

currently, users encounter this error if they simply rearrange pieces within their gallery, i.e. perform an action that does not produce a feed event. this is a confusing experience given that **_the gallery update itself is successful_**, and the error is unnecessarily and incorrectly displayed.
this PR silences the error for now to reduce confusion; we can update this once the server returns a more granular error type, or doesn't return an error at all.
suggested improvements:
1. don't return an error to the client if a gallery update is successful but feed event creation fails
2. if a user rearranges their pieces within a collection, a feed event _should_ be created, such as type `TokensRearrangedWithinCollection`
3. or, we could simply display a `gallery updated` event with the …

Silence unnecessary gallery update errors

---

apps/mobile/src/components/Feed/EventTokenGrid.tsx
apps/mobile/src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
apps/mobile/src/components/Feed/Events/CollectionUpdatedFeedEvent.tsx
apps/mobile/src/components/Feed/Events/CollectorsNoteAddedToCollectionFeedEvent.tsx
apps/mobile/src/components/Feed/Events/GalleryUpdatedFeedEvent.tsx
apps/mobile/src/components/Feed/Events/NonRecursiveFeedListItem.tsx
apps/mobile/src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
apps/mobile/src/components/Feed/FeedListCollectorsNote.tsx
apps/mobile/src/components/Markdown.tsx

- Make sure each slide is a consistent height
- We can't use a virtualized list for the carousel if we want to do this since the height of the carousel has to be max(...allSlides)
- This is fine since there aren't many slides per feed event
- Center images if there is extra height
- Implement line clamp for the `Markdown` component. This is a little weird, but it turned out great. Basically we have to override the underlying text component for the `textgroup` rule. **I also made it expandable with a tap. Watch the video to see**.
| <video src="https://user-images.githubusercontent.com/6754223/230481985-24596a4e-bdb2-49a2-a785-f35561bf2218.mp4" /> | <video src="https://user-images.githubusercontent.com/6754223/230481999-7ee6ad4a-64f8-43eb-a4d9-abac1387 …

Some Feed Carousel Polish

---

apps/mobile/src/components/Feed/EventTokenGrid.tsx
apps/mobile/src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
apps/mobile/src/components/Feed/Events/CollectionUpdatedFeedEvent.tsx
apps/mobile/src/components/Feed/Events/CollectorsNoteAddedToCollectionFeedEvent.tsx
apps/mobile/src/components/Feed/Events/GalleryUpdatedFeedEvent.tsx
apps/mobile/src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
apps/mobile/src/components/Feed/FeedListCollectorsNote.tsx
apps/mobile/src/components/Markdown.tsx
apps/mobile/src/components/NftPreview/NftPreview.tsx
apps/mobile/src/components/NftPreview/NftPreviewContextMenuPopup.tsx
apps/mobile/src/screens/HomeScreen/LatestScreen.tsx

- Make sure images in carousel fill the height of other slides
- Make height a little bit more predictable based on the layout mode we're in (2x2, 1x2, 1x1)
- Use higher quality images as requested by @Robinnnnn 
- Fix where we were trying to load more even if we reached the end of the feed
- Lock the scroll direction to horizontal so you can't move your finger up or down while scrolling between slides in a carousel
- Lower # of lines in Markdown to 2 on the feed
- Disable expandable markdown for now
- Fix crash GAL-2795
- Fix text clipping GAL-2794
There's a quirk with clamping line count w/ markdown. I think we could solve this but it would involve a lot of AST traversal / modification. Native isn't as cool as web on this front, you can only line clamp a single text element. When the …

Some more feed polish GAL-2795 GAL-2794

---

apps/mobile/src/components/Feed/FeedList.tsx
apps/mobile/src/navigation/FeedTabNavigator/TabBar.tsx
apps/mobile/src/navigation/MainTabNavigator/TabBar.tsx

Users expect to scroll to the top of the primary scrollable view if they press the tab item of the current route. Had to update a few things so we emit the right events to react navigation when we press a tab item, but all is good and works.

Scroll to top when navigating to current route

---

apps/mobile/src/components/Markdown.tsx

We were wasting perf here by creating these options every render. Search tab feels noticeably better.

Only create MarkdownIt options once

---

apps/mobile/src/components/Feed/EventTokenGrid.tsx

using width 50% and height 50% does not account for the gap between the columns / rows. using flex grow resolves this.
Refactor: The layout logic of the `EventTokenGrid` component in the mobile app's `Feed` section has been modified to improve responsiveness.
> "Fixed width no more, flex-grow takes the floor. Mobile app's Feed, now responsive galore!" 🎉📱

fix overflow on event token grid

---

apps/mobile/package.json
apps/web/package.json
package.json
yarn.lock

stable release! you can read the release notes here https://github.com/moonrepo/moon/releases/tag/v1.0.0
there have been a few releases since 1.0.0, and we're on the latest, but I figured I'd post the 1.0.0 release.

upgrade moon

---

apps/mobile/src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
apps/mobile/src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
apps/mobile/src/components/Feed/FeedListCaption.tsx
apps/mobile/src/components/Feed/FeedListSectionHeader.tsx
apps/mobile/src/components/FollowButton.tsx
apps/mobile/src/components/Pill.tsx
apps/mobile/src/components/ProfileView/ProfileView.tsx
apps/mobile/src/components/Trending/TrendingUserCard.tsx

Miscellaneous design polish items
- add width prop to FollowButton to so it can be fixed or grow  (follow button expands to fit parent on Explore page user cards)
- fixed FollowButton dark mode styling
- increased feed event text to 14px for better readability and consistency with other screens
- dimmed Twitter pill border on dark mode
- updated feed caption styling to match design
Screenshots
FollowButton
Before
After
Caption 
Before
AFter
Feed font
Before
After
Twitter pill
before
After

mobile style polish

---

apps/web/pages/mobile.tsx
apps/web/src/components/ManageWallets/ManageWallets.tsx
apps/web/src/components/ManageWallets/ManageWalletsRow.tsx
apps/web/src/components/Settings/ManageAccountsSection/ManageAccountsSection.tsx
apps/web/src/components/Settings/ManageEmailSection/ManageEmailSection.tsx
apps/web/src/components/Settings/ManageTwitterSection/ManageTwitterSection.tsx
apps/web/src/components/Settings/MembersClubSection/MembersClubSection.tsx
apps/web/src/components/Settings/MobileAuthManagerSection/MobileAuthManagerSection.tsx
apps/web/src/components/Settings/Settings.tsx
apps/web/src/components/Twitter/useOpenTwitterFollowingModal.tsx
apps/web/src/utils/graphql/isFeatureEnabled.tsx

https://www.loom.com/looms/videos/eng-0cd39ddabd44498398778ac306f0ac43
New Feature: Several new components were added to the web app, including `Mobile`, `ManageAccountsSection`, `ManageEmailSection`, `ManageTwitterSection`, `MembersClubSection`, and `MobileAuthManagerSection`. The `Settings` component underwent significant changes, including the removal of email notification settings and the addition of a mobile authentication manager section. Minor updates were made to other components.
> A web app sprouts new features,
> Mobile, Twitter, and more creatures.
> Manage wallets with ease,
> And join the club, if you please.
> With GraphQL and OpenSea,
> This PR is quite a spree!
Release Notes:
- New Feature: Added components that use `react-relay` to fetch data and render a sidebar with a …

Settings sidebar refactor, prep mobile sign-in

---

apps/web/graphql.config.js
apps/web/src/components/GalleryEditor/CollectionEditor/SortableStagedNft.tsx
apps/web/src/components/GalleryEditor/CollectionEditor/StagedItemDragging.tsx
apps/web/src/components/GalleryEditor/CollectionEditor/StagedNftImage.tsx
apps/web/src/components/GalleryEditor/CollectionEditor/StagedNftImageDragging.tsx
apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarNftIcon.tsx
apps/web/src/components/NftFailureFallback/NftFailureFallback.tsx
apps/web/src/components/NftPreview/NftPreview.tsx
apps/web/src/components/NftPreview/NftPreviewAsset.tsx
apps/web/src/scenes/NftDetailPage/NftDetailAsset.test.tsx
apps/web/src/scenes/NftDetailPage/NftDetailAsset.tsx
apps/web/src/scenes/NftDetailPage/NftDetailImage.tsx
apps/web/src/scenes/TokenDetailPage/TokenDetailAsset.tsx
graphql.config.yml

- Right now the backend only gives us the fallback media if the backend thinks the optimistic media is broken. I though the whole point of this was to handle cases the backend is unable to realize is broken. I had to change this backend logic locally to test this out.
- tokenPreviews on a Gallery or GalleryUser should use the fallback media, but I can't do anything about it since I only have access to the `TokenPreview`
Throughout the video, you'll see that the green token is being rendered. This is the fallback media provided by the backend. 
**In the gallery token preview part, you'll see a broken image. Re-read the follow up section of this PR to see why that is**
https://user-images.githubusercontent.com/6754223/236078349-659344ee-cbc3-4301-aa24-5c84ddf82cf8.mov
We now have two layers …

Use fallbackMedia as a fallback

---

apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarNftIcon.tsx

This PR allows NFTs with fallback media to be added to collections. Currently they can't be clicked in the sidebar, which is confusing to the user.
A user reported they couldn't add certain NFTs from the sidebar to their collection, and it was because those were displaying fallback media without the onClick handler.
Haven't thought deeply about the implications of this for different types of fallback media as listed in #1519 so will only merge after ok from terence/eng team
Before
https://user-images.githubusercontent.com/80802871/236385298-d1a3ef01-2387-421b-aab4-daf7fe148c10.mp4
After
https://user-images.githubusercontent.com/80802871/236385310-39c0323a-fae7-4af0-936b-2c21b52a352a.mp4

Enable nfts with fallback media to be added to collections

---

apps/mobile/src/screens/HomeScreen/TrendingScreen.tsx

The goal here is to show the `global` feed after the API has no more `trending` events.

Show global events after no more trending on trending screen

---

apps/mobile/src/components/Feed/Events/UserFollowedUsersFeedEvent.tsx
apps/mobile/src/components/Feed/Socialize/FeedEventSocializeSection.tsx
apps/mobile/src/components/Feed/createVirtualizedFeedEventItems.ts
apps/mobile/src/screens/HomeScreen/LatestScreen.tsx
apps/mobile/src/screens/HomeScreen/TrendingScreen.tsx

Putting the load more in an effect was really dumb without any extra safe guards. This fixes it by making sure we only load more on first mount.
I also removed this optimization from the trending screen since that isn't as critical for first load and will likely have worse performance since we're updating the list items more than once.
I also fixed a bug where we were only rendering GalleryUpdated events, now we actually render follow events so I had to make those presentable as well.

Fix Load Infinite Loop

---

apps/mobile/src/screens/AccountScreen.tsx
apps/mobile/src/screens/Login/EnterEmailScreen.tsx
apps/mobile/src/screens/NotificationsScreen.tsx

Relay being too smart here. It knows there's a `null` viewer in the store from the first load (since we're not logged in). After we log in, it's like "Right the viewer is null so let's use that until the network request has actually finished". 
We DO NOT want that to happen. We want full network only for the top level screens that use viewer data.

Fix bug w/ login having stale data

---

apps/mobile/src/components/ProfileView/ProfileView.tsx

I think there's some bugs in the library we're using with the `revealHeaderOnScroll` prop. For now I've disabled it.

[GAL-2981] remove revealHeaderOnScroll since it causes scrolling issues

---

apps/mobile/src/screens/NftDetailScreen/NftDetailAsset/NftDetailAsset.tsx

Since we're making the decision to use imgix urls for the NftDetail screen, we can just re-use the existing code we have to handle fallbacks.

Handle fallback on NFT Detail screen

---

apps/web/src/components/Announcement/AnnouncementList.tsx
apps/web/src/utils/graphql/experiences/useUpdateUserExperience.tsx

Currently, the only way to dismiss an announcement – and get rid of the blue dot in the sidebar – is by actively clicking on the announcement and going to its CTA.
This may be annoying for new users who see a bunch of notifications especially as our announcements grow over time.

Dismiss announcement notifications when moving away from panel

---

apps/mobile/src/components/Feed/Events/CollectionUpdatedFeedEvent.tsx
apps/mobile/src/components/Feed/Events/CollectorsNoteAddedToCollectionFeedEvent.tsx
apps/mobile/src/components/ProfileView/ProfileTabBar.tsx
apps/mobile/src/navigation/MainTabNavigator/MainTabNavigator.tsx

- reorder main tabs 
- reduce gallery+follower count font size
- fix typo in collectors note feed event + adjust size ("colloctors" -> "collector's")
New order of tabs
Home, Search, Notifications, Profile. this order was agreed upon in slack a few days back
Before (gallery+follower count font size)
After (gallery+follower count font size)

Misc Mobile Fixes

---

apps/mobile/src/navigation/FeedTabNavigator/FeedTabNavigator.tsx
apps/mobile/src/navigation/MainTabNavigator/MainTabNavigator.tsx

This bug is ruining us https://github.com/satya164/react-native-tab-view/issues/1181
Disabling animations feels better and solves the problem described in GAL-2816.

[GAL-2816] Disable animations on tab navigators

---

apps/mobile/app.config.ts

I forgot to make the environment variable file lookup relative to the `app.config.ts`. By default the look up is relative to the CWD (who knows what that might be in Expo land especially since we're in a monorepo).

Fix expo builds

---

apps/mobile/src/components/Markdown.tsx

**Changes**
- Fix markdown text didn't update on theme switcher (dark -> light)
**Demo**
**Before**
https://github.com/gallery-so/gallery/assets/4480258/c30f1eda-7f92-4a3a-b05e-fabbffd4527c
**After**
https://github.com/gallery-so/gallery/assets/4480258/ccb1bcc1-4f07-4355-b6d0-cedd1ea24b85

[GAL-3076] Fix search text color on theme switch

---

apps/mobile/src/components/BackButton.tsx
apps/mobile/src/components/ProfileView/GalleryProfileNavBar.tsx
apps/mobile/src/components/ProfileView/ProfileView.tsx
apps/mobile/src/components/ProfileView/ProfileViewFallback.tsx
apps/mobile/src/components/ProfileView/ProfileViewHeader.tsx
apps/mobile/src/components/ProfileView/Tabs/ProfileViewActivityTab.tsx
apps/mobile/src/components/ProfileView/Tabs/ProfileViewFeaturedTab.tsx
apps/mobile/src/components/ProfileView/Tabs/ProfileViewFollowersTab.tsx
apps/mobile/src/components/ProfileView/Tabs/ProfileViewGalleriesTab.tsx
apps/mobile/src/screens/CollectionScreen/CollectionScreenFallback.tsx
apps/mobile/src/screens/FeedEventScreen.tsx
apps/mobile/src/screens/GalleryScreen/GalleryScreenFallback.tsx
apps/mobile/src/screens/NftDetailScreen/LoadingNftDetailScreenInner.tsx
apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx
apps/mobile/src/screens/ProfileScreen/ProfileScreen.tsx

Watch this video first https://www.loom.com/share/2eaa9312162345b9b508e9b5777d2ed9 
| Profile | Gallery |
| <video src="https://github.com/gallery-so/gallery/assets/6754223/f685ac47-70f0-42c2-9673-f9abbf68abca" /> | <video src="https://github.com/gallery-so/gallery/assets/6754223/5b76b0bb-85d2-41a4-ac9a-ed9a5af4c233" /> | 
| Collection | Feed Event |
| <video src="https://github.com/gallery-so/gallery/assets/6754223/4c540c2a-0cd8-4c3f-9d04-83c014b9dac8" /> | <video src="https://github.com/gallery-so/gallery/assets/6754223/0c51b104-403e-4456-9824-a4ec418e797f" /> | 
- I updated all of the fallbacks to have a back button in them when appropriate.
- How do we achieve super granular loading states? 
- Make components closer to the leaves suspend instead …

[GAL-2957] Show back buttons when screen is loading

---

apps/mobile/src/components/Feed/EventTokenGrid.tsx

Instead of marking the event as a failure, we just show it with a failed token.

support failed tokens on event token grid

---

apps/mobile/src/components/Notification/NotificationList.tsx
apps/mobile/src/components/Notification/NotificationRegistrar.tsx
apps/mobile/src/hooks/useMobileClearNotifications.ts
packages/shared/src/relay/useClearNotifications.tsx

- I updated `useClearNotifications` to expose the underlying `clearNotifications` function so we could re-use it on mobile w/o relying on the hook.
- Now mobile has a `useMobileClearNotifications` which does what web does, but also calls `setBadgeCount(0)`
- I also updated the `NotificationList` to clear your notifications right away since that seems more like what the user would expect.
https://github.com/gallery-so/gallery/assets/6754223/85a4d8ed-468e-4e5c-baca-753d7c9d2864

[GAL-3089] Clear Notification Count

---

apps/mobile/src/components/NftPreview/NftPreview.tsx
apps/mobile/src/components/NftPreview/NftPreviewContextMenuPopup.tsx
apps/mobile/src/navigation/types.ts
apps/mobile/src/screens/NftDetailScreen/NftDetailAsset/NftDetailAsset.tsx
apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx
apps/mobile/src/utils/shareToken.ts

Okay back story
- The web nft detail page requires the collection id since we let you slide between pieces in a collection.
- Since we have a share button on mobile that links to the web version, I thought it would make sense to thread down a `CollectionToken` type and not allow navigation if there wasn't a collection id.
- Sometimes, a feed event token's collection no longer exists, which means we couldn't navigate to the nft detail screen as it required a `collectionId`
Now we just optionally require a collectionId, and the Share button just doesn't work if there's not a collection associated w/ the token.
Tested by setting the resolver on the backend to always return `nil` for the collection and observed that the nft detail and popup menu still work as expected.

Handle missing collection on NftDetail screen more gracefully

---

apps/web/src/scenes/NftDetailPage/NftDetailAudio.tsx

Not sure when this stopped working but we're using `preload="none"` on the audio tag which tells the page it doesn't have to start loading the audio file. This means `onLoad` will never get called, which means the shimmer will never go away.
If we want `preload="none"`, then my changes are chill, I just use the image asset for the `onLoad` part.

Fix Audio NFT Detail Page

---

apps/mobile/src/components/Feed/Socialize/AdmireLine.tsx
apps/mobile/src/components/Feed/Socialize/CommentLine.tsx
apps/mobile/src/components/Feed/Socialize/NotesModal/AdmireNote.tsx
apps/mobile/src/components/Feed/Socialize/NotesModal/CommentNote.tsx
apps/mobile/src/components/GalleryBottomSheet/GalleryBottomSheetModal.tsx
apps/mobile/src/components/UsernameDisplay.tsx

**Changes**
1. Make the username in the feed clickable
2. Username in comment/admire in the Notes modal clickable
**Demo**
**Feed**
https://github.com/gallery-so/gallery/assets/4480258/0fde635f-16df-442f-9519-5108c4335ae6
**Notes Modal**
https://github.com/gallery-so/gallery/assets/4480258/f1d46104-7cb8-4998-aa52-88ef17bb5fcb
**Pending**

[GAL-3170] Make usernames on admires + comments tappable

---

apps/mobile/src/navigation/MainTabNavigator/TabBar.tsx

**I'm leaving out the color palette changes so we can land that in one go. I don't want the app to feel fragmented**
- Add top border to footer
- remove opacity from inactive icons to improve visibility
- include "pressed" state, which is different from "active" state. in the figma, you can toggle the "Hover" state on the icon to see what this looks like. This is styling that is visible when you're pressing the icon.
- update colors, (dark mode has slightly update palette)
| Light | Dark |
| <video src="https://github.com/gallery-so/gallery/assets/6754223/5acc8f3c-3eaa-423d-91a3-3e11ff47a889" /> | <video src="https://github.com/gallery-so/gallery/assets/6754223/d6df93ac-1afa-4a86-bd92-2e6cb5a5978a" /> |

[GAL-3168] Update Footer styling

---

apps/web/pages/opengraph/user/[username].tsx

**Problem**
In this case, the first gallery in the **lau** profile is empty. Previously, we always select the first gallery to show in the OG image. 
Solved it just by filter the non empty gallery. 
**Demo**
**Before**
**After**

Fix OG Image on Empty Gallery

---

apps/mobile/src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
apps/mobile/src/components/Feed/FeedListSectionHeader.tsx
apps/mobile/src/components/Markdown.tsx
apps/mobile/src/components/ProfileView/ProfileViewFallback.tsx

**Bug Fixes**
1. Hamsun's profile's bio is large for some reason
2. Empty lines aren't being rendered in user bio on mobile app
3. Untitled Collections show up in event descriptions as blank space instead of "their collection"
4. Left align username on profiles in loading state skeleton
**Demo**
**Hamsun's profile's bio is large for some reason**
| ![image](https://github.com/gallery-so/gallery/assets/4480258/cebf93a6-b3f4-464a-8223-2d31b569328e) | <img width="486" alt="CleanShot 2023-06-06 at 17 51 33@2x" src="https://github.com/gallery-so/gallery/assets/4480258/ab28ae8d-8657-45f6-84ee-756398cb2f9f"> |
**Empty lines aren't being rendered in user bio on mobile app**
| …

[GAL-3182] [GAL-3183] [GAL-3213] [GAL-3027] fix feed/profile bug

---

apps/web/src/components/NftPreview/NftPreview.tsx

The idea here is iframes don't know how to size themselves, so we just tell them to fill their height. The downstream `aspect-ratio: 1` property seems to be helping figure out the corresponding width from that height.
| <img width="1237" alt="Screenshot 2023-06-07 at 4 59 06 PM" src="https://github.com/gallery-so/gallery/assets/6754223/c3046d52-e5ba-41dd-81bc-6a51f032b00c"> | <img width="1237" alt="Screenshot 2023-06-07 at 4 59 00 PM" src="https://github.com/gallery-so/gallery/assets/6754223/bf615add-3990-4d3d-bec3-2394f143c69b"> |

make live rendering iframes full height

---

apps/mobile/src/components/Gallery/GalleryVirtualizedRow.tsx
apps/mobile/src/components/Notification/Notifications/SomeoneFollowedYou.tsx
apps/mobile/src/screens/SettingsScreen/SettingsScreen.tsx

**Bug Fixes**
1. stacked formatting for multiple follows notification
2. Hide collection title on mobile if no title exists
3. truncate commit hash in settings to only display first 6 characters
**Hide collection title on mobile if no title exists**
| <img alt="demo" src="https://github.com/gallery-so/gallery/assets/4480258/dc5c0152-943e-4261-9904-d23836785fe7"> | <img width="487" alt="CleanShot 2023-06-08 at 18 26 42@2x" src="https://github.com/gallery-so/gallery/assets/4480258/785efbde-0ce1-42f5-bc29-a9da7c4e9f20"> | 
**stacked formatting for multiple follows notification**
| <img width="478" alt="CleanShot 2023-06-08 at 16 22 33@2x" src="https://github.com/gallery-so/gallery/assets/4480258/c945d5ce-03ef-4702-8 …

[GAL-3184] [GAL-3225] [GAL-3226] Fix notification / collection / commit hash

---

apps/web/src/components/GalleryEditor/CollectionEditor/UnstageButton.tsx
apps/web/src/components/NftPreview/NftPreview.tsx

1. Ensure trash icon is visible on editor hover
2. fix label positioning bug

Fix NFT hover regressions

---

apps/web/src/components/GalleryEditor/CollectionEditor/LiveDisplayButton.tsx

move live display toggle to top left to avoid clashing with label
Before
After

move live display toggle to top left to avoid clashing with label

---

apps/mobile/src/components/DeepLinkRegistrar.tsx
apps/web/public/.well-known/apple-app-site-association

Turns out it's very important that the exclusions come before the catch all.

Fix deep linking exclusion priority

---

apps/mobile/src/components/SvgWebView.tsx
apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx
packages/shared/src/relay/getVideoOrImageUrlForNftPreview.ts

- we still don't support rendering these on the NFT Detail screen
- I also made SVG rendering a little bit better by consulting w/ chat gpt.
- I added a fallback view on the detail screen for when we fail (pdfs)

Support previews for PDF Media

---

graphql.config.yml
relay-extensions.graphql

The LSP didn't like that the relay extensions schema we used had a `__clientField` directive. To fix this, I copied the extensions file locally and removed that directive since we don't use it. This will keep the LSP happy for now.

add local relay extensions to stop the lsp from erroring out

---

apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarList/CollectionTitle.tsx

Previously, if a title was too long you weren't able to mark it as spam or see its token count
| <img width="250" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/76db822e-a287-4f0a-9a85-6649ee35720c"> | <img width="248" alt="Screenshot 2023-06-23 at 10 07 41 PM" src="https://github.com/gallery-so/gallery/assets/12162433/212e984d-8de2-46a5-a497-086354d2d927"> |

Fix collection title text overflow

---

apps/web/pages/[username]/activity.tsx
apps/web/pages/[username]/followers.tsx
apps/web/pages/[username]/galleries.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/CollectionNavbar/CollectionNavbar.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/CollectionNavbar/CollectionRightContent.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavLinks.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavbar.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryRightContent.tsx
apps/web/src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
apps/web/src/scenes/GalleryPage/GalleriesPage.tsx
apps/web/src/scenes/UserActivityPage/UserActivityPage.tsx
apps/web/src/scenes/UserGalleryPage/GalleryNameDescriptionHeader.tsx
apps/web/src/scenes/UserGalleryPage/GalleryTitleBreadcrumb.tsx
apps/web/src/scenes/UserGalleryPage/UserGallery.tsx
apps/web/src/scenes/UserGalleryPage/UserGalleryHeader.tsx
apps/web/src/scenes/UserGalleryPage/UserNameAndDescriptionHeader.tsx
apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedCommunities.tsx
apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedFollowers.tsx

This PR makes the profile page on mobile web look closer to the mobile app. currently they have a different layout, making it more complicated to make changes that apply to both the app and mobile web.
- this affects the Featured, Galleries, Followers, Activities tabs on a user profile. 
- It also affects the individual gallery and collection screens.
- We now display the user profile info (bio, shared communities+followers, twitter handle) on every tab on the profile like we do in the mobile app.
screenshots
each screenshot contains 3 screens: Web Before, Web After, Mobile App for comparison
User Profile screen (featured tab)
User Profile screen (galleries tab)
Gallery screen
Collection screen
bonus:
Updated copy in shared communities and followers to match mobile (removed the text "you …

Bring mobile web user profiles to parity with mobile app profiles

---

apps/web/src/components/GalleryEditor/GalleryEditor.tsx
apps/web/src/hooks/api/tokens/useSyncTokens.ts

we were previously updating the `CollectionEditorViewerFragment` cache post-sync mutation, but that is no longer high enough in the tree to update the sidebar tokens list.

Fix sync refresh

---

apps/web/src/contexts/globalLayout/GlobalLayoutContext.tsx
apps/web/tests/graphql/mockGlobalLayoutQuery.ts

Unnecessary fragment eating up a ton of resources when loading `GlobalContextQuery`

Disable global announcement query

---

apps/web/pages/onboarding/add-user-info.tsx
apps/web/src/components/Profile/EditUserInfoForm.tsx
apps/web/src/scenes/UserGalleryPage/EditUserInfoModal.tsx

**Problem**
We can't recycle the same `UserInfoForm` for both the onboarding flow and edit profile flow given that the form now requires a `viewer.user` to be present to set a PFP, as an authenticated user picks one from their tokens. The issue is a user does not yet exist at the `add-user-info` step during onboarding.
**Temp solution**
Disable PFP selection during onboarding
**Long-term solution**
Consider creating a user prior to the `add-user-info` step, at the `welcome-step`. This is harder to do though as they'd need to be given a temporary username.

Temp disable PFP selector during onboarding

---

apps/web/src/scenes/NftDetailPage/NftDetailText.tsx

now it's consistent with the feed usernames
before
after

update username link styling on nft detail page

---

apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorViewSelector.tsx

we don't expect people to set a spam nft as their pfp, so remove the Hidden option from nft selector dropdown.
only show Collected and Created.

remove Hidden filter from nft selector

---

apps/mobile/src/screens/SettingsProfileScreen.tsx

the button is disabled, so hide it entirely to prevent confusion
before
after

hide edit button on profilesettings

---

apps/web/src/contexts/modal/AnimatedModal.tsx

before
after
admire/comment modals should still be ok after this change

fix animated modal height

---

apps/web/src/components/NftSelector/groupNftSelectorCollectionsByAddress.ts
apps/web/src/components/RawProfilePicture.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/SidebarPfp.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx

show pfp in left hand nav instead of profile icon , desktop only
Before
After
(image)
(placeholder)
(feature flag off)

show pfp in left hand nav instead of profile icon

---

apps/web/pages/_app.tsx
apps/web/src/components/NftPreview/NftPreview.tsx
apps/web/src/scenes/NftDetailPage/NftDetailAnimation.tsx
apps/web/src/scenes/NftDetailPage/NftDetailAsset.tsx
apps/web/src/scenes/NftDetailPage/NftDetailModel.tsx
apps/web/src/scenes/NftDetailPage/model-viewer.css

- The `height:100%` property prevented the model from rendering correctly in the Gallery NFT Preview view
- Tossed `model.css` in favor of inline styles

GLB liverender regression fix

---

apps/mobile/src/components/Feed/Socialize/AdmireLine.tsx
apps/mobile/src/components/Feed/Socialize/Interactions.tsx

Fixes "x collectors admired this" showing the wrong number - it was maxed at 5 even if there were more admires.
Uses the total count returned by the pagination query instead of the page length.
before
after

fix x collectors admired this copy count

---

apps/mobile/src/components/ProfilePicture/ProfilePicture.tsx

we weren't showing ens pfps in the mobile app.
this change will start querying + displaying them wherever we display pfps
before
after

retrieve and display ens pfps

---

apps/web/src/components/NftSelector/NftSelector.tsx
apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorFilterNetwork.tsx
apps/web/src/components/NftSelector/NftSelectorView.tsx

Update the NFT Selector network dropdown to display options based on all the chains defined in the chains.ts file, instead of hardcoded options. This way we'll automatically show the same available chains in the NFT Selector as the Gallery Editor. 
demo of Setting an Optimism token as a pfp:
https://github.com/gallery-so/gallery/assets/80802871/9435b8f0-8a51-4acd-966f-62ecf8425f46
non admin mode:
admin mode:

make nft selector work with all our enabled chains

---

apps/web/src/components/Feed/Socialize/CommentsModal/CommentsModal.tsx

The bug happens on the long comment text and only have one comment in the modal.
**Demo**
**Before**
**After**

Fix comment modal height on long comment

---

apps/mobile/src/components/Community/CommunityView.tsx
apps/mobile/src/components/LinkableAddress.tsx
apps/mobile/src/components/Search/Community/CommunitySearchResult.tsx
apps/mobile/src/components/Search/SearchResult.tsx
apps/mobile/src/components/Search/SearchSection.tsx
apps/mobile/src/components/Search/User/UserSearchResult.tsx
apps/mobile/src/components/UserFollowList/UserFollowCard.tsx

- center username and bio vertically relative to pfp
- before
after
- remove underline styling from link, fix color
before
after
- name should be bold on search results, make sure gap is enough 
realized title should actually only bold the keyword match, we can address as a follow up. fixed the gap, seen in screenshot below
- decrease gap between search section label (ie “CURATORS”) and first result
before
after

ux polish around community info

---

apps/web/pages/_/components.tsx
apps/web/src/components/Feed/Socialize/AdmireLine.tsx
apps/web/src/components/Notifications/notifications/SomeoneViewedYourGallery.tsx
apps/web/src/components/Profile/EditUserInfoForm.tsx
apps/web/src/components/ProfilePicture/CommunityProfilePicture.tsx
apps/web/src/components/ProfilePicture/ProfilePicture.tsx
apps/web/src/components/ProfilePicture/ProfilePictureStack.tsx
apps/web/src/components/ProfilePicture/RawProfilePicture.tsx
apps/web/src/components/Search/Community/CommunitySearchResult.tsx
apps/web/src/components/Search/Gallery/GallerySearchResult.tsx
apps/web/src/components/Search/SearchResult.tsx
apps/web/src/components/Search/User/UserSearchResult.tsx
apps/web/src/scenes/CommunityPage/CommunityPageView.tsx
apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedFollowers.tsx

Display Community PFPs on web
Community Page 
before vs after
Search result 
before vs after

add community pfps

---

apps/web/src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetails.tsx
apps/web/src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetailsEth.tsx
apps/web/src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetailsPOAP.tsx
apps/web/src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetailsTezos.tsx
apps/web/src/scenes/NftDetailPage/NftAdditionalDetails/NftDetailsExternalLinksEth.tsx
apps/web/src/scenes/NftDetailPage/NftDetailText.tsx

Adds external link for Prohibition items - links to detail page on prohibition site.
also moves external link logic into its own component to contain all the messy custom platform specific logic. 
also removes unused `showDetails` props
after:
https://github.com/gallery-so/gallery/assets/80802871/a555b00c-50eb-40ea-a4c4-a19258a15f80
regression checks:
poap links still good
mirror links still good
other tokens still good

Add external link for Prohibition items

---

apps/web/src/components/NftPreview/NftPreview.tsx

Mainly to reduce load times on mobile web browsers

Disable liverender on mobile web

---

apps/mobile/src/components/Feed/EventTokenGrid.tsx

Title says it all.
addressing feedback that the window feels a bit tight and sometimes accidentally navigate to the NFT Detail Page instead of admiring.
it's a feel thing so we'll try 250 and see if it makes a tangible difference

bump admire double tap window from 200 to 250ms

---

apps/web/src/components/MultiGallery/Gallery.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx

- clicking on the edit icon in the sidebar now navigates user to `/user/galleries?mode=edit`
- the gallery tile component checks if the mode is set to `edit` and accordingly links either to the `gallery edit` page or the `gallery view` page
https://www.loom.com/share/51f2dd8131d34f2a972537a805abe3a0?sid=046637dd-7a97-43da-86d6-3b0b991768e8

fix edit mode regression

---

apps/web/src/components/Feed/FeedItem.tsx
apps/web/src/components/Feed/Posts/DeletePostConfirmation.tsx
apps/web/src/components/Feed/Posts/PostData.tsx
apps/web/src/components/Feed/Posts/PostDropdown.tsx
apps/web/src/components/Feed/Posts/PostNftPreview.tsx
apps/web/src/components/core/Dropdown/Dropdown.tsx
apps/web/src/components/core/Dropdown/DropdownItem.tsx
apps/web/src/hooks/api/posts/useDeletePost.ts
apps/web/src/hooks/useTokenDetailModal.tsx

Adds a dropdown menu to posts for sharing, deletion, etc
There are 2 states
**User is author of post:**
**Someone else's post:**
What deleting looks like:
https://github.com/gallery-so/gallery/assets/80802871/b6e1d1ec-5430-4498-843b-47a0c28463e9

Add dropdown menu to posts

---

apps/web/src/components/core/TextArea/TextArea.tsx

adds a faint border to the text input when active, and a red border when there's an error

add focus outline to composer input

---

apps/web/src/components/Feed/Posts/PostDropdown.tsx

forgot to add copy to clipboard functionality for posts not owned by viewer

add share handler for other posts

---

apps/web/src/components/Pill.tsx
apps/web/src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetailsTezos.tsx
apps/web/src/scenes/NftDetailPage/NftAdditionalDetails/NftDetailsExternalLinksEth.tsx
apps/web/src/scenes/NftDetailPage/NftDetailAsset.test.tsx
apps/web/src/utils/formatDateString.ts

change the Refresh Metadata `InteractiveLink` to a `ButtonPill` component that shows the **last refreshed timestamp** in the `ToolTip`
https://www.loom.com/share/26481b03fa5e4f8193d34a24c88fea79?sid=fc8b3c32-c734-42a9-8f91-3f845a77f9da

GAL-2990: last refreshed timestamp on NFT detail page

---

apps/web/src/hooks/api/feedEvents/useAdmireFeedEvent.ts
apps/web/src/hooks/api/feedEvents/useCommentOnFeedEvent.ts
apps/web/src/hooks/api/posts/useAdmirePost.ts
apps/web/src/hooks/api/posts/useCommentOnPost.ts

app blows up with full page error when admiring or commenting as a user without a pfp.
the cause was in the optimistic updater for the admire + comment hooks for both posts and feed events.
`const hasProfileImage = optimisticUserInfo.profileImageUrl !== null` was evaluated incorrectly because `optimisticUserInfo.profileImageUrl` was an empty string, not null, in cases where the user did not have a profile image.
fixed the hooks to evaluate this correctly 
no errors for user without pfp
https://github.com/gallery-so/gallery/assets/80802871/3cbf26b6-a7d9-497b-912c-18e298f846df
no errors for user with pfp
https://github.com/gallery-so/gallery/assets/80802871/6038deaf-0333-49f9-a8e0-2a79b71a6d15

Fix bug breaking page when admiring or commenting without pfp

---

apps/web/src/components/Notifications/Notification.tsx

New not-yet supported notification types are showing up on prod , but empty.
we should not render a notification at all if the type isn't supported yet
before
after

hide unsupported notifications on web

---

apps/web/src/components/Notifications/Notification.tsx
apps/web/src/components/Notifications/notifications/SomeoneAdmiredYourFeedEvent.tsx
apps/web/src/components/Notifications/notifications/SomeoneAdmiredYourPost.tsx
apps/web/src/components/Notifications/notifications/SomeoneCommentedOnYourFeedEvent.tsx
apps/web/src/components/Notifications/notifications/SomeoneCommentedOnYourPost.tsx
apps/web/src/components/Notifications/notifications/SomeoneFollowedYou.tsx
apps/web/src/components/Notifications/notifications/SomeoneFollowedYouBack.tsx
apps/web/src/components/Notifications/notifications/SomeoneViewedYourGallery.tsx
packages/shared/src/utils/time.ts

Adds notifications for
- someone commented on your post
- someone admired your post
also includes these related changes
- increase pfp size from sm to md for all notifications
- move unread dot from left to right of notification
- fix width of container of dot + timestamp to 35px for consistent spacing
- change "just now" to "<1m" for very new notifications, so that it fits in the fixed width container
multiple admirers in a notification
wrap text caused by long username
truncate long comments, clamp to 1 line
handling screen sizes narrower than standard notification drawer 
handling screen sizes narrower than standard notification drawer

[GAL-3928] show notifications for someone commented+admired your post

---

pull_request_template.md

This PR adds a template for PRs that will prepopulate the description field of new PRs.
The goal is to encourage a consistent format for PRs to make it easier for reviewers to understand the changes being added, and ensure the thoroughness and readiness of the PR for review.

Proposal for adding PR Template

---

apps/web/src/components/Feed/Posts/PostDropdown.tsx
apps/web/src/components/GalleryEditor/CollectionSidebar/CollectionListItem.tsx
apps/web/src/components/MultiGallery/Gallery.tsx

on web in each Post's "…" dropdown, the delete option should be red to be consistent with our styling in other places like shown below
After
can test locally

[GAL-3931] Make Delete option red

---

apps/mobile/src/screens/NftDetailScreen/UniversalNftDetailScreenInner.tsx

Remove show/hide detail link on mobile nft detail page since now we show the expanded view by default.
After: 
-Tested different chain tokens
Can check locally

[GAL-3940] Remove show/hide detail link on detail page

---

apps/web/src/components/Posts/PostComposerModal.tsx

Add a header for the Discard Confirmational modal whenever this modal is shown (from clicking back button and clicking 'x' on modal and clicking outside modal when trying to create a post)
After
can test locally

[GAL-3959] Discard modal fix

---

apps/mobile/src/screens/SettingsScreen/DebugBottomSheet.tsx
apps/mobile/src/screens/SettingsScreen/SettingsScreen.tsx

This PR adds an admin only Debug panel in the Settings tab that will show some values like the notification push token that will help with debugging issues. 
We don't need to make this feature available for general users at the moment.
new "DEBUG" tappable element in Settings for users with Admin role
tapping will open bottom sheet with the push token 
The DEBUG element and bottom sheet do not appear for non-admin users.
Go to the Settings tab

show push token for admin users

---

apps/mobile/src/components/CommunitiesList/CommunityCard.tsx
apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedCommunities.tsx
apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedCommunitiesSheet.tsx
apps/mobile/src/components/ProfileView/ProfileViewSharedInfo/ProfileViewSharedFollowers.tsx

So the problem was we were using the `length` of the `users` data returned by the `ProfileViewSharedFollowersFollowingTextFragment` query which actually paginated or lazy loaded.. That's why it was showing the false count in the first render but once you open bottom sheet and scroll, the count gets updated to the correct number. 
So what I did is just used the `totalSharedFollowers` or `totalSharedCommunities` that refers to `pageInfo.total` which actually has the total number of shared followers or communities.
https://www.loom.com/share/d5718de1d03249558df7350a63174bbb?sid=d3e18ab5-5a4c-402b-a5e5-7850501c3027
https://www.loom.com/share/e9e3511f754d4d18b86f1b56be72baf8?sid=e608cda7-5e8c-4b41-a81a-4d4ef8ac214d
N/A
Note: Since this issue only happens when you have more than 20 shared …

GAL-3892: fix shared following regression

---

apps/mobile/package.json
apps/mobile/src/navigation/MainTabStackNavigator.tsx
apps/mobile/src/navigation/types.ts
apps/mobile/src/screens/SettingsScreen/NotificationSettingsScreen.tsx
apps/mobile/src/screens/SettingsScreen/SettingsScreen.tsx
yarn.lock

This PR adds a Notification Settings screen to the Settings menu.
Currently this is an admin-only feature since we want to add a bit more design polish before making it available to all users.
The primary goal is to give a user a chance to opt in to Push Notifications if they find that they're not receiving any. These users likely fall into 2 groups
1. they've never been prompted with the Enabled Notifications native iOS prompt
2. they've seen in and denied permission / turned off push notifications since
In the first case, pressing the new Enable Push Notifications button will trigger the prompt so that they can opt in. By showing the prompt, the Gallery app will also be listed in their iOS Settings app, so that they can toggle these settings on their own later. Without seeing this …

add notification setting + prompt

---

apps/web/src/components/Posts/PostComposer.tsx
apps/web/src/hooks/api/posts/useCreatePost.ts

Expected Behaviour:
-If the backend returns any errors after the user clicks "POST", display the generic error message in the footer as per design using the existing codebase icon.
-Immediately upon clicking "POST" again, the old error message should be cleared.
When set to offline from network tab on chrome devtools, we see this general error message trying to post offline.
Error clears up after connecting to network and 'POST' is clicked again.
Tested responsiveness with different window sizes.
Can test locally on branch or preview on vercel.

[GAL-3841] Add Error State to Post Composer on web

---

apps/web/pages/[username]/followers.tsx
apps/web/src/components/Feed/Events/UserFollowedUsersFeedEvent.tsx
apps/web/src/components/Follow/FollowList.tsx
apps/web/src/components/Follow/FollowListUserItem.tsx
apps/web/src/components/Follow/FollowListUsers.tsx
apps/web/src/components/HoverCard/HoverCard.tsx

Update User Profile's Following tab layout on web to match this [design](https://www.figma.com/file/X6iIs5hnI4NO3iKC3BAmJs/PFPs?type=design&node-id=4453-12328&mode=design&t=iX2lMVq9Jjcm7QUq-0)
some [slack design context](https://galleryso.slack.com/archives/C058WRKCPR6/p1691135549158799)
Check out this [Loom](https://www.loom.com/share/0417ba1197b94fc08828fd2397a2b944)
Before: 
After: 
-truncating the bio when long so it has spacing between the bio and the follow-back button
-tested different window sizes on desktop
can check out deployment or pull down branch and test locally

[GAL-3740] Update User Profile's Following tab layout on web

---

apps/mobile/src/components/Select.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorFilterBottomSheet.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx

Added sort by filter to NFT selector
https://github.com/gallery-so/gallery/assets/4480258/dd28b302-b051-4530-b85d-c91d9402943b
- Sort by alphabet
- Tested on post and pfp screen
1. Go to nft selector through create new post / update your PFP
2. Click the filter icon
3. You should see there is filter by **network** and **sort by**

[GAL-3907] Add Sort filters to NFT Selector on mobile

---

apps/mobile/src/components/Post/PostInput.tsx

Removes auto focus from the mobile post composer input, based on feedback
https://github.com/gallery-so/gallery/assets/80802871/ddfe4be8-2cef-44bc-9f0a-4ef8beb7f7a6
N/A
Go to the post composer and notice the keyboard doesn't automatically appear when you select an NFT.

remove autofocus from mobile post composer input

---

apps/web/src/hooks/api/posts/useCreatePost.ts

This PR updates the useCreatePost hook to optimistically update the curated feed with the new post.
https://github.com/gallery-so/gallery/assets/80802871/403f198e-4e43-4c0e-83d7-50850d2db6a4
- this only handles if you're already viewing the Curated feed. and if you refresh, it'll disappear since the post won't actually be included in the curated feed provided by the backend. this is expected.
Go to /home and create a post.

GAL-3955 optimistically update curated feed with post

---

apps/mobile/src/screens/NftSelectorScreen/NftSelectorFilterBottomSheet.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx

- Auto close the bottom sheet whenever the user select any filter (network/sort)
- If there is no tokens filtered, show empty screen
**Auto close the bottom sheet whenever the user select any filter (network/sort)**
**Before**
https://github.com/gallery-so/gallery/assets/4480258/dce29242-c8ad-4f08-b713-7329b32736cd
**After**
https://github.com/gallery-so/gallery/assets/4480258/e0ca2b33-8522-4f80-9886-1c40d0e3cc47
**Empty Screen**
| ![image](https://github.com/gallery-so/gallery/assets/4480258/4ff51a38-013c-47b0-930d-041a362a057a) | <img width="457" alt="CleanShot 2023-08-16 at 10 34 56@2x" src="https://github.com/gallery-so/gallery/assets/4480258/22239829-9665-4346-97ac-d286f430dabd"> | 
1. Filter any network that you don't have any nfts
2. Filter …

[GAL-4016] [GAL-4017] Nft Selector polish filter

---

apps/web/src/components/Feed/LatestFollowingFeed.tsx

Show Posts in the following feed.
See url bar, it's showing the following feed
N/A
Go to `/latest/following` while signed in.

[GAL-4046] show posts in following feed

---

apps/web/src/components/Notifications/Notification.tsx
apps/web/src/components/Notifications/notifications/NewTokens.tsx

Display new notification token in the notification sidebar
**Minted 1 token**
**If minted multiple tokens**
**Demo**
https://github.com/gallery-so/gallery/assets/4480258/92adefd7-d45c-4d64-8989-cd77ed978194
1. Submit a post from notification sidebar
2. Notification that has invalid media (shouldn't show in the list)
3. Notification that has multiple tokens
4. Test the feature flag whether the notification is shown or not
1. Login to web
2. You should see a new token notification
3. You're able to post directly from notification sidebar. It will open the post composer

[GAL-3849] Add Optimistic Syncing notification [web]

---

apps/mobile/src/components/Toast/Toast.tsx
apps/mobile/src/contexts/ToastContext.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx

- Add refresh functionality to nft selector
- Add positioning support to Toast
https://github.com/gallery-so/gallery/assets/4480258/95245038-a5c9-45fe-af29-650a0aec76ce
1. Test refresh from nft selector
2. Check whether the new nft show up
3. Only show the refresh icon if single network was selected
1. Open nft selector through pfp/post
2. Click the refresh icon

[GAL-4034] Add refresh to nft selector

---

apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheet.tsx
apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetLine.tsx
apps/mobile/src/components/Feed/Posts/FeedPostSocializeSection.tsx
apps/mobile/src/components/Feed/Socialize/CommentBox.tsx
apps/mobile/src/components/Feed/Socialize/CommentButton.tsx
apps/mobile/src/components/Feed/Socialize/FeedEventSocializeSection.tsx

This PR makes tapping "View X other comments" and the Comment icon open the same comments sheet.
it also adds an empty state to the sheet, along with minor layout adjustments to the comment list.
there are further styling fixes we'll need to make to comments, but we'll address them as a follow up PR
https://github.com/gallery-so/gallery/assets/80802871/5991b577-1f39-4973-845b-af9dc058db44
- if no comments, show "No Comments"
dark mode looking good
Tap both things mentioned above

make view more comment and comment icon open same sheet

---

apps/mobile/src/components/Notification/NotificationSkeleton.tsx
apps/mobile/src/components/Notification/Notifications/SomeoneCommentedOnYourPost.tsx

Fix overlap comment in the notification
| ![image](https://github.com/gallery-so/gallery/assets/4480258/04703608-8c41-4925-ac9f-92cccf71a3e2) | <img width="459" alt="CleanShot 2023-08-18 at 13 53 38@2x" src="https://github.com/gallery-so/gallery/assets/4480258/7557bd58-0256-4802-bd4f-f632f52ad8f7">| 
1. Display with one line comment
2. two line comment
3. three line comment
4. Make sure it didn't affect other notification
1. Open notification screen
2. You should see the text didn't overlap the image

[GAL-4044] Caption in "user commented on your post" notification overlaps image

---

apps/web/src/scenes/UserGalleryPage/UserNameAndDescriptionHeader.tsx

Old logic was preventing the username from appearing in the profile header if there was no bio
before
after
- still looks fine with or without bio
go to  a user without a bio (/jamiethetailor)

remove logic to hide heading if no bio on mobile

---

apps/web/src/components/Feed/Socialize/CommentLine.tsx

Comment timestamp was off on web, this fixes alignment so it appears centered against the first line of the comment 
before
after
multi line comments
check out a post + feed events with comments

adjust line height for comment timestamp for alignment

---

apps/web/src/hooks/api/posts/useCreatePost.ts
apps/web/src/hooks/api/posts/useDeletePost.ts
apps/web/src/scenes/CommunityPage/CommunityPageTabs.tsx
apps/web/src/scenes/CommunityPage/CommunityPageView.tsx

show number of posts in community page tab on web
**Before:**
**After:**

GAL-4078: show number of posts in community page tab on web

---

apps/web/src/components/NftSelector/NftSelector.tsx

Enable refresh button in NFT Select based on chain family, not just chain.
L2s are considered to be in the Ethereum chain family so our current logic to enable the refresh button wasn't working for L2s. 
I replaced the usage of `doesUserOwnWalletFromChain` with `doesUserOwnWalletFromChainFamily` to make the refresh button available for related chains.
before
after
N/A
Go to NFT Selector, select an L2 like Base. the refresh button should be clickable and work.

enable refresh button for all ethereum based chains

---

apps/web/src/components/Feed/Socialize/CommentsModal/CommentsModal.tsx

when 0 comments, modal has empty state message "No comments yet" in the color metal
When comments > 0, no change is seen
Tested with 0, 1 and 1+ comments on modal and different window sizes

[GAL-4076] Add empty state to comments on web

---

apps/web/src/components/NftPreview/CollectionTokenPreview.tsx

Fixes regression from https://github.com/gallery-so/gallery/pull/1727, and makes sure to disable live rendering elements on mobile web to allow heavier profiles to load.
https://gallery.so/mitchell is now actually scrollable on mobile web

Disable liverender again on mobile

---

apps/web/src/components/Posts/PostComposerModal.tsx
apps/web/src/components/Profile/EditUserInfoForm.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
apps/web/src/hooks/api/tokens/useSyncTokens.ts
apps/web/src/scenes/CommunityPage/CommunityPageMetadata.tsx
apps/web/src/scenes/CommunityPage/CommunityPagePostsTab.tsx

Loom Overview, which contains Demo: https://www.loom.com/share/5060a674c9ac4aa7b2b8c60c3de317cb?sid=ca87088c-a695-491b-813a-330adb15ce9f
**TL;DR – when firing a mutation, we need to explicitly specify which fragments we want to update in the relay cache.** 
Without specifying the `PostComposerModalFragment` to be updated after calling `useSyncTokens`, the tokens remained stale in the post composer despite refreshing. The exact same issue occurred in the Editor in the past, which was fixed with #1659.
The way we need to remember to list which fragments to update in the relay cache is very annoying. I asked ChatGPT why this is necessary, and it provided some pros / cons:

Fix stale composer refresh

---

apps/web/src/components/Pill.tsx

Due to a typo we weren't getting `cursor: pointer` for pills on web

Fix cursor pointer for pills on web

---

apps/web/src/scenes/CommunityPage/CommunityPageTabs.tsx

add totalCollectors count in community tab on web. for mobile, it's already implemented!
**Before:**
**After:**

GAL-4100: add collectors count in community tab [web]

---

apps/web/src/components/Feed/Socialize/CommentsModal/CommentsModal.tsx

Updates the default row height we use for comments in the comment modal. we recently updated the comment row layout, so the modal wasn't fitting everything in.
before
after
still doesn't account for if the comment is 2 lines and taller than default, but we can follow up . this pr is an incremental improvement
note: noticed an existing bug for mobile web, made a ticket https://linear.app/galleryso/issue/GAL-4136/comment-modal-list-doesnt-use-full-screen-height-on-web

update default comment row height

---

apps/mobile/src/screens/NftSelectorScreen/NftSelectorContractScreen.tsx

Make collection screen scrollable in NFT Selector in mobile app
Before
https://github.com/gallery-so/gallery/assets/80802871/0cc69ad0-3128-4742-9a8b-553ac50584e5
AFter
https://github.com/gallery-so/gallery/assets/80802871/bfda2b8b-3cae-4346-b5da-5cb7289b72ad
Collection screen works when there are more than nfts than fit the screen
it also works when all nfts fit in screen
Go to nft selector and pick a collection that that has many owned tokens

GAL-4067 Make collection screen scrollable in NFT Selector in mobile app

---

apps/mobile/src/screens/PostScreen/PostComposerScreen.tsx

Updates the logic for the Discard Post Confirmation so that we only show it if the user has entered a caption. If the input is empty, don't show it. there's a separate ticket for web GAL-4139
before
https://github.com/gallery-so/gallery/assets/80802871/25f967fb-c59e-4186-a35c-87b05805aa82
after
https://github.com/gallery-so/gallery/assets/80802871/d1b90878-d81a-46e7-9e6b-7f1e7bf1f717
cases tested:
Add caption -> show confirmation 
Don't add caption -> don't show confirmation 
add caption and then delete -> don't show confirmation 
go to nft selector, select an nft and then go back with or without a caption

GAL-4103 dont show discard post confirmation if there's no caption

---

apps/mobile/src/components/GallerySkeleton.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorContractScreen.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerSingularAsset.tsx

Added skeleton placeholders to loading assets in the NFT Selector
other changes
- added an optional `borderRadius` prop on `GallerySkeleton`
before
https://github.com/gallery-so/gallery/assets/80802871/66994cdf-9b29-4fc5-8e0e-4731857b1e3e
after
https://github.com/gallery-so/gallery/assets/80802871/7d51f0f6-1c31-4bcb-8ef9-86a6fb40c1cb
check both the default grid and also tap into a contract
Go to the nft selector and watch the items load

GAL-4069 GAL-4138 update nftselector proper placeholders and also add to contract groups

---

apps/mobile/src/components/Community/CommunityPostBottomSheet.tsx

fix tiny typo in refresh bottom sheet (its -> it's)
and increase font size (sm -> md)
before
after
n/a
go to a community page you don't have a token for and tap the post button

GAL-4071 fix tiny typo in refresh bottom sheet and increase font size 

---

apps/mobile/src/navigation/FeedTabNavigator/FeedTabNavigator.tsx
apps/mobile/src/screens/HomeScreen/CuratedScreen.tsx
apps/mobile/src/screens/HomeScreen/LatestScreen.tsx
apps/mobile/src/screens/Login/NotificationUpsellScreen.tsx
apps/mobile/src/screens/Login/navigateToNotificationUpsellOrHomeScreen.ts

Change the default screen on mobile app from Latest to Curated.
Also move the Beta Welcome bottom sheet from Latest to Curated so we can continue to show it.
Before
https://github.com/gallery-so/gallery/assets/80802871/68b9c833-0665-49eb-823d-43b3ce5195a5
After
https://github.com/gallery-so/gallery/assets/80802871/8a48bde1-30da-4121-b792-a6cec1ce749e
- for first time sign in users we show a Welcome to the Beta bottom sheet. made sure we keep showing that
reboot the app, the first thing you should see is the Curated Screen

GAL-4102 make Curated the default screen on mobile app

---

apps/mobile/src/components/Community/CommunityMeta.tsx
apps/mobile/src/components/LinkableAddress.tsx

seems like we don't show the network icon for a few icons on community pages on mobile
No real edge cases I can think of.
Can test locally on the branch

[GAL-4074]: Add all icons for community page networks

---

apps/mobile/src/components/Community/CommunityPostListFallback.tsx
apps/mobile/src/components/Community/CommunityViewFallback.tsx

when entering community page and Posts tab is active (it is by default), show an empty state reflecting posts, not collectors
Testing communities that do not have posts enabled by default
Can test locally on branch and visit a community with posts enabled

[GAL-4072] Show Posts skeleton state in Community Page

---

apps/mobile/src/screens/PostScreen/PostComposerNftFallback.tsx
apps/mobile/src/screens/PostScreen/PostComposerScreen.tsx

when transitioning from the NFT Selector to the Post Composer, there isn't a blank screen and instead there are placeholder elements for the Post Composer UI.
the suspense state for the nft is limited to the area with the token image and name
When selecting token from NFT picker for post composer
| Before | Before 2 | After | After 2 |
|--------|--------|--------|--------|
| <img width="475" alt="Screenshot 2023-08-29 at 5 28 47 PM" src="https://github.com/gallery-so/gallery/assets/49758803/d32b6886-67f7-4044-8f58-25624cd54212"> | <img width="466" alt="Screenshot 2023-08-29 at 5 29 00 PM" src="https://github.com/gallery-so/gallery/assets/49758803/35125050-5b9f-45f7-a7bc-78e5d7a5ac91"> | <img width="533" alt="Screenshot 2023-08-29 at 5 23 25 PM" …

[GAL-4142] Add skeleton state for Post Composer

---

apps/mobile/src/screens/NftSelectorScreen/NftSelectorFilterBottomSheet.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx
apps/web/.env.sample

on mobile app, we default to Ethereum in the NFT Selector similar to web as we can't show a refresh button for 'all' option only
| Before | Before 2 | After | After 2 |
|--------|--------|--------|--------|
| ![Screenshot 2023-08-29 at 3 20 48 PM](https://github.com/gallery-so/gallery/assets/49758803/30932de2-6a5d-40c5-93f8-5b98fcb53045) | ![Screenshot 2023-08-29 at 3 20 59 PM](https://github.com/gallery-so/gallery/assets/49758803/837768bc-ab17-4a67-b676-5b5c8050d32d) | ![Screenshot 2023-08-29 at 5 54 47 PM](https://github.com/gallery-so/gallery/assets/49758803/06e2a71e-7b48-4d07-9956-f8f04b9f581f) | ![Screenshot 2023-08-29 at 3 15 39 PM](https://github.com/gallery-so/gallery/assets/49758803/a1d718a0-c893-413f-8aa5-5437e2b1d3f9) |
Hmm not sure about what else to consider
Can test locally …

[GAL-4059] Remove All Networks view from Selector for now

---

apps/web/src/hooks/api/posts/useCreatePost.ts

The production feed passes in `includePosts: false` when loading its curated feed, which was not handled by the optimistic update logic.

Fix optimistic update on Curated feed on prod

---

apps/mobile/src/icons/EthIcon.tsx

Fix eth icon when we tried to scale it (different sizes)
1. Check the eth icon in wallet selector (wallet connect)
2. Community screen
3. NFT selector (chain filter)
1. Go to wallet connect authentication
2. Check any ethereum community screen
3. NFT selector (during post / pfp)

[GAL-4174] Fix non-scalable eth icon

---

apps/web/src/components/Posts/DiscardPostConfirmation.tsx
apps/web/src/components/Posts/PostComposer.tsx
apps/web/src/components/Posts/PostComposerModal.tsx
apps/web/src/contexts/AppProvider.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
apps/web/src/contexts/modal/AnimatedModal.tsx
apps/web/src/contexts/modal/ModalContext.tsx
apps/web/src/contexts/postComposer/PostComposerContext.tsx
apps/web/src/icons/TrashIconNew.tsx

- Remove unnecessary `Discard Post` modal when user leaves flow without writing a caption
- Add ability to save post drafts
- Create post composer context to store drafts and custom URL param state
- Typescript improvements for modal context
- Ergonomic `onCloseOverride` handler
_Discard Post, Save Draft Flow_ 📹 
https://github.com/gallery-so/gallery/assets/12162433/07ea22f3-b345-4d44-878a-efaa816abf8a
_URL param autofill_

[GAL-4139] Post composer context, improve discard modal handling

---

apps/mobile/src/components/Community/CommunityMeta.tsx
apps/mobile/src/navigation/MainTabNavigator/PostIcon.tsx
apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx

Increase the stroke weight on the PostIcon in some instances to the design
| Before | Before 2 | 
| <img width="457" alt="Screenshot 2023-08-30 at 2 24 06 PM" src="https://github.com/gallery-so/gallery/assets/49758803/ade88158-0bff-4b9b-9a1b-6131bb6cdd6a"> | <img width="497" alt="Screenshot 2023-08-30 at 2 24 13 PM" src="https://github.com/gallery-so/gallery/assets/49758803/8f1a54ce-3256-4eb7-b6cd-0613452bfa7c"> | 
| After | After 2 |
| <img width="418" alt="Screenshot 2023-08-30 at 2 21 29 PM" src="https://github.com/gallery-so/gallery/assets/49758803/549dca1f-f525-474b-8d2e-78cb6b973d55"> | <img width="408" alt="Screenshot 2023-08-30 at 2 20 36 PM" src="https://github.com/gallery-so/gallery/assets/49758803/8ff025b9-b309-4c94-9bf3-02b06136c73e"> | …

[GAL-4022] Post button icon stroke weight update

---

apps/web/src/components/Notifications/notifications/SomeoneFollowedYou.tsx
apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedInfoList/SharedFollowersList.tsx
apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedInfoList/SharedInfoListRow.tsx

modal should close upon clicking on a navigational element within it and the modal is height is reduced.
Upon opening the modal and clicking a user, it now closes the modal in addition to rerouting to the new user profile page
Different shared user list lengths
Can test locally on branch and visit profile with shared followers.

[GAL-4110] fix navigation in shared followers, communities modal

---

apps/web/src/components/Notifications/notifications/SomeoneFollowedYou.tsx

Wrap "followed you" button in 'userX followed you' notification if username is too long, and **no changes** if username is not too long
| Before (should stay unchanged) | Before (issue) |
| ![Screenshot 2023-08-31 at 1 44 21 PM](https://github.com/gallery-so/gallery/assets/49758803/dc1abe21-caee-497d-8b66-f46e64f1fde2) | ![Screenshot 2023-08-31 at 3 13 01 PM](https://github.com/gallery-so/gallery/assets/49758803/6c002667-85c1-421b-93b2-720d92ce3b08) | 
| After (should stay unchanged) | After (issue resolved) |
| ![Screenshot 2023-08-31 at 2 48 50 PM](https://github.com/gallery-so/gallery/assets/49758803/17e7489f-cb54-4c3d-81ac-15bd6663da55) | ![Screenshot 2023-08-31 at 3 31 05 PM](https://github.com/gallery-so/gallery/assets/49758803/20a7a3ef-acaf-4b …

[GAL-4112] Ensure "followed you" wraps to next line in web notifications

---

apps/mobile/src/navigation/FeedTabNavigator/TabBar.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/HomeNavbar/HomeNavbar.tsx

Rename Curated to For You based on user feedback.
Since we're still testing the name change, I decided to keep this a surface level change and only change the user facing copy instead of changing the naming in all of the code. It's possible that we get additional feedback and change the label again.
Before
After 
Make sure routing, etc still works. functionality should not be affected 
Go to to feed on webs and mobile and verify copy change and no functional regressions.

rename Curated to For You

---

apps/web/src/contexts/globalLayout/GlobalNavbar/HomeNavbar/HomeNavbar.tsx

We recently rename the Curated tab to Trending, but it doesn't make sense if you're signed out
So show Trending instead of For You if signed out 
signed in on left, signed out on right
- signed in, signed out
Look at the home page while signed in and signed out

show Trending instead of For You if signed out

---

apps/web/src/components/Feed/Posts/PostHeader.tsx
apps/web/src/components/HoverCard/HoverCardCommunityInner.tsx
apps/web/src/components/HoverCard/HoverCardOnCommunity.tsx
apps/web/src/components/HoverCard/HoverCardOnUsername.tsx
apps/web/src/components/HoverCard/HoverCardUsernameInner.tsx
apps/web/src/components/ProfilePicture/RawProfilePicture.tsx
apps/web/src/components/core/Spinner/Spinner.tsx

fix content overflow on community hover card, and implement some new design changes suggested by Fraser
**Before:**
**After:**
So there's an edge case here, `-webkit-line-clamp` works well with regular text content but may struggle with long URLs or single continuous strings of characters because it doesn't have natural breakpoints to determine where to truncate.. that's way the NFTs that have some mint urls in their description which are a little long, the content seems to overflow outside the hover card.. See the screenshot below:
So I tried the `word-break: break-all;`: This property allows long strings to break at any character, ensuring that they stay within their container.. this works fine but again this will affect readability of regular text. So I set a `max-width` to the …

GAL-4177: fix content overflow on community hover card

---

apps/web/src/components/NftSelector/NftSelectorToken.tsx
apps/web/src/components/NftSelector/NftSelectorTokenPreview.tsx
apps/web/src/components/NftSelector/NftSelectorView.tsx
apps/web/src/components/NftSelector/RawNftSelectorPreviewAsset.tsx
apps/web/src/components/NftSelector/groupNftSelectorCollectionsByAddress.ts
apps/web/src/components/Posts/PostComposerAsset.tsx

Branch of #1885 targeting Web Post Composer
- migrated usages of `getVideoOrImageUrlForNftPreview` in Web Post Composer
- noticed we were doubling up on error boundaries which we should avoid doing (explained in video)
- improved display of token titles when within a grouped
https://www.loom.com/share/c1363eadaa814e1f9589c72b31718cda?sid=4e82c367-c9a3-4656-9891-946afa5275e5
Before
After

Refactor web post composer for getting previews

---

apps/web/src/components/Feed/Posts/PostNftPreview.tsx

Live rendering posts on mobile web drag down performance significantly
- Posts no longer live render on mobile width
- Posts continue to live render on non-mobile width

Disable post live rendering on mobile web

---

apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarList/SidebarList.tsx
apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarNftIcon.tsx
apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarTokens.tsx
apps/web/src/components/GalleryEditor/PiecesSidebar/createVirtualizedRowsFromGroups.ts

Historically, we wanted to push errored token IDs to the bottom of the list in the user's sidebar. But this is less necessary at this point since we group tokens by contract address, and it frees up a lot of complex business logic.
| <img width="245" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/9ac28155-c3ae-47d9-81f0-e1332430c0a4"> | <img width="225" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/5941f4f6-7916-4c8d-b58f-d32265746489"> |

Deprecate sorting sidebar tokens by errored IDs

---

apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetLine.tsx

Currently, from comments modal on mobile you can't navigate to user profile by clicking on user's pfp, username or comment. This pr adds that functionality 
https://github.com/gallery-so/gallery/assets/49758803/b236aecc-0caf-45bb-afbf-554dd729c4d3
Hmm not sure just tested with a bunch of user comments

[GAL-4196] Add navigation in mobile comments modal

---

apps/web/src/components/NftSelector/NftSelectorTokenPreview.tsx

contract name is truncated to fit in the parent container so that the label fits inside the nft.
| Before | After | After |
|--------|--------|--------|
| <img width="317" alt="Screenshot 2023-09-10 at 3 30 19 AM" src="https://github.com/gallery-so/gallery/assets/49758803/408e8fd5-e504-4475-b278-74793dccc18f"> | <img width="312" alt="Screenshot 2023-09-11 at 9 58 01 AM" src="https://github.com/gallery-so/gallery/assets/49758803/bba726ac-c93e-48e4-a9df-24afe39a5497"> | <img width="332" alt="Screenshot 2023-09-10 at 3 18 12 AM" src="https://github.com/gallery-so/gallery/assets/49758803/f0c76a24-4546-46c8-b742-d0eb2af4ef73"> | 
No specific cases tested

[GAL-4135] Long Contract name spills over in web nft selector

---

apps/mobile/src/contexts/MobileAnalyticsProvider.tsx
apps/web/src/contexts/analytics/WebAnalyticsProvider.tsx
packages/shared/src/contexts/AnalyticsContext.tsx

Include in events whether or not a user is a beta tester.
there are two methods: including the flag in every event, and setting the flag on the user profile.
there are pros and cons to each method, so we'll start by doing both to minimize gaps or incomplete data. we can evaluate if one turns out to be more reliable or accurate. for example, one difference is user role state - we may add or remove Beta Tester roles in the future, and including it in every event maintains historical context because you can see more directly whether a user was a beta tester at the time the event was triggered. 
- If this PR makes visual changes, include before and after screenshots. You can type `/table` to quickly come …

[GAL-4259] include isBetaTester in events

---

apps/mobile/src/screens/NftDetailScreen/NftAdditionalDetailsEth.tsx
apps/web/src/components/CommunityHolderGrid/CommunityHolderGridItem.tsx
apps/web/src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetailsEth.tsx
apps/web/src/scenes/NftDetailPage/NftAdditionalDetails/NftAdditionalDetailsTezos.tsx
apps/web/src/scenes/NftDetailPage/NftDetailText.tsx
packages/shared/src/utils/extractRelevantMetadataFromToken.ts
packages/shared/src/utils/getOpenseaExternalUrl.ts
packages/shared/src/utils/getProhibitionUrl.ts
packages/shared/src/utils/getTezosExternalUrl.ts
packages/shared/src/utils/hexToDec.ts

Core problem: we store token IDs in hex, and convert it back to decimal on the client for display purposes. Given that we use token IDs in various ways, there were areas where we'd forget to convert it to decimal, or worse, run the conversion multiple times.
Solution:
- refactor all relevant areas to use `extractRelevantMetadataFromToken`. this is what we should use in 99% of cases, and will ensure the hexToDec conversion is applied once
- strongly encourage the usage of above exclusively by appending direct helper functions with `-Dangerously`
Opening external links on various chains works
| <img width="1343" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/56cf6a2a-d8af-4a23-873b-5b4652dc8f56"> | <img width="1203" alt="image" …

Fix broken OS links, refactor

---

apps/mobile/src/components/DeepLinkRegistrar.tsx
apps/mobile/src/utils/hashString.tsx

For Marfa a specific url shared at the event will trigger the Check In flow. we previously had all the pieces of the url hardcoded so someone outside the event could figure out the url.
wanted to add a simple hash so that the url isn't obviously hardcoded. 
recording in slack
- correct url triggers check in flow,
- incorrect url opens regular home landing page, and doesn't crash app 
follow url shared in slack

add simple hash to obfuscate event param

---

apps/web/src/components/HoverCard/HoverCardCommunityInner.tsx
apps/web/src/components/HoverCard/HoverCardOnUsername.tsx
apps/web/src/components/HoverCard/HoverCardUsernameInner.tsx
packages/shared/src/utils/regex.ts
packages/shared/src/utils/wallet.ts

Truncate long strings in community hover cards and check for user hover cards.
Try with ETH addresses and long user names

[GAL-4227] truncate string in hover card

---

apps/mobile/src/components/Notification/Notifications/SomeoneFollowedYou.tsx

Display the follow-back button on "user followed you" notification if you are not following the user back.
| Before | After | After (Dark)|
|--------|--------|-------|
| <img width="457" alt="Screenshot 2023-09-15 at 5 30 26 AM" src="https://github.com/gallery-so/gallery/assets/49758803/d578edc2-bc61-480d-a16b-7e70927751d9"> | <img width="460" alt="Screenshot 2023-09-15 at 5 19 53 AM" src="https://github.com/gallery-so/gallery/assets/49758803/09668442-e5a8-4c33-8b52-0c3db6a3ebef"> | <img width="464" alt="Screenshot 2023-09-15 at 5 28 31 AM" src="https://github.com/gallery-so/gallery/assets/49758803/e1b810ae-5aab-43a5-a0bd-d84c86f75750"> |
When you already follow back the user
Make sure it wraps when there's a super long username
Will need to uhm improve this case not sure yet how
Also, …

Add Follow Back Button on mobile notifs

---

apps/web/src/components/NftSelector/NftSelector.tsx
apps/web/src/components/NftSelector/useNftSelector.tsx
apps/web/src/components/Notifications/notifications/NewTokens.tsx
apps/web/src/components/Posts/PostComposer.tsx
apps/web/src/components/Posts/PostComposerModal.tsx
apps/web/src/components/Profile/EditUserInfoForm.tsx
apps/web/src/components/Profile/ProfilePictureDropdown.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
apps/web/src/contexts/relay/RelayProvider.tsx
apps/web/src/hooks/api/tokens/useSyncTokens.ts
apps/web/src/scenes/CommunityPage/CommunityPageMetadata.tsx
apps/web/src/scenes/CommunityPage/CommunityPagePostsTab.tsx
apps/web/src/scenes/NftDetailPage/NftDetailAsset.test.tsx
apps/web/src/scenes/NftDetailPage/NftDetailText.tsx
packages/shared/src/relay/missingFieldHandlers.ts

The goal of this PR is to stop eagerly loading a user's entire list of tokens. For now we can push the loading of tokens down to the modal that needs it and show a nice fallback state while we wait. 
**This is still super slow for users with large # of tokens. In the future we should come up w/ a plan to paginate tokens**.
https://github.com/gallery-so/gallery/assets/6754223/6634ff1f-87a8-4e88-85a7-4c3132e4c3ff

Lazy Load NftSelector & PostComposer

---

apps/mobile/src/components/NftPreview/NftPreviewErrorFallback.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerSingularAsset.tsx

An unhandled error while rendering items in the grid view (which we display for collections you own multiple tokens of) in the nft selector caused the app to crash for some users.
this pr adds a ReportingErrorBoundary around the offending component and improves styling for an existing error fallback component.
before: app crashed
https://github.com/gallery-so/gallery/assets/80802871/b8da6399-a95a-4973-b421-8718e93c0f4c
After: app doesn't crash
https://github.com/gallery-so/gallery/assets/80802871/fdc09d99-cd74-42ac-8e0f-ad91505c83d3
Before: error grid fallback looks bad
After: error grid looks good
na, this is the edge case
test as user `Mitchell` and confirm the nft selector doesn't crash

GAL-4301 handle error in nft selector grid

---

apps/mobile/src/components/MarfaCheckIn/CheckInEmailEntry.tsx

Input color was wrong for email input in darkmode
before
after
light mode still looks fine
open check in flow in dark mode

fix input color in check in form for darkmode

---

apps/mobile/src/screens/FeedEventScreen.tsx
apps/mobile/src/screens/NftDetailScreen/UniversalNftDetailScreen.tsx
apps/mobile/src/screens/PostScreen/PostScreen.tsx

Fix regression on specific screen that cause by upsell banner PR
1. Single post screen
2. Universal nft detail screen
3. Single feed screen
**Single post screen**
| <img width="455" alt="CleanShot 2023-09-19 at 11 20 58@2x" src="https://github.com/gallery-so/gallery/assets/4480258/7e997bce-f438-4c43-b90c-9e979cf4a3e3"> |<img width="441" alt="CleanShot 2023-09-19 at 11 18 52@2x" src="https://github.com/gallery-so/gallery/assets/4480258/6a95dc24-9a98-40d8-aa06-ea63b79de234"> | 
**Universal nft detail screen**
| <img width="447" alt="CleanShot 2023-09-19 at 11 20 23@2x" src="https://github.com/gallery-so/gallery/assets/4480258/e47d1bd1-7bb2-4c08-98f7-f8eb03b5f210"> | <img width="460" alt="CleanShot 2023-09-19 at 11 …

[GAL-4323] Fix regression upsell screen

---

apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheet.tsx

Dismiss keyboard after commenting on post or feed event on mobile
https://github.com/gallery-so/gallery/assets/49758803/7f89419e-37c8-462f-b706-2bc22a9261fd
tested commenting on both post and feed events
can test locally on branch by making a comment

[GAL-4314] Dismiss keyboard after commenting on mobile

---

apps/mobile/src/components/MarfaCheckIn/CheckInWalletSelection.tsx

Make Marfa Check IN wallet list scrollable in case user has many wallets connected
scrollable now. previously any part of the list that didnt fit on the screen was not viewable 
https://github.com/gallery-so/gallery/assets/80802871/2db56b0d-489d-4c06-80df-500f099a0291
no wallets, many wallets
no wallets is ok
go to Marfa Check in flow

make marfa check in wallet list scrollable

---

apps/mobile/src/components/Feed/Posts/PostBottomSheet.tsx

Copies the correct URL to Post on mobile from "..." menu of a post
| After | After | After pasting copied link |
|--------|--------|--------|
| <img width="449" alt="Screenshot 2023-09-20 at 4 09 40 AM" src="https://github.com/gallery-so/gallery/assets/49758803/7fdb67a3-c405-46c0-9f26-9d2f20eb2db1"> | <img width="452" alt="Screenshot 2023-09-20 at 4 09 45 AM" src="https://github.com/gallery-so/gallery/assets/49758803/e9994b16-30f5-49d9-830a-aa6213bb6a1e"> | <img width="448" alt="Screenshot 2023-09-20 at 4 09 53 AM" src="https://github.com/gallery-so/gallery/assets/49758803/a01a762b-f181-4f6c-8aaa-29475409fcb2"> | 
No specific cases considered

[GAL-4298] Share button in "..." menu copies wrong url [mobile]

---

apps/mobile/src/components/Notification/Notifications/SomeoneCommentedOnYourPost.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorFilterBottomSheet.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx

These were supposed to be included in here: https://github.com/gallery-so/gallery/pull/1934
Swapping Network dropdown out so that it's accessible from the outside. It's more relevant than the Created vs Collected tab

stuff i forgot in other PR

---

apps/mobile/package.json
apps/mobile/src/App.tsx
apps/mobile/src/screens/Onboarding/OnboardingVideoScreen.tsx
apps/mobile/src/screens/Onboarding/useCacheIntroVideo.ts
yarn.lock

The idea:
1. Download the video when the user in the splash screen (same as phase when we setup our color scheme and font)
2. Store it inside the user device cache folder
3. Save the path inside the local storage
4. We just load the video from the local storage path
https://github.com/gallery-so/gallery/assets/4480258/7c934240-ef0c-4b8c-8624-da7be048ea33
1. Test open the app with clear cache + local storage
2. Reopen the app and check whether are we downloading the video again
**Before**
1. Clear the local storage through expo debugger
2. Run with this command `yarn workspace mobile expo start --clear` to fresh start the app with clear cache
**Steps**
1. Enter with secret gesture
2. You should see the intro video instantly

Cache the video on load

---

apps/web/next.config.js
apps/web/src/components/NftSelector/NftSelector.tsx
apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorViewSelector.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
apps/web/src/contexts/postComposer/PostComposerContext.tsx
packages/shared/src/utils/chains.ts

Full walkthrough of code changes with demo: https://www.loom.com/share/e0967092a7104f128c3d8c727d2f0101?sid=c81819b8-91f3-4cd4-aa7f-96a25aaca331
v0 share-to-gallery implementation on web.
**Example redirect**
start: `http://localhost:3000/~/compose?tokenId=98&contractAddress=0xE480a895DE49B49e37A8f0a8bD7e07FC9844CDb9&chain=Arbitrum&collection_title=Dots&token_title=Dots+%2398&caption=I+just+minted+Dots+%2398+by+wutsit2u+on+Prohibition`
end: `http://localhost:3000/home?tokenId=98&contractAddress=0xE480a895DE49B49e37A8f0a8bD7e07FC9844CDb9&chain=Arbitrum&collection_title=Dots&token_title=Dots%20%2398&caption=I%20just%20minted%20Dots%20%2398%20by%20wutsit2u%20on%20Prohibition&composer=true`
If Logged In:
- automatically opens post modal with arbitrum selected (upon ensuring they've supplied …

Share-to-Gallery on Web

---

apps/web/src/components/Posts/PostComposerModal.tsx
apps/web/src/components/Settings/Settings.tsx
apps/web/src/utils/useClearURLQueryParams.ts

- Fixes a regression where the composer would continue to open after you closed it, triggered another element (e.g. sidebar notifications), then closed the sidebar. This would occur because the URL query params would continue to feature `composer=true`
- Introduce a new utility, `useClearURLQueryParams`, to help prevent this

Fix composer regression, useClearURLQueryParams

---

apps/mobile/src/components/Community/CommunityView.tsx
apps/mobile/src/components/GalleryTabs/GalleryTabsContainer.tsx
apps/mobile/src/screens/CommunityScreen/CommunityScreen.tsx

- Add pull to refresh on collection screen
- Fix overlap community header
**Add pull to refresh on collection screen**
https://github.com/gallery-so/gallery/assets/4480258/ce54b27d-08f1-44ac-b85f-ceba9d08c7d9
**Fix overlap on community header**
| <img width="512" alt="CleanShot 2023-09-26 at 12 20 10@2x" src="https://github.com/gallery-so/gallery/assets/4480258/cd054c8a-293f-4880-8412-60dabbfcef8b"> | <img width="529" alt="CleanShot 2023-09-26 at 12 19 38@2x" src="https://github.com/gallery-so/gallery/assets/4480258/904ae950-bba4-4149-8870-97cefcb29344"> | 
1. Check any community screen
2. Check profile screen to make sure there is no regression
1. Open any community screen

[GAL-4310] [GAL-4312] Pull-to-refresh on community page / Fix cut-off bio

---

apps/mobile/src/components/Feed/FeedList.tsx
apps/mobile/src/components/Feed/createVirtualizedFeedEventItems.ts
apps/mobile/src/components/ProfileView/Tabs/ProfileViewActivityTab.tsx
apps/web/src/components/NftSelector/NftSelector.tsx
apps/web/src/components/NftSelector/NftSelectorView.tsx

Remove sticky header from items on the feed.
We are keeping the sticky header for other screens like the Gallery and Collection screens. this only affects the username header for Posts and Feed Events.
https://github.com/gallery-so/gallery/assets/80802871/4144824a-140d-4cba-9765-6ceea5b6e9b9
Gallery and Collection screens should still have the sticky header where they used to be.
Scroll on the Feed and User Activity Feed, and verify that the username header on Posts and Feed Events are no longer sticky and scroll with the screen.

GAL-4384 remove sticky header from feed

---

apps/mobile/src/components/Feed/FeedListItem.tsx
apps/mobile/src/components/Feed/Posts/PostListItem.tsx
apps/web/src/components/NftSelector/NftSelector.tsx
apps/web/src/components/NftSelector/NftSelectorView.tsx

Double Tapping on a post or feed event currently toggles an admire.
Instead, make it so it only admires, not unadmire. this is in line with what users are used to.
Posts:
https://github.com/gallery-so/gallery/assets/80802871/ebf83ce7-5727-400e-b552-53227987b112
Feed Events
https://github.com/gallery-so/gallery/assets/80802871/7d6c19d5-52c3-417a-8fcf-4e8495f4eb4a
- Post/FeedEvent that you haven't admired
- Post/FeedEvent that you have admired
- admire via pressing the icon, then try to double tap
- double tap, then try to unadmire via the icon, etc
try to admire/unadmire posts or FeedEvents by double tapping 
double tap posts a bunch of times and try to admire/unadmire

GAL-4320 only admire on double tap

---

apps/mobile/src/components/Search/SearchResult.tsx

If there's no second line in the search result like a bio, the text should still remain vertically aligned against the PFP.
Before
AFter
- has username + bio
- has username, no bio
- same for galleries, and communities
- search for something and verify 
- 

GAL-4394 vertically center search result if no second line

---

apps/web/src/components/Settings/Settings.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryRightContent.tsx
apps/web/src/contexts/globalLayout/GlobalSidebar/StandardSidebar.tsx
apps/web/src/hooks/useLogout.ts
apps/web/src/scenes/Nuke/Nuke.tsx

Add settings back to mobile web. this was lost after we added the Post button to the nav footer.
The Settings and Logout code was couple with the drawer context, so this PR separates them so the Settings modal can be used outside of the Drawer.
- on mobile web, go to the signed in user profile to access the Settings icon in the top right corner.
- verify that the settings modal opens.
- also verify that the Settings icon doesn't show on other user profiles 
regression test:
- verify that the settings menu works on desktop, and logging out works and closes the sidebar.

GAL-4339 add settings back to moweb

---

apps/mobile/src/contexts/ManageWalletContext.tsx

Fix a bug where the wallet connect still ask for signature when re-open the apps. 
**Solution**
We cleared up the web3 provider after the user attempt to sign the signature message (success or failed)
1. Sign with with wallet connect -> Close app -> Re-open the app again 
2. Add wallet to existing user -> Close app -> Re-open the app again
1. Sign with with wallet connect -> Close app -> Re-open the app again 

[GAL-4387] Clear up provider after connect wallet

---

apps/mobile/src/screens/NftDetailScreen/NftDetailScreenInner.tsx
apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx
apps/mobile/src/screens/NftDetailScreen/UniversalNftDetailScreenInner.tsx

Previously, we have the issue the `NftDetailScreen` doesnt support if the `token` didn't have any `collection` . So, we decided to duplicate our `NftDetailScreen` and named it `UniversalNftDetailScreen`. 
This PR should clean up a bit that we used the same component for both screen
Throw some UI polish on NFT description
|<img width="389" alt="CleanShot 2023-09-29 at 18 00 37@2x" src="https://github.com/gallery-so/gallery/assets/4480258/ba38b5b8-a75e-4d83-a7b8-bd37072744dc"> |<img width="382" alt="CleanShot 2023-09-29 at 18 00 15@2x" src="https://github.com/gallery-so/gallery/assets/4480258/e7442fe9-2598-46a1-989f-1d5310c76e23"> | 
1. View a token from feed (universal token screen)
2. View a token from gallery (normal token screen + collection)
3. …

Clean up Nft Detail Screen

---

apps/mobile/src/components/ProfileView/ProfileView.tsx
apps/mobile/src/components/ProfileView/ProfileViewHeader.tsx
apps/web/pages/[username]/posts.tsx
apps/web/src/components/Notifications/Notification.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryNavLinks.tsx
apps/web/src/scenes/UserActivityPage/UserActivityFeed.tsx

Rename the Activity tab on user profiles to Posts, on web and mobile
| <img width="347" alt="CleanShot 2023-10-02 at 19 37 20@2x" src="https://github.com/gallery-so/gallery/assets/80802871/31678295-e43c-42aa-9f6a-d1e6801911c7"> | <img width="436" alt="CleanShot 2023-10-02 at 19 24 56@2x" src="https://github.com/gallery-so/gallery/assets/80802871/386d35da-5860-4c7d-8a48-66c5ae7ef3b9">|
|<img width="360" alt="CleanShot 2023-10-02 at 19 38 16@2x" …

GAL-4169 rename Activity tab to Posts

---

apps/mobile/src/utils/shareToken.ts

updates the share URL to use token owner's username
| After                                     | After  2                                    |After   3                                   |
| ------------------------------------------ | ------------------------------------------ | ------------------------------------------ |
| <img width="439" alt="Screenshot 2023-10-04 at 8 12 41 PM" src="https://github.com/gallery-so/gallery/assets/49758803/75c4e284-8c81-40ee-8ff8-9606f144449f"> | <img width="449" alt="Screenshot 2023-10-04 at 8 12 48 PM" src="https://github.com/gallery-so/gallery/assets/49758803/57a2f610-ac28-4d7e-afad-c6f5b850ce50"> | <img width="450" alt="Screenshot 2023-10-04 at 8 13 02 PM" src="https://github.com/gallery-so/gallery/assets/49758803/1f5b6855-c32d-44bd-b0ba-f82d217ddea6 …

[GAl-4435] NFT Detail Page share link on mobile is wrong url

---

apps/web/src/components/Feed/FeedList.tsx

We currently render about 10-12 items in the virtualized feed at any given moment on web. Since we live render pieces, this creates a big burden on the browser if there are a lot of generative pieces on the feed. We're currently rendering ~10 rows total that aren't visible above or below the screen edge via the `overscanRowCount` prop, so this PR reduces it to 2 above and below. 
This means we only render 2 rows above and 2 rows below what's currently visible, drastically reducing the number of invisible items we display.
| …

reduce the amount of list items rendered simultaneously

---

apps/mobile/src/components/ProfileView/ProfileViewHeader.tsx
apps/web/src/scenes/UserGalleryPage/UserGalleryHeader.tsx
packages/shared/src/hooks/useIsChristinaFromLens.ts

Generally, in accordance with the nature of web3, we want to display whatever social profiles may be associated with a user's address, and prevent them from toggling them on/off.
That said, we're making an exception for 0xChristina, the head of growth for Lens!
| Before                                     | After Web                                      | After Mobile |
| ------------------------------------------ | ------------------------------------------ | ------------------------------------------ |
| <img width="387" alt="Screenshot 2023-10-04 at 11 23 53 PM" src="https://github.com/gallery-so/gallery/assets/12162433/aeecf998 …

Hide farcaster pill for christina

---

apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetLine.tsx
apps/mobile/src/components/Feed/Posts/FeedPostSocializeSection.tsx
apps/mobile/src/components/Feed/Socialize/AdmireButton.tsx
apps/mobile/src/components/Feed/Socialize/Admires.tsx
apps/mobile/src/components/Feed/Socialize/CommentButton.tsx
apps/mobile/src/components/Feed/Socialize/CommentLine.tsx
apps/mobile/src/components/Feed/Socialize/Comments.tsx
apps/mobile/src/components/Feed/Socialize/FeedEventSocializeSection.tsx
apps/mobile/src/components/Feed/Socialize/ProcessedCommentText.tsx
apps/mobile/src/components/UsernameDisplay.tsx

This PR refactors how comments are rendered. Previously we used the Markdown to display the comment with links.
Problem:
For comments specifically, (vs other text like the Post caption), we don’t need to support markdown. Instead we only need to support links and mentions. The Markdown component introduce unnecessary complexity and rigidity because it handles a lot of other cases that we don't need to for displaying comments. Specifically, the Markdown component prevented us from being able to wrap the comment under the username in the preview.
Solution
This PR adds a new `ProcessedCommentText` that we'll now use instead of `Markdown` to render comments. This component will parse the raw comment for any urls and display them as tappable links. In the future, this can be updated to also …

GAL-4161 refactor how comments are rendered to solve wrapping

---

apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx

Match nft detail page styling from [design here](https://www.figma.com/file/joBcmzJpAoCuQK0Tz093YI/Global-Product-Design-%5BWIP%5D?type=design&node-id=1-3&mode=design&t=JCJWSmSNJfsvBFzN-0)
| <img width="447" alt="Screenshot 2023-10-10 at 4 26 47 AM" src="https://github.com/gallery-so/gallery/assets/49758803/bf4289f9-bd11-410b-aca1-68a7bc7eb307"> | <img width="450" alt="Screenshot 2023-10-10 at 4 28 46 AM" src="https://github.com/gallery-so/gallery/assets/49758803/42451efb-d287-4b82-83f6-7f32fcf02dbe"> |
Provide steps on how the reviewer can test …

[GAl-4437] Address spacing in NFT detail view on mobile

---

apps/web/src/components/Feed/Posts/PostDropdown.tsx
apps/web/src/components/GalleryEditor/CollectionSidebar/CollectionListItem.tsx
apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarChainDropdown.tsx
apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarViewSelector.tsx
apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarWalletSelector.tsx
apps/web/src/components/MultiGallery/Gallery.tsx
apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorFilterNetwork.tsx
apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorFilterSort.tsx
apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorViewSelector.tsx
apps/web/src/components/Profile/EditUserInfoForm.tsx
apps/web/src/components/Profile/ProfilePictureDropdown.tsx
apps/web/src/components/ProfilePicture/ProfilePicture.tsx
apps/web/src/components/core/Dropdown/DropdownItem.tsx
apps/web/src/components/core/Dropdown/DropdownLink.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/CollectionNavbar/CollectionRightContent.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryRightContent.tsx
apps/web/src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
apps/web/src/scenes/UserGalleryPage/UserGalleryCollection.tsx
apps/web/src/scenes/UserGalleryPage/UserNameAndDescriptionHeader.tsx
packages/shared/src/analytics/constants.ts

- QoL update to simply supply a `label` to `DropdownItem` or `DropdownLink` instead of specifying a `BaseM`, with 
- QoL update to automatically add the trash icon when variant `delete` is set
- add `clickDisabled` prop for PFPs to prevent unnecessary redirects and click takeovers when clicking an element that happens to feature a PFP (e.g. trying to edit your PFP by clicking on it when you're on your own profile)

Web Instrumentation: Dropdowns

---

apps/mobile/src/components/Community/Tabs/CommunityViewPostsTab.tsx
apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheet.tsx
apps/mobile/src/components/Feed/Events/UserFollowedUsersFeedEvent.tsx
apps/mobile/src/components/Feed/FeedList.tsx
apps/mobile/src/components/NftPreview/NftPreview.tsx
apps/mobile/src/components/NftPreview/NftPreviewAsset.tsx
apps/mobile/src/components/NftPreview/UniversalNftPreview.tsx
apps/mobile/src/components/Notification/Notifications/SomeoneMentionedYou.tsx
apps/mobile/src/components/ProfileView/Tabs/ProfileViewActivityTab.tsx
apps/mobile/src/components/Search/Community/CommunitySearchResult.tsx
apps/mobile/src/components/Search/SearchResults.tsx
apps/mobile/src/components/Search/User/UserSearchResult.tsx
apps/mobile/src/components/Toast/Toast.tsx
apps/mobile/src/contexts/ManageWalletContext.tsx
apps/mobile/src/hooks/useEventComment.ts
apps/mobile/src/hooks/usePostComment.ts
apps/mobile/src/screens/FeedEventScreen.tsx
apps/mobile/src/screens/PostScreen/PostComposerScreen.tsx
apps/mobile/src/screens/PostScreen/PostScreen.tsx
apps/web/pages/_/components.tsx
apps/web/src/contexts/toast/Toast.tsx
apps/web/src/contexts/toast/ToastContext.tsx
packages/shared/src/contexts/AnalyticsContext.tsx
packages/shared/src/hooks/useCreateNonce.ts

Rather than defining empty functions inline `() => {}`, we should use the `noop` module from our shared package

Migrate noop functions to import noop

---

apps/web/src/components/NftSelector/NftSelectorPreviewAsset.tsx
apps/web/src/components/Posts/PostComposer.tsx
apps/web/src/components/Posts/PostComposerAsset.tsx
apps/web/src/components/Posts/PostComposerModal.tsx

Update web Nft Composer to display landscape and portrait images properly while keeping the images elsewhere unchanged
| Before                                     | After                                      | 
| ------------------------------------------ | ------------------------------------------ |  
|  <img width="766" alt="Screenshot 2023-10-02 at 1 23 32 PM" src="https://github.com/gallery-so/gallery/assets/49758803/c04e4f96-3167-4788-98cf-3ea70998f06a"> | <img width="706" alt="Screenshot 2023-10-15 at 8 50 36 AM" src="https://github.com/gallery-so/gallery/assets/49758803/c9b0a85b-33b9-4296-903a-55041853d9be"> |
| After                                     | After 2                                     |  …

[GAL-3843] Update web Nft Composer to display landscape and portrait images properly 

---

apps/web/pages/features/posts.tsx
apps/web/src/scenes/ContentPages/ContentModules/Faq.tsx
apps/web/src/scenes/ContentPages/ContentModules/FeatureHighlight.tsx
apps/web/src/scenes/ContentPages/PostsFeaturePage.tsx
apps/web/src/scenes/ContentPages/cms_types.ts

This PR adds a Feature Page to introduce posts. it can be found at /features/posts.
The content is provided via our CMS, and rendered using new components that match the CMS content models.
- mobile responsive
- go to /features/posts

add Posts feature page and required cms components

---

apps/web/src/scenes/ContentPages/ContentModules/FeatureHighlight.tsx

add props to enable auto play on iOS
note - 2 of the videos still don't play, we suspect its because they were rendered with a slightly different codec from the one that works. will resolve by rendering new files
before
https://github.com/gallery-so/gallery/assets/80802871/8af417c8-5f95-4a8a-a163-80b160f41a53
after
https://github.com/gallery-so/gallery/assets/80802871/525c7a45-8875-4b11-897a-106f3bd2789f

add props to enable auto play on ios

---

README.md
apps/web/pages/features/posts.tsx
apps/web/src/contexts/globalLayout/GlobalAnnouncementPopover/useGlobalAnnouncementPopover.tsx
apps/web/src/contexts/globalLayout/GlobalLayoutContext.tsx
apps/web/src/contexts/modal/AnimatedModal.tsx
apps/web/src/scenes/ContentPages/PostsFeaturePage.tsx
apps/web/tests/graphql/mockGlobalLayoutQuery.ts
schema.graphql

Show global modal for posts
expected behavior 
- should be controlled by an experience flag
- should not be shown to signed out users
- should look the same as /features/posts page
I also added an error boundary to the animated modal content, so that the error fallback screen is displayed within the modal instead of taking over the full page, which allows the user to close the modal. Otherwise, if there's an error in this global modal it blocks the whole user experience.
desktop
mobile
not shown for signed out users
Error boundary
go to gallery.so/home

show global modal for posts

---

apps/mobile/src/components/Feed/Socialize/CommentBox.tsx

Change Comment Keyboard Layout so that "@" is immediately accessible
| 
|
|
- Verify the comment input looks like the after screenshot
- verify other keyboards (like in the post composer) haven't changed

change comment keyboard layout

---

apps/web/src/scenes/ContentPages/PostsFeaturePage.tsx

Adding a beta label to the posts feature page.
|
| 
|
n/a
go to /features/posts

add beta label to posts feature page

---

apps/web/src/contexts/boundary/Boundary.tsx

This PR modifies the global app level boundary to allow disabling the Full Page Loader for specified paths.
This is so that we can avoid showing a full screen loader for content pages like the Features Posts page.
This change should only affect the Features Posts page and not other pages.
No loader on Posts Feature page:
https://github.com/gallery-so/gallery/assets/80802871/808fef71-b546-41c5-a65a-e96edb2dccf9
Loader still shows for Collection Page:
https://github.com/gallery-so/gallery/assets/80802871/720bb353-6e3c-4a8f-93d5-4e8f3d7a01fe
Loader still shows for User Page:
https://github.com/gallery-so/gallery/assets/80802871/b2981f62-3613-4326-ad5a-68acdabaf461
Loader still shows for Feed;
https://github.com/gallery-so/gallery/assets/80802871/496155e0-d7b2-4342-8a29-5565e37d5cb1
n/a
go to …

remove full page loader from global app level boundary suspense

---

apps/web/public/.well-known/apple-app-site-association

Don't deep link to app on Features pages (like Posts Feature page)
open a url for /features/posts and it should open in the browser instead of deep linking to app

dont deep link to app on features pages

---

apps/mobile/src/components/Search/Community/CommunitySearchResult.tsx
apps/mobile/src/components/Search/SearchResults.tsx
apps/mobile/src/components/Search/User/UserSearchResult.tsx

Fix the regression from mentions PR that the search result can't be pressed.
**Search**
https://github.com/gallery-so/gallery/assets/4480258/84bd80b9-5663-4b17-98b5-74e4981aacbf
**Mentions**
https://github.com/gallery-so/gallery/assets/4480258/66dc646c-f05e-452a-9dde-b5a74f965a62
1. Search any user/community/galleries
2. Mention user or gallery in comment/post
1. Search anything in search screen
2. You should be able to browse around

Fix regression on search onClick

---

apps/web/src/scenes/ContentPages/PostsFeaturePage.tsx

This PR updates the cta button destination on the Posts Features page such that if the viewer is signed in, the button takes them to the feed and opens the Composer.
If they are not signed in they are taken to the auth page.
Signed in
https://github.com/gallery-so/gallery/assets/80802871/f772e327-4f01-460a-a75b-c20dcbb795d2
https://github.com/gallery-so/gallery/assets/80802871/4c36c386-1430-4880-b92c-94cb8bae66c0
na
go to /features/posts and hit the Get Started button

update Posts Features page cta for signed in users

---

apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx

Fix Markdown import - was using different Markdown component so the color was incorrect on dark mode.
Dark Mode
Light Mode
na
View the NFT Detail Page on both light and dark mode

fix description color for darkmode

---

apps/web/public/.well-known/apple-app-site-association

Disable deep link for mint pages 
Open a url like gallery.so/mint/mementos and confirm it doesn't deep link to the app.

disable deep link for mint pages

---

apps/web/src/scenes/MintPages/MementosPage.tsx

Show Share On Gallery button after successful memento mint
https://github.com/gallery-so/gallery/assets/80802871/b1b21d4f-e43d-45b0-bdb5-52c86bab82dd
na, same behavior as existing share on gallery buttons - signed out users will see the auth modal.
if the token hasn't been synced yet, user will have to wait a bit.
after minting memento, (can hardcode this state locally), click on the Share ON Gallery button and confirm it takes you to the composer if you're signed in.

add share on gallery button to post-mint flow

---

apps/web/src/components/core/TextArea/TextArea.tsx

TextArea in Post Composer Web truncated early and this removes the early truncation
| <img width="740" alt="Screenshot 2023-10-20 at 3 22 10 PM" src="https://github.com/gallery-so/gallery/assets/49758803/63b3031e-08d0-4ed7-8dd3-ac4c9f02f314"> | <img width="755" alt="Screenshot 2023-10-20 at 3 21 38 PM" src="https://github.com/gallery-so/gallery/assets/49758803/786dab7c-44f4-4e72-9ad1-121c11711255"> |

TextArea in Post Composer Web truncated early

---

apps/mobile/src/hooks/useMentionableMessage.ts

Fix double @@ mention on trigger
https://github.com/gallery-so/gallery/assets/4480258/7ac08a80-fe32-46a6-8312-e1d4ab7f4368

Fix double @ on mention

---

apps/web/src/components/Settings/ManageEmailSection/ManageEmailSection.tsx

For some reason this button had been disabled due to a [past change](https://github.com/gallery-so/gallery/pull/1926/files#diff-a11afa3a50f04b9a5e469c0fcb87b5d18167b7f1f1b771b053622b7c38f666a8R152).

Fix email input regression

---

apps/web/src/components/Notifications/notifications/NotificationPostPreview.tsx
apps/web/src/components/Notifications/notifications/SomeoneCommentedOnYourPost.tsx

update styling of SomeoneCommentedOnYourPost notification to accommodate text and token preview correctly
| <img width="604" alt="Screenshot 2023-10-23 at 7 32 53 PM" src="https://github.com/gallery-so/gallery/assets/49758803/7ae8af23-b130-4b86-a0fe-70b32364d696"> | <img width="669" alt="Screenshot 2023-10-23 at 7 27 44 PM" src="https://github.com/gallery-so/gallery/assets/49758803/79a2de52-9966-4662-a054-8727b8540e3f">|
| <img …

[GAL-4436] notification regression

---

apps/web/src/scenes/UserGalleryPage/UserSocialPill.tsx

Adding a hyphen in the social pill is causing it to wrap to a new line, which is not desired
| <img width="392" alt="Screenshot 2023-10-31 at 1 18 26 AM" src="https://github.com/gallery-so/gallery/assets/49758803/3b35792c-cd96-4be2-b868-472ef9340458"> | <img width="392" alt="Screenshot 2023-10-31 at 1 18 26 AM" src="https://github.com/gallery-so/gallery/assets/49758803/baceacd6-1b69-4cfc-b0f3-5d9a6d2eafeb"> |
Tested different special character in the username

remove wrapping to new line on social pill

---

apps/mobile/src/components/Community/CommunityMeta.tsx
apps/mobile/src/components/EnsOrAddress.tsx
apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx
apps/web/src/components/NftPreview/NftPreviewLabel.tsx
apps/web/src/constants/creator.ts
apps/web/src/scenes/NftDetailPage/NftDetailText.tsx

1. deprecate ENABLED_CREATOR hard-coded variable
2. use this logic for NftDetailText
ownerIsHolder
-> true -> display Owner
-> false -> display null
ownerIsCreator
-> true -> display Creator
-> false -> look up contract's creator
-> if exists -> display Creator
-> else -> display null
| <img width="421" alt="Screenshot 2023-10-26 at 1 55 17 AM" src="https://github.com/gallery-so/gallery/assets/49758803/bd4f6ac9-bdf4-4177-acb2-f568de338172"> | <img width="426" alt="Screenshot 2023-10-26 at 1 14 12 AM" src="https://github.com/gallery-so/gallery/assets/49758803/fda1a78f-5977-4c5e-9080-79a185b80175"> |
| Before …

[GAl-4256] Displaying Creators in NFT Token Page

---

apps/web/src/contexts/postComposer/PostComposerContext.tsx

Before: The composer filters network based on most recent collection page viewed.
After: The composer should reset to default (ethereum) after a user has left a specific collection page

[GAL-4678] Fix network autoselect

---

apps/mobile/src/components/Trending/TrendingUserCard.tsx
apps/web/src/components/Badge/Badge.tsx
apps/web/src/constants/community.ts
apps/web/src/scenes/CommunityPage/CommunityPageCollectorsTab.tsx
packages/shared/src/utils/communities.ts

Badges that weren't being displayed on web were being showcased on mobile.
This PR move the badge filter to a shared package and applies it to mobile.

Apply badge filtering on mobile

---

apps/mobile/src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
apps/mobile/src/components/Feed/Events/CollectionUpdatedFeedEvent.tsx
apps/mobile/src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
apps/web/src/components/Feed/Events/CollectionCreatedFeedEvent.tsx
apps/web/src/components/Feed/Events/CollectionUpdatedFeedEvent.tsx
apps/web/src/components/Feed/Events/CollectorsNoteAddedToCollectionFeedEvent.tsx
apps/web/src/components/Feed/Events/TokensAddedToCollectionFeedEvent.tsx
apps/web/src/components/GalleryEditor/CollectionCreateOrEditForm.tsx
apps/web/src/components/GalleryEditor/CollectionEditor/DragAndDrop/Section.tsx
apps/web/src/components/GalleryEditor/CollectionEditor/StagingArea.tsx
apps/web/src/components/GalleryEditor/CollectionSidebar/CollectionListItem.tsx
apps/web/src/components/GalleryEditor/CollectionSidebar/CollectionSearch.tsx
apps/web/src/components/GalleryEditor/CollectionSidebar/CollectionSidebar.tsx
apps/web/src/components/GalleryEditor/CollectionSidebar/MoveCollectionModal.tsx
apps/web/src/components/MultiGallery/Gallery.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/CollectionNavbar/CollectionRightContent.tsx
apps/web/src/scenes/CollectionGalleryPage/CollectionGallery.tsx
apps/web/src/scenes/CollectionGalleryPage/CollectionGalleryHeader.tsx
apps/web/src/scenes/UserGalleryPage/UserGalleryCollection.tsx

In the context of galleries, rename collection to section to simplify. on web and mobile
Mainly affects 
- Editor (web only)
- Gallery
- Feed events
| ![CleanShot 2023-11-09 at 17 28 26](https://github.com/gallery-so/gallery/assets/80802871/dbcca3e8-3e74-4594-99db-1585fec083cf) | ![CleanShot 2023-11-09 at 17 19 19](https://github.com/gallery-so/gallery/assets/80802871/15816b56-1810-4b48-916e-ee4cc2ffd081) |
| ![CleanShot 2023-11-09 at 17 28 …

rename collection to section in user facing copy

---

apps/mobile/src/components/Notification/NotificationList.tsx
apps/mobile/src/hooks/useMobileClearNotifications.ts
apps/mobile/src/navigation/MainTabNavigator/NotificationBlueDot.tsx
apps/mobile/src/navigation/MainTabNavigator/TabBar.tsx
apps/mobile/src/screens/PostScreen/PostScreen.tsx
apps/mobile/src/utils/useEffectOnAppForeground.ts
apps/mobile/src/utils/useIntervalEffectOnAppForeground.ts
apps/mobile/src/utils/useSanityMaintenanceCheckMobile.ts

cool helper functions: `useEffectOnAppForeground`, `useIntervalEffectOnAppForeground`
https://www.loom.com/share/c0da1d2b7024400c9b76d00e75560021?sid=939c250e-4eaa-4225-8490-0ec878212c03

Fix stale notifications on mobile

---

packages/shared/src/components/GalleryProccessedText/GalleryTextElementParser.ts

Fix duplicate mention tagging. Found out at the issue happens when there is multiple `mention` interval
| ![image](https://github.com/gallery-so/gallery/assets/4480258/531696b8-7126-4597-8291-ef2d7a656ed2) | ![CleanShot 2023-11-13 at 18 11 24@2x](https://github.com/gallery-so/gallery/assets/4480258/de6090cd-2ad4-45ce-b55f-0045d0eb72b0) |
| ![image](https://github.com/gallery-so/gallery/assets/4480258/1d352b79-d525-4853-b7f7-692c40ef4e2c) | ![CleanShot 2023-11-13 at 18 12 35@2x](https://github.com/gallery-so/gallery/assets/4480258/155b1cc4-a385-4d19-93e5-ce06a1e26ef4)|
- Open any post/comment that has …

[GAL-4757] Fix duplicate mention tagging

---

packages/shared/src/hooks/useMentionableMessage.ts

Automatically add a space after selecting a mention
https://github.com/gallery-so/gallery/assets/80802871/f96840f6-4ad6-47e4-897a-88b083d4cea0
- adding a mention at the end of the input (standard case)
- adding a mention in the start/middle of the input (less common case)
- mention a user and confirm a space is automatically added after the username

add space after selecting mention

---

apps/mobile/src/components/Notification/Notifications/NewTokens.tsx
apps/web/src/components/Notifications/notifications/NewTokens.tsx

This will now say "Collected" instead of "Minted", since the user could get this notification for receiving a token

Minted -> Collected notification row

---

apps/web/src/components/Feed/Socialize/CommentBox/CommentBox.tsx

The issue is whenever we paste any text in the text input, it will overwrite the value instead of retain the current value. 
**Before**
https://github.com/gallery-so/gallery/assets/4480258/6a9a3fbc-0a9d-4efd-8d96-77429ac21283
**After**
https://github.com/gallery-so/gallery/assets/4480258/37ded91d-d55a-4c13-bdcb-455d62397fe1
1. Comment anything in the comment box
2. Mention any user
3. Paste any link inside the comment box

Fix the on paste callback

---

apps/web/src/components/Feed/Socialize/CommentBox/CommentBox.tsx
apps/web/src/components/Feed/Socialize/CommentsModal/CommentNote.tsx
apps/web/src/components/Feed/Socialize/CommentsModal/CommentsModal.tsx

- increase comments modal height
- Fix list height calculation to accurately reflect row heights
- reduce padding between heading and comment list
- add input placeholder cta
| <img width="758" alt="CleanShot 2023-11-16 at 18 12 57@2x" src="https://github.com/gallery-so/gallery/assets/80802871/7d7da7be-df45-496e-962f-e7ca332b1144"> | <img width="1512" alt="CleanShot 2023-11-16 at 18 07 40@2x" …

comments modal adjusments - height, spacing, etc

---

packages/shared/src/hooks/useMentionableMessage.test.ts
packages/shared/src/hooks/useMentionableMessage.ts

Improve on how we calculate the positioning of `Mention`. 
Previously, we are tracking on every keystroke and update the position manually. Its getting tricky to make it perfect and we didn't have much confident that it will works 100%. 
Current solution would be use regex to the whole string and get the index for each mention.
https://github.com/gallery-so/gallery/assets/4480258/5579aadb-6594-4281-bbe7-5c061022fa08

Update how we write/store mention

---

apps/mobile/src/components/Notification/Notifications/SomeoneMentionedYou.tsx
apps/mobile/src/components/Notification/Notifications/SomeoneYouFollowPostedTheirFirstPost.tsx
apps/mobile/src/components/ProcessedText/ProcessedText.tsx
apps/web/src/components/Notifications/notifications/SomeoneMentionedYou.tsx
apps/web/src/components/Notifications/notifications/SomeoneYouFollowPostedTheirFirstPost.tsx
packages/shared/src/components/GalleryProccessedText/GalleryProcessedText.tsx

- truncate caption and comment previews in mobile app notifications by making sure the numberOfLines prop is applied to the processedText component
- set web clamp for notifications to 2 lines
Before
After
notifications with different length caption/comments
check notifications on web and mobile

make numberOfLines prop apply to processed text and update web clamp count 

---

apps/web/src/components/HoverCard/CommunityHoverCard.tsx
apps/web/src/components/HoverCard/HoverCard.tsx
apps/web/src/components/HoverCard/UserHoverCard.tsx
apps/web/src/contexts/modal/AnimatedModal.tsx
apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedInfoList/SharedCommunitiesList.tsx
apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedInfoList/SharedFollowersList.tsx
apps/web/src/scenes/UserGalleryPage/UserSharedInfo/UserSharedInfoList/SharedInfoListRow.tsx

- made animated modal always add padding if there's a header
- made shared followers and communities modal dynamic height
- adjust hover card to optionally expand to fit space via prop
| ![CleanShot 2023-11-17 at 16 25 39](https://github.com/gallery-so/gallery/assets/80802871/8d36a954-1aad-4f04-af85-18a0be8bdcdc) | ![CleanShot 2023-11-17 at 16 23 59](https://github.com/gallery-so/gallery/assets/80802871/ab0a1303-2522-4557-9f07-5572c49b4326) |
| …

fix shared info modal regression and make height dynamic

---

apps/mobile/src/screens/NftSelectorScreen/CreatorSupportAnnouncementBottomSheet.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx
apps/web/pages/_/reset.tsx
apps/web/src/components/Announcement/AnnouncementList.tsx
apps/web/src/components/GalleryEditor/GalleryOnboardingGuide/OnboardingDialogContext.tsx
apps/web/src/components/GalleryEditor/PiecesSidebar/PiecesSidebar.tsx
apps/web/src/components/NftSelector/NftSelectorTokens.tsx
apps/web/src/components/Notifications/NotificationList.tsx
apps/web/src/components/Notifications/NotificationTwitterAlert.tsx
apps/web/src/components/UpsellBanner/UpsellBanner.tsx
apps/web/src/contexts/globalLayout/GlobalAnnouncementPopover/useGlobalAnnouncementPopover.tsx
apps/web/src/contexts/globalLayout/GlobalBanner/MobileBetaUpsell.tsx
packages/shared/src/hooks/useExperience.ts
packages/shared/src/relay/useUpdateUserExperience.tsx

Show Creator Support announcement to users when they select the "Created" filter in the composer.
We use an experience flag to make sure they only see it once. This uses the same flag as the frontend, so if they've seen the announcement on web, they won't see it in the app.
This is the first time using experiences in the mobile app, so I moved the useExperience hook and relay files from web into shared.
Note: there's currently a visual issue where the Token Sync toast is displayed above the announcement. I believe we are removing the toast as part of the other follow up changes, so this should be temporary.
Note2: the useUpdateUserExperience file I moved from web to shared used the web toast hook, so I just removed the toast for now. I don't think it's important for the user to be shown …

show creator announcement in mobile composer and make useExperience shared

---

apps/mobile/src/components/AnimatedRefreshIcon.tsx
apps/mobile/src/contexts/SyncTokensContext.tsx
apps/mobile/src/icons/SpinnerIcon.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorContractScreen.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorLoadingSkeleton.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerGrid.tsx
apps/mobile/src/screens/NftSelectorScreen/NftSelectorPickerScreen.tsx

Our mobile syncing state is very ugly!
- Adds skeleton states
- Kills refresh icon spinning; uses opacity instead
- Removes initial toast; still displays error toast
https://github.com/gallery-so/gallery/assets/12162433/6fdeaede-f2d6-4548-ad5c-ac2c261f8496
| network view                                     | contract view                                      |
| <img width="527" alt="Screenshot 2023-11-22 at 2 40 45 PM" src="https://github.com/gallery-so/gallery/assets/12162433/41588d46-2589-4711-abbb-357577a9d3cd"> | <img width="527" alt="Screenshot 2023-11-22 at 2 40 23 PM" src="https://github.com/gallery-so/gallery/assets/12162433/1d1b5955-bd7e-4f41-9397-0f659e580c52"> |
List any common edge …

Mobile syncing skeleton support

---

apps/web/src/components/opengraph/PostOpenGraphPreview.tsx

Ensure the caption in opengraph is truncated to 5 lines exactly and there is no overflow.
This is achieved by replacing the `Markdown` component with the new `ProcesedText` component
| <img width="1263" alt="Screenshot 2023-11-25 at 7 16 15 AM" src="https://github.com/gallery-so/gallery/assets/49758803/91c8a01c-bda0-46c0-9eef-7a20da8edd3f"> | <img width="1208" alt="Screenshot 2023-11-25 at 7 16 52 AM" src="https://github.com/gallery-so/gallery/assets/49758803/bfe51029-a0d3-4b9d-9f31-cb22736d160a"> |
Provide steps on how the reviewer can test the …

opengraph truncation bug fix

---

apps/web/src/components/Notifications/Notification.tsx
apps/web/src/components/Notifications/notifications/SomeoneCommentedOnYourFeedEvent.tsx
apps/web/src/components/Notifications/notifications/SomeoneCommentedOnYourPost.tsx
apps/web/src/components/Notifications/notifications/SomeoneMentionedYou.tsx

remove timestamp in web notification and make it inline only for these activities:
-comment
-mention
-reply
also move unseen notification blue dot to left side from existing right side of notification row
slack context: https://galleryso.slack.com/archives/C056S2FD5HU/p1699930021897119
| <img width="482" alt="Screenshot 2023-11-28 at 1 28 31 PM" src="https://github.com/gallery-so/gallery/assets/49758803/a5399f19-28da-4ce6-bf57-b04dacaa3402"> | <img …

inline timestamp notifs for web

---

apps/mobile/src/hooks/useLogout.ts

Only go through official logout flow if user is using a real device, since we need to de-register their push token (which doesn't exist for simulator)

Fix mobile logouts for local dev

---

apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx

for some reason just does not work when textClassName is `text-darkModeBlue` when the darkModeBlue is defined in `colors.ts`
| <img width="486" alt="Screenshot 2023-12-05 at 6 09 35 PM" src="https://github.com/gallery-so/gallery/assets/49758803/8f60f3bc-1733-4524-8536-e100fe2b3aec"> | <img width="502" alt="Screenshot 2023-12-05 at 6 07 52 PM" src="https://github.com/gallery-so/gallery/assets/49758803/29a3abdb-8507-4ed7-967d-3a9879126253"> |
Please make sure to review and check all of the …

fix admire token text color not updating correctly

---

apps/mobile/src/components/MintLinkButton.tsx

Using `overwriteURL ?? ...` evaluated to the left-hand side even if overwriteURL was an empty string. This prevented the server-provided mint URL from being used as the fallback.

Fix overwriteURL detection for mint buttons

---

apps/web/src/contexts/fullPageNftDetailModalListener/FullPageNftDetailModalListener.tsx
apps/web/src/scenes/NftDetailPage/NftDetailPage.tsx
apps/web/src/scenes/NftDetailPage/NftDetailPageFallback.tsx
apps/web/src/scenes/TokenDetailPage/TokenDetailPage.tsx

Adds a skeleton state for the `NftDetailView` on web. this is triggered basically whenever you click on a token from the feed or a user's gallery 
https://github.com/gallery-so/gallery/assets/49758803/8a00354a-48b0-4afc-9e32-18570c7feeae
https://github.com/gallery-so/gallery/assets/49758803/d9ad5ddf-bbfa-4021-aa57-017e904a9733
https://github.com/gallery-so/gallery/assets/49758803/104ac801-f0e1-4893-8e71-2c336067302b

nft detail skeleton on web

---

apps/web/src/hooks/api/posts/useCommentOnPost.ts
apps/web/src/utils/useClearURLQueryParams.ts

- Fix optimistic update whenever user comment
- Fix random refresh feed whenever the user comment on any post
This bug only happens if the user comment on post (not reply). This line triggered the refresh
https://github.com/gallery-so/gallery/blob/main/apps/web/src/components/Feed/Socialize/CommentsModal/PostCommentsModal.tsx#L61
**Optimistic Update**
https://github.com/gallery-so/gallery/assets/4480258/68742bd8-86c9-4f32-88a1-aa519cad0a46
**Random Feed refetch**
https://github.com/gallery-so/gallery/assets/4480258/3bf8cc74-bd1e-42c4-ac8a-d0e53b7eeb1f

Fix feed randomly refetch on comment

---

apps/mobile/src/components/Community/CommunityMeta.tsx
apps/mobile/src/components/Feed/Posts/PostListMintButtonSection.tsx
apps/mobile/src/components/MintLinkButton.tsx
apps/mobile/src/screens/NftDetailScreen/NftDetailSection.tsx

This PR moves the values for the eventElementId and eventName props into the MintLinkButton component itself, so that we only need to define them once.
Currently, due to defining the value for each distinct usage of MintLinkButton, we are using two different event names "Press Mint Link Button" and "Press Mint Link" for the same event, fragmenting our data unnecessarily.
NA
NA
confirm the different usages of the Mint Link Button component trigger the same event name.

move event element id + name into mint link component

---

apps/mobile/src/screens/PostScreen/SharePostBottomSheet.tsx

After copying url from x post bottomSheet, and bottomSheet is reopened the tick mark is updated to to copy icon again. does this by updating local state after bottom sheet is dismissed (because the bottom sheet never really dismounts.)
https://github.com/gallery-so/gallery/assets/49758803/42d35eb5-148f-4fac-a8ae-bbc260a17b1d

update copy icon state on share post bottom sheet

---

apps/web/src/scenes/NftDetailPage/LinkToFullPageNftDetailModal.tsx

Make it possible to command-click an nft on the feed or gallery to open in new tab by wrapping it in an a tag
command-click opens in new tab, regular click opens in same window
https://github.com/gallery-so/gallery/assets/80802871/d9d882d0-79c8-4663-a2e1-33aea9a8a291
this still won't work for iframes because they don't register the click to open the nft detail page in the first place. this change only applies to nfts that already open an nft detail page when clicked
command click an nft on the feed or in a gallery

GAL-5015 wrap nft detail preview in a tag

---

apps/web/src/components/Feed/Socialize/CommentBox/CommentBox.tsx

Before
After
(can submit if equal to max length)
NA
type a comment longer than max length and see if you can submit, you should not be able to

GAL-5006 disable comment submit button if over max length

---

apps/web/src/hooks/useContainedDimensionsForToken.ts
apps/web/src/scenes/NftDetailPage/NftDetailAsset.tsx
apps/web/src/scenes/NftDetailPage/NftDetailNote.tsx
apps/web/src/scenes/NftDetailPage/NftDetailPage.tsx
apps/web/src/scenes/NftDetailPage/NftDetailPageFallback.tsx
apps/web/src/scenes/NftDetailPage/NftDetailText.tsx
apps/web/src/scenes/NftDetailPage/NftDetailView.tsx
apps/web/src/scenes/TokenDetailPage/TokenDetailAsset.tsx
apps/web/src/scenes/TokenDetailPage/TokenDetailView.tsx
packages/shared/src/utils/fitDimensionsToContainer.ts

This PR updates how the NFT on the NFT Detail Page is sized.
- Increased max size so that the artwork takes up more space on the detail page.
- as a general rule, the Detail Text (non artwork content) has a fixed width, and the artwork grows to take up the available space on the screen, up until whichever is smaller: 80vh or 800px.
- adjusted skeleton states too to reflect the updated sizes
- removed the next and previous nav arrows on the detail page on mobile web, after chatting with design …

Increase displayed nft size on detail page + other polish

---

apps/web/src/scenes/NftDetailPage/NftDetailPageFallback.tsx
apps/web/src/scenes/NftDetailPage/NftDetailText.tsx

- fix scroll extra space bug
- fix oversized fallback image on mobile
- fix unexpected fallback placement on desktop
**fix scroll extra space bug:**
Before:
https://github.com/gallery-so/gallery/assets/80802871/dc019eb4-3cd9-47f2-828b-b8fa1a45d160
After:
https://github.com/gallery-so/gallery/assets/80802871/ea5045b8-843c-4235-b4bd-4b218ad7b5fc
**fix oversized fallback image on mobile**
Before:
https://github.com/gallery-so/gallery/assets/80802871/1544ff19-7359-479e-b383-a1a2ff16fd24
After:
https://github.com/gallery-so/gallery/assets/80802871/34c3cb6a-dabd-434d-9727-9bb7e02c452b
**fix unexpected fallback placement on desktop**
Before:
https://github.com/gallery-so/gallery/assets/80802871/152fdf69-cad2-4433-ac03-10f804deae57
After: …

follow up on nft detail page updates

---

apps/mobile/src/screens/PostScreen/PostComposerScreen.tsx
apps/web/src/components/Posts/PostComposer.tsx

- disable automatic mint links for all ETH tokens
- only auto-enable if zora chain, or manually provided via URL params
**Web Mainnet (not set)**
**Web Mainnet (set when provided via URL params)**
**Zora (autoset)**
**Mobile Mainnet (not set)**
**Mobile Zora (autoset)**

only enable mint links on zora, or when manually set

---

apps/web/src/components/Notifications/Notification.tsx

- Fix click the `RepliedNotification` in the web, didn't highlight the comment automatically
https://github.com/gallery-so/gallery/assets/4480258/f78c13f1-32d6-4c6d-81c1-e761a930be73
1. Check the mobile reply notification too. Works fine

Fix highlight reply notification web

---

apps/mobile/src/components/Markdown.tsx

the `Markdown` tag now ignores header md styling like prefixing a string with '#', '##', '###', as it used in instances where the description coming from a token/contract is also styled for markdown heading, which breaks our styling.
| <img width="475" alt="Screenshot 2024-01-18 at 4 08 16 PM" src="https://github.com/gallery-so/gallery/assets/49758803/8fe7c34d-ea43-4139-83de-7a324234f3dd"> | <img width="471" alt="Screenshot 2024-01-18 at 4 01 53 PM" src="https://github.com/gallery-so/gallery/assets/49758803/052564b0-1cd9-404b-abf6-bc2dec51abf6"> |
| Before                                     | After …

Markdown render ignores header md styling 

---

apps/web/src/scenes/NftDetailPage/NftDetailPageFallback.tsx

Fix an issue with the NFT Detail page fallback where the images are enlarged to fill the square container , which skews any portrait or landscape orientation images. 
object-fit: contain maintains the image aspect ratio
before
https://github.com/gallery-so/gallery/assets/80802871/4e59df8d-79c7-49a1-839e-22bd5422064a
after
https://github.com/gallery-so/gallery/assets/80802871/16fde6e3-9c85-4d5b-bad6-87f80950ad48
for this specific bug, there shouldn't be any edge cases
click into the nft detail page of any non-square nft. as the image loads in, there shouldn't be any obvious changes in aspect ratio of the image where you see the image stretched too wide or tall.

contain fallback image size on nft detail page

---

apps/web/src/hooks/useMintContractWithQuantity.tsx
apps/web/src/utils/MerkleTree.ts

Shop was broken, didnt load because of an error while calling a function from the web3-util library. Syntax was outdated after a library version upgrade.
loads now
na
go to /shop

fix shop - update import syntax for web3 utils

---

apps/web/src/scenes/UserGalleryPage/UserSocialPill.tsx
apps/web/src/scenes/UserGalleryPage/UserTwitterSection.tsx

update pill styling for social profile pills to match design
Before:
After
good on mobile too
- twitter connected vs not connected 
go to user profile and look at social pills

update pill styling

---

apps/mobile/src/components/Community/CommunityGalleries/CommunityGalleries.tsx
apps/mobile/src/components/Community/CommunityGalleries/CommunityGalleriesItem.tsx
apps/mobile/src/components/Community/CommunityGalleries/CommunityGalleriesRow.tsx
apps/mobile/src/components/Community/CommunityTabsHeader.tsx
apps/mobile/src/components/Community/CommunityView.tsx
apps/mobile/src/constants/community.ts
apps/mobile/src/screens/CommunityScreen/CommunityScreen.tsx
schema.graphql

- Add a galleries tab to the community screen for mobile
- We display all the tokens in the preview as 1:1 instead of using token's dimension
https://github.com/gallery-so/gallery/assets/4480258/bfe379ed-a78c-46bf-96e0-7b24e615b22a
**Different aspect ratio**
**Portrait**
**Landscape**
**Mixed ratio**
1. Tested with different aspect ratio of token

Community Gallery Mobile

---

apps/web/pages/home.tsx
apps/web/src/components/Feed/FeedList.tsx

Make /home feed infinite scroll. 
and hide footer because users won't be able to reach it 
https://github.com/gallery-so/gallery/assets/80802871/736fbf98-e488-4fcf-86f4-8d339fcfb40f
na
scroll the feed on /home. it should load the next page automatically

GAL-5095 make feed infinite scroll and remove footer from home

---

apps/web/src/utils/token.ts

Remove hardcoded bg color for punks.
before
after
na
go to view a punk like /rodo/2UDToNdkPZtTKpJrIltKhIy2sZQ/2UDPCpSdAf9Y58Q6IYLQzx4kVnQ

remove hardcoded bg color for punks

---

apps/web/src/scenes/NftDetailPage/NftDetailAsset.tsx
apps/web/src/scenes/NftDetailPage/NftDetailPageFallback.tsx

apply same styling for preview in page and skeleton to change remove the shifting and the stretching of image
https://github.com/gallery-so/gallery/assets/49758803/df516c80-a3c5-419d-833b-00196bd1a61b
https://github.com/gallery-so/gallery/assets/49758803/806febcf-e7f8-47a7-8622-03dff42419ed

improvement to nft detail page transition

---

apps/web/src/scenes/NftDetailPage/NftDetailView.tsx
packages/shared/src/relay/getPreviewImageUrlsInlineDangerously.ts

From a gallery, when you click on nft detail page of a token adjacent to a token with broken token media, we render an error page. This ignores the error for now so that the token clicked can render as it's media is valid
https://github.com/gallery-so/gallery/assets/49758803/0b19d422-674e-4093-ae42-eb664da70c8b
https://github.com/gallery-so/gallery/assets/49758803/5cfc2d3d-b6f5-441f-91a4-aa73cf2754e9

bug fix for tokens adjacent to broken token media in gallery

---

apps/web/src/components/MultiGallery/Gallery.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/GalleryNavbar/GalleryRightContent.tsx

Add clear Edit gallery button for easy access. 
Not logged in: see sign in buttons
Logged in, viewing own gallery: see Edit button
Logged in, viewing someone else's gallery : no button
Button is also visible when viewing an individual gallery (gallery page)
Video demonstrating the edit button navigates to the editor for the correct gallery:
https://github.com/gallery-so/gallery/assets/80802871/c218a359-2bd9-4cfc-a421-c5695af37923
Edit gallery icon appears on hover on the Gallery card on the Galleries tab.  
Edit Gallery option is now in the dropdown on the same card.

add clear edit gallery button

---

apps/web/pages/[username]/[collectionId]/[tokenId]/index.tsx
apps/web/pages/[username]/[collectionId]/index.tsx
apps/web/pages/[username]/galleries/[galleryId].tsx
apps/web/pages/[username]/index.tsx
apps/web/pages/[username]/posts.tsx
apps/web/pages/[username]/token/[tokenId]/index.tsx
apps/web/pages/post/[postId].tsx
apps/web/src/utils/openGraphMetaTags.ts

- Upgrade to new OG URLs defined in https://github.com/gallery-so/opengraph/pull/8
- Only include frame meta tags if compatible
**User**
**User frame**
**Collection**
https://gallery-opengraph.vercel.app/api/og/collection/27OZhb3WThH2NfbEoojqRtVr2XV
Doesn't seem to work, likely because we don't support `HTMLMedia` from the OG service
**Collection frame**
Busted, likely for the same reason
https://gallery-opengraph.vercel.app/api/og/collection/27OZhb3WThH2NfbEoojqRtVr2XV/
**User Gallery**
https://gallery-opengraph.vercel.app/api/og/gallery/27Gj11lEF6opjoWwewUakY7hhXi
**User Gallery frame**
NOT IMPLEMENTED; low prio
**Single token**
https://gallery-opengraph.vercel.app/api/og/nft/28w4uPmP2k5xTq6tvLBShuE3A5i
**Post**
https://gallery-opengraph.vercel.app/api/og/post/2bm9lhTOD3cbLLFX9WYU7mgl2Ng …

upgrade to new OG URLs

---

apps/web/src/components/Feed/FeedList.tsx

fixes bug where the feed is really short if you navigate from the feed -> user profile -> return to feed. 
seems related to this issue: https://github.com/bvaughn/react-virtualized/issues/1324
forcing the resize calculation causes the list to appear as expected.
before
https://github.com/gallery-so/gallery/assets/80802871/b33bf8c4-55b1-4f3c-b179-057e923a43d9
after
https://github.com/gallery-so/gallery/assets/80802871/84dbff12-c837-4ac8-8508-ad2733a1659d
na
Provide steps on how the reviewer can test the changes
1. go to the feed /home
2. click on a username to visit their profile
3. click back in the browse to return to feed
4. verify that the feed is displayed as expected and you can continue to infinite scroll 

fix issue of missing feed items when remounting list

---

apps/web/pages/[username]/galleries/[galleryId].tsx

We allowed fc frame compatibility for user profiles and collection pages, but not gallery pages. Paired with https://github.com/gallery-so/opengraph/pull/12

add single gallery frame compatibility

---

apps/web/src/scenes/CollectionGalleryPage/CollectionGalleryPage.tsx
apps/web/src/scenes/Post/StandalonePostPage.tsx

fix mobile spacing on post page and gallery section page
post page
before
after
gallery section page
before
after
desktop should be unaffected
go to a gallery section page and go to an individual post page

GAL-5132 fix mobile spacing on post page and gallery section page

---

apps/web/src/components/Profile/ProfilePictureDropdown.tsx

we were defaulting to sending the `primaryWallet` chainAddress when updating PFPs, which broke if the ENS PFP was set on a non-primary wallet.
| <img width="576" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/92ecae14-62e5-4c02-818a-ac96ea56957b"> | ![image](https://github.com/gallery-so/gallery/assets/12162433/a1bf202d-6f7c-40d8-a09e-3503f654fccb) |
Provide steps …

send correct wallet chainAddress for ENS pfp updates

---

apps/web/src/components/Feed/Events/FeedEventNftPreviewWrapper.tsx
apps/web/src/components/NftPreview/CollectionTokenPreview.tsx
apps/web/src/hooks/api/posts/useAdmireToken.ts

- Fix bug where disableBookmarkOnHover was true for gallery previews. make sure it only applies to feed event previews.
- update post-mutation store update to insert new edge at beginning of connection instead of end, now that we sort by new -> old]
na

be more selective about disableBookmarkOnHover and insert new edge at start of connection

---

apps/web/src/utils/token.ts

Add blue background back for punks now that we're re-processing them all without a background
| <img width="932" alt="image" src="https://github.com/gallery-so/gallery/assets/12162433/dadf60bb-fc9f-426d-b70d-122a390d4226"> | everything should have a blue background after backend reprocessing lol |

Add blue background back for punks

---

apps/web/src/components/MultiGallery/Gallery.tsx

fix z-index bug where the notifications tab is open in the /galleries view, and the 'Featured' text is shown above the notification elements.
https://github.com/gallery-so/gallery/assets/49758803/598fa732-bbfc-4ab8-a09a-2a6d34134874

'Featured' text is shown above the notification bug fix

---

apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorFilterSort.tsx

the Sort Filter in the NFT Selector was missing justify:space-between so the arrow moved depending on label length 
before
https://github.com/gallery-so/gallery/assets/80802871/a66052ab-1afa-4e0c-bc2c-00ab958066e1
after
https://github.com/gallery-so/gallery/assets/80802871/8dd69abc-5efa-431f-a68a-c7d0822ed272

add justify space between to nft selector sort dropdown

---

apps/web/src/components/core/IconContainer.tsx

Dont  render tooltip in IconContainer on mobile
the tooltip isn't accessible anyway on mobile because it appears on hover, and its presence in the dom was affecting mobile window width on certain screen sizes
before
after
na
test tooltips in general (should still appear on desktop)
and check profile pages with the Active Badge, which was causing the screen width issue on smaller devices

GAL-5122 dont render tooltip in IconContainer on mobile

---

apps/web/src/components/MultiGallery/Gallery.tsx

Add Share button to dropdown of Gallery on Multi Gallery tab (if gallery isn't hidden)
na
go to Galleries tab on your profile and click dropdown of a gallery. you should see a Share option and it should copy the gallery url.

Add Share button to dropdown of Gallery on Multi Gallery tab

---

apps/web/src/components/Onboarding/WelcomeNewUser.tsx
apps/web/src/components/Onboarding/WelcomeNewUserModal.tsx
apps/web/src/scenes/Home/CuratedHomePage.tsx

Added tooltips to welcome user after user going through onboarding
**Desktop view**
https://github.com/gallery-so/gallery/assets/4480258/f39aa1ff-0d0b-4855-9617-31eafe514981
**Mobile view**
https://github.com/gallery-so/gallery/assets/4480258/fde4324b-6c48-4b2d-9865-290f9086ae97
1. Visit `https://localhost/home?onboarding=true`

Add tooltips for onboarding

---

apps/mobile/src/components/GalleryRefreshControl.tsx

add haptic when pulling down to refresh. this is common in most apps so it felt like some feedback was missing when refreshing.
NA
NA
Pull down to refresh on a device

add haptic when pulling down to refresh

---

apps/web/src/scenes/UserGalleryPage/FocusedGalleryPage.tsx

Fix page gutter for individual gallery page on mobile
before
after
na
go an individual gallery page like http://localhost:3000/gianna/galleries/0c4e5e97fc3d407a23313aa748ff319d on mobile screen size, there should be a page gutter so the content isn't flush with the screen edge

GAL-5263 fix gallery page spacing on mobile

---

apps/mobile/src/icons/BookmarkIcon.tsx

Bookmark icon on detail page was not visible in dark mode when inactive
before
after

fix darkmode inactive color for bookmark icon

---

apps/web/pages/explore.tsx
apps/web/src/components/Explore/Explore.tsx
apps/web/src/components/Explore/FeaturedUsers.tsx
apps/web/src/components/Explore/TrendingSection.tsx
apps/web/src/scenes/Home/ExploreHomePage.tsx

The explore is slow to load. This is because the query to retrieve featured/trending users takes a while to resolve. 
Currently the request blocks the whole page from loading, which makes it look super slow.
This PR separates the trending users query into its own lazy loaded query and wraps it in a suspense so that the rest of the Explore page can load first.
before:
https://github.com/gallery-so/gallery/assets/80802871/8a50f759-d431-4976-a340-955fc0a1f887
after
https://github.com/gallery-so/gallery/assets/80802871/cb2960f1-f72e-44e0-ba58-b485fa18d207
na
go to /explore
you should see the page load fairly quickly and a loading skeleton state for the users sections

refactor explore page data loading to prevent featured user query from blocking the whole page

---

apps/mobile/src/icons/CircleCheckIcon.tsx
apps/mobile/src/screens/SettingsScreen/EmailNotificationSettingsSection.tsx
apps/mobile/src/screens/SettingsScreen/NotificationSettingsScreen.tsx
apps/web/src/components/Email/useUpdateEmailNotificationSettings.ts
apps/web/src/components/Settings/ManageEmailSection/ManageEmailSection.tsx
packages/shared/src/hooks/useUpdateEmailNotificationSettings.ts
schema.graphql

You can now unsubscribe to specific mailing lists from the notification settings, and when you toggle an email notification subscription, a toast is pushed when the mutation succeeds or fails.
https://github.com/gallery-so/gallery/assets/49758803/11f07815-3f5d-4a10-8483-b43807ef614b
| <img width="412" alt="Screenshot 2024-03-09 at 14 19 47" src="https://github.com/gallery-so/gallery/assets/49758803/34be7c86-5a6b-4e10-90de-4a3038a576f3"> | <img width="413" alt="Screenshot 2024-03-09 at 14 05 46" src="https://github.com/gallery-so/gallery/assets/49758803/949c9da9-186c-4134-b603-fee5a4ee7e7e"> | …

add Email Notification Setting unsub options

---

apps/web/src/scenes/NftDetailPage/NftDetailText.tsx

The referrer address in the zora URL mint link is missing if visited from the 'Mint On Zora' button from the NFT Detail Page web
| ![Screenshot 2024-03-25 at 19 43 45](https://github.com/gallery-so/gallery/assets/49758803/8323b202-b834-4e39-8237-607a769978fd) | ![Screenshot 2024-03-25 at 19 43 35](https://github.com/gallery-so/gallery/assets/49758803/babf4117-0667-4dee-b12d-e81dc8751bac) |

[GAL-5338] add referrer on Mint On Zora button from the NFT Detail Page

---

apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetLine.tsx
apps/mobile/src/components/Feed/CommentsBottomSheet/CommentsBottomSheetSection.tsx
apps/web/src/components/Feed/Socialize/CommentsModal/CommentNote.tsx
apps/web/src/components/Feed/Socialize/CommentsModal/CommentNoteSection.tsx

If the comment that has been deleted has no replies then hide that comment.
Made the changes for both web and mobile
| ![Screenshot 2024-03-27 at 13 13 06](https://github.com/gallery-so/gallery/assets/112896251/3cb17329-85b9-4afb-84b3-20c73af74a63) | ![Screenshot 2024-03-27 at 17 54 17](https://github.com/gallery-so/gallery/assets/112896251/4066602b-fb3b-4aef-8bf9-d30b9a4b8322) |
More pics:
I'd just like to note the fact that if the post has 1 comment (that is deleted) then the condition to show "No comments yet" is not fulfilled and thus just shows a blank screen as in the screenshot. 
I tried fixing this …

hide deleted comment if no replies

---

apps/mobile/package.json
apps/mobile/src/components/Feed/Posts/PostListCaption.tsx
yarn.lock

Added a check for line height and added a gradient that suggests there is more to be seen. When tapped it expands to show the whole text. Can also be tapped again to collapse
https://linear.app/galleryso/issue/GAL-4476/truncate-long-post-captions-on-mobile-app
|![Screenshot 2024-04-01 at 16 48 28](https://github.com/gallery-so/gallery/assets/112896251/04f2e82f-c1e9-4456-ab02-214706effa3c)|![Screenshot 2024-04-01 at 16 48 25](https://github.com/gallery-so/gallery/assets/112896251/44576241-ef71-4581-bdf4-56ce10480372)|

truncate long posts with gradient

---

apps/web/pages/explore.tsx
apps/web/src/components/Explore/Explore.tsx
apps/web/src/components/Explore/GallerySelects.tsx
apps/web/src/icons/ArrowUpRightIcon.tsx
apps/web/src/scenes/ContentPages/cms_types.ts
apps/web/src/scenes/Home/ExploreHomePage.tsx

Replace hardcoded article on Explore page with content from Sanity
na
go to /explore

make explore page gallery selects powered by sanity

---

apps/mobile/src/screens/Login/Onboarding2FAScreen.tsx
apps/mobile/src/screens/Login/OnboardingEmailScreen.tsx
apps/mobile/src/screens/Onboarding/OnboardingUsernameScreen.tsx
packages/shared/src/hooks/useAuthPayloadQuery.ts
packages/shared/src/hooks/useCreateUser.ts

Use privy auth mechanism, improve email validation UI

---

apps/mobile/src/components/Feed/Posts/PostListCaption.tsx
apps/mobile/src/hooks/useGradientColorScheme.ts

Fixed gradient for long mobile posts

fix dark mode gradient

---

apps/web/src/scenes/NftDetailPage/NftDetailAssetContainer.tsx

Weird stretching when you go to nft detail page from feed or a gallery. 
https://github.com/gallery-so/gallery/assets/49758803/6cfcb92d-6d61-4622-8582-caac9811a229
https://github.com/gallery-so/gallery/assets/49758803/2789032c-906b-4a7b-9e61-384143c02d96

fix transition to NftDetail page on web

---

apps/mobile/src/components/EnsOrAddress.tsx

| <img width="469" alt="Screenshot 2024-04-09 at 19 46 40" src="https://github.com/gallery-so/gallery/assets/49758803/76ba8675-1b19-47a2-8133-cbf35f0b92d5"> | <img width="453" alt="Screenshot 2024-04-09 at 19 45 17" src="https://github.com/gallery-so/gallery/assets/49758803/d72c7820-ebc4-4bb3-a2e8-e51cf0e7e8a9"> |
when address is name still working as per usual

bug fix: wallet truncation on nft detail mobile

---

apps/web/src/components/GalleryEditor/PiecesSidebar/SidebarChainDropdown.tsx
apps/web/src/components/NftSelector/NftSelectorFilter/NftSelectorFilterNetwork.tsx

fix regression where all chains are disabled for collected tab
Before
Non admin , collected tab
Non admin, created tab
After
Non admin, collected tab
Non admin, created tab
Same fix for nft selector dropdown
- is admin user
- is not admin user
- log in as a non admin user
- go to the editor or nft selector and select the network dropdown
- you should be able to select any chain for the Collected tab
- you should see a limited selection of chains for the Created tab
- if you log in as an admin user you should see all chains enabled

fix regression where all chains are disabled for collected tab

---

apps/mobile/src/components/Mint/MintCampaign/MintCampaignPreTransaction.tsx

Some users are unable to mint because their primary wallet is a Tezos address, which results in an error while trying to mint.
This PR checks if the primary wallet is an Eth address, and if not checks to see if any other connected wallets are eligible and uses that instead if one exists. If there are no eligible wallets, we show an error message and disable the mint button to make the issue clear.
- User has a non eth address as their primary, but has an eth address connected
- User has a non eth address as their primary, and doesn't have an eth address connected
Set a non eth address as the primary, and go through the mint flow

if primary address is non eth, check other wallets to mint to

---

apps/mobile/src/components/Feed/FeedList.tsx
apps/mobile/src/components/Feed/FeedVirtualizedRow.tsx
apps/mobile/src/components/Feed/Posts/FeedSuggestedProfileRow.tsx
apps/mobile/src/components/Feed/createVirtualizedFeedEventItems.ts

Adds a new suggested profile section in the Feed, that shows up `4` feed items down the list.
https://github.com/gallery-so/gallery/assets/49758803/a3c4daa9-777c-49fd-adf3-71fab524c33a
light mode

add SuggestedUser card row in mobile feed

---

apps/mobile/src/components/ClaimMintUpsellBanner.tsx
apps/mobile/src/components/Feed/Posts/PostListMintButtonSection.tsx
apps/mobile/src/components/MintLinkButton.tsx
apps/mobile/src/components/Notification/NotificationSkeleton.tsx
apps/mobile/src/icons/GLogoIcon.tsx
apps/mobile/src/navigation/RootStackNavigator.tsx
apps/mobile/src/utils/isRadianceContractAddress.ts
schema.graphql

- Added the banner for mchx mint in mobile (web still in progress)
- Added pin notification UI (have to properly get the data from the backend)
- Added Mint on gallery button (opens campaign bottom sheet) if not claimed and mint on highlight if already minted

mchx campaign banner and mint on gallery

---

apps/web/src/components/Badge/Badge.tsx
apps/web/src/components/Feed/CuratedFeed.tsx
apps/web/src/components/Feed/FeedList.tsx
apps/web/src/components/Feed/FeedSuggestedProfileSection.tsx
apps/web/src/components/Feed/SuggestedProfileCard.tsx
apps/web/src/components/Search/SearchDefaultSuggestedUsersSection.tsx
apps/web/src/components/core/Carousel/Carousel.tsx

adds a new item (the Suggested Profiles section) in the `Curated` Feed after the 8th feed list item.
| Design                                     | Demo with changes                                      |
| <img width="998" alt="Screenshot 2024-04-17 at 12 07 17" src="https://github.com/gallery-so/gallery/assets/49758803/784f770c-d226-4bd7-a376-7a500dd6c895"> | <img width="1178" alt="Screenshot 2024-04-17 at 12 07 29" src="https://github.com/gallery-so/gallery/assets/49758803/355588db-c391-49e6-ad11-9d139df29ae4">|
Moweb:
Provide steps on …

[GAL-5440] add Suggested Profiles in curated Feed web

---

apps/mobile/src/screens/Onboarding/OnboardingRecommendedUsers.tsx

| <img width="454" alt="Screenshot 2024-04-24 at 19 38 15" src="https://github.com/gallery-so/gallery/assets/49758803/7d29987a-cbb3-4749-9d60-229fc074a527"> | <img width="475" alt="Screenshot 2024-04-24 at 19 37 59" src="https://github.com/gallery-so/gallery/assets/49758803/5c6c5f88-186f-4057-bf98-3f75dd166cd1"> |
List any …

bug fix: padding lost in onboarding recommended user follow list

---

apps/mobile/src/components/ProfilePicture/ProfilePicture.tsx

update mobile logic to fetch pfp image URL to match that of web
| ![IMG_2786 2 (1)](https://github.com/gallery-so/gallery/assets/49758803/acfb8d46-157e-44a1-bb8b-84f0e1e6afd0) | <img width="446" alt="Screenshot 2024-04-25 at 20 24 34" src="https://github.com/gallery-so/gallery/assets/49758803/1782edf7-f73a-418b-bd7f-f8e3a08f3eda"> |

bug fix: pfp not working on mobile

---

apps/web/pages/[username]/index.tsx
apps/web/src/components/MultiShimmer/MultiShimmer.tsx
apps/web/src/components/Profile/ProfileScreenLoadingSkeleton.tsx
apps/web/src/contexts/globalLayout/GlobalNavbar/useGlobalNavbarHeight.tsx
apps/web/src/contexts/shimmer/ShimmerContext.tsx
apps/web/src/hooks/useNftRetry.tsx
apps/web/src/scenes/GalleryPage/GalleriesPage.tsx
apps/web/src/scenes/UserGalleryPage/UserGalleryCollections.tsx

- Skeleton loaders for profile screen (web)
- Also adding a key to Suspense makes it so it retriggers the actual boundary when navigating between same routes (form profile to profiel, ie. robin -> santa)
https://github.com/gallery-so/gallery/assets/112896251/d4a6c686-0e69-4315-aa83-06c1d13e762f

profile screen skeleton loader

---

apps/web/src/scenes/Onboarding/OnboardingRecommendUsersPage.tsx

Was causing unnecessary errors during onboarding

Remove requirement for suggested farcaster users

---

apps/mobile/src/App.tsx
apps/mobile/src/components/ClaimMintUpsellBanner.tsx
apps/mobile/src/components/Mint/MintCampaign/MintCampaignBottomSheet.tsx
apps/mobile/src/components/Mint/MintCampaign/MintCampaignPostTransaction.tsx
apps/mobile/src/components/Mint/MintCampaign/MintCampaignPreTransaction.tsx
apps/mobile/src/components/MintLinkButton.tsx
apps/mobile/src/components/Notification/NotificationList.tsx
apps/mobile/src/components/Notification/Notifications/AnnouncementNotification.tsx
apps/mobile/src/components/Notification/Notifications/GalleryAnnouncement.tsx
apps/mobile/src/contexts/AnnouncementContext.tsx
apps/mobile/src/contexts/SanityAnnouncementContext.tsx
apps/mobile/src/contexts/SanityDataContext.tsx
apps/mobile/src/navigation/MainTabNavigator/NotificationBlueDot.tsx
apps/mobile/src/navigation/RootStackNavigator.tsx
apps/mobile/src/screens/SettingsScreen/DebugBottomSheetModal.tsx
apps/mobile/src/screens/SettingsScreen/SettingsScreen.tsx

Announcement
Mint Flow
Demo on slack
- Backwards compatibility with ongoing mint
- sanity data not loading
Watch Loom on slack
- turn on announcement (active === true) in Sanity and verify it appears as expected in the app

Mobile: Add pinned announcement notification powered by Sanity + Make Mint Flow configurable via Sanity

---

apps/mobile/src/contexts/SanityAnnouncementContext.tsx

On mobile the announcement dismissed and seen status weren't persisting because there was a typo in the storage key.
na
na

fix announcement and seen state typo

---

apps/web/src/scenes/UserGalleryPage/UserGalleryCollections.tsx

fix: temp empty array for skeleton loader

---

apps/web/src/components/Search/SearchDefaultSuggestedUsersSection.tsx

| <img width="454" alt="Screenshot 2024-05-07 at 23 39 50" src="https://github.com/gallery-so/gallery/assets/49758803/b37ded35-00d6-4d7f-9ebb-b943950036b0"> | <img width="454" alt="Screenshot 2024-05-07 at 23 39 50" src="https://github.com/gallery-so/gallery/assets/49758803/3ee6df0c-353c-479e-99c2-4d0ab63e6c77"> |
Please make sure …

fix for missing preview cards in search default mobile

---

apps/mobile/src/components/Notification/Notifications/AnnouncementNotification.tsx
apps/mobile/src/hooks/useNavigateToCommunityScreen.ts

- Navigation was undefined and crashed the app. Added a check in the hook itself just in case and passed navigation to the bottom sheet context to actually fix it 
https://galleryso.slack.com/archives/C04DUEVL22U/p1715715459661029

fix navigation crash after mint campaign

---

packages/shared/src/utils/getMintUrlWithReferrer.ts

dd prohibition art daily to allowed mint links
Allow https://daily.prohibition.art as a valid mint link url
before
after
na
try to post an nft and add a custom mint link. the new one should now be allowed 

allowlist new prohibition url for mint link

---

apps/web/src/components/Onboarding/FullPageCenteredStep.tsx
apps/web/src/components/WalletSelector/mutations/useLoginOrRedirectToOnboarding.ts
apps/web/src/contexts/AppProvider.tsx
apps/web/src/contexts/globalLayout/useStabilizedRouteTransitionKey.ts
apps/web/src/contexts/onboardingProgress/index.tsx
apps/web/src/scenes/Onboarding/OnboardingAddBioPage.tsx
apps/web/src/scenes/Onboarding/OnboardingAddEmailPage.tsx
apps/web/src/scenes/Onboarding/OnboardingAddProfilePicturePage.tsx
apps/web/src/scenes/Onboarding/OnboardingAddUsernamePage.tsx

- Fixed onboarding flash on next step, which sort of broke the animation of the progress bar so also fixed that by adding a context for the actual progress step
https://github.com/gallery-so/gallery/assets/112896251/fb6aa0e1-1a6d-4e97-8fc1-8d27158ded9a

fix onboarding flash and progress animation
